require({cache:{
'dojox/grid/enhanced/nls/en/Filter':function(){
define('dojox/grid/enhanced/nls/en/Filter',{});
},
'dojox/grid/enhanced/nls/en-nz/Filter':function(){
define('dojox/grid/enhanced/nls/en-nz/Filter',{});
},
'dojox/grid/enhanced/nls/en/EnhancedGrid':function(){
define('dojox/grid/enhanced/nls/en/EnhancedGrid',{});
},
'dojox/grid/enhanced/nls/en-nz/EnhancedGrid':function(){
define('dojox/grid/enhanced/nls/en-nz/EnhancedGrid',{});
},
'dojox/grid/enhanced/nls/en/Pagination':function(){
define('dojox/grid/enhanced/nls/en/Pagination',{});
},
'dojox/grid/enhanced/nls/en-nz/Pagination':function(){
define('dojox/grid/enhanced/nls/en-nz/Pagination',{});
},
'dojox/form/nls/en/Uploader':function(){
define('dojox/form/nls/en/Uploader',{});
},
'dojox/form/nls/en-nz/Uploader':function(){
define('dojox/form/nls/en-nz/Uploader',{});
}}});
define("dojox/nls/dojox_en-nz", [], 1);
