require({cache:{
'dojox/grid/enhanced/nls/en/Filter':function(){
define('dojox/grid/enhanced/nls/en/Filter',{});
},
'dojox/grid/enhanced/nls/en-jm/Filter':function(){
define('dojox/grid/enhanced/nls/en-jm/Filter',{});
},
'dojox/grid/enhanced/nls/en/EnhancedGrid':function(){
define('dojox/grid/enhanced/nls/en/EnhancedGrid',{});
},
'dojox/grid/enhanced/nls/en-jm/EnhancedGrid':function(){
define('dojox/grid/enhanced/nls/en-jm/EnhancedGrid',{});
},
'dojox/grid/enhanced/nls/en/Pagination':function(){
define('dojox/grid/enhanced/nls/en/Pagination',{});
},
'dojox/grid/enhanced/nls/en-jm/Pagination':function(){
define('dojox/grid/enhanced/nls/en-jm/Pagination',{});
},
'dojox/form/nls/en/Uploader':function(){
define('dojox/form/nls/en/Uploader',{});
},
'dojox/form/nls/en-jm/Uploader':function(){
define('dojox/form/nls/en-jm/Uploader',{});
}}});
define("dojox/nls/dojox_en-jm", [], 1);
