//>>built
define("dojo/cldr/nls/currency", { root:

//begin v1.x content
{
	"USD_symbol": "US$",
	"CAD_symbol": "CA$",
	"GBP_symbol": "£",
	"HKD_symbol": "HK$",
	"JPY_symbol": "JP¥",
	"AUD_symbol": "AU$",
	"CNY_symbol": "CN¥",
	"EUR_symbol": "€"
}
//end v1.x content
,
	"af": true,
	"ar": true,
	"az": true,
	"be": true,
	"bg": true,
	"ca": true,
	"cs": true,
	"da": true,
	"de": true,
	"el": true,
	"en": true,
	"en-au": true,
	"en-bz": true,
	"en-ca": true,
	"en-jm": true,
	"en-nz": true,
	"en-tt": true,
	"en-za": true,
	"es": true,
	"es-ec": true,
	"es-pr": true,
	"et": true,
	"eu": true,
	"fa": true,
	"fi": true,
	"fr": true,
	"fr-ca": true,
	"he": true,
	"hi": true,
	"hr": true,
	"hu": true,
	"id": true,
	"is": true,
	"it": true,
	"ja": true,
	"kk": true,
	"ko": true,
	"lt": true,
	"lv": true,
	"mk": true,
	"ms": true,
	"mt": true,
	"nb": true,
	"nl": true,
	"pl": true,
	"pt": true,
	"pt-pt": true,
	"rm": true,
	"ro": true,
	"ru": true,
	"sk": true,
	"sl": true,
	"sq": true,
	"sr": true,
	"sv": true,
	"th": true,
	"tr": true,
	"uk": true,
	"ur": true,
	"vi": true,
	"zh": true,
	"zu": true
});