//>>built
define("dojo/cldr/nls/number", { root:

//begin v1.x content
{
	"scientificFormat": "#E0",
	"currencySpacing-afterCurrency-currencyMatch": "[:letter:]",
	"infinity": "∞",
	"list": ";",
	"percentSign": "%",
	"minusSign": "-",
	"currencySpacing-beforeCurrency-surroundingMatch": "[:digit:]",
	"decimalFormat-short": "000T",
	"currencySpacing-afterCurrency-insertBetween": " ",
	"nan": "NaN",
	"plusSign": "+",
	"currencySpacing-afterCurrency-surroundingMatch": "[:digit:]",
	"currencySpacing-beforeCurrency-currencyMatch": "[:letter:]",
	"currencyFormat": "¤ #,##0.00",
	"perMille": "‰",
	"group": ",",
	"percentFormat": "#,##0%",
	"decimalFormat": "#,##0.###",
	"decimal": ".",
	"currencySpacing-beforeCurrency-insertBetween": " ",
	"exponential": "E"
}
//end v1.x content
,
	"af": true,
	"ar": true,
	"ar-sy": true,
	"ar-tn": true,
	"az": true,
	"be": true,
	"bg": true,
	"ca": true,
	"cs": true,
	"da": true,
	"de": true,
	"de-at": true,
	"de-ch": true,
	"de-li": true,
	"el": true,
	"en": true,
	"en-bz": true,
	"en-gb": true,
	"en-jm": true,
	"en-tt": true,
	"en-za": true,
	"es": true,
	"es-ar": true,
	"es-bo": true,
	"es-cl": true,
	"es-co": true,
	"es-cr": true,
	"es-ec": true,
	"es-py": true,
	"es-uy": true,
	"es-ve": true,
	"et": true,
	"eu": true,
	"fa": true,
	"fi": true,
	"fo": true,
	"fr": true,
	"fr-be": true,
	"fr-ca": true,
	"fr-ch": true,
	"fr-lu": true,
	"he": true,
	"hi": true,
	"hr": true,
	"hu": true,
	"id": true,
	"is": true,
	"it": true,
	"it-ch": true,
	"ja": true,
	"kk": true,
	"ko": true,
	"lt": true,
	"lv": true,
	"mk": true,
	"ms": true,
	"mt": true,
	"nb": true,
	"nl": true,
	"nl-be": true,
	"pl": true,
	"pt": true,
	"pt-pt": true,
	"rm": true,
	"ro": true,
	"ru": true,
	"sk": true,
	"sl": true,
	"sq": true,
	"sr": true,
	"sv": true,
	"th": true,
	"tn": true,
	"tr": true,
	"ts": true,
	"uk": true,
	"ur": true,
	"ve": true,
	"vi": true,
	"xh": true,
	"zh": true,
	"zu": true
});