define(
    ({
        labelWidth: '100',
        tabNameGeneralText: 'Generale',
        tabNameAttachmentsText: 'Allegati',
        scheduleText: 'Pianifica',
        startTimeText: 'Pianificato',
        completedDateText: 'Completato',
        timeLessText: 'Senza orario',
        durationText: 'Durata',
        contactText: 'Contatto',
        accountText: 'Azienda',
        leadText: 'Nominativo',
        opportunityText: 'Opportunità',
        ticketText: 'Ticket',
        companyText: 'Società',
        regardingText: 'Argomento',
        resultText: 'Risultato',
        notesText: 'Nota',
        priorityText: 'Priorità',
        leaderText: 'Responsabile',
        categoryText: 'Categoria',
        locationText: 'Posizione',
        scheduledByFormatText: 'Pianificato da ${user} il ${date}',
        cancelText: 'Annulla',
        okText: 'OK',
        deleteText: 'Elimina',
        lookupActText: 'Ricerca Azienda',
        lookupContactText: 'Ricerca Contatto',
        lookupOpportunityText: 'Ricerca opportunità',
        lookupTicketText: 'Ricerca Ticket',
        lookupLeadText: 'Ricerca Nominativo',
        lookupLeaderText: 'Ricerca Leader',
        lookupResourcesText: 'Ricerca',
        mainPhoneText: 'Telefono principale',
        typeText: 'Tipo',
        subTypeText: 'Sotto-Tipo',
        nameText: 'Nome',
        cityText: 'Città',
        stateText: 'Status',
        workphoneText: 'Tel. Ufficio',
        emailText: 'E-Mail',
        acctMgrText: 'Responsabile',
        descriptionText: 'Descrizione',
        stageText: 'Fase',
        statusText: 'Status',
        ownerText: 'Proprietario',
        ticketNumberText: 'Numero Ticket',
        phoneText: 'Telefono',
        urgencyText: 'Urgenza',
        areaText: 'Area',
        recurringText: 'Ricorrente',
        followupText: 'Seguito',
        noneText: 'Nessuno',
        carryOverAttachmentsText: 'Riporta Allegati',
        carryOverNotesText: 'Riporta note',
        asScheduledText: 'Come pianificato',
        insertText: 'Inserisci',
        couldNotSaveErrorText: 'Non è stato possibile salvare la cronologia perché si è verificato un errore.',
        deleteMessage: 'Stai per eliminare definitivamente questo record.',
        deleteTitle: 'Elimina cronologia',
        postalText: 'Cap',
        couldNotDeleteErrorText: 'La cronologia potrebbe non essere stata eliminata perché si è verificato un errore.'
       
    })
);
