define(
        ({
            activityOccurrsText: 'Questa attività ricorre...',
            onceText: 'Una volta',
            dailyText: 'Giornalmente',
            weeklyText: 'Settimanalmente',
            monthlyText: 'Mensilmente',
            yearlyText: 'Annualmente',
            occursOnceText: 'Questa Attività ricorre solo una volta',
            everyText: 'Ogni',
            daysText: 'Giorno(i)',
            daysAfterText: 'Giorno(i) dopo il completamento',
            startRecurringText: 'Inizio ricorrenza: ',
            endAfterText: 'Finire dopo',
            endOnText: 'Fine Ricorrenza',
            occurrencesText: 'occorrenze',
            weeksOnText: 'Settimana(e) il:',
            monText: 'Lunedì',
            tueText: 'Martedì',
            wedText: 'Mercoledì',
            thurText: 'Giovedì',
            friText: 'Venerdì',
            satText: 'Sabato',
            sunText: 'Domenica',
            weeksAfterText: 'Settimane(i) dopo il completamento',
            monthsOnText: 'Giorno del Mese(i)',
            monthsOnTheText: 'Mese(i) il',
            monthsAfterText: 'Mese(i) dopo completamento',
            firstText: '1°',
            secondText: '2°',
            thirdText: '3°',
            fourthText: '4°',
            lastText: 'ultimo',
            yearsOnText: 'Anno(i) il',
            yearsAfterText: 'Anno(i) dopo il completamento',
            janText: 'Gennaio',
            febText: 'Febbraio',
            marText: 'Marzo',
            aprText: 'Aprile',
            mayText: 'Maggio',
            junText: 'Giugno',
            julText: 'Luglio',
            augText: 'Agosto',
            sepText: 'Settembre',
            octText: 'Ottobre',
            novText: 'Novembre',
            decText: 'Dicembre',
            theText: 'Il',
            inText: 'in'
        })
);
      