define(
        ({
            labelWidth: '120',
            tabNameGeneralText: 'Общие',
            tabNameAvailabilityText: 'Доступность',
            tabNameAssociationsText: 'Взаимосвязи',
            tabNameRecurringText: 'Повторение',
            tabNameAttachmentsText: 'Вложения',
            tabNameNotesText: 'Заметки',
            scheduleText: 'Планировать',
            startTimeText: 'Время начала',
            timeLessText: 'В течение дня',
            alarmText: 'Оповещение',
            durationText: 'Длительность',
            rolloverText: 'Автоматически переносить на следующий день',
            contactText: 'Контакт',
            accountText: 'Субъект',
            leadText: 'Наводка',
            opportunityText: 'Сделка',
            ticketText: 'Заявка',
            companyText: 'Компания',
            regardingText: 'Тема',
            notesText: 'Заметки',
            priorityText: 'Приоритет',
            leaderText: 'Руководитель',
            categoryText: 'Категория',
            locationText: 'Размещение',
            dialogHeaderFormatText: '${actionText} ${activityType} - ${description}',
            scheduledByFormatText: 'Запланировал ${user} ${date}',
            completeScheduledByFormatText: 'Запланировал ${user} ${date} первоначально на ${startDate}',
            newConfirmationHeaderFormatText: 'Подтверждение ${activityType}. Запланировал ${user}',
            otherConfimationHeaderFormatText: '${activityType} ${actionText} ${user}',
            acceptedText: 'Принят',
            declinedText: 'Отклонено',
            scheduledText: 'Запланировано',
            updatedText: 'Изменено',
            deletedText: 'Удалено',
            cancelText: 'Отмена',
            okText: 'ОК',
            completeText: 'Завершить',
            completeBtnText: 'Завершить...',
            completedText: 'Заверш.',
            deleteText: 'Удалить',
            lookupActText: 'Поиск Субъекта',
            lookupContactText: 'Поиск Контакта',
            lookupOpportunityText: 'Поиск сделки',
            lookupTicketText: 'Поиск Заявки',
            lookupLeadText: 'Поиск Наводки',
            lookupLeaderText: 'Поиск лидера',
            lookupResourcesText: 'Добавить участников и ресурсы',
            addResourceText: 'Добавить',
            mainPhoneText: 'Основной тел.',
            typeText: 'Тип',
            subTypeText: 'Подтип',
            nameText: 'Имя',
            cityText: 'Город',
            stateText: 'Область',
            workphoneText: 'Раб. телефон',
            emailText: 'Эл.почта',
            acctMgrText: 'Менеджер',
            descriptionText: 'Описание',
            stageText: 'Стадия',
            statusText: 'Статус',
            ownerText: 'Доступ',
            ticketNumberText: 'Номер заявки',
            phoneText: 'Телефон',
            urgencyText: 'Срочность',
            areaText: 'Область',
            recurringText: 'Повторение',
            resultText: 'Результат',
            followupText: 'Последующее',
            noneText: 'Нет',
            carryOverAttachmentsText: 'Перенести вложения',
            carryOverNotesText: 'Перенести заметки',
            asScheduledText: 'Как запланировано',
            nowText: 'Сейчас',
            responseText: 'Ответ',
            acceptText: 'Принять',
            declineText: 'Отклонить',
            deleteConfText: 'Удалить подтверждение',
            closeText: 'Закрыть',
            leadFullNameText: 'Имя',
            postalText: 'Почтовый код',
            failedLoadingDataMsg: 'Произошла ошибка при загрузке данных.',
            removeText: 'Исключить',
            noText: 'Нет',
            yesText: 'Да',
            areYouSureText: 'Запись будет удалена без возможности восстановления',
            couldNotSaveErrorText: 'К сожалению, дело не может быть сохранено, потому что произошла ошибка.',
            couldNotDeleteErrorText: 'К сожалению, дело не может быть удалено, потому что произошла ошибка.',
            couldNotCompleteErrorText : 'К сожалению, дело не может быть завершено из-за ошибки.'
        })
);
