require({cache:{
'Sage/Utility/File/nls/ar/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/ar-om/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar-om/FallbackFilePicker',{});
},
'Sage/UI/nls/ar/Boolean':function(){
define('Sage/UI/nls/ar/Boolean',{});
},
'Sage/UI/nls/ar-om/Boolean':function(){
define('Sage/UI/nls/ar-om/Boolean',{});
},
'Sage/UI/Controls/nls/ar/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/ar-om/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar-om/CopyToClipboard',{});
},
'Sage/Services/nls/ar/ActivityService':function(){
define('Sage/Services/nls/ar/ActivityService',{});
},
'Sage/Services/nls/ar-om/ActivityService':function(){
define('Sage/Services/nls/ar-om/ActivityService',{});
},
'Sage/Utility/nls/ar/Activity':function(){
define('Sage/Utility/nls/ar/Activity',{});
},
'Sage/Utility/nls/ar-om/Activity':function(){
define('Sage/Utility/nls/ar-om/Activity',{});
},
'Sage/UI/nls/ar/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar/TimelessActivitiesPane',{});
},
'Sage/UI/nls/ar-om/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar-om/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-om/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-om/ActivityEditor',{});
},
'Sage/MainView/nls/ar/ActivityManager':function(){
define('Sage/MainView/nls/ar/ActivityManager',{});
},
'Sage/MainView/nls/ar-om/ActivityManager':function(){
define('Sage/MainView/nls/ar-om/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-om/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-om/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/ar/Service':function(){
define('Sage/Reporting/nls/ar/Service',{});
},
'Sage/Reporting/nls/ar-om/Service':function(){
define('Sage/Reporting/nls/ar-om/Service',{});
},
'Sage/Utility/File/nls/ar/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar-om/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar-om/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/ar-om/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar-om/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPane',{});
},
'Sage/UI/Alarms/nls/ar-om/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar-om/AlarmPane',{});
},
'Sage/TaskPane/nls/ar/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/ar-om/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar-om/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/ar-om/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar-om/DashboardWidget',{});
},
'Sage/UI/Filters/nls/ar/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar/FilterPanel',{});
},
'Sage/UI/Filters/nls/ar-om/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar-om/FilterPanel',{});
},
'Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/ar-om/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar-om/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/ar/OwnerType':function(){
define('Sage/UI/nls/ar/OwnerType',{});
},
'Sage/UI/nls/ar-om/OwnerType':function(){
define('Sage/UI/nls/ar-om/OwnerType',{});
},
'Sage/TaskPane/nls/ar/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-om/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-om/LeadTasksTasklet',{});
},
'Sage/UI/nls/ar/SDataLookup':function(){
define('Sage/UI/nls/ar/SDataLookup',{});
},
'Sage/UI/nls/ar-om/SDataLookup':function(){
define('Sage/UI/nls/ar-om/SDataLookup',{});
},
'Sage/TaskPane/nls/ar/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-om/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-om/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ar/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/ar-om/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar-om/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ar/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar/LibraryDocument',{});
},
'Sage/Utility/File/nls/ar-om/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar-om/LibraryDocument',{});
},
'Sage/UI/nls/ar/ConditionManager':function(){
define('Sage/UI/nls/ar/ConditionManager',{});
},
'Sage/UI/nls/ar-om/ConditionManager':function(){
define('Sage/UI/nls/ar-om/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ar/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/ar-om/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar-om/WidgetDefinition',{});
},
'Sage/UI/nls/ar/SearchConditionWidget':function(){
define('Sage/UI/nls/ar/SearchConditionWidget',{});
},
'Sage/UI/nls/ar-om/SearchConditionWidget':function(){
define('Sage/UI/nls/ar-om/SearchConditionWidget',{});
},
'Sage/UI/nls/ar/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/ar-om/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar-om/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/ar/Name':function(){
define('Sage/UI/Controls/nls/ar/Name',{});
},
'Sage/UI/Controls/nls/ar-om/Name':function(){
define('Sage/UI/Controls/nls/ar-om/Name',{});
},
'Sage/MainView/Lead/nls/ar/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/ar-om/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar-om/UpdateLeads',{});
},
'Sage/UI/nls/ar/ListPanel':function(){
define('Sage/UI/nls/ar/ListPanel',{});
},
'Sage/UI/nls/ar-om/ListPanel':function(){
define('Sage/UI/nls/ar-om/ListPanel',{});
},
'Sage/UI/Filters/nls/ar/EditFilters':function(){
define('Sage/UI/Filters/nls/ar/EditFilters',{});
},
'Sage/UI/Filters/nls/ar-om/EditFilters':function(){
define('Sage/UI/Filters/nls/ar-om/EditFilters',{});
},
'Sage/UI/Controls/nls/ar/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar/DurationSelect',{});
},
'Sage/UI/Controls/nls/ar-om/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar-om/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ar/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/ar-om/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar-om/AlarmCountDown',{});
},
'Sage/UI/nls/ar/AttachmentList':function(){
define('Sage/UI/nls/ar/AttachmentList',{});
},
'Sage/UI/nls/ar-om/AttachmentList':function(){
define('Sage/UI/nls/ar-om/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/ar-om/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar-om/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/ar/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/ar-om/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar-om/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/ar-om/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar-om/DashboardTabController',{});
},
'Sage/Groups/nls/ar/GroupNavigator':function(){
define('Sage/Groups/nls/ar/GroupNavigator',{});
},
'Sage/Groups/nls/ar-om/GroupNavigator':function(){
define('Sage/Groups/nls/ar-om/GroupNavigator',{});
},
'Sage/Utility/File/nls/ar/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar/AddURLAttachment',{});
},
'Sage/Utility/File/nls/ar-om/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar-om/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ar/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar/EditFilterItems',{});
},
'Sage/UI/Filters/nls/ar-om/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar-om/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-om/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-om/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-om/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-om/EventListPanelConfig',{});
},
'Sage/UI/nls/ar/ActivityScheduler':function(){
define('Sage/UI/nls/ar/ActivityScheduler',{});
},
'Sage/UI/nls/ar-om/ActivityScheduler':function(){
define('Sage/UI/nls/ar-om/ActivityScheduler',{});
},
'Sage/MainView/nls/ar/SecurityManager':function(){
define('Sage/MainView/nls/ar/SecurityManager',{});
},
'Sage/MainView/nls/ar-om/SecurityManager':function(){
define('Sage/MainView/nls/ar-om/SecurityManager',{});
},
'Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/ar-om/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar-om/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar-om/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar-om/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/ar/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/ar-om/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar-om/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/ar/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar/HelpMenu',{});
},
'Sage/UI/Controls/nls/ar-om/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar-om/HelpMenu',{});
},
'Sage/TaskPane/nls/ar/UserTasklet':function(){
define('Sage/TaskPane/nls/ar/UserTasklet',{});
},
'Sage/TaskPane/nls/ar-om/UserTasklet':function(){
define('Sage/TaskPane/nls/ar-om/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ar/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/ar-om/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar-om/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ar/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/ar-om/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar-om/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/ar/MenuHelper':function(){
define('Sage/MailMerge/nls/ar/MenuHelper',{});
},
'Sage/MailMerge/nls/ar-om/MenuHelper':function(){
define('Sage/MailMerge/nls/ar-om/MenuHelper',{});
},
'Sage/UI/nls/ar/SearchMenuItem':function(){
define('Sage/UI/nls/ar/SearchMenuItem',{});
},
'Sage/UI/nls/ar-om/SearchMenuItem':function(){
define('Sage/UI/nls/ar-om/SearchMenuItem',{});
},
'Sage/UI/nls/ar/NotesHistoryList':function(){
define('Sage/UI/nls/ar/NotesHistoryList',{});
},
'Sage/UI/nls/ar-om/NotesHistoryList':function(){
define('Sage/UI/nls/ar-om/NotesHistoryList',{});
},
'Sage/Utility/File/nls/ar/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/ar-om/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar-om/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-om/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-om/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-om/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-om/HistoryEditor',{});
},
'Sage/Groups/nls/ar/GroupManager':function(){
define('Sage/Groups/nls/ar/GroupManager',{});
},
'Sage/Groups/nls/ar-om/GroupManager':function(){
define('Sage/Groups/nls/ar-om/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/ar/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-om/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-om/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedAlarm',{});
},
'Sage/UI/Alarms/nls/ar-om/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/ar-om/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/ar-om/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar-om/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/ar/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-om/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-om/AccountingTasksTasklet',{});
},
'Sage/UI/nls/ar/EditableGrid':function(){
define('Sage/UI/nls/ar/EditableGrid',{});
},
'Sage/UI/nls/ar-om/EditableGrid':function(){
define('Sage/UI/nls/ar-om/EditableGrid',{});
},
'Sage/UI/nls/ar/SpeedSearch':function(){
define('Sage/UI/nls/ar/SpeedSearch',{});
},
'Sage/UI/nls/ar-om/SpeedSearch':function(){
define('Sage/UI/nls/ar-om/SpeedSearch',{});
},
'Sage/UI/nls/ar/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar/SLXPreviewGrid',{});
},
'Sage/UI/nls/ar-om/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar-om/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/ar-om/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar-om/UnconfirmedPane',{});
},
'Sage/Utility/nls/ar/Utility':function(){
define('Sage/Utility/nls/ar/Utility',{});
},
'Sage/Utility/nls/ar-om/Utility':function(){
define('Sage/Utility/nls/ar-om/Utility',{});
},
'Sage/UI/Controls/nls/ar/Address':function(){
define('Sage/UI/Controls/nls/ar/Address',{});
},
'Sage/UI/Controls/nls/ar-om/Address':function(){
define('Sage/UI/Controls/nls/ar-om/Address',{});
},
'Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-om/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-om/BaseListPanelConfig',{});
},
'Sage/UI/nls/ar/UserType':function(){
define('Sage/UI/nls/ar/UserType',{});
},
'Sage/UI/nls/ar-om/UserType':function(){
define('Sage/UI/nls/ar-om/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/ar-om/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar-om/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/ar/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/ar-om/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar-om/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/ar/ActivityList':function(){
define('Sage/UI/nls/ar/ActivityList',{});
},
'Sage/UI/nls/ar-om/ActivityList':function(){
define('Sage/UI/nls/ar-om/ActivityList',{});
},
'Sage/UI/nls/ar/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar/CalendarUsersListPane',{});
},
'Sage/UI/nls/ar-om/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar-om/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/ar-om/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar-om/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ar/Attachment':function(){
define('Sage/Utility/File/nls/ar/Attachment',{});
},
'Sage/Utility/File/nls/ar-om/Attachment':function(){
define('Sage/Utility/File/nls/ar-om/Attachment',{});
},
'Sage/MailMerge/nls/ar/Helper':function(){
define('Sage/MailMerge/nls/ar/Helper',{});
},
'Sage/MailMerge/nls/ar-om/Helper':function(){
define('Sage/MailMerge/nls/ar-om/Helper',{});
},
'Sage/UI/Dashboard/nls/ar/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar/Dashboard',{});
},
'Sage/UI/Dashboard/nls/ar-om/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar-om/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-om/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-om/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ar/PickList':function(){
define('Sage/UI/Controls/nls/ar/PickList',{});
},
'Sage/UI/Controls/nls/ar-om/PickList':function(){
define('Sage/UI/Controls/nls/ar-om/PickList',{});
},
'Sage/Utility/nls/ar/Email':function(){
define('Sage/Utility/nls/ar/Email',{});
},
'Sage/Utility/nls/ar-om/Email':function(){
define('Sage/Utility/nls/ar-om/Email',{});
},
'Sage/UI/nls/ar/TimeZoneItem':function(){
define('Sage/UI/nls/ar/TimeZoneItem',{});
},
'Sage/UI/nls/ar-om/TimeZoneItem':function(){
define('Sage/UI/nls/ar-om/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ar/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar/SlxEdit',{});
},
'Sage/UI/Columns/nls/ar-om/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar-om/SlxEdit',{});
},
'Sage/UI/Controls/nls/ar/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar/LogOffButton',{});
},
'Sage/UI/Controls/nls/ar-om/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar-om/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-om/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-om/EditEventEditor',{});
},
'Sage/MailMerge/nls/ar/Loader':function(){
define('Sage/MailMerge/nls/ar/Loader',{});
},
'Sage/MailMerge/nls/ar-om/Loader':function(){
define('Sage/MailMerge/nls/ar-om/Loader',{});
},
'Sage/UI/Controls/nls/ar/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar/DateTimePicker',{});
},
'Sage/UI/Controls/nls/ar-om/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar-om/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/ar-om/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar-om/AlarmPopup',{});
},
'Sage/UI/Controls/nls/ar/Lookup':function(){
define('Sage/UI/Controls/nls/ar/Lookup',{});
},
'Sage/UI/Controls/nls/ar-om/Lookup':function(){
define('Sage/UI/Controls/nls/ar-om/Lookup',{});
},
'Sage/Utility/File/nls/ar/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar/DescriptionsForm',{});
},
'Sage/Utility/File/nls/ar-om/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar-om/DescriptionsForm',{});
},
'Sage/TaskPane/nls/ar/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-om/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-om/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_ar-om", [], 1);
