require({cache:{
'Sage/Utility/File/nls/sr/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/sr/FallbackFilePicker',{});
},
'Sage/UI/nls/sr/Boolean':function(){
define('Sage/UI/nls/sr/Boolean',{});
},
'Sage/Services/nls/sr/ActivityService':function(){
define('Sage/Services/nls/sr/ActivityService',{});
},
'Sage/UI/Controls/nls/sr/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/sr/CopyToClipboard',{});
},
'Sage/Utility/nls/sr/Activity':function(){
define('Sage/Utility/nls/sr/Activity',{});
},
'Sage/QuickForms/Design/nls/sr/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/sr/DesignPanel',{});
},
'Sage/UI/nls/sr/TimelessActivitiesPane':function(){
define('Sage/UI/nls/sr/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/sr/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sr/ActivityEditor',{});
},
'Sage/MainView/nls/sr/ActivityManager':function(){
define('Sage/MainView/nls/sr/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/sr/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/_PropertyEditor',{});
},
'Sage/Services/nls/sr/ActivityActionProcessor':function(){
define('Sage/Services/nls/sr/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sr/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sr/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/sr/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/sr/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/sr/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/sr/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/sr/AlarmPane':function(){
define('Sage/UI/Alarms/nls/sr/AlarmPane',{});
},
'Sage/TaskPane/nls/sr/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/sr/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/sr/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/sr/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sr/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sr/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/sr/FilterPanel':function(){
define('Sage/UI/Filters/nls/sr/FilterPanel',{});
},
'Sage/TaskPane/nls/sr/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/sr/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/sr/OwnerType':function(){
define('Sage/UI/nls/sr/OwnerType',{});
},
'Sage/TaskPane/nls/sr/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/sr/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/sr/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/sr/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sr/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sr/InvoiceRTDV',{});
},
'Sage/UI/nls/sr/SDataLookup':function(){
define('Sage/UI/nls/sr/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/sr/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/RowDesigner',{});
},
'Sage/TaskPane/nls/sr/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/sr/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/sr/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/sr/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/sr/LibraryDocument':function(){
define('Sage/Utility/File/nls/sr/LibraryDocument',{});
},
'Sage/UI/nls/sr/ConditionManager':function(){
define('Sage/UI/nls/sr/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/sr/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/sr/WidgetDefinition',{});
},
'Sage/UI/nls/sr/SearchConditionWidget':function(){
define('Sage/UI/nls/sr/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/sr/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/sr/DataSourcePanel',{});
},
'Sage/UI/nls/sr/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/sr/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/sr/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/sr/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/sr/Name':function(){
define('Sage/UI/Controls/nls/sr/Name',{});
},
'Sage/QuickForms/Design/nls/sr/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/sr/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/sr/UpdateLeads',{});
},
'Sage/UI/nls/sr/ListPanel':function(){
define('Sage/UI/nls/sr/ListPanel',{});
},
'Sage/UI/Filters/nls/sr/EditFilters':function(){
define('Sage/UI/Filters/nls/sr/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/sr/DurationSelect':function(){
define('Sage/UI/Controls/nls/sr/DurationSelect',{});
},
'Sage/UI/Alarms/nls/sr/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/sr/AlarmCountDown',{});
},
'Sage/UI/nls/sr/AttachmentList':function(){
define('Sage/UI/nls/sr/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/sr/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sr/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sr/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/sr/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/sr/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/sr/Dialogs':function(){
define('Sage/UI/nls/sr/Dialogs',{});
},
'Sage/TaskPane/nls/sr/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/sr/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/sr/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/sr/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/sr/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sr/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/sr/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/UserControlDesigner',{});
},
'Sage/Groups/nls/sr/GroupNavigator':function(){
define('Sage/Groups/nls/sr/GroupNavigator',{});
},
'Sage/Utility/File/nls/sr/AddURLAttachment':function(){
define('Sage/Utility/File/nls/sr/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/sr/EditFilterItems':function(){
define('Sage/UI/Filters/nls/sr/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/sr/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/sr/DesignSurface',{});
},
'Sage/Utility/File/nls/sr/DragDropWatcher':function(){
define('Sage/Utility/File/nls/sr/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/sr/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sr/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sr/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sr/EventListPanelConfig',{});
},
'Sage/UI/nls/sr/ActivityScheduler':function(){
define('Sage/UI/nls/sr/ActivityScheduler',{});
},
'Sage/MainView/nls/sr/SecurityManager':function(){
define('Sage/MainView/nls/sr/SecurityManager',{});
},
'Sage/TaskPane/nls/sr/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/sr/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/sr/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/sr/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/sr/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/sr/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/sr/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/sr/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/sr/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/sr/HelpMenu':function(){
define('Sage/UI/Controls/nls/sr/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/sr/UserTasklet':function(){
define('Sage/TaskPane/nls/sr/UserTasklet',{});
},
'Sage/UI/Alarms/nls/sr/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/sr/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/sr/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/sr/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/sr/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/sr/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/sr/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/ColumnDesigner',{});
},
'Sage/UI/nls/sr/SearchMenuItem':function(){
define('Sage/UI/nls/sr/SearchMenuItem',{});
},
'Sage/UI/nls/sr/NotesHistoryList':function(){
define('Sage/UI/nls/sr/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/sr/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/sr/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/sr/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/sr/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sr/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sr/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sr/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sr/HistoryEditor',{});
},
'Sage/Groups/nls/sr/GroupManager':function(){
define('Sage/Groups/nls/sr/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sr/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sr/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/sr/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sr/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sr/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/sr/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/sr/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sr/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/sr/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/sr/EditableGrid':function(){
define('Sage/UI/nls/sr/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/sr/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/sr/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sr/SpeedSearch':function(){
define('Sage/UI/nls/sr/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sr/SLXPreviewGrid':function(){
define('Sage/UI/nls/sr/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/sr/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/sr/UnconfirmedPane',{});
},
'Sage/Utility/nls/sr/Utility':function(){
define('Sage/Utility/nls/sr/Utility',{});
},
'Sage/QuickForms/Design/nls/sr/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/ControlDesigner',{});
},
'Sage/UI/Controls/nls/sr/Address':function(){
define('Sage/UI/Controls/nls/sr/Address',{});
},
'Sage/MainView/ActivityMgr/nls/sr/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sr/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sr/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/OwnerControlDesigner',{});
},
'Sage/UI/nls/sr/UserType':function(){
define('Sage/UI/nls/sr/UserType',{});
},
'Sage/QuickForms/Design/nls/sr/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sr/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/sr/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/sr/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/sr/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sr/ActivityList':function(){
define('Sage/UI/nls/sr/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sr/CalendarUsersListPane':function(){
define('Sage/UI/nls/sr/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sr/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/sr/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sr/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/sr/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/sr/Attachment':function(){
define('Sage/Utility/File/nls/sr/Attachment',{});
},
'Sage/QuickForms/Design/nls/sr/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sr/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/sr/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/sr/Helper':function(){
define('Sage/MailMerge/nls/sr/Helper',{});
},
'Sage/UI/Dashboard/nls/sr/Dashboard':function(){
define('Sage/UI/Dashboard/nls/sr/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/sr/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sr/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/sr/PickList':function(){
define('Sage/UI/Controls/nls/sr/PickList',{});
},
'Sage/Utility/nls/sr/Email':function(){
define('Sage/Utility/nls/sr/Email',{});
},
'Sage/TaskPane/nls/sr/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sr/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/sr/TimeZoneItem':function(){
define('Sage/UI/nls/sr/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/sr/SlxEdit':function(){
define('Sage/UI/Columns/nls/sr/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/sr/LogOffButton':function(){
define('Sage/UI/Controls/nls/sr/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sr/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sr/EditEventEditor',{});
},
'Sage/MailMerge/nls/sr/Loader':function(){
define('Sage/MailMerge/nls/sr/Loader',{});
},
'Sage/UI/Controls/nls/sr/DateTimePicker':function(){
define('Sage/UI/Controls/nls/sr/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/sr/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/sr/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/sr/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sr/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sr/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/sr/Lookup':function(){
define('Sage/UI/Controls/nls/sr/Lookup',{});
},
'Sage/Utility/File/nls/sr/DescriptionsForm':function(){
define('Sage/Utility/File/nls/sr/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/sr/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sr/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sr/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/sr/CommonTasksTasklet',{});
},
'Sage/Utility/nls/sr/Dashboard':function(){
define('Sage/Utility/nls/sr/Dashboard',{});
}}});
define("Sage/nls/Sage_sr", [], 1);
