require({cache:{
'Sage/Utility/File/nls/ms/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ms/FallbackFilePicker',{});
},
'Sage/UI/nls/ms/Boolean':function(){
define('Sage/UI/nls/ms/Boolean',{});
},
'Sage/Services/nls/ms/ActivityService':function(){
define('Sage/Services/nls/ms/ActivityService',{});
},
'Sage/UI/Controls/nls/ms/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ms/CopyToClipboard',{});
},
'Sage/Utility/nls/ms/Activity':function(){
define('Sage/Utility/nls/ms/Activity',{});
},
'Sage/QuickForms/Design/nls/ms/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ms/DesignPanel',{});
},
'Sage/UI/nls/ms/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ms/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ms/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ms/ActivityEditor',{});
},
'Sage/MainView/nls/ms/ActivityManager':function(){
define('Sage/MainView/nls/ms/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/ms/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/_PropertyEditor',{});
},
'Sage/Services/nls/ms/ActivityActionProcessor':function(){
define('Sage/Services/nls/ms/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ms/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ms/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/ms/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ms/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ms/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ms/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ms/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ms/AlarmPane',{});
},
'Sage/TaskPane/nls/ms/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ms/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ms/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ms/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ms/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ms/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ms/FilterPanel':function(){
define('Sage/UI/Filters/nls/ms/FilterPanel',{});
},
'Sage/TaskPane/nls/ms/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ms/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/ms/OwnerType':function(){
define('Sage/UI/nls/ms/OwnerType',{});
},
'Sage/TaskPane/nls/ms/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ms/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ms/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ms/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ms/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ms/InvoiceRTDV',{});
},
'Sage/UI/nls/ms/SDataLookup':function(){
define('Sage/UI/nls/ms/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ms/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/RowDesigner',{});
},
'Sage/TaskPane/nls/ms/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ms/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ms/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ms/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ms/LibraryDocument':function(){
define('Sage/Utility/File/nls/ms/LibraryDocument',{});
},
'Sage/UI/nls/ms/ConditionManager':function(){
define('Sage/UI/nls/ms/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ms/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ms/WidgetDefinition',{});
},
'Sage/UI/nls/ms/SearchConditionWidget':function(){
define('Sage/UI/nls/ms/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/ms/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ms/DataSourcePanel',{});
},
'Sage/UI/nls/ms/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ms/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ms/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ms/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ms/Name':function(){
define('Sage/UI/Controls/nls/ms/Name',{});
},
'Sage/QuickForms/Design/nls/ms/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ms/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ms/UpdateLeads',{});
},
'Sage/UI/nls/ms/ListPanel':function(){
define('Sage/UI/nls/ms/ListPanel',{});
},
'Sage/UI/Filters/nls/ms/EditFilters':function(){
define('Sage/UI/Filters/nls/ms/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ms/DurationSelect':function(){
define('Sage/UI/Controls/nls/ms/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ms/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ms/AlarmCountDown',{});
},
'Sage/UI/nls/ms/AttachmentList':function(){
define('Sage/UI/nls/ms/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/ms/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ms/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ms/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ms/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ms/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ms/Dialogs':function(){
define('Sage/UI/nls/ms/Dialogs',{});
},
'Sage/TaskPane/nls/ms/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ms/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ms/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ms/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ms/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ms/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ms/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/UserControlDesigner',{});
},
'Sage/Groups/nls/ms/GroupNavigator':function(){
define('Sage/Groups/nls/ms/GroupNavigator',{});
},
'Sage/Utility/File/nls/ms/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ms/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ms/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ms/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/ms/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ms/DesignSurface',{});
},
'Sage/Utility/File/nls/ms/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ms/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/ms/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ms/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ms/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ms/EventListPanelConfig',{});
},
'Sage/UI/nls/ms/ActivityScheduler':function(){
define('Sage/UI/nls/ms/ActivityScheduler',{});
},
'Sage/MainView/nls/ms/SecurityManager':function(){
define('Sage/MainView/nls/ms/SecurityManager',{});
},
'Sage/TaskPane/nls/ms/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ms/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ms/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ms/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ms/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ms/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/ms/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ms/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/ms/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ms/HelpMenu':function(){
define('Sage/UI/Controls/nls/ms/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ms/UserTasklet':function(){
define('Sage/TaskPane/nls/ms/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ms/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ms/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ms/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ms/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/ms/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ms/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ms/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/ColumnDesigner',{});
},
'Sage/UI/nls/ms/SearchMenuItem':function(){
define('Sage/UI/nls/ms/SearchMenuItem',{});
},
'Sage/UI/nls/ms/NotesHistoryList':function(){
define('Sage/UI/nls/ms/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/ms/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/ms/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ms/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ms/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ms/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ms/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ms/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ms/HistoryEditor',{});
},
'Sage/Groups/nls/ms/GroupManager':function(){
define('Sage/Groups/nls/ms/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ms/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ms/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/ms/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ms/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ms/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ms/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ms/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ms/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ms/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ms/EditableGrid':function(){
define('Sage/UI/nls/ms/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/ms/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ms/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ms/SpeedSearch':function(){
define('Sage/UI/nls/ms/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ms/SLXPreviewGrid':function(){
define('Sage/UI/nls/ms/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ms/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ms/UnconfirmedPane',{});
},
'Sage/Utility/nls/ms/Utility':function(){
define('Sage/Utility/nls/ms/Utility',{});
},
'Sage/QuickForms/Design/nls/ms/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ms/Address':function(){
define('Sage/UI/Controls/nls/ms/Address',{});
},
'Sage/MainView/ActivityMgr/nls/ms/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ms/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ms/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/OwnerControlDesigner',{});
},
'Sage/UI/nls/ms/UserType':function(){
define('Sage/UI/nls/ms/UserType',{});
},
'Sage/QuickForms/Design/nls/ms/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ms/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ms/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/ms/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ms/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ms/ActivityList':function(){
define('Sage/UI/nls/ms/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ms/CalendarUsersListPane':function(){
define('Sage/UI/nls/ms/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ms/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ms/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ms/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ms/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ms/Attachment':function(){
define('Sage/Utility/File/nls/ms/Attachment',{});
},
'Sage/QuickForms/Design/nls/ms/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ms/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ms/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/ms/Helper':function(){
define('Sage/MailMerge/nls/ms/Helper',{});
},
'Sage/UI/Dashboard/nls/ms/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ms/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ms/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ms/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ms/PickList':function(){
define('Sage/UI/Controls/nls/ms/PickList',{});
},
'Sage/Utility/nls/ms/Email':function(){
define('Sage/Utility/nls/ms/Email',{});
},
'Sage/TaskPane/nls/ms/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ms/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ms/TimeZoneItem':function(){
define('Sage/UI/nls/ms/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ms/SlxEdit':function(){
define('Sage/UI/Columns/nls/ms/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/ms/LogOffButton':function(){
define('Sage/UI/Controls/nls/ms/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ms/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ms/EditEventEditor',{});
},
'Sage/MailMerge/nls/ms/Loader':function(){
define('Sage/MailMerge/nls/ms/Loader',{});
},
'Sage/UI/Controls/nls/ms/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ms/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/ms/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ms/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/ms/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ms/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ms/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ms/Lookup':function(){
define('Sage/UI/Controls/nls/ms/Lookup',{});
},
'Sage/Utility/File/nls/ms/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ms/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ms/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ms/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ms/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ms/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ms/Dashboard':function(){
define('Sage/Utility/nls/ms/Dashboard',{});
}}});
define("Sage/nls/Sage_ms", [], 1);
