require({cache:{
'Sage/Utility/File/nls/fo/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/fo/FallbackFilePicker',{});
},
'Sage/UI/nls/fo/Boolean':function(){
define('Sage/UI/nls/fo/Boolean',{});
},
'Sage/Services/nls/fo/ActivityService':function(){
define('Sage/Services/nls/fo/ActivityService',{});
},
'Sage/UI/Controls/nls/fo/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/fo/CopyToClipboard',{});
},
'Sage/Utility/nls/fo/Activity':function(){
define('Sage/Utility/nls/fo/Activity',{});
},
'Sage/QuickForms/Design/nls/fo/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/fo/DesignPanel',{});
},
'Sage/UI/nls/fo/TimelessActivitiesPane':function(){
define('Sage/UI/nls/fo/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/fo/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fo/ActivityEditor',{});
},
'Sage/MainView/nls/fo/ActivityManager':function(){
define('Sage/MainView/nls/fo/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/fo/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/_PropertyEditor',{});
},
'Sage/Services/nls/fo/ActivityActionProcessor':function(){
define('Sage/Services/nls/fo/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/fo/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fo/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/fo/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/fo/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/fo/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/fo/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/fo/AlarmPane':function(){
define('Sage/UI/Alarms/nls/fo/AlarmPane',{});
},
'Sage/TaskPane/nls/fo/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/fo/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/fo/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/fo/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/fo/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/fo/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/fo/FilterPanel':function(){
define('Sage/UI/Filters/nls/fo/FilterPanel',{});
},
'Sage/TaskPane/nls/fo/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/fo/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/fo/OwnerType':function(){
define('Sage/UI/nls/fo/OwnerType',{});
},
'Sage/TaskPane/nls/fo/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/fo/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/fo/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/fo/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/fo/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/fo/InvoiceRTDV',{});
},
'Sage/UI/nls/fo/SDataLookup':function(){
define('Sage/UI/nls/fo/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/fo/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/RowDesigner',{});
},
'Sage/TaskPane/nls/fo/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/fo/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/fo/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/fo/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/fo/LibraryDocument':function(){
define('Sage/Utility/File/nls/fo/LibraryDocument',{});
},
'Sage/UI/nls/fo/ConditionManager':function(){
define('Sage/UI/nls/fo/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/fo/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/fo/WidgetDefinition',{});
},
'Sage/UI/nls/fo/SearchConditionWidget':function(){
define('Sage/UI/nls/fo/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/fo/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/fo/DataSourcePanel',{});
},
'Sage/UI/nls/fo/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/fo/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/fo/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/fo/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/fo/Name':function(){
define('Sage/UI/Controls/nls/fo/Name',{});
},
'Sage/QuickForms/Design/nls/fo/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/fo/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/fo/UpdateLeads',{});
},
'Sage/UI/nls/fo/ListPanel':function(){
define('Sage/UI/nls/fo/ListPanel',{});
},
'Sage/UI/Filters/nls/fo/EditFilters':function(){
define('Sage/UI/Filters/nls/fo/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/fo/DurationSelect':function(){
define('Sage/UI/Controls/nls/fo/DurationSelect',{});
},
'Sage/UI/Alarms/nls/fo/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/fo/AlarmCountDown',{});
},
'Sage/UI/nls/fo/AttachmentList':function(){
define('Sage/UI/nls/fo/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/fo/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fo/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fo/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/fo/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/fo/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/fo/Dialogs':function(){
define('Sage/UI/nls/fo/Dialogs',{});
},
'Sage/TaskPane/nls/fo/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/fo/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/fo/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/fo/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/fo/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/fo/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/fo/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/UserControlDesigner',{});
},
'Sage/Groups/nls/fo/GroupNavigator':function(){
define('Sage/Groups/nls/fo/GroupNavigator',{});
},
'Sage/Utility/File/nls/fo/AddURLAttachment':function(){
define('Sage/Utility/File/nls/fo/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/fo/EditFilterItems':function(){
define('Sage/UI/Filters/nls/fo/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/fo/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/fo/DesignSurface',{});
},
'Sage/Utility/File/nls/fo/DragDropWatcher':function(){
define('Sage/Utility/File/nls/fo/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/fo/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fo/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/fo/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fo/EventListPanelConfig',{});
},
'Sage/UI/nls/fo/ActivityScheduler':function(){
define('Sage/UI/nls/fo/ActivityScheduler',{});
},
'Sage/MainView/nls/fo/SecurityManager':function(){
define('Sage/MainView/nls/fo/SecurityManager',{});
},
'Sage/TaskPane/nls/fo/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/fo/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/fo/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/fo/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/fo/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/fo/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/fo/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/fo/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/fo/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/fo/HelpMenu':function(){
define('Sage/UI/Controls/nls/fo/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/fo/UserTasklet':function(){
define('Sage/TaskPane/nls/fo/UserTasklet',{});
},
'Sage/UI/Alarms/nls/fo/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/fo/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/fo/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/fo/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/fo/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/fo/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/fo/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/ColumnDesigner',{});
},
'Sage/UI/nls/fo/SearchMenuItem':function(){
define('Sage/UI/nls/fo/SearchMenuItem',{});
},
'Sage/UI/nls/fo/NotesHistoryList':function(){
define('Sage/UI/nls/fo/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/fo/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/fo/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/fo/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/fo/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/fo/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fo/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/fo/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fo/HistoryEditor',{});
},
'Sage/Groups/nls/fo/GroupManager':function(){
define('Sage/Groups/nls/fo/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/fo/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fo/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/fo/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fo/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fo/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/fo/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/fo/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/fo/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/fo/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/fo/EditableGrid':function(){
define('Sage/UI/nls/fo/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/fo/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/fo/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/fo/SpeedSearch':function(){
define('Sage/UI/nls/fo/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/fo/SLXPreviewGrid':function(){
define('Sage/UI/nls/fo/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/fo/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/fo/UnconfirmedPane',{});
},
'Sage/Utility/nls/fo/Utility':function(){
define('Sage/Utility/nls/fo/Utility',{});
},
'Sage/QuickForms/Design/nls/fo/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/ControlDesigner',{});
},
'Sage/UI/Controls/nls/fo/Address':function(){
define('Sage/UI/Controls/nls/fo/Address',{});
},
'Sage/MainView/ActivityMgr/nls/fo/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fo/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/fo/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/OwnerControlDesigner',{});
},
'Sage/UI/nls/fo/UserType':function(){
define('Sage/UI/nls/fo/UserType',{});
},
'Sage/QuickForms/Design/nls/fo/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/fo/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/fo/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/fo/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/fo/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/fo/ActivityList':function(){
define('Sage/UI/nls/fo/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/fo/CalendarUsersListPane':function(){
define('Sage/UI/nls/fo/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/fo/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/fo/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/fo/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/fo/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/fo/Attachment':function(){
define('Sage/Utility/File/nls/fo/Attachment',{});
},
'Sage/QuickForms/Design/nls/fo/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fo/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/fo/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/fo/Helper':function(){
define('Sage/MailMerge/nls/fo/Helper',{});
},
'Sage/UI/Dashboard/nls/fo/Dashboard':function(){
define('Sage/UI/Dashboard/nls/fo/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/fo/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fo/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/fo/PickList':function(){
define('Sage/UI/Controls/nls/fo/PickList',{});
},
'Sage/Utility/nls/fo/Email':function(){
define('Sage/Utility/nls/fo/Email',{});
},
'Sage/TaskPane/nls/fo/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/fo/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/fo/TimeZoneItem':function(){
define('Sage/UI/nls/fo/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/fo/SlxEdit':function(){
define('Sage/UI/Columns/nls/fo/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/fo/LogOffButton':function(){
define('Sage/UI/Controls/nls/fo/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/fo/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fo/EditEventEditor',{});
},
'Sage/MailMerge/nls/fo/Loader':function(){
define('Sage/MailMerge/nls/fo/Loader',{});
},
'Sage/UI/Controls/nls/fo/DateTimePicker':function(){
define('Sage/UI/Controls/nls/fo/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/fo/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/fo/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/fo/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fo/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fo/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/fo/Lookup':function(){
define('Sage/UI/Controls/nls/fo/Lookup',{});
},
'Sage/Utility/File/nls/fo/DescriptionsForm':function(){
define('Sage/Utility/File/nls/fo/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/fo/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fo/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/fo/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/fo/CommonTasksTasklet',{});
},
'Sage/Utility/nls/fo/Dashboard':function(){
define('Sage/Utility/nls/fo/Dashboard',{});
}}});
define("Sage/nls/Sage_fo", [], 1);
