require({cache:{
'Sage/Utility/File/nls/ga/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ga/FallbackFilePicker',{});
},
'Sage/UI/nls/ga/Boolean':function(){
define('Sage/UI/nls/ga/Boolean',{});
},
'Sage/UI/Controls/nls/ga/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ga/CopyToClipboard',{});
},
'Sage/Services/nls/ga/ActivityService':function(){
define('Sage/Services/nls/ga/ActivityService',{});
},
'Sage/Utility/nls/ga/Activity':function(){
define('Sage/Utility/nls/ga/Activity',{});
},
'Sage/UI/nls/ga/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ga/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ga/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ga/ActivityEditor',{});
},
'Sage/MainView/nls/ga/ActivityManager':function(){
define('Sage/MainView/nls/ga/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/ga/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ga/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/ga/Service':function(){
define('Sage/Reporting/nls/ga/Service',{});
},
'Sage/Utility/File/nls/ga/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ga/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ga/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ga/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ga/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ga/AlarmPane',{});
},
'Sage/TaskPane/nls/ga/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ga/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ga/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ga/DashboardWidget',{});
},
'Sage/UI/Filters/nls/ga/FilterPanel':function(){
define('Sage/UI/Filters/nls/ga/FilterPanel',{});
},
'Sage/TaskPane/nls/ga/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ga/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/ga/OwnerType':function(){
define('Sage/UI/nls/ga/OwnerType',{});
},
'Sage/TaskPane/nls/ga/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ga/LeadTasksTasklet',{});
},
'Sage/UI/nls/ga/SDataLookup':function(){
define('Sage/UI/nls/ga/SDataLookup',{});
},
'Sage/TaskPane/nls/ga/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ga/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ga/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ga/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ga/LibraryDocument':function(){
define('Sage/Utility/File/nls/ga/LibraryDocument',{});
},
'Sage/UI/nls/ga/ConditionManager':function(){
define('Sage/UI/nls/ga/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ga/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ga/WidgetDefinition',{});
},
'Sage/UI/nls/ga/SearchConditionWidget':function(){
define('Sage/UI/nls/ga/SearchConditionWidget',{});
},
'Sage/UI/nls/ga/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ga/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/ga/Name':function(){
define('Sage/UI/Controls/nls/ga/Name',{});
},
'Sage/MainView/Lead/nls/ga/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ga/UpdateLeads',{});
},
'Sage/UI/nls/ga/ListPanel':function(){
define('Sage/UI/nls/ga/ListPanel',{});
},
'Sage/UI/Filters/nls/ga/EditFilters':function(){
define('Sage/UI/Filters/nls/ga/EditFilters',{});
},
'Sage/UI/Controls/nls/ga/DurationSelect':function(){
define('Sage/UI/Controls/nls/ga/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ga/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ga/AlarmCountDown',{});
},
'Sage/UI/nls/ga/AttachmentList':function(){
define('Sage/UI/nls/ga/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/ga/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ga/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/ga/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ga/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ga/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ga/DashboardTabController',{});
},
'Sage/Groups/nls/ga/GroupNavigator':function(){
define('Sage/Groups/nls/ga/GroupNavigator',{});
},
'Sage/Utility/File/nls/ga/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ga/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ga/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ga/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/ga/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ga/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ga/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ga/EventListPanelConfig',{});
},
'Sage/UI/nls/ga/ActivityScheduler':function(){
define('Sage/UI/nls/ga/ActivityScheduler',{});
},
'Sage/MainView/nls/ga/SecurityManager':function(){
define('Sage/MainView/nls/ga/SecurityManager',{});
},
'Sage/TaskPane/nls/ga/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ga/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/ga/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ga/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/ga/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ga/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/ga/HelpMenu':function(){
define('Sage/UI/Controls/nls/ga/HelpMenu',{});
},
'Sage/TaskPane/nls/ga/UserTasklet':function(){
define('Sage/TaskPane/nls/ga/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ga/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ga/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ga/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ga/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/ga/MenuHelper':function(){
define('Sage/MailMerge/nls/ga/MenuHelper',{});
},
'Sage/UI/nls/ga/SearchMenuItem':function(){
define('Sage/UI/nls/ga/SearchMenuItem',{});
},
'Sage/UI/nls/ga/NotesHistoryList':function(){
define('Sage/UI/nls/ga/NotesHistoryList',{});
},
'Sage/Utility/File/nls/ga/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ga/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/ga/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ga/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ga/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ga/HistoryEditor',{});
},
'Sage/Groups/nls/ga/GroupManager':function(){
define('Sage/Groups/nls/ga/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/ga/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ga/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/ga/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/ga/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/ga/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ga/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/ga/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ga/AccountingTasksTasklet',{});
},
'Sage/UI/nls/ga/EditableGrid':function(){
define('Sage/UI/nls/ga/EditableGrid',{});
},
'Sage/UI/nls/ga/SpeedSearch':function(){
define('Sage/UI/nls/ga/SpeedSearch',{});
},
'Sage/UI/nls/ga/SLXPreviewGrid':function(){
define('Sage/UI/nls/ga/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ga/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ga/UnconfirmedPane',{});
},
'Sage/Utility/nls/ga/Utility':function(){
define('Sage/Utility/nls/ga/Utility',{});
},
'Sage/UI/Controls/nls/ga/Address':function(){
define('Sage/UI/Controls/nls/ga/Address',{});
},
'Sage/MainView/ActivityMgr/nls/ga/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ga/BaseListPanelConfig',{});
},
'Sage/UI/nls/ga/UserType':function(){
define('Sage/UI/nls/ga/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/ga/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ga/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/ga/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ga/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/ga/ActivityList':function(){
define('Sage/UI/nls/ga/ActivityList',{});
},
'Sage/UI/nls/ga/CalendarUsersListPane':function(){
define('Sage/UI/nls/ga/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/ga/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ga/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ga/Attachment':function(){
define('Sage/Utility/File/nls/ga/Attachment',{});
},
'Sage/MailMerge/nls/ga/Helper':function(){
define('Sage/MailMerge/nls/ga/Helper',{});
},
'Sage/UI/Dashboard/nls/ga/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ga/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ga/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ga/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ga/PickList':function(){
define('Sage/UI/Controls/nls/ga/PickList',{});
},
'Sage/Utility/nls/ga/Email':function(){
define('Sage/Utility/nls/ga/Email',{});
},
'Sage/UI/nls/ga/TimeZoneItem':function(){
define('Sage/UI/nls/ga/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ga/SlxEdit':function(){
define('Sage/UI/Columns/nls/ga/SlxEdit',{});
},
'Sage/UI/Controls/nls/ga/LogOffButton':function(){
define('Sage/UI/Controls/nls/ga/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/ga/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ga/EditEventEditor',{});
},
'Sage/MailMerge/nls/ga/Loader':function(){
define('Sage/MailMerge/nls/ga/Loader',{});
},
'Sage/UI/Controls/nls/ga/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ga/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/ga/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ga/AlarmPopup',{});
},
'Sage/UI/Controls/nls/ga/Lookup':function(){
define('Sage/UI/Controls/nls/ga/Lookup',{});
},
'Sage/Utility/File/nls/ga/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ga/DescriptionsForm',{});
},
'Sage/TaskPane/nls/ga/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ga/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_ga", [], 1);
