require({cache:{
'Sage/Utility/File/nls/zh/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zh/FallbackFilePicker',{});
},
'Sage/UI/nls/zh/Boolean':function(){
define('Sage/UI/nls/zh/Boolean',{});
},
'Sage/Services/nls/zh/ActivityService':function(){
define('Sage/Services/nls/zh/ActivityService',{});
},
'Sage/UI/Controls/nls/zh/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zh/CopyToClipboard',{});
},
'Sage/Utility/nls/zh/Activity':function(){
define('Sage/Utility/nls/zh/Activity',{});
},
'Sage/QuickForms/Design/nls/zh/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/zh/DesignPanel',{});
},
'Sage/UI/nls/zh/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zh/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityEditor',{});
},
'Sage/MainView/nls/zh/ActivityManager':function(){
define('Sage/MainView/nls/zh/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/zh/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/_PropertyEditor',{});
},
'Sage/Services/nls/zh/ActivityActionProcessor':function(){
define('Sage/Services/nls/zh/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/zh/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zh/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/zh/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zh/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/zh/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zh/AlarmPane',{});
},
'Sage/TaskPane/nls/zh/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zh/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/zh/FilterPanel':function(){
define('Sage/UI/Filters/nls/zh/FilterPanel',{});
},
'Sage/TaskPane/nls/zh/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zh/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/zh/OwnerType':function(){
define('Sage/UI/nls/zh/OwnerType',{});
},
'Sage/TaskPane/nls/zh/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/zh/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/zh/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/InvoiceRTDV',{});
},
'Sage/UI/nls/zh/SDataLookup':function(){
define('Sage/UI/nls/zh/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/zh/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/RowDesigner',{});
},
'Sage/TaskPane/nls/zh/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/zh/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zh/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/zh/LibraryDocument':function(){
define('Sage/Utility/File/nls/zh/LibraryDocument',{});
},
'Sage/UI/nls/zh/ConditionManager':function(){
define('Sage/UI/nls/zh/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/zh/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zh/WidgetDefinition',{});
},
'Sage/UI/nls/zh/SearchConditionWidget':function(){
define('Sage/UI/nls/zh/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/zh/DataSourcePanel',{});
},
'Sage/UI/nls/zh/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zh/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/zh/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/zh/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/zh/Name':function(){
define('Sage/UI/Controls/nls/zh/Name',{});
},
'Sage/QuickForms/Design/nls/zh/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/zh/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zh/UpdateLeads',{});
},
'Sage/UI/nls/zh/ListPanel':function(){
define('Sage/UI/nls/zh/ListPanel',{});
},
'Sage/UI/Filters/nls/zh/EditFilters':function(){
define('Sage/UI/Filters/nls/zh/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/zh/DurationSelect':function(){
define('Sage/UI/Controls/nls/zh/DurationSelect',{});
},
'Sage/UI/Alarms/nls/zh/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zh/AlarmCountDown',{});
},
'Sage/UI/nls/zh/AttachmentList':function(){
define('Sage/UI/nls/zh/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/zh/Dialogs':function(){
define('Sage/UI/nls/zh/Dialogs',{});
},
'Sage/TaskPane/nls/zh/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zh/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/zh/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/zh/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/UserControlDesigner',{});
},
'Sage/Groups/nls/zh/GroupNavigator':function(){
define('Sage/Groups/nls/zh/GroupNavigator',{});
},
'Sage/Utility/File/nls/zh/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zh/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/zh/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zh/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/zh/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/zh/DesignSurface',{});
},
'Sage/Utility/File/nls/zh/DragDropWatcher':function(){
define('Sage/Utility/File/nls/zh/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/EventListPanelConfig',{});
},
'Sage/UI/nls/zh/ActivityScheduler':function(){
define('Sage/UI/nls/zh/ActivityScheduler',{});
},
'Sage/MainView/nls/zh/SecurityManager':function(){
define('Sage/MainView/nls/zh/SecurityManager',{});
},
'Sage/TaskPane/nls/zh/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zh/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/zh/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/zh/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/zh/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zh/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/zh/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/HelpMenu':function(){
define('Sage/UI/Controls/nls/zh/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/UserTasklet':function(){
define('Sage/TaskPane/nls/zh/UserTasklet',{});
},
'Sage/UI/Alarms/nls/zh/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zh/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/zh/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zh/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/zh/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/zh/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/zh/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ColumnDesigner',{});
},
'Sage/UI/nls/zh/SearchMenuItem':function(){
define('Sage/UI/nls/zh/SearchMenuItem',{});
},
'Sage/UI/nls/zh/NotesHistoryList':function(){
define('Sage/UI/nls/zh/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/zh/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/zh/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zh/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/zh/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zh/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/HistoryEditor',{});
},
'Sage/Groups/nls/zh/GroupManager':function(){
define('Sage/Groups/nls/zh/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/zh/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zh/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/zh/EditableGrid':function(){
define('Sage/UI/nls/zh/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/zh/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/zh/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/SpeedSearch':function(){
define('Sage/UI/nls/zh/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/SLXPreviewGrid':function(){
define('Sage/UI/nls/zh/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/zh/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zh/UnconfirmedPane',{});
},
'Sage/Utility/nls/zh/Utility':function(){
define('Sage/Utility/nls/zh/Utility',{});
},
'Sage/QuickForms/Design/nls/zh/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/Address':function(){
define('Sage/UI/Controls/nls/zh/Address',{});
},
'Sage/MainView/ActivityMgr/nls/zh/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zh/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/OwnerControlDesigner',{});
},
'Sage/UI/nls/zh/UserType':function(){
define('Sage/UI/nls/zh/UserType',{});
},
'Sage/QuickForms/Design/nls/zh/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/zh/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zh/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/ActivityList':function(){
define('Sage/UI/nls/zh/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/CalendarUsersListPane':function(){
define('Sage/UI/nls/zh/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/zh/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zh/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/zh/Attachment':function(){
define('Sage/Utility/File/nls/zh/Attachment',{});
},
'Sage/QuickForms/Design/nls/zh/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/zh/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/zh/Helper':function(){
define('Sage/MailMerge/nls/zh/Helper',{});
},
'Sage/UI/Dashboard/nls/zh/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zh/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/zh/PickList':function(){
define('Sage/UI/Controls/nls/zh/PickList',{});
},
'Sage/Utility/nls/zh/Email':function(){
define('Sage/Utility/nls/zh/Email',{});
},
'Sage/TaskPane/nls/zh/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/zh/TimeZoneItem':function(){
define('Sage/UI/nls/zh/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/zh/SlxEdit':function(){
define('Sage/UI/Columns/nls/zh/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/zh/LogOffButton':function(){
define('Sage/UI/Controls/nls/zh/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/EditEventEditor',{});
},
'Sage/MailMerge/nls/zh/Loader':function(){
define('Sage/MailMerge/nls/zh/Loader',{});
},
'Sage/UI/Controls/nls/zh/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zh/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/zh/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zh/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/Lookup':function(){
define('Sage/UI/Controls/nls/zh/Lookup',{});
},
'Sage/Utility/File/nls/zh/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zh/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/CommonTasksTasklet',{});
},
'Sage/Utility/nls/zh/Dashboard':function(){
define('Sage/Utility/nls/zh/Dashboard',{});
}}});
define("Sage/nls/Sage_zh", [], 1);
