require({cache:{
'Sage/Utility/File/nls/zh/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zh/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/zh-tw/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zh-tw/FallbackFilePicker',{});
},
'Sage/UI/nls/zh/Boolean':function(){
define('Sage/UI/nls/zh/Boolean',{});
},
'Sage/UI/nls/zh-tw/Boolean':function(){
define('Sage/UI/nls/zh-tw/Boolean',{});
},
'Sage/Services/nls/zh/ActivityService':function(){
define('Sage/Services/nls/zh/ActivityService',{});
},
'Sage/Services/nls/zh-tw/ActivityService':function(){
define('Sage/Services/nls/zh-tw/ActivityService',{});
},
'Sage/UI/Controls/nls/zh/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zh/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/zh-tw/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zh-tw/CopyToClipboard',{});
},
'Sage/Utility/nls/zh/Activity':function(){
define('Sage/Utility/nls/zh/Activity',{});
},
'Sage/Utility/nls/zh-tw/Activity':function(){
define('Sage/Utility/nls/zh-tw/Activity',{});
},
'Sage/QuickForms/Design/nls/zh/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/zh/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/zh-tw/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/zh-tw/DesignPanel',{});
},
'Sage/UI/nls/zh/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zh/TimelessActivitiesPane',{});
},
'Sage/UI/nls/zh-tw/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zh-tw/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-tw/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-tw/ActivityEditor',{});
},
'Sage/MainView/nls/zh/ActivityManager':function(){
define('Sage/MainView/nls/zh/ActivityManager',{});
},
'Sage/MainView/nls/zh-tw/ActivityManager':function(){
define('Sage/MainView/nls/zh-tw/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/zh/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/_PropertyEditor',{});
},
'Sage/Services/nls/zh/ActivityActionProcessor':function(){
define('Sage/Services/nls/zh/ActivityActionProcessor',{});
},
'Sage/Services/nls/zh-tw/ActivityActionProcessor':function(){
define('Sage/Services/nls/zh-tw/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-tw/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-tw/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/zh/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zh/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/zh-tw/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zh-tw/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/zh/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zh/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/zh-tw/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zh-tw/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/zh/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zh/AlarmPane',{});
},
'Sage/UI/Alarms/nls/zh-tw/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zh-tw/AlarmPane',{});
},
'Sage/TaskPane/nls/zh/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zh/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/zh-tw/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zh-tw/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/zh-tw/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zh-tw/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zh-tw/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh-tw/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/zh/FilterPanel':function(){
define('Sage/UI/Filters/nls/zh/FilterPanel',{});
},
'Sage/UI/Filters/nls/zh-tw/FilterPanel':function(){
define('Sage/UI/Filters/nls/zh-tw/FilterPanel',{});
},
'Sage/TaskPane/nls/zh/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zh/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/zh-tw/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zh-tw/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/zh/OwnerType':function(){
define('Sage/UI/nls/zh/OwnerType',{});
},
'Sage/UI/nls/zh-tw/OwnerType':function(){
define('Sage/UI/nls/zh-tw/OwnerType',{});
},
'Sage/TaskPane/nls/zh/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-tw/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-tw/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/zh/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/zh/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/zh-tw/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/zh-tw/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zh-tw/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh-tw/InvoiceRTDV',{});
},
'Sage/UI/nls/zh/SDataLookup':function(){
define('Sage/UI/nls/zh/SDataLookup',{});
},
'Sage/UI/nls/zh-tw/SDataLookup':function(){
define('Sage/UI/nls/zh-tw/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/zh/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/RowDesigner',{});
},
'Sage/TaskPane/nls/zh/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-tw/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-tw/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/zh/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zh/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/zh-tw/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zh-tw/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/zh/LibraryDocument':function(){
define('Sage/Utility/File/nls/zh/LibraryDocument',{});
},
'Sage/Utility/File/nls/zh-tw/LibraryDocument':function(){
define('Sage/Utility/File/nls/zh-tw/LibraryDocument',{});
},
'Sage/UI/nls/zh/ConditionManager':function(){
define('Sage/UI/nls/zh/ConditionManager',{});
},
'Sage/UI/nls/zh-tw/ConditionManager':function(){
define('Sage/UI/nls/zh-tw/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/zh/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zh/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/zh-tw/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zh-tw/WidgetDefinition',{});
},
'Sage/UI/nls/zh/SearchConditionWidget':function(){
define('Sage/UI/nls/zh/SearchConditionWidget',{});
},
'Sage/UI/nls/zh-tw/SearchConditionWidget':function(){
define('Sage/UI/nls/zh-tw/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/zh/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/zh-tw/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/zh-tw/DataSourcePanel',{});
},
'Sage/UI/nls/zh/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zh/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/zh-tw/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zh-tw/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/zh/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/zh/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/zh-tw/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/zh-tw/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/zh/Name':function(){
define('Sage/UI/Controls/nls/zh/Name',{});
},
'Sage/UI/Controls/nls/zh-tw/Name':function(){
define('Sage/UI/Controls/nls/zh-tw/Name',{});
},
'Sage/QuickForms/Design/nls/zh/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/zh/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zh/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/zh-tw/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zh-tw/UpdateLeads',{});
},
'Sage/UI/nls/zh/ListPanel':function(){
define('Sage/UI/nls/zh/ListPanel',{});
},
'Sage/UI/nls/zh-tw/ListPanel':function(){
define('Sage/UI/nls/zh-tw/ListPanel',{});
},
'Sage/UI/Filters/nls/zh/EditFilters':function(){
define('Sage/UI/Filters/nls/zh/EditFilters',{});
},
'Sage/UI/Filters/nls/zh-tw/EditFilters':function(){
define('Sage/UI/Filters/nls/zh-tw/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/zh/DurationSelect':function(){
define('Sage/UI/Controls/nls/zh/DurationSelect',{});
},
'Sage/UI/Controls/nls/zh-tw/DurationSelect':function(){
define('Sage/UI/Controls/nls/zh-tw/DurationSelect',{});
},
'Sage/UI/Alarms/nls/zh/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zh/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/zh-tw/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zh-tw/AlarmCountDown',{});
},
'Sage/UI/nls/zh/AttachmentList':function(){
define('Sage/UI/nls/zh/AttachmentList',{});
},
'Sage/UI/nls/zh-tw/AttachmentList':function(){
define('Sage/UI/nls/zh-tw/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/zh-tw/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zh-tw/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/zh/Dialogs':function(){
define('Sage/UI/nls/zh/Dialogs',{});
},
'Sage/UI/nls/zh-tw/Dialogs':function(){
define('Sage/UI/nls/zh-tw/Dialogs',{});
},
'Sage/TaskPane/nls/zh/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zh/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/zh-tw/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zh-tw/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/zh-tw/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zh-tw/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/zh/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zh-tw/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh-tw/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/zh/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/UserControlDesigner',{});
},
'Sage/Groups/nls/zh/GroupNavigator':function(){
define('Sage/Groups/nls/zh/GroupNavigator',{});
},
'Sage/Groups/nls/zh-tw/GroupNavigator':function(){
define('Sage/Groups/nls/zh-tw/GroupNavigator',{});
},
'Sage/Utility/File/nls/zh/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zh/AddURLAttachment',{});
},
'Sage/Utility/File/nls/zh-tw/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zh-tw/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/zh/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zh/EditFilterItems',{});
},
'Sage/UI/Filters/nls/zh-tw/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zh-tw/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/zh/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/zh/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/zh-tw/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/zh-tw/DesignSurface',{});
},
'Sage/Utility/File/nls/zh/DragDropWatcher':function(){
define('Sage/Utility/File/nls/zh/DragDropWatcher',{});
},
'Sage/Utility/File/nls/zh-tw/DragDropWatcher':function(){
define('Sage/Utility/File/nls/zh-tw/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-tw/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-tw/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-tw/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-tw/EventListPanelConfig',{});
},
'Sage/UI/nls/zh/ActivityScheduler':function(){
define('Sage/UI/nls/zh/ActivityScheduler',{});
},
'Sage/UI/nls/zh-tw/ActivityScheduler':function(){
define('Sage/UI/nls/zh-tw/ActivityScheduler',{});
},
'Sage/MainView/nls/zh/SecurityManager':function(){
define('Sage/MainView/nls/zh/SecurityManager',{});
},
'Sage/MainView/nls/zh-tw/SecurityManager':function(){
define('Sage/MainView/nls/zh-tw/SecurityManager',{});
},
'Sage/TaskPane/nls/zh/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zh/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/zh-tw/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zh-tw/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/zh/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/zh/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/zh-tw/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/zh-tw/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/zh-tw/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zh-tw/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/zh/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zh/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/zh-tw/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zh-tw/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/zh/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/HelpMenu':function(){
define('Sage/UI/Controls/nls/zh/HelpMenu',{});
},
'Sage/UI/Controls/nls/zh-tw/HelpMenu':function(){
define('Sage/UI/Controls/nls/zh-tw/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/UserTasklet':function(){
define('Sage/TaskPane/nls/zh/UserTasklet',{});
},
'Sage/TaskPane/nls/zh-tw/UserTasklet':function(){
define('Sage/TaskPane/nls/zh-tw/UserTasklet',{});
},
'Sage/UI/Alarms/nls/zh/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zh/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/zh-tw/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zh-tw/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/zh/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zh/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/zh-tw/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zh-tw/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/zh/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/zh/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/zh-tw/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/zh-tw/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/zh/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/ColumnDesigner',{});
},
'Sage/UI/nls/zh/SearchMenuItem':function(){
define('Sage/UI/nls/zh/SearchMenuItem',{});
},
'Sage/UI/nls/zh-tw/SearchMenuItem':function(){
define('Sage/UI/nls/zh-tw/SearchMenuItem',{});
},
'Sage/UI/nls/zh/NotesHistoryList':function(){
define('Sage/UI/nls/zh/NotesHistoryList',{});
},
'Sage/UI/nls/zh-tw/NotesHistoryList':function(){
define('Sage/UI/nls/zh-tw/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/zh/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/zh/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zh/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/zh-tw/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zh-tw/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/zh/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zh/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-tw/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-tw/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-tw/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-tw/HistoryEditor',{});
},
'Sage/Groups/nls/zh/GroupManager':function(){
define('Sage/Groups/nls/zh/GroupManager',{});
},
'Sage/Groups/nls/zh-tw/GroupManager':function(){
define('Sage/Groups/nls/zh-tw/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-tw/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-tw/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/zh/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zh/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/zh-tw/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zh-tw/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-tw/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-tw/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/zh/EditableGrid':function(){
define('Sage/UI/nls/zh/EditableGrid',{});
},
'Sage/UI/nls/zh-tw/EditableGrid':function(){
define('Sage/UI/nls/zh-tw/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/zh/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/zh/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/zh-tw/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/zh-tw/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/SpeedSearch':function(){
define('Sage/UI/nls/zh/SpeedSearch',{});
},
'Sage/UI/nls/zh-tw/SpeedSearch':function(){
define('Sage/UI/nls/zh-tw/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/SLXPreviewGrid':function(){
define('Sage/UI/nls/zh/SLXPreviewGrid',{});
},
'Sage/UI/nls/zh-tw/SLXPreviewGrid':function(){
define('Sage/UI/nls/zh-tw/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/zh/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zh/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/zh-tw/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zh-tw/UnconfirmedPane',{});
},
'Sage/Utility/nls/zh/Utility':function(){
define('Sage/Utility/nls/zh/Utility',{});
},
'Sage/Utility/nls/zh-tw/Utility':function(){
define('Sage/Utility/nls/zh-tw/Utility',{});
},
'Sage/QuickForms/Design/nls/zh/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/ControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/Address':function(){
define('Sage/UI/Controls/nls/zh/Address',{});
},
'Sage/UI/Controls/nls/zh-tw/Address':function(){
define('Sage/UI/Controls/nls/zh-tw/Address',{});
},
'Sage/MainView/ActivityMgr/nls/zh/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-tw/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-tw/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zh/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/OwnerControlDesigner',{});
},
'Sage/UI/nls/zh/UserType':function(){
define('Sage/UI/nls/zh/UserType',{});
},
'Sage/UI/nls/zh-tw/UserType':function(){
define('Sage/UI/nls/zh-tw/UserType',{});
},
'Sage/QuickForms/Design/nls/zh/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/zh-tw/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zh-tw/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/zh/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zh/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/zh-tw/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zh-tw/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/ActivityList':function(){
define('Sage/UI/nls/zh/ActivityList',{});
},
'Sage/UI/nls/zh-tw/ActivityList':function(){
define('Sage/UI/nls/zh-tw/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/CalendarUsersListPane':function(){
define('Sage/UI/nls/zh/CalendarUsersListPane',{});
},
'Sage/UI/nls/zh-tw/CalendarUsersListPane':function(){
define('Sage/UI/nls/zh-tw/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/zh/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/zh-tw/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/zh-tw/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zh/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/zh-tw/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zh-tw/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/zh/Attachment':function(){
define('Sage/Utility/File/nls/zh/Attachment',{});
},
'Sage/Utility/File/nls/zh-tw/Attachment':function(){
define('Sage/Utility/File/nls/zh-tw/Attachment',{});
},
'Sage/QuickForms/Design/nls/zh/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/zh/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/zh-tw/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/zh-tw/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/zh/Helper':function(){
define('Sage/MailMerge/nls/zh/Helper',{});
},
'Sage/MailMerge/nls/zh-tw/Helper':function(){
define('Sage/MailMerge/nls/zh-tw/Helper',{});
},
'Sage/UI/Dashboard/nls/zh/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zh/Dashboard',{});
},
'Sage/UI/Dashboard/nls/zh-tw/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zh-tw/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-tw/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-tw/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/zh/PickList':function(){
define('Sage/UI/Controls/nls/zh/PickList',{});
},
'Sage/UI/Controls/nls/zh-tw/PickList':function(){
define('Sage/UI/Controls/nls/zh-tw/PickList',{});
},
'Sage/Utility/nls/zh/Email':function(){
define('Sage/Utility/nls/zh/Email',{});
},
'Sage/Utility/nls/zh-tw/Email':function(){
define('Sage/Utility/nls/zh-tw/Email',{});
},
'Sage/TaskPane/nls/zh/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-tw/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-tw/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/zh/TimeZoneItem':function(){
define('Sage/UI/nls/zh/TimeZoneItem',{});
},
'Sage/UI/nls/zh-tw/TimeZoneItem':function(){
define('Sage/UI/nls/zh-tw/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/zh/SlxEdit':function(){
define('Sage/UI/Columns/nls/zh/SlxEdit',{});
},
'Sage/UI/Columns/nls/zh-tw/SlxEdit':function(){
define('Sage/UI/Columns/nls/zh-tw/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/zh/LogOffButton':function(){
define('Sage/UI/Controls/nls/zh/LogOffButton',{});
},
'Sage/UI/Controls/nls/zh-tw/LogOffButton':function(){
define('Sage/UI/Controls/nls/zh-tw/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-tw/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-tw/EditEventEditor',{});
},
'Sage/MailMerge/nls/zh/Loader':function(){
define('Sage/MailMerge/nls/zh/Loader',{});
},
'Sage/MailMerge/nls/zh-tw/Loader':function(){
define('Sage/MailMerge/nls/zh-tw/Loader',{});
},
'Sage/UI/Controls/nls/zh/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zh/DateTimePicker',{});
},
'Sage/UI/Controls/nls/zh-tw/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zh-tw/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/zh/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zh/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/zh-tw/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zh-tw/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-tw/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-tw/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/Lookup':function(){
define('Sage/UI/Controls/nls/zh/Lookup',{});
},
'Sage/UI/Controls/nls/zh-tw/Lookup':function(){
define('Sage/UI/Controls/nls/zh-tw/Lookup',{});
},
'Sage/Utility/File/nls/zh/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zh/DescriptionsForm',{});
},
'Sage/Utility/File/nls/zh-tw/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zh-tw/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-tw/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-tw/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-tw/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-tw/CommonTasksTasklet',{});
},
'Sage/Utility/nls/zh/Dashboard':function(){
define('Sage/Utility/nls/zh/Dashboard',{});
},
'Sage/Utility/nls/zh-tw/Dashboard':function(){
define('Sage/Utility/nls/zh-tw/Dashboard',{});
}}});
define("Sage/nls/Sage_zh-tw", [], 1);
