require({cache:{
'Sage/Utility/File/nls/az/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/az/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/az-az/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/az-az/FallbackFilePicker',{});
},
'Sage/UI/nls/az/Boolean':function(){
define('Sage/UI/nls/az/Boolean',{});
},
'Sage/UI/nls/az-az/Boolean':function(){
define('Sage/UI/nls/az-az/Boolean',{});
},
'Sage/UI/Controls/nls/az/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/az/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/az-az/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/az-az/CopyToClipboard',{});
},
'Sage/Services/nls/az/ActivityService':function(){
define('Sage/Services/nls/az/ActivityService',{});
},
'Sage/Services/nls/az-az/ActivityService':function(){
define('Sage/Services/nls/az-az/ActivityService',{});
},
'Sage/Utility/nls/az/Activity':function(){
define('Sage/Utility/nls/az/Activity',{});
},
'Sage/Utility/nls/az-az/Activity':function(){
define('Sage/Utility/nls/az-az/Activity',{});
},
'Sage/UI/nls/az/TimelessActivitiesPane':function(){
define('Sage/UI/nls/az/TimelessActivitiesPane',{});
},
'Sage/UI/nls/az-az/TimelessActivitiesPane':function(){
define('Sage/UI/nls/az-az/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/az/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/ActivityEditor',{});
},
'Sage/MainView/nls/az/ActivityManager':function(){
define('Sage/MainView/nls/az/ActivityManager',{});
},
'Sage/MainView/nls/az-az/ActivityManager':function(){
define('Sage/MainView/nls/az-az/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/az/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/az/Service':function(){
define('Sage/Reporting/nls/az/Service',{});
},
'Sage/Reporting/nls/az-az/Service':function(){
define('Sage/Reporting/nls/az-az/Service',{});
},
'Sage/Utility/File/nls/az/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/az/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/az-az/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/az-az/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/az/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/az/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/az-az/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/az-az/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/az/AlarmPane':function(){
define('Sage/UI/Alarms/nls/az/AlarmPane',{});
},
'Sage/UI/Alarms/nls/az-az/AlarmPane':function(){
define('Sage/UI/Alarms/nls/az-az/AlarmPane',{});
},
'Sage/TaskPane/nls/az/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/az/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/az-az/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/az-az/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/az/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/az/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/az-az/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/az-az/DashboardWidget',{});
},
'Sage/UI/Filters/nls/az/FilterPanel':function(){
define('Sage/UI/Filters/nls/az/FilterPanel',{});
},
'Sage/UI/Filters/nls/az-az/FilterPanel':function(){
define('Sage/UI/Filters/nls/az-az/FilterPanel',{});
},
'Sage/TaskPane/nls/az/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/az/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/az-az/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/az-az/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/az/OwnerType':function(){
define('Sage/UI/nls/az/OwnerType',{});
},
'Sage/UI/nls/az-az/OwnerType':function(){
define('Sage/UI/nls/az-az/OwnerType',{});
},
'Sage/TaskPane/nls/az/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/az/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/az-az/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/az-az/LeadTasksTasklet',{});
},
'Sage/UI/nls/az/SDataLookup':function(){
define('Sage/UI/nls/az/SDataLookup',{});
},
'Sage/UI/nls/az-az/SDataLookup':function(){
define('Sage/UI/nls/az-az/SDataLookup',{});
},
'Sage/TaskPane/nls/az/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/az/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/az-az/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/az-az/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/az/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/az/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/az-az/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/az-az/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/az/LibraryDocument':function(){
define('Sage/Utility/File/nls/az/LibraryDocument',{});
},
'Sage/Utility/File/nls/az-az/LibraryDocument':function(){
define('Sage/Utility/File/nls/az-az/LibraryDocument',{});
},
'Sage/UI/nls/az/ConditionManager':function(){
define('Sage/UI/nls/az/ConditionManager',{});
},
'Sage/UI/nls/az-az/ConditionManager':function(){
define('Sage/UI/nls/az-az/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/az/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/az/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/az-az/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/az-az/WidgetDefinition',{});
},
'Sage/UI/nls/az/SearchConditionWidget':function(){
define('Sage/UI/nls/az/SearchConditionWidget',{});
},
'Sage/UI/nls/az-az/SearchConditionWidget':function(){
define('Sage/UI/nls/az-az/SearchConditionWidget',{});
},
'Sage/UI/nls/az/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/az/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/az-az/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/az-az/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/az/Name':function(){
define('Sage/UI/Controls/nls/az/Name',{});
},
'Sage/UI/Controls/nls/az-az/Name':function(){
define('Sage/UI/Controls/nls/az-az/Name',{});
},
'Sage/MainView/Lead/nls/az/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/az/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/az-az/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/az-az/UpdateLeads',{});
},
'Sage/UI/nls/az/ListPanel':function(){
define('Sage/UI/nls/az/ListPanel',{});
},
'Sage/UI/nls/az-az/ListPanel':function(){
define('Sage/UI/nls/az-az/ListPanel',{});
},
'Sage/UI/Filters/nls/az/EditFilters':function(){
define('Sage/UI/Filters/nls/az/EditFilters',{});
},
'Sage/UI/Filters/nls/az-az/EditFilters':function(){
define('Sage/UI/Filters/nls/az-az/EditFilters',{});
},
'Sage/UI/Controls/nls/az/DurationSelect':function(){
define('Sage/UI/Controls/nls/az/DurationSelect',{});
},
'Sage/UI/Controls/nls/az-az/DurationSelect':function(){
define('Sage/UI/Controls/nls/az-az/DurationSelect',{});
},
'Sage/UI/Alarms/nls/az/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/az/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/az-az/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/az-az/AlarmCountDown',{});
},
'Sage/UI/nls/az/AttachmentList':function(){
define('Sage/UI/nls/az/AttachmentList',{});
},
'Sage/UI/nls/az-az/AttachmentList':function(){
define('Sage/UI/nls/az-az/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/az/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/az/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/az-az/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/az-az/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/az/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/az/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/az-az/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/az-az/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/az/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/az/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/az-az/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/az-az/DashboardTabController',{});
},
'Sage/Groups/nls/az/GroupNavigator':function(){
define('Sage/Groups/nls/az/GroupNavigator',{});
},
'Sage/Groups/nls/az-az/GroupNavigator':function(){
define('Sage/Groups/nls/az-az/GroupNavigator',{});
},
'Sage/Utility/File/nls/az/AddURLAttachment':function(){
define('Sage/Utility/File/nls/az/AddURLAttachment',{});
},
'Sage/Utility/File/nls/az-az/AddURLAttachment':function(){
define('Sage/Utility/File/nls/az-az/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/az/EditFilterItems':function(){
define('Sage/UI/Filters/nls/az/EditFilterItems',{});
},
'Sage/UI/Filters/nls/az-az/EditFilterItems':function(){
define('Sage/UI/Filters/nls/az-az/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/az/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/EventListPanelConfig',{});
},
'Sage/UI/nls/az/ActivityScheduler':function(){
define('Sage/UI/nls/az/ActivityScheduler',{});
},
'Sage/UI/nls/az-az/ActivityScheduler':function(){
define('Sage/UI/nls/az-az/ActivityScheduler',{});
},
'Sage/MainView/nls/az/SecurityManager':function(){
define('Sage/MainView/nls/az/SecurityManager',{});
},
'Sage/MainView/nls/az-az/SecurityManager':function(){
define('Sage/MainView/nls/az-az/SecurityManager',{});
},
'Sage/TaskPane/nls/az/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/az/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/az-az/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/az-az/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/az/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/az/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/az/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/az/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/az-az/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/az-az/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/az/HelpMenu':function(){
define('Sage/UI/Controls/nls/az/HelpMenu',{});
},
'Sage/UI/Controls/nls/az-az/HelpMenu':function(){
define('Sage/UI/Controls/nls/az-az/HelpMenu',{});
},
'Sage/TaskPane/nls/az/UserTasklet':function(){
define('Sage/TaskPane/nls/az/UserTasklet',{});
},
'Sage/TaskPane/nls/az-az/UserTasklet':function(){
define('Sage/TaskPane/nls/az-az/UserTasklet',{});
},
'Sage/UI/Alarms/nls/az/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/az/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/az-az/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/az-az/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/az/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/az/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/az-az/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/az-az/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/az/MenuHelper':function(){
define('Sage/MailMerge/nls/az/MenuHelper',{});
},
'Sage/MailMerge/nls/az-az/MenuHelper':function(){
define('Sage/MailMerge/nls/az-az/MenuHelper',{});
},
'Sage/UI/nls/az/SearchMenuItem':function(){
define('Sage/UI/nls/az/SearchMenuItem',{});
},
'Sage/UI/nls/az-az/SearchMenuItem':function(){
define('Sage/UI/nls/az-az/SearchMenuItem',{});
},
'Sage/UI/nls/az/NotesHistoryList':function(){
define('Sage/UI/nls/az/NotesHistoryList',{});
},
'Sage/UI/nls/az-az/NotesHistoryList':function(){
define('Sage/UI/nls/az-az/NotesHistoryList',{});
},
'Sage/Utility/File/nls/az/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/az/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/az-az/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/az-az/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/az/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/HistoryEditor',{});
},
'Sage/Groups/nls/az/GroupManager':function(){
define('Sage/Groups/nls/az/GroupManager',{});
},
'Sage/Groups/nls/az-az/GroupManager':function(){
define('Sage/Groups/nls/az-az/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/az/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/az/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/az/UnconfirmedAlarm',{});
},
'Sage/UI/Alarms/nls/az-az/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/az-az/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/az/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/az/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/az-az/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/az-az/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/az/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/az/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/az-az/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/az-az/AccountingTasksTasklet',{});
},
'Sage/UI/nls/az/EditableGrid':function(){
define('Sage/UI/nls/az/EditableGrid',{});
},
'Sage/UI/nls/az-az/EditableGrid':function(){
define('Sage/UI/nls/az-az/EditableGrid',{});
},
'Sage/UI/nls/az/SpeedSearch':function(){
define('Sage/UI/nls/az/SpeedSearch',{});
},
'Sage/UI/nls/az-az/SpeedSearch':function(){
define('Sage/UI/nls/az-az/SpeedSearch',{});
},
'Sage/UI/nls/az/SLXPreviewGrid':function(){
define('Sage/UI/nls/az/SLXPreviewGrid',{});
},
'Sage/UI/nls/az-az/SLXPreviewGrid':function(){
define('Sage/UI/nls/az-az/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/az/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/az/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/az-az/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/az-az/UnconfirmedPane',{});
},
'Sage/Utility/nls/az/Utility':function(){
define('Sage/Utility/nls/az/Utility',{});
},
'Sage/Utility/nls/az-az/Utility':function(){
define('Sage/Utility/nls/az-az/Utility',{});
},
'Sage/UI/Controls/nls/az/Address':function(){
define('Sage/UI/Controls/nls/az/Address',{});
},
'Sage/UI/Controls/nls/az-az/Address':function(){
define('Sage/UI/Controls/nls/az-az/Address',{});
},
'Sage/MainView/ActivityMgr/nls/az/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/BaseListPanelConfig',{});
},
'Sage/UI/nls/az/UserType':function(){
define('Sage/UI/nls/az/UserType',{});
},
'Sage/UI/nls/az-az/UserType':function(){
define('Sage/UI/nls/az-az/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/az/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/az/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/az/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/az/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/az-az/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/az-az/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/az/ActivityList':function(){
define('Sage/UI/nls/az/ActivityList',{});
},
'Sage/UI/nls/az-az/ActivityList':function(){
define('Sage/UI/nls/az-az/ActivityList',{});
},
'Sage/UI/nls/az/CalendarUsersListPane':function(){
define('Sage/UI/nls/az/CalendarUsersListPane',{});
},
'Sage/UI/nls/az-az/CalendarUsersListPane':function(){
define('Sage/UI/nls/az-az/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/az/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/az/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/az/Attachment':function(){
define('Sage/Utility/File/nls/az/Attachment',{});
},
'Sage/Utility/File/nls/az-az/Attachment':function(){
define('Sage/Utility/File/nls/az-az/Attachment',{});
},
'Sage/MailMerge/nls/az/Helper':function(){
define('Sage/MailMerge/nls/az/Helper',{});
},
'Sage/MailMerge/nls/az-az/Helper':function(){
define('Sage/MailMerge/nls/az-az/Helper',{});
},
'Sage/UI/Dashboard/nls/az/Dashboard':function(){
define('Sage/UI/Dashboard/nls/az/Dashboard',{});
},
'Sage/UI/Dashboard/nls/az-az/Dashboard':function(){
define('Sage/UI/Dashboard/nls/az-az/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/az/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/az/PickList':function(){
define('Sage/UI/Controls/nls/az/PickList',{});
},
'Sage/UI/Controls/nls/az-az/PickList':function(){
define('Sage/UI/Controls/nls/az-az/PickList',{});
},
'Sage/Utility/nls/az/Email':function(){
define('Sage/Utility/nls/az/Email',{});
},
'Sage/Utility/nls/az-az/Email':function(){
define('Sage/Utility/nls/az-az/Email',{});
},
'Sage/UI/nls/az/TimeZoneItem':function(){
define('Sage/UI/nls/az/TimeZoneItem',{});
},
'Sage/UI/nls/az-az/TimeZoneItem':function(){
define('Sage/UI/nls/az-az/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/az/SlxEdit':function(){
define('Sage/UI/Columns/nls/az/SlxEdit',{});
},
'Sage/UI/Columns/nls/az-az/SlxEdit':function(){
define('Sage/UI/Columns/nls/az-az/SlxEdit',{});
},
'Sage/UI/Controls/nls/az/LogOffButton':function(){
define('Sage/UI/Controls/nls/az/LogOffButton',{});
},
'Sage/UI/Controls/nls/az-az/LogOffButton':function(){
define('Sage/UI/Controls/nls/az-az/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/az/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/az-az/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/az-az/EditEventEditor',{});
},
'Sage/MailMerge/nls/az/Loader':function(){
define('Sage/MailMerge/nls/az/Loader',{});
},
'Sage/MailMerge/nls/az-az/Loader':function(){
define('Sage/MailMerge/nls/az-az/Loader',{});
},
'Sage/UI/Controls/nls/az/DateTimePicker':function(){
define('Sage/UI/Controls/nls/az/DateTimePicker',{});
},
'Sage/UI/Controls/nls/az-az/DateTimePicker':function(){
define('Sage/UI/Controls/nls/az-az/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/az/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/az/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/az-az/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/az-az/AlarmPopup',{});
},
'Sage/UI/Controls/nls/az/Lookup':function(){
define('Sage/UI/Controls/nls/az/Lookup',{});
},
'Sage/UI/Controls/nls/az-az/Lookup':function(){
define('Sage/UI/Controls/nls/az-az/Lookup',{});
},
'Sage/Utility/File/nls/az/DescriptionsForm':function(){
define('Sage/Utility/File/nls/az/DescriptionsForm',{});
},
'Sage/Utility/File/nls/az-az/DescriptionsForm':function(){
define('Sage/Utility/File/nls/az-az/DescriptionsForm',{});
},
'Sage/TaskPane/nls/az/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/az/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/az-az/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/az-az/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_az-az", [], 1);
