require({cache:{
'Sage/Utility/File/nls/ar/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/ar-kw/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar-kw/FallbackFilePicker',{});
},
'Sage/UI/nls/ar/Boolean':function(){
define('Sage/UI/nls/ar/Boolean',{});
},
'Sage/UI/nls/ar-kw/Boolean':function(){
define('Sage/UI/nls/ar-kw/Boolean',{});
},
'Sage/UI/Controls/nls/ar/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/ar-kw/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar-kw/CopyToClipboard',{});
},
'Sage/Services/nls/ar/ActivityService':function(){
define('Sage/Services/nls/ar/ActivityService',{});
},
'Sage/Services/nls/ar-kw/ActivityService':function(){
define('Sage/Services/nls/ar-kw/ActivityService',{});
},
'Sage/Utility/nls/ar/Activity':function(){
define('Sage/Utility/nls/ar/Activity',{});
},
'Sage/Utility/nls/ar-kw/Activity':function(){
define('Sage/Utility/nls/ar-kw/Activity',{});
},
'Sage/UI/nls/ar/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar/TimelessActivitiesPane',{});
},
'Sage/UI/nls/ar-kw/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar-kw/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/ActivityEditor',{});
},
'Sage/MainView/nls/ar/ActivityManager':function(){
define('Sage/MainView/nls/ar/ActivityManager',{});
},
'Sage/MainView/nls/ar-kw/ActivityManager':function(){
define('Sage/MainView/nls/ar-kw/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/ar/Service':function(){
define('Sage/Reporting/nls/ar/Service',{});
},
'Sage/Reporting/nls/ar-kw/Service':function(){
define('Sage/Reporting/nls/ar-kw/Service',{});
},
'Sage/Utility/File/nls/ar/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar-kw/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar-kw/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/ar-kw/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar-kw/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPane',{});
},
'Sage/UI/Alarms/nls/ar-kw/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar-kw/AlarmPane',{});
},
'Sage/TaskPane/nls/ar/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/ar-kw/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar-kw/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/ar-kw/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar-kw/DashboardWidget',{});
},
'Sage/UI/Filters/nls/ar/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar/FilterPanel',{});
},
'Sage/UI/Filters/nls/ar-kw/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar-kw/FilterPanel',{});
},
'Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/ar/OwnerType':function(){
define('Sage/UI/nls/ar/OwnerType',{});
},
'Sage/UI/nls/ar-kw/OwnerType':function(){
define('Sage/UI/nls/ar-kw/OwnerType',{});
},
'Sage/TaskPane/nls/ar/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/LeadTasksTasklet',{});
},
'Sage/UI/nls/ar/SDataLookup':function(){
define('Sage/UI/nls/ar/SDataLookup',{});
},
'Sage/UI/nls/ar-kw/SDataLookup':function(){
define('Sage/UI/nls/ar-kw/SDataLookup',{});
},
'Sage/TaskPane/nls/ar/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ar/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/ar-kw/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar-kw/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ar/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar/LibraryDocument',{});
},
'Sage/Utility/File/nls/ar-kw/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar-kw/LibraryDocument',{});
},
'Sage/UI/nls/ar/ConditionManager':function(){
define('Sage/UI/nls/ar/ConditionManager',{});
},
'Sage/UI/nls/ar-kw/ConditionManager':function(){
define('Sage/UI/nls/ar-kw/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ar/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/ar-kw/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar-kw/WidgetDefinition',{});
},
'Sage/UI/nls/ar/SearchConditionWidget':function(){
define('Sage/UI/nls/ar/SearchConditionWidget',{});
},
'Sage/UI/nls/ar-kw/SearchConditionWidget':function(){
define('Sage/UI/nls/ar-kw/SearchConditionWidget',{});
},
'Sage/UI/nls/ar/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/ar-kw/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar-kw/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/ar/Name':function(){
define('Sage/UI/Controls/nls/ar/Name',{});
},
'Sage/UI/Controls/nls/ar-kw/Name':function(){
define('Sage/UI/Controls/nls/ar-kw/Name',{});
},
'Sage/MainView/Lead/nls/ar/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/ar-kw/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar-kw/UpdateLeads',{});
},
'Sage/UI/nls/ar/ListPanel':function(){
define('Sage/UI/nls/ar/ListPanel',{});
},
'Sage/UI/nls/ar-kw/ListPanel':function(){
define('Sage/UI/nls/ar-kw/ListPanel',{});
},
'Sage/UI/Filters/nls/ar/EditFilters':function(){
define('Sage/UI/Filters/nls/ar/EditFilters',{});
},
'Sage/UI/Filters/nls/ar-kw/EditFilters':function(){
define('Sage/UI/Filters/nls/ar-kw/EditFilters',{});
},
'Sage/UI/Controls/nls/ar/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar/DurationSelect',{});
},
'Sage/UI/Controls/nls/ar-kw/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar-kw/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ar/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/ar-kw/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar-kw/AlarmCountDown',{});
},
'Sage/UI/nls/ar/AttachmentList':function(){
define('Sage/UI/nls/ar/AttachmentList',{});
},
'Sage/UI/nls/ar-kw/AttachmentList':function(){
define('Sage/UI/nls/ar-kw/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/ar-kw/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar-kw/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/ar/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/ar-kw/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar-kw/DashboardTabController',{});
},
'Sage/Groups/nls/ar/GroupNavigator':function(){
define('Sage/Groups/nls/ar/GroupNavigator',{});
},
'Sage/Groups/nls/ar-kw/GroupNavigator':function(){
define('Sage/Groups/nls/ar-kw/GroupNavigator',{});
},
'Sage/Utility/File/nls/ar/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar/AddURLAttachment',{});
},
'Sage/Utility/File/nls/ar-kw/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar-kw/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ar/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar/EditFilterItems',{});
},
'Sage/UI/Filters/nls/ar-kw/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar-kw/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/EventListPanelConfig',{});
},
'Sage/UI/nls/ar/ActivityScheduler':function(){
define('Sage/UI/nls/ar/ActivityScheduler',{});
},
'Sage/UI/nls/ar-kw/ActivityScheduler':function(){
define('Sage/UI/nls/ar-kw/ActivityScheduler',{});
},
'Sage/MainView/nls/ar/SecurityManager':function(){
define('Sage/MainView/nls/ar/SecurityManager',{});
},
'Sage/MainView/nls/ar-kw/SecurityManager':function(){
define('Sage/MainView/nls/ar-kw/SecurityManager',{});
},
'Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/ar-kw/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar-kw/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/ar/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/ar-kw/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar-kw/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/ar/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar/HelpMenu',{});
},
'Sage/UI/Controls/nls/ar-kw/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar-kw/HelpMenu',{});
},
'Sage/TaskPane/nls/ar/UserTasklet':function(){
define('Sage/TaskPane/nls/ar/UserTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/UserTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ar/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/ar-kw/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar-kw/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ar/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/ar-kw/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar-kw/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/ar/MenuHelper':function(){
define('Sage/MailMerge/nls/ar/MenuHelper',{});
},
'Sage/MailMerge/nls/ar-kw/MenuHelper':function(){
define('Sage/MailMerge/nls/ar-kw/MenuHelper',{});
},
'Sage/UI/nls/ar/SearchMenuItem':function(){
define('Sage/UI/nls/ar/SearchMenuItem',{});
},
'Sage/UI/nls/ar-kw/SearchMenuItem':function(){
define('Sage/UI/nls/ar-kw/SearchMenuItem',{});
},
'Sage/UI/nls/ar/NotesHistoryList':function(){
define('Sage/UI/nls/ar/NotesHistoryList',{});
},
'Sage/UI/nls/ar-kw/NotesHistoryList':function(){
define('Sage/UI/nls/ar-kw/NotesHistoryList',{});
},
'Sage/Utility/File/nls/ar/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/ar-kw/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar-kw/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/HistoryEditor',{});
},
'Sage/Groups/nls/ar/GroupManager':function(){
define('Sage/Groups/nls/ar/GroupManager',{});
},
'Sage/Groups/nls/ar-kw/GroupManager':function(){
define('Sage/Groups/nls/ar-kw/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/ar/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedAlarm',{});
},
'Sage/UI/Alarms/nls/ar-kw/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/ar-kw/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/ar-kw/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar-kw/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/ar/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/AccountingTasksTasklet',{});
},
'Sage/UI/nls/ar/EditableGrid':function(){
define('Sage/UI/nls/ar/EditableGrid',{});
},
'Sage/UI/nls/ar-kw/EditableGrid':function(){
define('Sage/UI/nls/ar-kw/EditableGrid',{});
},
'Sage/UI/nls/ar/SpeedSearch':function(){
define('Sage/UI/nls/ar/SpeedSearch',{});
},
'Sage/UI/nls/ar-kw/SpeedSearch':function(){
define('Sage/UI/nls/ar-kw/SpeedSearch',{});
},
'Sage/UI/nls/ar/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar/SLXPreviewGrid',{});
},
'Sage/UI/nls/ar-kw/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar-kw/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/ar-kw/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar-kw/UnconfirmedPane',{});
},
'Sage/Utility/nls/ar/Utility':function(){
define('Sage/Utility/nls/ar/Utility',{});
},
'Sage/Utility/nls/ar-kw/Utility':function(){
define('Sage/Utility/nls/ar-kw/Utility',{});
},
'Sage/UI/Controls/nls/ar/Address':function(){
define('Sage/UI/Controls/nls/ar/Address',{});
},
'Sage/UI/Controls/nls/ar-kw/Address':function(){
define('Sage/UI/Controls/nls/ar-kw/Address',{});
},
'Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/BaseListPanelConfig',{});
},
'Sage/UI/nls/ar/UserType':function(){
define('Sage/UI/nls/ar/UserType',{});
},
'Sage/UI/nls/ar-kw/UserType':function(){
define('Sage/UI/nls/ar-kw/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/ar/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/ar-kw/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar-kw/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/ar/ActivityList':function(){
define('Sage/UI/nls/ar/ActivityList',{});
},
'Sage/UI/nls/ar-kw/ActivityList':function(){
define('Sage/UI/nls/ar-kw/ActivityList',{});
},
'Sage/UI/nls/ar/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar/CalendarUsersListPane',{});
},
'Sage/UI/nls/ar-kw/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar-kw/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ar/Attachment':function(){
define('Sage/Utility/File/nls/ar/Attachment',{});
},
'Sage/Utility/File/nls/ar-kw/Attachment':function(){
define('Sage/Utility/File/nls/ar-kw/Attachment',{});
},
'Sage/MailMerge/nls/ar/Helper':function(){
define('Sage/MailMerge/nls/ar/Helper',{});
},
'Sage/MailMerge/nls/ar-kw/Helper':function(){
define('Sage/MailMerge/nls/ar-kw/Helper',{});
},
'Sage/UI/Dashboard/nls/ar/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar/Dashboard',{});
},
'Sage/UI/Dashboard/nls/ar-kw/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar-kw/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ar/PickList':function(){
define('Sage/UI/Controls/nls/ar/PickList',{});
},
'Sage/UI/Controls/nls/ar-kw/PickList':function(){
define('Sage/UI/Controls/nls/ar-kw/PickList',{});
},
'Sage/Utility/nls/ar/Email':function(){
define('Sage/Utility/nls/ar/Email',{});
},
'Sage/Utility/nls/ar-kw/Email':function(){
define('Sage/Utility/nls/ar-kw/Email',{});
},
'Sage/UI/nls/ar/TimeZoneItem':function(){
define('Sage/UI/nls/ar/TimeZoneItem',{});
},
'Sage/UI/nls/ar-kw/TimeZoneItem':function(){
define('Sage/UI/nls/ar-kw/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ar/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar/SlxEdit',{});
},
'Sage/UI/Columns/nls/ar-kw/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar-kw/SlxEdit',{});
},
'Sage/UI/Controls/nls/ar/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar/LogOffButton',{});
},
'Sage/UI/Controls/nls/ar-kw/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar-kw/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-kw/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-kw/EditEventEditor',{});
},
'Sage/MailMerge/nls/ar/Loader':function(){
define('Sage/MailMerge/nls/ar/Loader',{});
},
'Sage/MailMerge/nls/ar-kw/Loader':function(){
define('Sage/MailMerge/nls/ar-kw/Loader',{});
},
'Sage/UI/Controls/nls/ar/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar/DateTimePicker',{});
},
'Sage/UI/Controls/nls/ar-kw/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar-kw/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/ar-kw/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar-kw/AlarmPopup',{});
},
'Sage/UI/Controls/nls/ar/Lookup':function(){
define('Sage/UI/Controls/nls/ar/Lookup',{});
},
'Sage/UI/Controls/nls/ar-kw/Lookup':function(){
define('Sage/UI/Controls/nls/ar-kw/Lookup',{});
},
'Sage/Utility/File/nls/ar/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar/DescriptionsForm',{});
},
'Sage/Utility/File/nls/ar-kw/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar-kw/DescriptionsForm',{});
},
'Sage/TaskPane/nls/ar/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-kw/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-kw/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_ar-kw", [], 1);
