require({cache:{
'Sage/Utility/File/nls/vi/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/vi/FallbackFilePicker',{});
},
'Sage/UI/nls/vi/Boolean':function(){
define('Sage/UI/nls/vi/Boolean',{});
},
'Sage/Services/nls/vi/ActivityService':function(){
define('Sage/Services/nls/vi/ActivityService',{});
},
'Sage/UI/Controls/nls/vi/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/vi/CopyToClipboard',{});
},
'Sage/Utility/nls/vi/Activity':function(){
define('Sage/Utility/nls/vi/Activity',{});
},
'Sage/QuickForms/Design/nls/vi/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/vi/DesignPanel',{});
},
'Sage/UI/nls/vi/TimelessActivitiesPane':function(){
define('Sage/UI/nls/vi/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/vi/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/vi/ActivityEditor',{});
},
'Sage/MainView/nls/vi/ActivityManager':function(){
define('Sage/MainView/nls/vi/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/vi/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/_PropertyEditor',{});
},
'Sage/Services/nls/vi/ActivityActionProcessor':function(){
define('Sage/Services/nls/vi/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/vi/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/vi/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/vi/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/vi/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/vi/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/vi/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/vi/AlarmPane':function(){
define('Sage/UI/Alarms/nls/vi/AlarmPane',{});
},
'Sage/TaskPane/nls/vi/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/vi/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/vi/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/vi/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/vi/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/vi/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/vi/FilterPanel':function(){
define('Sage/UI/Filters/nls/vi/FilterPanel',{});
},
'Sage/TaskPane/nls/vi/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/vi/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/vi/OwnerType':function(){
define('Sage/UI/nls/vi/OwnerType',{});
},
'Sage/TaskPane/nls/vi/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/vi/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/vi/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/vi/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/vi/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/vi/InvoiceRTDV',{});
},
'Sage/UI/nls/vi/SDataLookup':function(){
define('Sage/UI/nls/vi/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/vi/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/RowDesigner',{});
},
'Sage/TaskPane/nls/vi/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/vi/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/vi/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/vi/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/vi/LibraryDocument':function(){
define('Sage/Utility/File/nls/vi/LibraryDocument',{});
},
'Sage/UI/nls/vi/ConditionManager':function(){
define('Sage/UI/nls/vi/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/vi/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/vi/WidgetDefinition',{});
},
'Sage/UI/nls/vi/SearchConditionWidget':function(){
define('Sage/UI/nls/vi/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/vi/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/vi/DataSourcePanel',{});
},
'Sage/UI/nls/vi/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/vi/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/vi/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/vi/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/vi/Name':function(){
define('Sage/UI/Controls/nls/vi/Name',{});
},
'Sage/QuickForms/Design/nls/vi/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/vi/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/vi/UpdateLeads',{});
},
'Sage/UI/nls/vi/ListPanel':function(){
define('Sage/UI/nls/vi/ListPanel',{});
},
'Sage/UI/Filters/nls/vi/EditFilters':function(){
define('Sage/UI/Filters/nls/vi/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/vi/DurationSelect':function(){
define('Sage/UI/Controls/nls/vi/DurationSelect',{});
},
'Sage/UI/Alarms/nls/vi/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/vi/AlarmCountDown',{});
},
'Sage/UI/nls/vi/AttachmentList':function(){
define('Sage/UI/nls/vi/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/vi/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/vi/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/vi/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/vi/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/vi/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/vi/Dialogs':function(){
define('Sage/UI/nls/vi/Dialogs',{});
},
'Sage/TaskPane/nls/vi/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/vi/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/vi/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/vi/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/vi/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/vi/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/vi/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/UserControlDesigner',{});
},
'Sage/Groups/nls/vi/GroupNavigator':function(){
define('Sage/Groups/nls/vi/GroupNavigator',{});
},
'Sage/Utility/File/nls/vi/AddURLAttachment':function(){
define('Sage/Utility/File/nls/vi/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/vi/EditFilterItems':function(){
define('Sage/UI/Filters/nls/vi/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/vi/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/vi/DesignSurface',{});
},
'Sage/Utility/File/nls/vi/DragDropWatcher':function(){
define('Sage/Utility/File/nls/vi/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/vi/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/vi/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/vi/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/vi/EventListPanelConfig',{});
},
'Sage/UI/nls/vi/ActivityScheduler':function(){
define('Sage/UI/nls/vi/ActivityScheduler',{});
},
'Sage/MainView/nls/vi/SecurityManager':function(){
define('Sage/MainView/nls/vi/SecurityManager',{});
},
'Sage/TaskPane/nls/vi/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/vi/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/vi/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/vi/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/vi/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/vi/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/vi/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/vi/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/vi/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/vi/HelpMenu':function(){
define('Sage/UI/Controls/nls/vi/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/vi/UserTasklet':function(){
define('Sage/TaskPane/nls/vi/UserTasklet',{});
},
'Sage/UI/Alarms/nls/vi/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/vi/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/vi/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/vi/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/vi/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/vi/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/vi/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/ColumnDesigner',{});
},
'Sage/UI/nls/vi/SearchMenuItem':function(){
define('Sage/UI/nls/vi/SearchMenuItem',{});
},
'Sage/UI/nls/vi/NotesHistoryList':function(){
define('Sage/UI/nls/vi/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/vi/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/vi/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/vi/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/vi/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/vi/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/vi/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/vi/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/vi/HistoryEditor',{});
},
'Sage/Groups/nls/vi/GroupManager':function(){
define('Sage/Groups/nls/vi/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/vi/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/vi/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/vi/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/vi/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/vi/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/vi/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/vi/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/vi/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/vi/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/vi/EditableGrid':function(){
define('Sage/UI/nls/vi/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/vi/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/vi/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/vi/SpeedSearch':function(){
define('Sage/UI/nls/vi/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/vi/SLXPreviewGrid':function(){
define('Sage/UI/nls/vi/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/vi/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/vi/UnconfirmedPane',{});
},
'Sage/Utility/nls/vi/Utility':function(){
define('Sage/Utility/nls/vi/Utility',{});
},
'Sage/QuickForms/Design/nls/vi/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/ControlDesigner',{});
},
'Sage/UI/Controls/nls/vi/Address':function(){
define('Sage/UI/Controls/nls/vi/Address',{});
},
'Sage/MainView/ActivityMgr/nls/vi/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/vi/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/vi/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/OwnerControlDesigner',{});
},
'Sage/UI/nls/vi/UserType':function(){
define('Sage/UI/nls/vi/UserType',{});
},
'Sage/QuickForms/Design/nls/vi/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/vi/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/vi/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/vi/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/vi/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/vi/ActivityList':function(){
define('Sage/UI/nls/vi/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/vi/CalendarUsersListPane':function(){
define('Sage/UI/nls/vi/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/vi/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/vi/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/vi/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/vi/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/vi/Attachment':function(){
define('Sage/Utility/File/nls/vi/Attachment',{});
},
'Sage/QuickForms/Design/nls/vi/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/vi/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/vi/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/vi/Helper':function(){
define('Sage/MailMerge/nls/vi/Helper',{});
},
'Sage/UI/Dashboard/nls/vi/Dashboard':function(){
define('Sage/UI/Dashboard/nls/vi/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/vi/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/vi/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/vi/PickList':function(){
define('Sage/UI/Controls/nls/vi/PickList',{});
},
'Sage/Utility/nls/vi/Email':function(){
define('Sage/Utility/nls/vi/Email',{});
},
'Sage/TaskPane/nls/vi/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/vi/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/vi/TimeZoneItem':function(){
define('Sage/UI/nls/vi/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/vi/SlxEdit':function(){
define('Sage/UI/Columns/nls/vi/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/vi/LogOffButton':function(){
define('Sage/UI/Controls/nls/vi/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/vi/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/vi/EditEventEditor',{});
},
'Sage/MailMerge/nls/vi/Loader':function(){
define('Sage/MailMerge/nls/vi/Loader',{});
},
'Sage/UI/Controls/nls/vi/DateTimePicker':function(){
define('Sage/UI/Controls/nls/vi/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/vi/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/vi/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/vi/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/vi/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/vi/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/vi/Lookup':function(){
define('Sage/UI/Controls/nls/vi/Lookup',{});
},
'Sage/Utility/File/nls/vi/DescriptionsForm':function(){
define('Sage/Utility/File/nls/vi/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/vi/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/vi/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/vi/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/vi/CommonTasksTasklet',{});
},
'Sage/Utility/nls/vi/Dashboard':function(){
define('Sage/Utility/nls/vi/Dashboard',{});
}}});
define("Sage/nls/Sage_vi", [], 1);
