require({cache:{
'Sage/Utility/File/nls/lt/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/lt/FallbackFilePicker',{});
},
'Sage/UI/nls/lt/Boolean':function(){
define('Sage/UI/nls/lt/Boolean',{});
},
'Sage/Services/nls/lt/ActivityService':function(){
define('Sage/Services/nls/lt/ActivityService',{});
},
'Sage/UI/Controls/nls/lt/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/lt/CopyToClipboard',{});
},
'Sage/Utility/nls/lt/Activity':function(){
define('Sage/Utility/nls/lt/Activity',{});
},
'Sage/QuickForms/Design/nls/lt/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/lt/DesignPanel',{});
},
'Sage/UI/nls/lt/TimelessActivitiesPane':function(){
define('Sage/UI/nls/lt/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/lt/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/lt/ActivityEditor',{});
},
'Sage/MainView/nls/lt/ActivityManager':function(){
define('Sage/MainView/nls/lt/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/lt/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/_PropertyEditor',{});
},
'Sage/Services/nls/lt/ActivityActionProcessor':function(){
define('Sage/Services/nls/lt/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/lt/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/lt/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/lt/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/lt/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/lt/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/lt/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/lt/AlarmPane':function(){
define('Sage/UI/Alarms/nls/lt/AlarmPane',{});
},
'Sage/TaskPane/nls/lt/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/lt/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/lt/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/lt/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/lt/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/lt/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/lt/FilterPanel':function(){
define('Sage/UI/Filters/nls/lt/FilterPanel',{});
},
'Sage/TaskPane/nls/lt/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/lt/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/lt/OwnerType':function(){
define('Sage/UI/nls/lt/OwnerType',{});
},
'Sage/TaskPane/nls/lt/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/lt/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/lt/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/lt/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/lt/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/lt/InvoiceRTDV',{});
},
'Sage/UI/nls/lt/SDataLookup':function(){
define('Sage/UI/nls/lt/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/lt/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/RowDesigner',{});
},
'Sage/TaskPane/nls/lt/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/lt/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/lt/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/lt/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/lt/LibraryDocument':function(){
define('Sage/Utility/File/nls/lt/LibraryDocument',{});
},
'Sage/UI/nls/lt/ConditionManager':function(){
define('Sage/UI/nls/lt/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/lt/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/lt/WidgetDefinition',{});
},
'Sage/UI/nls/lt/SearchConditionWidget':function(){
define('Sage/UI/nls/lt/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/lt/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/lt/DataSourcePanel',{});
},
'Sage/UI/nls/lt/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/lt/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/lt/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/lt/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/lt/Name':function(){
define('Sage/UI/Controls/nls/lt/Name',{});
},
'Sage/QuickForms/Design/nls/lt/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/lt/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/lt/UpdateLeads',{});
},
'Sage/UI/nls/lt/ListPanel':function(){
define('Sage/UI/nls/lt/ListPanel',{});
},
'Sage/UI/Filters/nls/lt/EditFilters':function(){
define('Sage/UI/Filters/nls/lt/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/lt/DurationSelect':function(){
define('Sage/UI/Controls/nls/lt/DurationSelect',{});
},
'Sage/UI/Alarms/nls/lt/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/lt/AlarmCountDown',{});
},
'Sage/UI/nls/lt/AttachmentList':function(){
define('Sage/UI/nls/lt/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/lt/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/lt/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/lt/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/lt/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/lt/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/lt/Dialogs':function(){
define('Sage/UI/nls/lt/Dialogs',{});
},
'Sage/TaskPane/nls/lt/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/lt/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/lt/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/lt/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/lt/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/lt/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/lt/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/UserControlDesigner',{});
},
'Sage/Groups/nls/lt/GroupNavigator':function(){
define('Sage/Groups/nls/lt/GroupNavigator',{});
},
'Sage/Utility/File/nls/lt/AddURLAttachment':function(){
define('Sage/Utility/File/nls/lt/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/lt/EditFilterItems':function(){
define('Sage/UI/Filters/nls/lt/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/lt/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/lt/DesignSurface',{});
},
'Sage/Utility/File/nls/lt/DragDropWatcher':function(){
define('Sage/Utility/File/nls/lt/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/lt/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/lt/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/lt/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/lt/EventListPanelConfig',{});
},
'Sage/UI/nls/lt/ActivityScheduler':function(){
define('Sage/UI/nls/lt/ActivityScheduler',{});
},
'Sage/MainView/nls/lt/SecurityManager':function(){
define('Sage/MainView/nls/lt/SecurityManager',{});
},
'Sage/TaskPane/nls/lt/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/lt/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/lt/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/lt/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/lt/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/lt/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/lt/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/lt/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/lt/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/lt/HelpMenu':function(){
define('Sage/UI/Controls/nls/lt/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/lt/UserTasklet':function(){
define('Sage/TaskPane/nls/lt/UserTasklet',{});
},
'Sage/UI/Alarms/nls/lt/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/lt/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/lt/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/lt/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/lt/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/lt/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/lt/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/ColumnDesigner',{});
},
'Sage/UI/nls/lt/SearchMenuItem':function(){
define('Sage/UI/nls/lt/SearchMenuItem',{});
},
'Sage/UI/nls/lt/NotesHistoryList':function(){
define('Sage/UI/nls/lt/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/lt/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/lt/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/lt/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/lt/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/lt/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/lt/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/lt/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/lt/HistoryEditor',{});
},
'Sage/Groups/nls/lt/GroupManager':function(){
define('Sage/Groups/nls/lt/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/lt/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/lt/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/lt/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/lt/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/lt/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/lt/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/lt/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/lt/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/lt/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/lt/EditableGrid':function(){
define('Sage/UI/nls/lt/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/lt/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/lt/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/lt/SpeedSearch':function(){
define('Sage/UI/nls/lt/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/lt/SLXPreviewGrid':function(){
define('Sage/UI/nls/lt/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/lt/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/lt/UnconfirmedPane',{});
},
'Sage/Utility/nls/lt/Utility':function(){
define('Sage/Utility/nls/lt/Utility',{});
},
'Sage/QuickForms/Design/nls/lt/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/ControlDesigner',{});
},
'Sage/UI/Controls/nls/lt/Address':function(){
define('Sage/UI/Controls/nls/lt/Address',{});
},
'Sage/MainView/ActivityMgr/nls/lt/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/lt/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/lt/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/OwnerControlDesigner',{});
},
'Sage/UI/nls/lt/UserType':function(){
define('Sage/UI/nls/lt/UserType',{});
},
'Sage/QuickForms/Design/nls/lt/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/lt/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/lt/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/lt/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/lt/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/lt/ActivityList':function(){
define('Sage/UI/nls/lt/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/lt/CalendarUsersListPane':function(){
define('Sage/UI/nls/lt/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/lt/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/lt/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/lt/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/lt/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/lt/Attachment':function(){
define('Sage/Utility/File/nls/lt/Attachment',{});
},
'Sage/QuickForms/Design/nls/lt/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/lt/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/lt/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/lt/Helper':function(){
define('Sage/MailMerge/nls/lt/Helper',{});
},
'Sage/UI/Dashboard/nls/lt/Dashboard':function(){
define('Sage/UI/Dashboard/nls/lt/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/lt/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/lt/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/lt/PickList':function(){
define('Sage/UI/Controls/nls/lt/PickList',{});
},
'Sage/Utility/nls/lt/Email':function(){
define('Sage/Utility/nls/lt/Email',{});
},
'Sage/TaskPane/nls/lt/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/lt/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/lt/TimeZoneItem':function(){
define('Sage/UI/nls/lt/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/lt/SlxEdit':function(){
define('Sage/UI/Columns/nls/lt/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/lt/LogOffButton':function(){
define('Sage/UI/Controls/nls/lt/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/lt/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/lt/EditEventEditor',{});
},
'Sage/MailMerge/nls/lt/Loader':function(){
define('Sage/MailMerge/nls/lt/Loader',{});
},
'Sage/UI/Controls/nls/lt/DateTimePicker':function(){
define('Sage/UI/Controls/nls/lt/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/lt/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/lt/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/lt/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/lt/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/lt/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/lt/Lookup':function(){
define('Sage/UI/Controls/nls/lt/Lookup',{});
},
'Sage/Utility/File/nls/lt/DescriptionsForm':function(){
define('Sage/Utility/File/nls/lt/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/lt/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/lt/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/lt/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/lt/CommonTasksTasklet',{});
},
'Sage/Utility/nls/lt/Dashboard':function(){
define('Sage/Utility/nls/lt/Dashboard',{});
}}});
define("Sage/nls/Sage_lt", [], 1);
