require({cache:{
'Sage/Utility/File/nls/sl/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/sl/FallbackFilePicker',{});
},
'Sage/UI/nls/sl/Boolean':function(){
define('Sage/UI/nls/sl/Boolean',{});
},
'Sage/Services/nls/sl/ActivityService':function(){
define('Sage/Services/nls/sl/ActivityService',{});
},
'Sage/UI/Controls/nls/sl/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/sl/CopyToClipboard',{});
},
'Sage/Utility/nls/sl/Activity':function(){
define('Sage/Utility/nls/sl/Activity',{});
},
'Sage/QuickForms/Design/nls/sl/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/sl/DesignPanel',{});
},
'Sage/UI/nls/sl/TimelessActivitiesPane':function(){
define('Sage/UI/nls/sl/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/sl/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sl/ActivityEditor',{});
},
'Sage/MainView/nls/sl/ActivityManager':function(){
define('Sage/MainView/nls/sl/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/sl/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/_PropertyEditor',{});
},
'Sage/Services/nls/sl/ActivityActionProcessor':function(){
define('Sage/Services/nls/sl/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sl/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sl/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/sl/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/sl/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/sl/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/sl/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/sl/AlarmPane':function(){
define('Sage/UI/Alarms/nls/sl/AlarmPane',{});
},
'Sage/TaskPane/nls/sl/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/sl/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/sl/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/sl/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sl/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sl/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/sl/FilterPanel':function(){
define('Sage/UI/Filters/nls/sl/FilterPanel',{});
},
'Sage/TaskPane/nls/sl/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/sl/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/sl/OwnerType':function(){
define('Sage/UI/nls/sl/OwnerType',{});
},
'Sage/TaskPane/nls/sl/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/sl/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/sl/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/sl/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sl/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sl/InvoiceRTDV',{});
},
'Sage/UI/nls/sl/SDataLookup':function(){
define('Sage/UI/nls/sl/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/sl/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/RowDesigner',{});
},
'Sage/TaskPane/nls/sl/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/sl/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/sl/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/sl/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/sl/LibraryDocument':function(){
define('Sage/Utility/File/nls/sl/LibraryDocument',{});
},
'Sage/UI/nls/sl/ConditionManager':function(){
define('Sage/UI/nls/sl/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/sl/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/sl/WidgetDefinition',{});
},
'Sage/UI/nls/sl/SearchConditionWidget':function(){
define('Sage/UI/nls/sl/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/sl/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/sl/DataSourcePanel',{});
},
'Sage/UI/nls/sl/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/sl/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/sl/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/sl/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/sl/Name':function(){
define('Sage/UI/Controls/nls/sl/Name',{});
},
'Sage/QuickForms/Design/nls/sl/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/sl/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/sl/UpdateLeads',{});
},
'Sage/UI/nls/sl/ListPanel':function(){
define('Sage/UI/nls/sl/ListPanel',{});
},
'Sage/UI/Filters/nls/sl/EditFilters':function(){
define('Sage/UI/Filters/nls/sl/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/sl/DurationSelect':function(){
define('Sage/UI/Controls/nls/sl/DurationSelect',{});
},
'Sage/UI/Alarms/nls/sl/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/sl/AlarmCountDown',{});
},
'Sage/UI/nls/sl/AttachmentList':function(){
define('Sage/UI/nls/sl/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/sl/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sl/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sl/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/sl/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/sl/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/sl/Dialogs':function(){
define('Sage/UI/nls/sl/Dialogs',{});
},
'Sage/TaskPane/nls/sl/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/sl/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/sl/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/sl/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/sl/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sl/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/sl/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/UserControlDesigner',{});
},
'Sage/Groups/nls/sl/GroupNavigator':function(){
define('Sage/Groups/nls/sl/GroupNavigator',{});
},
'Sage/Utility/File/nls/sl/AddURLAttachment':function(){
define('Sage/Utility/File/nls/sl/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/sl/EditFilterItems':function(){
define('Sage/UI/Filters/nls/sl/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/sl/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/sl/DesignSurface',{});
},
'Sage/Utility/File/nls/sl/DragDropWatcher':function(){
define('Sage/Utility/File/nls/sl/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/sl/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sl/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sl/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sl/EventListPanelConfig',{});
},
'Sage/UI/nls/sl/ActivityScheduler':function(){
define('Sage/UI/nls/sl/ActivityScheduler',{});
},
'Sage/MainView/nls/sl/SecurityManager':function(){
define('Sage/MainView/nls/sl/SecurityManager',{});
},
'Sage/TaskPane/nls/sl/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/sl/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/sl/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/sl/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/sl/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/sl/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/sl/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/sl/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/sl/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/sl/HelpMenu':function(){
define('Sage/UI/Controls/nls/sl/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/sl/UserTasklet':function(){
define('Sage/TaskPane/nls/sl/UserTasklet',{});
},
'Sage/UI/Alarms/nls/sl/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/sl/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/sl/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/sl/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/sl/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/sl/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/sl/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/ColumnDesigner',{});
},
'Sage/UI/nls/sl/SearchMenuItem':function(){
define('Sage/UI/nls/sl/SearchMenuItem',{});
},
'Sage/UI/nls/sl/NotesHistoryList':function(){
define('Sage/UI/nls/sl/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/sl/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/sl/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/sl/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/sl/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sl/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sl/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sl/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sl/HistoryEditor',{});
},
'Sage/Groups/nls/sl/GroupManager':function(){
define('Sage/Groups/nls/sl/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sl/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sl/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/sl/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sl/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sl/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/sl/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/sl/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sl/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/sl/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/sl/EditableGrid':function(){
define('Sage/UI/nls/sl/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/sl/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/sl/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sl/SpeedSearch':function(){
define('Sage/UI/nls/sl/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sl/SLXPreviewGrid':function(){
define('Sage/UI/nls/sl/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/sl/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/sl/UnconfirmedPane',{});
},
'Sage/Utility/nls/sl/Utility':function(){
define('Sage/Utility/nls/sl/Utility',{});
},
'Sage/QuickForms/Design/nls/sl/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/ControlDesigner',{});
},
'Sage/UI/Controls/nls/sl/Address':function(){
define('Sage/UI/Controls/nls/sl/Address',{});
},
'Sage/MainView/ActivityMgr/nls/sl/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sl/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sl/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/OwnerControlDesigner',{});
},
'Sage/UI/nls/sl/UserType':function(){
define('Sage/UI/nls/sl/UserType',{});
},
'Sage/QuickForms/Design/nls/sl/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sl/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/sl/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/sl/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/sl/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sl/ActivityList':function(){
define('Sage/UI/nls/sl/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sl/CalendarUsersListPane':function(){
define('Sage/UI/nls/sl/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sl/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/sl/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sl/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/sl/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/sl/Attachment':function(){
define('Sage/Utility/File/nls/sl/Attachment',{});
},
'Sage/QuickForms/Design/nls/sl/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sl/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/sl/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/sl/Helper':function(){
define('Sage/MailMerge/nls/sl/Helper',{});
},
'Sage/UI/Dashboard/nls/sl/Dashboard':function(){
define('Sage/UI/Dashboard/nls/sl/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/sl/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sl/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/sl/PickList':function(){
define('Sage/UI/Controls/nls/sl/PickList',{});
},
'Sage/Utility/nls/sl/Email':function(){
define('Sage/Utility/nls/sl/Email',{});
},
'Sage/TaskPane/nls/sl/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sl/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/sl/TimeZoneItem':function(){
define('Sage/UI/nls/sl/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/sl/SlxEdit':function(){
define('Sage/UI/Columns/nls/sl/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/sl/LogOffButton':function(){
define('Sage/UI/Controls/nls/sl/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sl/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sl/EditEventEditor',{});
},
'Sage/MailMerge/nls/sl/Loader':function(){
define('Sage/MailMerge/nls/sl/Loader',{});
},
'Sage/UI/Controls/nls/sl/DateTimePicker':function(){
define('Sage/UI/Controls/nls/sl/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/sl/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/sl/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/sl/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sl/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sl/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/sl/Lookup':function(){
define('Sage/UI/Controls/nls/sl/Lookup',{});
},
'Sage/Utility/File/nls/sl/DescriptionsForm':function(){
define('Sage/Utility/File/nls/sl/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/sl/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sl/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sl/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/sl/CommonTasksTasklet',{});
},
'Sage/Utility/nls/sl/Dashboard':function(){
define('Sage/Utility/nls/sl/Dashboard',{});
}}});
define("Sage/nls/Sage_sl", [], 1);
