require({cache:{
'Sage/Utility/File/nls/eu/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/eu/FallbackFilePicker',{});
},
'Sage/UI/nls/eu/Boolean':function(){
define('Sage/UI/nls/eu/Boolean',{});
},
'Sage/Services/nls/eu/ActivityService':function(){
define('Sage/Services/nls/eu/ActivityService',{});
},
'Sage/UI/Controls/nls/eu/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/eu/CopyToClipboard',{});
},
'Sage/Utility/nls/eu/Activity':function(){
define('Sage/Utility/nls/eu/Activity',{});
},
'Sage/QuickForms/Design/nls/eu/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/eu/DesignPanel',{});
},
'Sage/UI/nls/eu/TimelessActivitiesPane':function(){
define('Sage/UI/nls/eu/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/eu/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/eu/ActivityEditor',{});
},
'Sage/MainView/nls/eu/ActivityManager':function(){
define('Sage/MainView/nls/eu/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/eu/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/_PropertyEditor',{});
},
'Sage/Services/nls/eu/ActivityActionProcessor':function(){
define('Sage/Services/nls/eu/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/eu/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/eu/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/eu/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/eu/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/eu/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/eu/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/eu/AlarmPane':function(){
define('Sage/UI/Alarms/nls/eu/AlarmPane',{});
},
'Sage/TaskPane/nls/eu/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/eu/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/eu/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/eu/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/eu/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/eu/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/eu/FilterPanel':function(){
define('Sage/UI/Filters/nls/eu/FilterPanel',{});
},
'Sage/TaskPane/nls/eu/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/eu/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/eu/OwnerType':function(){
define('Sage/UI/nls/eu/OwnerType',{});
},
'Sage/TaskPane/nls/eu/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/eu/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/eu/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/eu/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/eu/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/eu/InvoiceRTDV',{});
},
'Sage/UI/nls/eu/SDataLookup':function(){
define('Sage/UI/nls/eu/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/eu/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/RowDesigner',{});
},
'Sage/TaskPane/nls/eu/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/eu/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/eu/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/eu/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/eu/LibraryDocument':function(){
define('Sage/Utility/File/nls/eu/LibraryDocument',{});
},
'Sage/UI/nls/eu/ConditionManager':function(){
define('Sage/UI/nls/eu/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/eu/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/eu/WidgetDefinition',{});
},
'Sage/UI/nls/eu/SearchConditionWidget':function(){
define('Sage/UI/nls/eu/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/eu/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/eu/DataSourcePanel',{});
},
'Sage/UI/nls/eu/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/eu/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/eu/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/eu/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/eu/Name':function(){
define('Sage/UI/Controls/nls/eu/Name',{});
},
'Sage/QuickForms/Design/nls/eu/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/eu/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/eu/UpdateLeads',{});
},
'Sage/UI/nls/eu/ListPanel':function(){
define('Sage/UI/nls/eu/ListPanel',{});
},
'Sage/UI/Filters/nls/eu/EditFilters':function(){
define('Sage/UI/Filters/nls/eu/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/eu/DurationSelect':function(){
define('Sage/UI/Controls/nls/eu/DurationSelect',{});
},
'Sage/UI/Alarms/nls/eu/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/eu/AlarmCountDown',{});
},
'Sage/UI/nls/eu/AttachmentList':function(){
define('Sage/UI/nls/eu/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/eu/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/eu/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/eu/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/eu/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/eu/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/eu/Dialogs':function(){
define('Sage/UI/nls/eu/Dialogs',{});
},
'Sage/TaskPane/nls/eu/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/eu/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/eu/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/eu/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/eu/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/eu/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/eu/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/UserControlDesigner',{});
},
'Sage/Groups/nls/eu/GroupNavigator':function(){
define('Sage/Groups/nls/eu/GroupNavigator',{});
},
'Sage/Utility/File/nls/eu/AddURLAttachment':function(){
define('Sage/Utility/File/nls/eu/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/eu/EditFilterItems':function(){
define('Sage/UI/Filters/nls/eu/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/eu/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/eu/DesignSurface',{});
},
'Sage/Utility/File/nls/eu/DragDropWatcher':function(){
define('Sage/Utility/File/nls/eu/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/eu/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/eu/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/eu/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/eu/EventListPanelConfig',{});
},
'Sage/UI/nls/eu/ActivityScheduler':function(){
define('Sage/UI/nls/eu/ActivityScheduler',{});
},
'Sage/MainView/nls/eu/SecurityManager':function(){
define('Sage/MainView/nls/eu/SecurityManager',{});
},
'Sage/TaskPane/nls/eu/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/eu/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/eu/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/eu/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/eu/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/eu/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/eu/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/eu/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/eu/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/eu/HelpMenu':function(){
define('Sage/UI/Controls/nls/eu/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/eu/UserTasklet':function(){
define('Sage/TaskPane/nls/eu/UserTasklet',{});
},
'Sage/UI/Alarms/nls/eu/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/eu/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/eu/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/eu/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/eu/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/eu/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/eu/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/ColumnDesigner',{});
},
'Sage/UI/nls/eu/SearchMenuItem':function(){
define('Sage/UI/nls/eu/SearchMenuItem',{});
},
'Sage/UI/nls/eu/NotesHistoryList':function(){
define('Sage/UI/nls/eu/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/eu/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/eu/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/eu/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/eu/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/eu/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/eu/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/eu/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/eu/HistoryEditor',{});
},
'Sage/Groups/nls/eu/GroupManager':function(){
define('Sage/Groups/nls/eu/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/eu/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/eu/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/eu/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/eu/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/eu/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/eu/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/eu/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/eu/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/eu/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/eu/EditableGrid':function(){
define('Sage/UI/nls/eu/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/eu/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/eu/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/eu/SpeedSearch':function(){
define('Sage/UI/nls/eu/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/eu/SLXPreviewGrid':function(){
define('Sage/UI/nls/eu/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/eu/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/eu/UnconfirmedPane',{});
},
'Sage/Utility/nls/eu/Utility':function(){
define('Sage/Utility/nls/eu/Utility',{});
},
'Sage/QuickForms/Design/nls/eu/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/ControlDesigner',{});
},
'Sage/UI/Controls/nls/eu/Address':function(){
define('Sage/UI/Controls/nls/eu/Address',{});
},
'Sage/MainView/ActivityMgr/nls/eu/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/eu/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/eu/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/OwnerControlDesigner',{});
},
'Sage/UI/nls/eu/UserType':function(){
define('Sage/UI/nls/eu/UserType',{});
},
'Sage/QuickForms/Design/nls/eu/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/eu/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/eu/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/eu/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/eu/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/eu/ActivityList':function(){
define('Sage/UI/nls/eu/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/eu/CalendarUsersListPane':function(){
define('Sage/UI/nls/eu/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/eu/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/eu/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/eu/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/eu/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/eu/Attachment':function(){
define('Sage/Utility/File/nls/eu/Attachment',{});
},
'Sage/QuickForms/Design/nls/eu/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/eu/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/eu/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/eu/Helper':function(){
define('Sage/MailMerge/nls/eu/Helper',{});
},
'Sage/UI/Dashboard/nls/eu/Dashboard':function(){
define('Sage/UI/Dashboard/nls/eu/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/eu/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/eu/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/eu/PickList':function(){
define('Sage/UI/Controls/nls/eu/PickList',{});
},
'Sage/Utility/nls/eu/Email':function(){
define('Sage/Utility/nls/eu/Email',{});
},
'Sage/TaskPane/nls/eu/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/eu/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/eu/TimeZoneItem':function(){
define('Sage/UI/nls/eu/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/eu/SlxEdit':function(){
define('Sage/UI/Columns/nls/eu/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/eu/LogOffButton':function(){
define('Sage/UI/Controls/nls/eu/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/eu/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/eu/EditEventEditor',{});
},
'Sage/MailMerge/nls/eu/Loader':function(){
define('Sage/MailMerge/nls/eu/Loader',{});
},
'Sage/UI/Controls/nls/eu/DateTimePicker':function(){
define('Sage/UI/Controls/nls/eu/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/eu/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/eu/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/eu/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/eu/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/eu/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/eu/Lookup':function(){
define('Sage/UI/Controls/nls/eu/Lookup',{});
},
'Sage/Utility/File/nls/eu/DescriptionsForm':function(){
define('Sage/Utility/File/nls/eu/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/eu/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/eu/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/eu/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/eu/CommonTasksTasklet',{});
},
'Sage/Utility/nls/eu/Dashboard':function(){
define('Sage/Utility/nls/eu/Dashboard',{});
}}});
define("Sage/nls/Sage_eu", [], 1);
