require({cache:{
'Sage/Utility/File/nls/zu/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zu/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/zu-za/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zu-za/FallbackFilePicker',{});
},
'Sage/UI/nls/zu/Boolean':function(){
define('Sage/UI/nls/zu/Boolean',{});
},
'Sage/UI/nls/zu-za/Boolean':function(){
define('Sage/UI/nls/zu-za/Boolean',{});
},
'Sage/UI/Controls/nls/zu/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zu/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/zu-za/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zu-za/CopyToClipboard',{});
},
'Sage/Services/nls/zu/ActivityService':function(){
define('Sage/Services/nls/zu/ActivityService',{});
},
'Sage/Services/nls/zu-za/ActivityService':function(){
define('Sage/Services/nls/zu-za/ActivityService',{});
},
'Sage/Utility/nls/zu/Activity':function(){
define('Sage/Utility/nls/zu/Activity',{});
},
'Sage/Utility/nls/zu-za/Activity':function(){
define('Sage/Utility/nls/zu-za/Activity',{});
},
'Sage/UI/nls/zu/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zu/TimelessActivitiesPane',{});
},
'Sage/UI/nls/zu-za/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zu-za/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/ActivityEditor',{});
},
'Sage/MainView/nls/zu/ActivityManager':function(){
define('Sage/MainView/nls/zu/ActivityManager',{});
},
'Sage/MainView/nls/zu-za/ActivityManager':function(){
define('Sage/MainView/nls/zu-za/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/zu/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/zu/Service':function(){
define('Sage/Reporting/nls/zu/Service',{});
},
'Sage/Reporting/nls/zu-za/Service':function(){
define('Sage/Reporting/nls/zu-za/Service',{});
},
'Sage/Utility/File/nls/zu/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zu/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/zu-za/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zu-za/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/zu/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zu/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/zu-za/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zu-za/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/zu/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zu/AlarmPane',{});
},
'Sage/UI/Alarms/nls/zu-za/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zu-za/AlarmPane',{});
},
'Sage/TaskPane/nls/zu/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zu/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/zu-za/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zu-za/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/zu/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zu/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/zu-za/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zu-za/DashboardWidget',{});
},
'Sage/UI/Filters/nls/zu/FilterPanel':function(){
define('Sage/UI/Filters/nls/zu/FilterPanel',{});
},
'Sage/UI/Filters/nls/zu-za/FilterPanel':function(){
define('Sage/UI/Filters/nls/zu-za/FilterPanel',{});
},
'Sage/TaskPane/nls/zu/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zu/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/zu-za/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zu-za/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/zu/OwnerType':function(){
define('Sage/UI/nls/zu/OwnerType',{});
},
'Sage/UI/nls/zu-za/OwnerType':function(){
define('Sage/UI/nls/zu-za/OwnerType',{});
},
'Sage/TaskPane/nls/zu/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/zu-za/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zu-za/LeadTasksTasklet',{});
},
'Sage/UI/nls/zu/SDataLookup':function(){
define('Sage/UI/nls/zu/SDataLookup',{});
},
'Sage/UI/nls/zu-za/SDataLookup':function(){
define('Sage/UI/nls/zu-za/SDataLookup',{});
},
'Sage/TaskPane/nls/zu/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/zu-za/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zu-za/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/zu/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zu/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/zu-za/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zu-za/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/zu/LibraryDocument':function(){
define('Sage/Utility/File/nls/zu/LibraryDocument',{});
},
'Sage/Utility/File/nls/zu-za/LibraryDocument':function(){
define('Sage/Utility/File/nls/zu-za/LibraryDocument',{});
},
'Sage/UI/nls/zu/ConditionManager':function(){
define('Sage/UI/nls/zu/ConditionManager',{});
},
'Sage/UI/nls/zu-za/ConditionManager':function(){
define('Sage/UI/nls/zu-za/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/zu/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zu/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/zu-za/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zu-za/WidgetDefinition',{});
},
'Sage/UI/nls/zu/SearchConditionWidget':function(){
define('Sage/UI/nls/zu/SearchConditionWidget',{});
},
'Sage/UI/nls/zu-za/SearchConditionWidget':function(){
define('Sage/UI/nls/zu-za/SearchConditionWidget',{});
},
'Sage/UI/nls/zu/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zu/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/zu-za/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zu-za/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/zu/Name':function(){
define('Sage/UI/Controls/nls/zu/Name',{});
},
'Sage/UI/Controls/nls/zu-za/Name':function(){
define('Sage/UI/Controls/nls/zu-za/Name',{});
},
'Sage/MainView/Lead/nls/zu/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zu/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/zu-za/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zu-za/UpdateLeads',{});
},
'Sage/UI/nls/zu/ListPanel':function(){
define('Sage/UI/nls/zu/ListPanel',{});
},
'Sage/UI/nls/zu-za/ListPanel':function(){
define('Sage/UI/nls/zu-za/ListPanel',{});
},
'Sage/UI/Filters/nls/zu/EditFilters':function(){
define('Sage/UI/Filters/nls/zu/EditFilters',{});
},
'Sage/UI/Filters/nls/zu-za/EditFilters':function(){
define('Sage/UI/Filters/nls/zu-za/EditFilters',{});
},
'Sage/UI/Controls/nls/zu/DurationSelect':function(){
define('Sage/UI/Controls/nls/zu/DurationSelect',{});
},
'Sage/UI/Controls/nls/zu-za/DurationSelect':function(){
define('Sage/UI/Controls/nls/zu-za/DurationSelect',{});
},
'Sage/UI/Alarms/nls/zu/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zu/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/zu-za/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zu-za/AlarmCountDown',{});
},
'Sage/UI/nls/zu/AttachmentList':function(){
define('Sage/UI/nls/zu/AttachmentList',{});
},
'Sage/UI/nls/zu-za/AttachmentList':function(){
define('Sage/UI/nls/zu-za/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/zu/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zu/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/zu-za/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zu-za/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/zu/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zu/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/zu-za/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zu-za/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/zu/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zu/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/zu-za/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zu-za/DashboardTabController',{});
},
'Sage/Groups/nls/zu/GroupNavigator':function(){
define('Sage/Groups/nls/zu/GroupNavigator',{});
},
'Sage/Groups/nls/zu-za/GroupNavigator':function(){
define('Sage/Groups/nls/zu-za/GroupNavigator',{});
},
'Sage/Utility/File/nls/zu/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zu/AddURLAttachment',{});
},
'Sage/Utility/File/nls/zu-za/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zu-za/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/zu/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zu/EditFilterItems',{});
},
'Sage/UI/Filters/nls/zu-za/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zu-za/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/EventListPanelConfig',{});
},
'Sage/UI/nls/zu/ActivityScheduler':function(){
define('Sage/UI/nls/zu/ActivityScheduler',{});
},
'Sage/UI/nls/zu-za/ActivityScheduler':function(){
define('Sage/UI/nls/zu-za/ActivityScheduler',{});
},
'Sage/MainView/nls/zu/SecurityManager':function(){
define('Sage/MainView/nls/zu/SecurityManager',{});
},
'Sage/MainView/nls/zu-za/SecurityManager':function(){
define('Sage/MainView/nls/zu-za/SecurityManager',{});
},
'Sage/TaskPane/nls/zu/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zu/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/zu-za/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zu-za/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/zu/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zu/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/zu-za/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zu-za/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/zu/HelpMenu':function(){
define('Sage/UI/Controls/nls/zu/HelpMenu',{});
},
'Sage/UI/Controls/nls/zu-za/HelpMenu':function(){
define('Sage/UI/Controls/nls/zu-za/HelpMenu',{});
},
'Sage/TaskPane/nls/zu/UserTasklet':function(){
define('Sage/TaskPane/nls/zu/UserTasklet',{});
},
'Sage/TaskPane/nls/zu-za/UserTasklet':function(){
define('Sage/TaskPane/nls/zu-za/UserTasklet',{});
},
'Sage/UI/Alarms/nls/zu/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zu/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/zu-za/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zu-za/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/zu/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zu/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/zu-za/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zu-za/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/zu/MenuHelper':function(){
define('Sage/MailMerge/nls/zu/MenuHelper',{});
},
'Sage/MailMerge/nls/zu-za/MenuHelper':function(){
define('Sage/MailMerge/nls/zu-za/MenuHelper',{});
},
'Sage/UI/nls/zu/SearchMenuItem':function(){
define('Sage/UI/nls/zu/SearchMenuItem',{});
},
'Sage/UI/nls/zu-za/SearchMenuItem':function(){
define('Sage/UI/nls/zu-za/SearchMenuItem',{});
},
'Sage/UI/nls/zu/NotesHistoryList':function(){
define('Sage/UI/nls/zu/NotesHistoryList',{});
},
'Sage/UI/nls/zu-za/NotesHistoryList':function(){
define('Sage/UI/nls/zu-za/NotesHistoryList',{});
},
'Sage/Utility/File/nls/zu/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zu/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/zu-za/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zu-za/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/zu/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/HistoryEditor',{});
},
'Sage/Groups/nls/zu/GroupManager':function(){
define('Sage/Groups/nls/zu/GroupManager',{});
},
'Sage/Groups/nls/zu-za/GroupManager':function(){
define('Sage/Groups/nls/zu-za/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/zu/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/zu/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/zu/UnconfirmedAlarm',{});
},
'Sage/UI/Alarms/nls/zu-za/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/zu-za/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/zu/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zu/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/zu-za/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zu-za/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/zu/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/zu-za/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zu-za/AccountingTasksTasklet',{});
},
'Sage/UI/nls/zu/EditableGrid':function(){
define('Sage/UI/nls/zu/EditableGrid',{});
},
'Sage/UI/nls/zu-za/EditableGrid':function(){
define('Sage/UI/nls/zu-za/EditableGrid',{});
},
'Sage/UI/nls/zu/SpeedSearch':function(){
define('Sage/UI/nls/zu/SpeedSearch',{});
},
'Sage/UI/nls/zu-za/SpeedSearch':function(){
define('Sage/UI/nls/zu-za/SpeedSearch',{});
},
'Sage/UI/nls/zu/SLXPreviewGrid':function(){
define('Sage/UI/nls/zu/SLXPreviewGrid',{});
},
'Sage/UI/nls/zu-za/SLXPreviewGrid':function(){
define('Sage/UI/nls/zu-za/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/zu/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zu/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/zu-za/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zu-za/UnconfirmedPane',{});
},
'Sage/Utility/nls/zu/Utility':function(){
define('Sage/Utility/nls/zu/Utility',{});
},
'Sage/Utility/nls/zu-za/Utility':function(){
define('Sage/Utility/nls/zu-za/Utility',{});
},
'Sage/UI/Controls/nls/zu/Address':function(){
define('Sage/UI/Controls/nls/zu/Address',{});
},
'Sage/UI/Controls/nls/zu-za/Address':function(){
define('Sage/UI/Controls/nls/zu-za/Address',{});
},
'Sage/MainView/ActivityMgr/nls/zu/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/BaseListPanelConfig',{});
},
'Sage/UI/nls/zu/UserType':function(){
define('Sage/UI/nls/zu/UserType',{});
},
'Sage/UI/nls/zu-za/UserType':function(){
define('Sage/UI/nls/zu-za/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/zu/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zu/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/zu-za/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zu-za/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/zu/ActivityList':function(){
define('Sage/UI/nls/zu/ActivityList',{});
},
'Sage/UI/nls/zu-za/ActivityList':function(){
define('Sage/UI/nls/zu-za/ActivityList',{});
},
'Sage/UI/nls/zu/CalendarUsersListPane':function(){
define('Sage/UI/nls/zu/CalendarUsersListPane',{});
},
'Sage/UI/nls/zu-za/CalendarUsersListPane':function(){
define('Sage/UI/nls/zu-za/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/zu/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zu/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/zu/Attachment':function(){
define('Sage/Utility/File/nls/zu/Attachment',{});
},
'Sage/Utility/File/nls/zu-za/Attachment':function(){
define('Sage/Utility/File/nls/zu-za/Attachment',{});
},
'Sage/MailMerge/nls/zu/Helper':function(){
define('Sage/MailMerge/nls/zu/Helper',{});
},
'Sage/MailMerge/nls/zu-za/Helper':function(){
define('Sage/MailMerge/nls/zu-za/Helper',{});
},
'Sage/UI/Dashboard/nls/zu/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zu/Dashboard',{});
},
'Sage/UI/Dashboard/nls/zu-za/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zu-za/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/zu/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/zu/PickList':function(){
define('Sage/UI/Controls/nls/zu/PickList',{});
},
'Sage/UI/Controls/nls/zu-za/PickList':function(){
define('Sage/UI/Controls/nls/zu-za/PickList',{});
},
'Sage/Utility/nls/zu/Email':function(){
define('Sage/Utility/nls/zu/Email',{});
},
'Sage/Utility/nls/zu-za/Email':function(){
define('Sage/Utility/nls/zu-za/Email',{});
},
'Sage/UI/nls/zu/TimeZoneItem':function(){
define('Sage/UI/nls/zu/TimeZoneItem',{});
},
'Sage/UI/nls/zu-za/TimeZoneItem':function(){
define('Sage/UI/nls/zu-za/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/zu/SlxEdit':function(){
define('Sage/UI/Columns/nls/zu/SlxEdit',{});
},
'Sage/UI/Columns/nls/zu-za/SlxEdit':function(){
define('Sage/UI/Columns/nls/zu-za/SlxEdit',{});
},
'Sage/UI/Controls/nls/zu/LogOffButton':function(){
define('Sage/UI/Controls/nls/zu/LogOffButton',{});
},
'Sage/UI/Controls/nls/zu-za/LogOffButton':function(){
define('Sage/UI/Controls/nls/zu-za/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/zu/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zu-za/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zu-za/EditEventEditor',{});
},
'Sage/MailMerge/nls/zu/Loader':function(){
define('Sage/MailMerge/nls/zu/Loader',{});
},
'Sage/MailMerge/nls/zu-za/Loader':function(){
define('Sage/MailMerge/nls/zu-za/Loader',{});
},
'Sage/UI/Controls/nls/zu/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zu/DateTimePicker',{});
},
'Sage/UI/Controls/nls/zu-za/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zu-za/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/zu/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zu/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/zu-za/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zu-za/AlarmPopup',{});
},
'Sage/UI/Controls/nls/zu/Lookup':function(){
define('Sage/UI/Controls/nls/zu/Lookup',{});
},
'Sage/UI/Controls/nls/zu-za/Lookup':function(){
define('Sage/UI/Controls/nls/zu-za/Lookup',{});
},
'Sage/Utility/File/nls/zu/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zu/DescriptionsForm',{});
},
'Sage/Utility/File/nls/zu-za/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zu-za/DescriptionsForm',{});
},
'Sage/TaskPane/nls/zu/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zu/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/zu-za/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zu-za/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_zu-za", [], 1);
