require({cache:{
'Sage/Utility/File/nls/es/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/es-do/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es-do/FallbackFilePicker',{});
},
'Sage/UI/nls/es/Boolean':function(){
define('Sage/UI/nls/es/Boolean',{});
},
'Sage/UI/nls/es-do/Boolean':function(){
define('Sage/UI/nls/es-do/Boolean',{});
},
'Sage/UI/Controls/nls/es/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/es-do/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es-do/CopyToClipboard',{});
},
'Sage/Services/nls/es/ActivityService':function(){
define('Sage/Services/nls/es/ActivityService',{});
},
'Sage/Services/nls/es-do/ActivityService':function(){
define('Sage/Services/nls/es-do/ActivityService',{});
},
'Sage/Utility/nls/es/Activity':function(){
define('Sage/Utility/nls/es/Activity',{});
},
'Sage/Utility/nls/es-do/Activity':function(){
define('Sage/Utility/nls/es-do/Activity',{});
},
'Sage/UI/nls/es/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es/TimelessActivitiesPane',{});
},
'Sage/UI/nls/es-do/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es-do/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/ActivityEditor',{});
},
'Sage/MainView/nls/es/ActivityManager':function(){
define('Sage/MainView/nls/es/ActivityManager',{});
},
'Sage/MainView/nls/es-do/ActivityManager':function(){
define('Sage/MainView/nls/es-do/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/es/Service':function(){
define('Sage/Reporting/nls/es/Service',{});
},
'Sage/Reporting/nls/es-do/Service':function(){
define('Sage/Reporting/nls/es-do/Service',{});
},
'Sage/Utility/File/nls/es/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es-do/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es-do/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/es-do/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es-do/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/es/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es/AlarmPane',{});
},
'Sage/UI/Alarms/nls/es-do/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es-do/AlarmPane',{});
},
'Sage/TaskPane/nls/es/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/es-do/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es-do/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/es-do/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es-do/DashboardWidget',{});
},
'Sage/UI/Filters/nls/es/FilterPanel':function(){
define('Sage/UI/Filters/nls/es/FilterPanel',{});
},
'Sage/UI/Filters/nls/es-do/FilterPanel':function(){
define('Sage/UI/Filters/nls/es-do/FilterPanel',{});
},
'Sage/TaskPane/nls/es/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/es-do/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es-do/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/es/OwnerType':function(){
define('Sage/UI/nls/es/OwnerType',{});
},
'Sage/UI/nls/es-do/OwnerType':function(){
define('Sage/UI/nls/es-do/OwnerType',{});
},
'Sage/TaskPane/nls/es/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/es-do/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es-do/LeadTasksTasklet',{});
},
'Sage/UI/nls/es/SDataLookup':function(){
define('Sage/UI/nls/es/SDataLookup',{});
},
'Sage/UI/nls/es-do/SDataLookup':function(){
define('Sage/UI/nls/es-do/SDataLookup',{});
},
'Sage/TaskPane/nls/es/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/es-do/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es-do/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/es/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/es-do/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es-do/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/es/LibraryDocument':function(){
define('Sage/Utility/File/nls/es/LibraryDocument',{});
},
'Sage/Utility/File/nls/es-do/LibraryDocument':function(){
define('Sage/Utility/File/nls/es-do/LibraryDocument',{});
},
'Sage/UI/nls/es/ConditionManager':function(){
define('Sage/UI/nls/es/ConditionManager',{});
},
'Sage/UI/nls/es-do/ConditionManager':function(){
define('Sage/UI/nls/es-do/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/es/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/es-do/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es-do/WidgetDefinition',{});
},
'Sage/UI/nls/es/SearchConditionWidget':function(){
define('Sage/UI/nls/es/SearchConditionWidget',{});
},
'Sage/UI/nls/es-do/SearchConditionWidget':function(){
define('Sage/UI/nls/es-do/SearchConditionWidget',{});
},
'Sage/UI/nls/es/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/es-do/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es-do/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/es/Name':function(){
define('Sage/UI/Controls/nls/es/Name',{});
},
'Sage/UI/Controls/nls/es-do/Name':function(){
define('Sage/UI/Controls/nls/es-do/Name',{});
},
'Sage/MainView/Lead/nls/es/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/es-do/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es-do/UpdateLeads',{});
},
'Sage/UI/nls/es/ListPanel':function(){
define('Sage/UI/nls/es/ListPanel',{});
},
'Sage/UI/nls/es-do/ListPanel':function(){
define('Sage/UI/nls/es-do/ListPanel',{});
},
'Sage/UI/Filters/nls/es/EditFilters':function(){
define('Sage/UI/Filters/nls/es/EditFilters',{});
},
'Sage/UI/Filters/nls/es-do/EditFilters':function(){
define('Sage/UI/Filters/nls/es-do/EditFilters',{});
},
'Sage/UI/Controls/nls/es/DurationSelect':function(){
define('Sage/UI/Controls/nls/es/DurationSelect',{});
},
'Sage/UI/Controls/nls/es-do/DurationSelect':function(){
define('Sage/UI/Controls/nls/es-do/DurationSelect',{});
},
'Sage/UI/Alarms/nls/es/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/es-do/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es-do/AlarmCountDown',{});
},
'Sage/UI/nls/es/AttachmentList':function(){
define('Sage/UI/nls/es/AttachmentList',{});
},
'Sage/UI/nls/es-do/AttachmentList':function(){
define('Sage/UI/nls/es-do/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/es-do/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es-do/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/es/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/es-do/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es-do/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/es/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/es-do/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es-do/DashboardTabController',{});
},
'Sage/Groups/nls/es/GroupNavigator':function(){
define('Sage/Groups/nls/es/GroupNavigator',{});
},
'Sage/Groups/nls/es-do/GroupNavigator':function(){
define('Sage/Groups/nls/es-do/GroupNavigator',{});
},
'Sage/Utility/File/nls/es/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es/AddURLAttachment',{});
},
'Sage/Utility/File/nls/es-do/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es-do/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/es/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es/EditFilterItems',{});
},
'Sage/UI/Filters/nls/es-do/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es-do/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/EventListPanelConfig',{});
},
'Sage/UI/nls/es/ActivityScheduler':function(){
define('Sage/UI/nls/es/ActivityScheduler',{});
},
'Sage/UI/nls/es-do/ActivityScheduler':function(){
define('Sage/UI/nls/es-do/ActivityScheduler',{});
},
'Sage/MainView/nls/es/SecurityManager':function(){
define('Sage/MainView/nls/es/SecurityManager',{});
},
'Sage/MainView/nls/es-do/SecurityManager':function(){
define('Sage/MainView/nls/es-do/SecurityManager',{});
},
'Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/es-do/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es-do/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/es/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/es-do/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es-do/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/es/HelpMenu':function(){
define('Sage/UI/Controls/nls/es/HelpMenu',{});
},
'Sage/UI/Controls/nls/es-do/HelpMenu':function(){
define('Sage/UI/Controls/nls/es-do/HelpMenu',{});
},
'Sage/TaskPane/nls/es/UserTasklet':function(){
define('Sage/TaskPane/nls/es/UserTasklet',{});
},
'Sage/TaskPane/nls/es-do/UserTasklet':function(){
define('Sage/TaskPane/nls/es-do/UserTasklet',{});
},
'Sage/UI/Alarms/nls/es/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/es-do/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es-do/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/es/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/es-do/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es-do/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/es/MenuHelper':function(){
define('Sage/MailMerge/nls/es/MenuHelper',{});
},
'Sage/MailMerge/nls/es-do/MenuHelper':function(){
define('Sage/MailMerge/nls/es-do/MenuHelper',{});
},
'Sage/UI/nls/es/SearchMenuItem':function(){
define('Sage/UI/nls/es/SearchMenuItem',{});
},
'Sage/UI/nls/es-do/SearchMenuItem':function(){
define('Sage/UI/nls/es-do/SearchMenuItem',{});
},
'Sage/UI/nls/es/NotesHistoryList':function(){
define('Sage/UI/nls/es/NotesHistoryList',{});
},
'Sage/UI/nls/es-do/NotesHistoryList':function(){
define('Sage/UI/nls/es-do/NotesHistoryList',{});
},
'Sage/Utility/File/nls/es/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/es-do/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es-do/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/HistoryEditor',{});
},
'Sage/Groups/nls/es/GroupManager':function(){
define('Sage/Groups/nls/es/GroupManager',{});
},
'Sage/Groups/nls/es-do/GroupManager':function(){
define('Sage/Groups/nls/es-do/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/es/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/es/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/es/UnconfirmedAlarm',{});
},
'Sage/UI/Alarms/nls/es-do/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/es-do/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/es/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/es-do/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es-do/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/es/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/es-do/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es-do/AccountingTasksTasklet',{});
},
'Sage/UI/nls/es/EditableGrid':function(){
define('Sage/UI/nls/es/EditableGrid',{});
},
'Sage/UI/nls/es-do/EditableGrid':function(){
define('Sage/UI/nls/es-do/EditableGrid',{});
},
'Sage/UI/nls/es/SpeedSearch':function(){
define('Sage/UI/nls/es/SpeedSearch',{});
},
'Sage/UI/nls/es-do/SpeedSearch':function(){
define('Sage/UI/nls/es-do/SpeedSearch',{});
},
'Sage/UI/nls/es/SLXPreviewGrid':function(){
define('Sage/UI/nls/es/SLXPreviewGrid',{});
},
'Sage/UI/nls/es-do/SLXPreviewGrid':function(){
define('Sage/UI/nls/es-do/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/es/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/es-do/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es-do/UnconfirmedPane',{});
},
'Sage/Utility/nls/es/Utility':function(){
define('Sage/Utility/nls/es/Utility',{});
},
'Sage/Utility/nls/es-do/Utility':function(){
define('Sage/Utility/nls/es-do/Utility',{});
},
'Sage/UI/Controls/nls/es/Address':function(){
define('Sage/UI/Controls/nls/es/Address',{});
},
'Sage/UI/Controls/nls/es-do/Address':function(){
define('Sage/UI/Controls/nls/es-do/Address',{});
},
'Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/BaseListPanelConfig',{});
},
'Sage/UI/nls/es/UserType':function(){
define('Sage/UI/nls/es/UserType',{});
},
'Sage/UI/nls/es-do/UserType':function(){
define('Sage/UI/nls/es-do/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/es/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/es-do/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es-do/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/es/ActivityList':function(){
define('Sage/UI/nls/es/ActivityList',{});
},
'Sage/UI/nls/es-do/ActivityList':function(){
define('Sage/UI/nls/es-do/ActivityList',{});
},
'Sage/UI/nls/es/CalendarUsersListPane':function(){
define('Sage/UI/nls/es/CalendarUsersListPane',{});
},
'Sage/UI/nls/es-do/CalendarUsersListPane':function(){
define('Sage/UI/nls/es-do/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/es/Attachment':function(){
define('Sage/Utility/File/nls/es/Attachment',{});
},
'Sage/Utility/File/nls/es-do/Attachment':function(){
define('Sage/Utility/File/nls/es-do/Attachment',{});
},
'Sage/MailMerge/nls/es/Helper':function(){
define('Sage/MailMerge/nls/es/Helper',{});
},
'Sage/MailMerge/nls/es-do/Helper':function(){
define('Sage/MailMerge/nls/es-do/Helper',{});
},
'Sage/UI/Dashboard/nls/es/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es/Dashboard',{});
},
'Sage/UI/Dashboard/nls/es-do/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es-do/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/es/PickList':function(){
define('Sage/UI/Controls/nls/es/PickList',{});
},
'Sage/UI/Controls/nls/es-do/PickList':function(){
define('Sage/UI/Controls/nls/es-do/PickList',{});
},
'Sage/Utility/nls/es/Email':function(){
define('Sage/Utility/nls/es/Email',{});
},
'Sage/Utility/nls/es-do/Email':function(){
define('Sage/Utility/nls/es-do/Email',{});
},
'Sage/UI/nls/es/TimeZoneItem':function(){
define('Sage/UI/nls/es/TimeZoneItem',{});
},
'Sage/UI/nls/es-do/TimeZoneItem':function(){
define('Sage/UI/nls/es-do/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/es/SlxEdit':function(){
define('Sage/UI/Columns/nls/es/SlxEdit',{});
},
'Sage/UI/Columns/nls/es-do/SlxEdit':function(){
define('Sage/UI/Columns/nls/es-do/SlxEdit',{});
},
'Sage/UI/Controls/nls/es/LogOffButton':function(){
define('Sage/UI/Controls/nls/es/LogOffButton',{});
},
'Sage/UI/Controls/nls/es-do/LogOffButton':function(){
define('Sage/UI/Controls/nls/es-do/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/es/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-do/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-do/EditEventEditor',{});
},
'Sage/MailMerge/nls/es/Loader':function(){
define('Sage/MailMerge/nls/es/Loader',{});
},
'Sage/MailMerge/nls/es-do/Loader':function(){
define('Sage/MailMerge/nls/es-do/Loader',{});
},
'Sage/UI/Controls/nls/es/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es/DateTimePicker',{});
},
'Sage/UI/Controls/nls/es-do/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es-do/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/es/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/es-do/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es-do/AlarmPopup',{});
},
'Sage/UI/Controls/nls/es/Lookup':function(){
define('Sage/UI/Controls/nls/es/Lookup',{});
},
'Sage/UI/Controls/nls/es-do/Lookup':function(){
define('Sage/UI/Controls/nls/es-do/Lookup',{});
},
'Sage/Utility/File/nls/es/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es/DescriptionsForm',{});
},
'Sage/Utility/File/nls/es-do/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es-do/DescriptionsForm',{});
},
'Sage/TaskPane/nls/es/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/es-do/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es-do/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_es-do", [], 1);
