require({cache:{
'Sage/Utility/File/nls/ja/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ja/FallbackFilePicker',{});
},
'Sage/UI/nls/ja/Boolean':function(){
define('Sage/UI/nls/ja/Boolean',{});
},
'Sage/Services/nls/ja/ActivityService':function(){
define('Sage/Services/nls/ja/ActivityService',{});
},
'Sage/UI/Controls/nls/ja/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ja/CopyToClipboard',{});
},
'Sage/Utility/nls/ja/Activity':function(){
define('Sage/Utility/nls/ja/Activity',{});
},
'Sage/QuickForms/Design/nls/ja/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ja/DesignPanel',{});
},
'Sage/UI/nls/ja/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ja/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ja/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ja/ActivityEditor',{});
},
'Sage/MainView/nls/ja/ActivityManager':function(){
define('Sage/MainView/nls/ja/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/ja/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/_PropertyEditor',{});
},
'Sage/Services/nls/ja/ActivityActionProcessor':function(){
define('Sage/Services/nls/ja/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ja/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ja/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/ja/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ja/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ja/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ja/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ja/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ja/AlarmPane',{});
},
'Sage/TaskPane/nls/ja/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ja/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ja/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ja/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ja/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ja/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ja/FilterPanel':function(){
define('Sage/UI/Filters/nls/ja/FilterPanel',{});
},
'Sage/TaskPane/nls/ja/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ja/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/ja/OwnerType':function(){
define('Sage/UI/nls/ja/OwnerType',{});
},
'Sage/TaskPane/nls/ja/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ja/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ja/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ja/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ja/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ja/InvoiceRTDV',{});
},
'Sage/UI/nls/ja/SDataLookup':function(){
define('Sage/UI/nls/ja/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ja/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/RowDesigner',{});
},
'Sage/TaskPane/nls/ja/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ja/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ja/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ja/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ja/LibraryDocument':function(){
define('Sage/Utility/File/nls/ja/LibraryDocument',{});
},
'Sage/UI/nls/ja/ConditionManager':function(){
define('Sage/UI/nls/ja/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ja/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ja/WidgetDefinition',{});
},
'Sage/UI/nls/ja/SearchConditionWidget':function(){
define('Sage/UI/nls/ja/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/ja/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ja/DataSourcePanel',{});
},
'Sage/UI/nls/ja/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ja/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ja/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ja/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ja/Name':function(){
define('Sage/UI/Controls/nls/ja/Name',{});
},
'Sage/QuickForms/Design/nls/ja/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ja/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ja/UpdateLeads',{});
},
'Sage/UI/nls/ja/ListPanel':function(){
define('Sage/UI/nls/ja/ListPanel',{});
},
'Sage/UI/Filters/nls/ja/EditFilters':function(){
define('Sage/UI/Filters/nls/ja/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ja/DurationSelect':function(){
define('Sage/UI/Controls/nls/ja/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ja/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ja/AlarmCountDown',{});
},
'Sage/UI/nls/ja/AttachmentList':function(){
define('Sage/UI/nls/ja/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/ja/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ja/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ja/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ja/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ja/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ja/Dialogs':function(){
define('Sage/UI/nls/ja/Dialogs',{});
},
'Sage/TaskPane/nls/ja/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ja/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ja/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ja/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ja/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ja/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ja/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/UserControlDesigner',{});
},
'Sage/Groups/nls/ja/GroupNavigator':function(){
define('Sage/Groups/nls/ja/GroupNavigator',{});
},
'Sage/Utility/File/nls/ja/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ja/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ja/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ja/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/ja/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ja/DesignSurface',{});
},
'Sage/Utility/File/nls/ja/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ja/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/ja/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ja/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ja/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ja/EventListPanelConfig',{});
},
'Sage/UI/nls/ja/ActivityScheduler':function(){
define('Sage/UI/nls/ja/ActivityScheduler',{});
},
'Sage/MainView/nls/ja/SecurityManager':function(){
define('Sage/MainView/nls/ja/SecurityManager',{});
},
'Sage/TaskPane/nls/ja/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ja/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ja/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ja/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ja/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ja/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/ja/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ja/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/ja/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ja/HelpMenu':function(){
define('Sage/UI/Controls/nls/ja/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ja/UserTasklet':function(){
define('Sage/TaskPane/nls/ja/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ja/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ja/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ja/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ja/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/ja/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ja/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ja/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/ColumnDesigner',{});
},
'Sage/UI/nls/ja/SearchMenuItem':function(){
define('Sage/UI/nls/ja/SearchMenuItem',{});
},
'Sage/UI/nls/ja/NotesHistoryList':function(){
define('Sage/UI/nls/ja/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/ja/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/ja/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ja/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ja/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ja/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ja/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ja/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ja/HistoryEditor',{});
},
'Sage/Groups/nls/ja/GroupManager':function(){
define('Sage/Groups/nls/ja/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ja/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ja/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/ja/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ja/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ja/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ja/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ja/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ja/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ja/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ja/EditableGrid':function(){
define('Sage/UI/nls/ja/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/ja/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ja/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ja/SpeedSearch':function(){
define('Sage/UI/nls/ja/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ja/SLXPreviewGrid':function(){
define('Sage/UI/nls/ja/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ja/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ja/UnconfirmedPane',{});
},
'Sage/Utility/nls/ja/Utility':function(){
define('Sage/Utility/nls/ja/Utility',{});
},
'Sage/QuickForms/Design/nls/ja/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ja/Address':function(){
define('Sage/UI/Controls/nls/ja/Address',{});
},
'Sage/MainView/ActivityMgr/nls/ja/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ja/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ja/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/OwnerControlDesigner',{});
},
'Sage/UI/nls/ja/UserType':function(){
define('Sage/UI/nls/ja/UserType',{});
},
'Sage/QuickForms/Design/nls/ja/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ja/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ja/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/ja/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ja/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ja/ActivityList':function(){
define('Sage/UI/nls/ja/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ja/CalendarUsersListPane':function(){
define('Sage/UI/nls/ja/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ja/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ja/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ja/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ja/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ja/Attachment':function(){
define('Sage/Utility/File/nls/ja/Attachment',{});
},
'Sage/QuickForms/Design/nls/ja/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ja/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ja/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/ja/Helper':function(){
define('Sage/MailMerge/nls/ja/Helper',{});
},
'Sage/UI/Dashboard/nls/ja/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ja/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ja/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ja/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ja/PickList':function(){
define('Sage/UI/Controls/nls/ja/PickList',{});
},
'Sage/Utility/nls/ja/Email':function(){
define('Sage/Utility/nls/ja/Email',{});
},
'Sage/TaskPane/nls/ja/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ja/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ja/TimeZoneItem':function(){
define('Sage/UI/nls/ja/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ja/SlxEdit':function(){
define('Sage/UI/Columns/nls/ja/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/ja/LogOffButton':function(){
define('Sage/UI/Controls/nls/ja/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ja/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ja/EditEventEditor',{});
},
'Sage/MailMerge/nls/ja/Loader':function(){
define('Sage/MailMerge/nls/ja/Loader',{});
},
'Sage/UI/Controls/nls/ja/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ja/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/ja/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ja/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/ja/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ja/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ja/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ja/Lookup':function(){
define('Sage/UI/Controls/nls/ja/Lookup',{});
},
'Sage/Utility/File/nls/ja/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ja/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ja/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ja/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ja/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ja/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ja/Dashboard':function(){
define('Sage/Utility/nls/ja/Dashboard',{});
}}});
define("Sage/nls/Sage_ja", [], 1);
