require({cache:{
'Sage/Utility/File/nls/nb/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/nb/FallbackFilePicker',{});
},
'Sage/UI/nls/nb/Boolean':function(){
define('Sage/UI/nls/nb/Boolean',{});
},
'Sage/Services/nls/nb/ActivityService':function(){
define('Sage/Services/nls/nb/ActivityService',{});
},
'Sage/UI/Controls/nls/nb/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/nb/CopyToClipboard',{});
},
'Sage/Utility/nls/nb/Activity':function(){
define('Sage/Utility/nls/nb/Activity',{});
},
'Sage/QuickForms/Design/nls/nb/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/nb/DesignPanel',{});
},
'Sage/UI/nls/nb/TimelessActivitiesPane':function(){
define('Sage/UI/nls/nb/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/nb/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb/ActivityEditor',{});
},
'Sage/MainView/nls/nb/ActivityManager':function(){
define('Sage/MainView/nls/nb/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/nb/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/_PropertyEditor',{});
},
'Sage/Services/nls/nb/ActivityActionProcessor':function(){
define('Sage/Services/nls/nb/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nb/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/nb/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/nb/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/nb/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/nb/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/nb/AlarmPane':function(){
define('Sage/UI/Alarms/nls/nb/AlarmPane',{});
},
'Sage/TaskPane/nls/nb/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/nb/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/nb/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/nb/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/nb/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nb/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/nb/FilterPanel':function(){
define('Sage/UI/Filters/nls/nb/FilterPanel',{});
},
'Sage/TaskPane/nls/nb/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/nb/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/nb/OwnerType':function(){
define('Sage/UI/nls/nb/OwnerType',{});
},
'Sage/TaskPane/nls/nb/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/nb/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/nb/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/nb/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/nb/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nb/InvoiceRTDV',{});
},
'Sage/UI/nls/nb/SDataLookup':function(){
define('Sage/UI/nls/nb/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/nb/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/RowDesigner',{});
},
'Sage/TaskPane/nls/nb/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/nb/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/nb/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/nb/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/nb/LibraryDocument':function(){
define('Sage/Utility/File/nls/nb/LibraryDocument',{});
},
'Sage/UI/nls/nb/ConditionManager':function(){
define('Sage/UI/nls/nb/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/nb/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/nb/WidgetDefinition',{});
},
'Sage/UI/nls/nb/SearchConditionWidget':function(){
define('Sage/UI/nls/nb/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/nb/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/nb/DataSourcePanel',{});
},
'Sage/UI/nls/nb/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/nb/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/nb/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/nb/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/nb/Name':function(){
define('Sage/UI/Controls/nls/nb/Name',{});
},
'Sage/QuickForms/Design/nls/nb/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/nb/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/nb/UpdateLeads',{});
},
'Sage/UI/nls/nb/ListPanel':function(){
define('Sage/UI/nls/nb/ListPanel',{});
},
'Sage/UI/Filters/nls/nb/EditFilters':function(){
define('Sage/UI/Filters/nls/nb/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/nb/DurationSelect':function(){
define('Sage/UI/Controls/nls/nb/DurationSelect',{});
},
'Sage/UI/Alarms/nls/nb/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/nb/AlarmCountDown',{});
},
'Sage/UI/nls/nb/AttachmentList':function(){
define('Sage/UI/nls/nb/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/nb/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/nb/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/nb/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/nb/Dialogs':function(){
define('Sage/UI/nls/nb/Dialogs',{});
},
'Sage/TaskPane/nls/nb/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/nb/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/nb/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/nb/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/nb/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/nb/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/nb/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/UserControlDesigner',{});
},
'Sage/Groups/nls/nb/GroupNavigator':function(){
define('Sage/Groups/nls/nb/GroupNavigator',{});
},
'Sage/Utility/File/nls/nb/AddURLAttachment':function(){
define('Sage/Utility/File/nls/nb/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/nb/EditFilterItems':function(){
define('Sage/UI/Filters/nls/nb/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/nb/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/nb/DesignSurface',{});
},
'Sage/Utility/File/nls/nb/DragDropWatcher':function(){
define('Sage/Utility/File/nls/nb/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/nb/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nb/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb/EventListPanelConfig',{});
},
'Sage/UI/nls/nb/ActivityScheduler':function(){
define('Sage/UI/nls/nb/ActivityScheduler',{});
},
'Sage/MainView/nls/nb/SecurityManager':function(){
define('Sage/MainView/nls/nb/SecurityManager',{});
},
'Sage/TaskPane/nls/nb/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/nb/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/nb/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/nb/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/nb/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/nb/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/nb/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/nb/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/nb/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/nb/HelpMenu':function(){
define('Sage/UI/Controls/nls/nb/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/nb/UserTasklet':function(){
define('Sage/TaskPane/nls/nb/UserTasklet',{});
},
'Sage/UI/Alarms/nls/nb/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/nb/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/nb/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/nb/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/nb/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/nb/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/nb/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/ColumnDesigner',{});
},
'Sage/UI/nls/nb/SearchMenuItem':function(){
define('Sage/UI/nls/nb/SearchMenuItem',{});
},
'Sage/UI/nls/nb/NotesHistoryList':function(){
define('Sage/UI/nls/nb/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/nb/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/nb/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/nb/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/nb/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/nb/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/nb/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb/HistoryEditor',{});
},
'Sage/Groups/nls/nb/GroupManager':function(){
define('Sage/Groups/nls/nb/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nb/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/nb/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/nb/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/nb/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/nb/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/nb/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/nb/EditableGrid':function(){
define('Sage/UI/nls/nb/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/nb/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/nb/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/nb/SpeedSearch':function(){
define('Sage/UI/nls/nb/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/nb/SLXPreviewGrid':function(){
define('Sage/UI/nls/nb/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/nb/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/nb/UnconfirmedPane',{});
},
'Sage/Utility/nls/nb/Utility':function(){
define('Sage/Utility/nls/nb/Utility',{});
},
'Sage/QuickForms/Design/nls/nb/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/ControlDesigner',{});
},
'Sage/UI/Controls/nls/nb/Address':function(){
define('Sage/UI/Controls/nls/nb/Address',{});
},
'Sage/MainView/ActivityMgr/nls/nb/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/nb/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/OwnerControlDesigner',{});
},
'Sage/UI/nls/nb/UserType':function(){
define('Sage/UI/nls/nb/UserType',{});
},
'Sage/QuickForms/Design/nls/nb/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/nb/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/nb/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/nb/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/nb/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/nb/ActivityList':function(){
define('Sage/UI/nls/nb/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/nb/CalendarUsersListPane':function(){
define('Sage/UI/nls/nb/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/nb/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/nb/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nb/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/nb/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/nb/Attachment':function(){
define('Sage/Utility/File/nls/nb/Attachment',{});
},
'Sage/QuickForms/Design/nls/nb/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/nb/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/nb/Helper':function(){
define('Sage/MailMerge/nls/nb/Helper',{});
},
'Sage/UI/Dashboard/nls/nb/Dashboard':function(){
define('Sage/UI/Dashboard/nls/nb/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/nb/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/nb/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/nb/PickList':function(){
define('Sage/UI/Controls/nls/nb/PickList',{});
},
'Sage/Utility/nls/nb/Email':function(){
define('Sage/Utility/nls/nb/Email',{});
},
'Sage/TaskPane/nls/nb/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/nb/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/nb/TimeZoneItem':function(){
define('Sage/UI/nls/nb/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/nb/SlxEdit':function(){
define('Sage/UI/Columns/nls/nb/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/nb/LogOffButton':function(){
define('Sage/UI/Controls/nls/nb/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/nb/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/nb/EditEventEditor',{});
},
'Sage/MailMerge/nls/nb/Loader':function(){
define('Sage/MailMerge/nls/nb/Loader',{});
},
'Sage/UI/Controls/nls/nb/DateTimePicker':function(){
define('Sage/UI/Controls/nls/nb/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/nb/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/nb/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/nb/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/nb/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/nb/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/nb/Lookup':function(){
define('Sage/UI/Controls/nls/nb/Lookup',{});
},
'Sage/Utility/File/nls/nb/DescriptionsForm':function(){
define('Sage/Utility/File/nls/nb/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/nb/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/nb/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/nb/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/nb/CommonTasksTasklet',{});
},
'Sage/Utility/nls/nb/Dashboard':function(){
define('Sage/Utility/nls/nb/Dashboard',{});
}}});
define("Sage/nls/Sage_nb", [], 1);
