require({cache:{
'Sage/Utility/File/nls/xh/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/xh/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/xh-za/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/xh-za/FallbackFilePicker',{});
},
'Sage/UI/nls/xh/Boolean':function(){
define('Sage/UI/nls/xh/Boolean',{});
},
'Sage/UI/nls/xh-za/Boolean':function(){
define('Sage/UI/nls/xh-za/Boolean',{});
},
'Sage/UI/Controls/nls/xh/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/xh/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/xh-za/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/xh-za/CopyToClipboard',{});
},
'Sage/Services/nls/xh/ActivityService':function(){
define('Sage/Services/nls/xh/ActivityService',{});
},
'Sage/Services/nls/xh-za/ActivityService':function(){
define('Sage/Services/nls/xh-za/ActivityService',{});
},
'Sage/Utility/nls/xh/Activity':function(){
define('Sage/Utility/nls/xh/Activity',{});
},
'Sage/Utility/nls/xh-za/Activity':function(){
define('Sage/Utility/nls/xh-za/Activity',{});
},
'Sage/UI/nls/xh/TimelessActivitiesPane':function(){
define('Sage/UI/nls/xh/TimelessActivitiesPane',{});
},
'Sage/UI/nls/xh-za/TimelessActivitiesPane':function(){
define('Sage/UI/nls/xh-za/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/ActivityEditor',{});
},
'Sage/MainView/nls/xh/ActivityManager':function(){
define('Sage/MainView/nls/xh/ActivityManager',{});
},
'Sage/MainView/nls/xh-za/ActivityManager':function(){
define('Sage/MainView/nls/xh-za/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/xh/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/xh/Service':function(){
define('Sage/Reporting/nls/xh/Service',{});
},
'Sage/Reporting/nls/xh-za/Service':function(){
define('Sage/Reporting/nls/xh-za/Service',{});
},
'Sage/Utility/File/nls/xh/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/xh/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/xh-za/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/xh-za/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/xh/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/xh/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/xh-za/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/xh-za/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/xh/AlarmPane':function(){
define('Sage/UI/Alarms/nls/xh/AlarmPane',{});
},
'Sage/UI/Alarms/nls/xh-za/AlarmPane':function(){
define('Sage/UI/Alarms/nls/xh-za/AlarmPane',{});
},
'Sage/TaskPane/nls/xh/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/xh/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/xh-za/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/xh-za/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/xh/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/xh/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/xh-za/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/xh-za/DashboardWidget',{});
},
'Sage/UI/Filters/nls/xh/FilterPanel':function(){
define('Sage/UI/Filters/nls/xh/FilterPanel',{});
},
'Sage/UI/Filters/nls/xh-za/FilterPanel':function(){
define('Sage/UI/Filters/nls/xh-za/FilterPanel',{});
},
'Sage/TaskPane/nls/xh/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/xh/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/xh-za/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/xh-za/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/xh/OwnerType':function(){
define('Sage/UI/nls/xh/OwnerType',{});
},
'Sage/UI/nls/xh-za/OwnerType':function(){
define('Sage/UI/nls/xh-za/OwnerType',{});
},
'Sage/TaskPane/nls/xh/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/xh-za/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/xh-za/LeadTasksTasklet',{});
},
'Sage/UI/nls/xh/SDataLookup':function(){
define('Sage/UI/nls/xh/SDataLookup',{});
},
'Sage/UI/nls/xh-za/SDataLookup':function(){
define('Sage/UI/nls/xh-za/SDataLookup',{});
},
'Sage/TaskPane/nls/xh/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/xh-za/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/xh-za/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/xh/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/xh/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/xh-za/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/xh-za/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/xh/LibraryDocument':function(){
define('Sage/Utility/File/nls/xh/LibraryDocument',{});
},
'Sage/Utility/File/nls/xh-za/LibraryDocument':function(){
define('Sage/Utility/File/nls/xh-za/LibraryDocument',{});
},
'Sage/UI/nls/xh/ConditionManager':function(){
define('Sage/UI/nls/xh/ConditionManager',{});
},
'Sage/UI/nls/xh-za/ConditionManager':function(){
define('Sage/UI/nls/xh-za/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/xh/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/xh/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/xh-za/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/xh-za/WidgetDefinition',{});
},
'Sage/UI/nls/xh/SearchConditionWidget':function(){
define('Sage/UI/nls/xh/SearchConditionWidget',{});
},
'Sage/UI/nls/xh-za/SearchConditionWidget':function(){
define('Sage/UI/nls/xh-za/SearchConditionWidget',{});
},
'Sage/UI/nls/xh/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/xh/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/xh-za/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/xh-za/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/xh/Name':function(){
define('Sage/UI/Controls/nls/xh/Name',{});
},
'Sage/UI/Controls/nls/xh-za/Name':function(){
define('Sage/UI/Controls/nls/xh-za/Name',{});
},
'Sage/MainView/Lead/nls/xh/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/xh/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/xh-za/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/xh-za/UpdateLeads',{});
},
'Sage/UI/nls/xh/ListPanel':function(){
define('Sage/UI/nls/xh/ListPanel',{});
},
'Sage/UI/nls/xh-za/ListPanel':function(){
define('Sage/UI/nls/xh-za/ListPanel',{});
},
'Sage/UI/Filters/nls/xh/EditFilters':function(){
define('Sage/UI/Filters/nls/xh/EditFilters',{});
},
'Sage/UI/Filters/nls/xh-za/EditFilters':function(){
define('Sage/UI/Filters/nls/xh-za/EditFilters',{});
},
'Sage/UI/Controls/nls/xh/DurationSelect':function(){
define('Sage/UI/Controls/nls/xh/DurationSelect',{});
},
'Sage/UI/Controls/nls/xh-za/DurationSelect':function(){
define('Sage/UI/Controls/nls/xh-za/DurationSelect',{});
},
'Sage/UI/Alarms/nls/xh/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/xh/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/xh-za/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/xh-za/AlarmCountDown',{});
},
'Sage/UI/nls/xh/AttachmentList':function(){
define('Sage/UI/nls/xh/AttachmentList',{});
},
'Sage/UI/nls/xh-za/AttachmentList':function(){
define('Sage/UI/nls/xh-za/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/xh/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/xh/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/xh-za/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/xh-za/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/xh/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/xh/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/xh-za/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/xh-za/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/xh/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/xh/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/xh-za/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/xh-za/DashboardTabController',{});
},
'Sage/Groups/nls/xh/GroupNavigator':function(){
define('Sage/Groups/nls/xh/GroupNavigator',{});
},
'Sage/Groups/nls/xh-za/GroupNavigator':function(){
define('Sage/Groups/nls/xh-za/GroupNavigator',{});
},
'Sage/Utility/File/nls/xh/AddURLAttachment':function(){
define('Sage/Utility/File/nls/xh/AddURLAttachment',{});
},
'Sage/Utility/File/nls/xh-za/AddURLAttachment':function(){
define('Sage/Utility/File/nls/xh-za/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/xh/EditFilterItems':function(){
define('Sage/UI/Filters/nls/xh/EditFilterItems',{});
},
'Sage/UI/Filters/nls/xh-za/EditFilterItems':function(){
define('Sage/UI/Filters/nls/xh-za/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/EventListPanelConfig',{});
},
'Sage/UI/nls/xh/ActivityScheduler':function(){
define('Sage/UI/nls/xh/ActivityScheduler',{});
},
'Sage/UI/nls/xh-za/ActivityScheduler':function(){
define('Sage/UI/nls/xh-za/ActivityScheduler',{});
},
'Sage/MainView/nls/xh/SecurityManager':function(){
define('Sage/MainView/nls/xh/SecurityManager',{});
},
'Sage/MainView/nls/xh-za/SecurityManager':function(){
define('Sage/MainView/nls/xh-za/SecurityManager',{});
},
'Sage/TaskPane/nls/xh/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/xh/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/xh-za/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/xh-za/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/xh/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/xh/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/xh-za/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/xh-za/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/xh/HelpMenu':function(){
define('Sage/UI/Controls/nls/xh/HelpMenu',{});
},
'Sage/UI/Controls/nls/xh-za/HelpMenu':function(){
define('Sage/UI/Controls/nls/xh-za/HelpMenu',{});
},
'Sage/TaskPane/nls/xh/UserTasklet':function(){
define('Sage/TaskPane/nls/xh/UserTasklet',{});
},
'Sage/TaskPane/nls/xh-za/UserTasklet':function(){
define('Sage/TaskPane/nls/xh-za/UserTasklet',{});
},
'Sage/UI/Alarms/nls/xh/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/xh/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/xh-za/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/xh-za/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/xh/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/xh/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/xh-za/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/xh-za/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/xh/MenuHelper':function(){
define('Sage/MailMerge/nls/xh/MenuHelper',{});
},
'Sage/MailMerge/nls/xh-za/MenuHelper':function(){
define('Sage/MailMerge/nls/xh-za/MenuHelper',{});
},
'Sage/UI/nls/xh/SearchMenuItem':function(){
define('Sage/UI/nls/xh/SearchMenuItem',{});
},
'Sage/UI/nls/xh-za/SearchMenuItem':function(){
define('Sage/UI/nls/xh-za/SearchMenuItem',{});
},
'Sage/UI/nls/xh/NotesHistoryList':function(){
define('Sage/UI/nls/xh/NotesHistoryList',{});
},
'Sage/UI/nls/xh-za/NotesHistoryList':function(){
define('Sage/UI/nls/xh-za/NotesHistoryList',{});
},
'Sage/Utility/File/nls/xh/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/xh/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/xh-za/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/xh-za/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/xh/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/HistoryEditor',{});
},
'Sage/Groups/nls/xh/GroupManager':function(){
define('Sage/Groups/nls/xh/GroupManager',{});
},
'Sage/Groups/nls/xh-za/GroupManager':function(){
define('Sage/Groups/nls/xh-za/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/xh/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/xh/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/xh/UnconfirmedAlarm',{});
},
'Sage/UI/Alarms/nls/xh-za/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/xh-za/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/xh/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/xh/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/xh-za/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/xh-za/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/xh/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/xh-za/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/xh-za/AccountingTasksTasklet',{});
},
'Sage/UI/nls/xh/EditableGrid':function(){
define('Sage/UI/nls/xh/EditableGrid',{});
},
'Sage/UI/nls/xh-za/EditableGrid':function(){
define('Sage/UI/nls/xh-za/EditableGrid',{});
},
'Sage/UI/nls/xh/SpeedSearch':function(){
define('Sage/UI/nls/xh/SpeedSearch',{});
},
'Sage/UI/nls/xh-za/SpeedSearch':function(){
define('Sage/UI/nls/xh-za/SpeedSearch',{});
},
'Sage/UI/nls/xh/SLXPreviewGrid':function(){
define('Sage/UI/nls/xh/SLXPreviewGrid',{});
},
'Sage/UI/nls/xh-za/SLXPreviewGrid':function(){
define('Sage/UI/nls/xh-za/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/xh/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/xh/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/xh-za/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/xh-za/UnconfirmedPane',{});
},
'Sage/Utility/nls/xh/Utility':function(){
define('Sage/Utility/nls/xh/Utility',{});
},
'Sage/Utility/nls/xh-za/Utility':function(){
define('Sage/Utility/nls/xh-za/Utility',{});
},
'Sage/UI/Controls/nls/xh/Address':function(){
define('Sage/UI/Controls/nls/xh/Address',{});
},
'Sage/UI/Controls/nls/xh-za/Address':function(){
define('Sage/UI/Controls/nls/xh-za/Address',{});
},
'Sage/MainView/ActivityMgr/nls/xh/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/BaseListPanelConfig',{});
},
'Sage/UI/nls/xh/UserType':function(){
define('Sage/UI/nls/xh/UserType',{});
},
'Sage/UI/nls/xh-za/UserType':function(){
define('Sage/UI/nls/xh-za/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/xh/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/xh/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/xh-za/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/xh-za/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/xh/ActivityList':function(){
define('Sage/UI/nls/xh/ActivityList',{});
},
'Sage/UI/nls/xh-za/ActivityList':function(){
define('Sage/UI/nls/xh-za/ActivityList',{});
},
'Sage/UI/nls/xh/CalendarUsersListPane':function(){
define('Sage/UI/nls/xh/CalendarUsersListPane',{});
},
'Sage/UI/nls/xh-za/CalendarUsersListPane':function(){
define('Sage/UI/nls/xh-za/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/xh/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/xh/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/xh/Attachment':function(){
define('Sage/Utility/File/nls/xh/Attachment',{});
},
'Sage/Utility/File/nls/xh-za/Attachment':function(){
define('Sage/Utility/File/nls/xh-za/Attachment',{});
},
'Sage/MailMerge/nls/xh/Helper':function(){
define('Sage/MailMerge/nls/xh/Helper',{});
},
'Sage/MailMerge/nls/xh-za/Helper':function(){
define('Sage/MailMerge/nls/xh-za/Helper',{});
},
'Sage/UI/Dashboard/nls/xh/Dashboard':function(){
define('Sage/UI/Dashboard/nls/xh/Dashboard',{});
},
'Sage/UI/Dashboard/nls/xh-za/Dashboard':function(){
define('Sage/UI/Dashboard/nls/xh-za/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/xh/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/xh/PickList':function(){
define('Sage/UI/Controls/nls/xh/PickList',{});
},
'Sage/UI/Controls/nls/xh-za/PickList':function(){
define('Sage/UI/Controls/nls/xh-za/PickList',{});
},
'Sage/Utility/nls/xh/Email':function(){
define('Sage/Utility/nls/xh/Email',{});
},
'Sage/Utility/nls/xh-za/Email':function(){
define('Sage/Utility/nls/xh-za/Email',{});
},
'Sage/UI/nls/xh/TimeZoneItem':function(){
define('Sage/UI/nls/xh/TimeZoneItem',{});
},
'Sage/UI/nls/xh-za/TimeZoneItem':function(){
define('Sage/UI/nls/xh-za/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/xh/SlxEdit':function(){
define('Sage/UI/Columns/nls/xh/SlxEdit',{});
},
'Sage/UI/Columns/nls/xh-za/SlxEdit':function(){
define('Sage/UI/Columns/nls/xh-za/SlxEdit',{});
},
'Sage/UI/Controls/nls/xh/LogOffButton':function(){
define('Sage/UI/Controls/nls/xh/LogOffButton',{});
},
'Sage/UI/Controls/nls/xh-za/LogOffButton':function(){
define('Sage/UI/Controls/nls/xh-za/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/xh/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/xh-za/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/xh-za/EditEventEditor',{});
},
'Sage/MailMerge/nls/xh/Loader':function(){
define('Sage/MailMerge/nls/xh/Loader',{});
},
'Sage/MailMerge/nls/xh-za/Loader':function(){
define('Sage/MailMerge/nls/xh-za/Loader',{});
},
'Sage/UI/Controls/nls/xh/DateTimePicker':function(){
define('Sage/UI/Controls/nls/xh/DateTimePicker',{});
},
'Sage/UI/Controls/nls/xh-za/DateTimePicker':function(){
define('Sage/UI/Controls/nls/xh-za/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/xh/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/xh/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/xh-za/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/xh-za/AlarmPopup',{});
},
'Sage/UI/Controls/nls/xh/Lookup':function(){
define('Sage/UI/Controls/nls/xh/Lookup',{});
},
'Sage/UI/Controls/nls/xh-za/Lookup':function(){
define('Sage/UI/Controls/nls/xh-za/Lookup',{});
},
'Sage/Utility/File/nls/xh/DescriptionsForm':function(){
define('Sage/Utility/File/nls/xh/DescriptionsForm',{});
},
'Sage/Utility/File/nls/xh-za/DescriptionsForm':function(){
define('Sage/Utility/File/nls/xh-za/DescriptionsForm',{});
},
'Sage/TaskPane/nls/xh/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/xh/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/xh-za/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/xh-za/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_xh-za", [], 1);
