require({cache:{
'Sage/Utility/File/nls/hi/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/hi/FallbackFilePicker',{});
},
'Sage/UI/nls/hi/Boolean':function(){
define('Sage/UI/nls/hi/Boolean',{});
},
'Sage/Services/nls/hi/ActivityService':function(){
define('Sage/Services/nls/hi/ActivityService',{});
},
'Sage/UI/Controls/nls/hi/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/hi/CopyToClipboard',{});
},
'Sage/Utility/nls/hi/Activity':function(){
define('Sage/Utility/nls/hi/Activity',{});
},
'Sage/QuickForms/Design/nls/hi/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/hi/DesignPanel',{});
},
'Sage/UI/nls/hi/TimelessActivitiesPane':function(){
define('Sage/UI/nls/hi/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/hi/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hi/ActivityEditor',{});
},
'Sage/MainView/nls/hi/ActivityManager':function(){
define('Sage/MainView/nls/hi/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/hi/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/_PropertyEditor',{});
},
'Sage/Services/nls/hi/ActivityActionProcessor':function(){
define('Sage/Services/nls/hi/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/hi/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hi/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/hi/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/hi/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/hi/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/hi/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/hi/AlarmPane':function(){
define('Sage/UI/Alarms/nls/hi/AlarmPane',{});
},
'Sage/TaskPane/nls/hi/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/hi/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/hi/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/hi/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/hi/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/hi/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/hi/FilterPanel':function(){
define('Sage/UI/Filters/nls/hi/FilterPanel',{});
},
'Sage/TaskPane/nls/hi/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/hi/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/hi/OwnerType':function(){
define('Sage/UI/nls/hi/OwnerType',{});
},
'Sage/TaskPane/nls/hi/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/hi/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/hi/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/hi/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/hi/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/hi/InvoiceRTDV',{});
},
'Sage/UI/nls/hi/SDataLookup':function(){
define('Sage/UI/nls/hi/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/hi/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/RowDesigner',{});
},
'Sage/TaskPane/nls/hi/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/hi/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/hi/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/hi/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/hi/LibraryDocument':function(){
define('Sage/Utility/File/nls/hi/LibraryDocument',{});
},
'Sage/UI/nls/hi/ConditionManager':function(){
define('Sage/UI/nls/hi/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/hi/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/hi/WidgetDefinition',{});
},
'Sage/UI/nls/hi/SearchConditionWidget':function(){
define('Sage/UI/nls/hi/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/hi/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/hi/DataSourcePanel',{});
},
'Sage/UI/nls/hi/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/hi/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/hi/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/hi/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/hi/Name':function(){
define('Sage/UI/Controls/nls/hi/Name',{});
},
'Sage/QuickForms/Design/nls/hi/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/hi/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/hi/UpdateLeads',{});
},
'Sage/UI/nls/hi/ListPanel':function(){
define('Sage/UI/nls/hi/ListPanel',{});
},
'Sage/UI/Filters/nls/hi/EditFilters':function(){
define('Sage/UI/Filters/nls/hi/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/hi/DurationSelect':function(){
define('Sage/UI/Controls/nls/hi/DurationSelect',{});
},
'Sage/UI/Alarms/nls/hi/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/hi/AlarmCountDown',{});
},
'Sage/UI/nls/hi/AttachmentList':function(){
define('Sage/UI/nls/hi/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/hi/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hi/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hi/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/hi/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/hi/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/hi/Dialogs':function(){
define('Sage/UI/nls/hi/Dialogs',{});
},
'Sage/TaskPane/nls/hi/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/hi/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/hi/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/hi/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/hi/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/hi/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/hi/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/UserControlDesigner',{});
},
'Sage/Groups/nls/hi/GroupNavigator':function(){
define('Sage/Groups/nls/hi/GroupNavigator',{});
},
'Sage/Utility/File/nls/hi/AddURLAttachment':function(){
define('Sage/Utility/File/nls/hi/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/hi/EditFilterItems':function(){
define('Sage/UI/Filters/nls/hi/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/hi/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/hi/DesignSurface',{});
},
'Sage/Utility/File/nls/hi/DragDropWatcher':function(){
define('Sage/Utility/File/nls/hi/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/hi/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hi/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/hi/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hi/EventListPanelConfig',{});
},
'Sage/UI/nls/hi/ActivityScheduler':function(){
define('Sage/UI/nls/hi/ActivityScheduler',{});
},
'Sage/MainView/nls/hi/SecurityManager':function(){
define('Sage/MainView/nls/hi/SecurityManager',{});
},
'Sage/TaskPane/nls/hi/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/hi/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/hi/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/hi/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/hi/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/hi/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/hi/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/hi/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/hi/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/hi/HelpMenu':function(){
define('Sage/UI/Controls/nls/hi/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/hi/UserTasklet':function(){
define('Sage/TaskPane/nls/hi/UserTasklet',{});
},
'Sage/UI/Alarms/nls/hi/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/hi/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/hi/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/hi/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/hi/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/hi/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/hi/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/ColumnDesigner',{});
},
'Sage/UI/nls/hi/SearchMenuItem':function(){
define('Sage/UI/nls/hi/SearchMenuItem',{});
},
'Sage/UI/nls/hi/NotesHistoryList':function(){
define('Sage/UI/nls/hi/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/hi/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/hi/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/hi/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/hi/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/hi/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hi/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/hi/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hi/HistoryEditor',{});
},
'Sage/Groups/nls/hi/GroupManager':function(){
define('Sage/Groups/nls/hi/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/hi/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hi/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/hi/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hi/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hi/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/hi/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/hi/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/hi/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/hi/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/hi/EditableGrid':function(){
define('Sage/UI/nls/hi/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/hi/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/hi/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/hi/SpeedSearch':function(){
define('Sage/UI/nls/hi/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/hi/SLXPreviewGrid':function(){
define('Sage/UI/nls/hi/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/hi/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/hi/UnconfirmedPane',{});
},
'Sage/Utility/nls/hi/Utility':function(){
define('Sage/Utility/nls/hi/Utility',{});
},
'Sage/QuickForms/Design/nls/hi/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/ControlDesigner',{});
},
'Sage/UI/Controls/nls/hi/Address':function(){
define('Sage/UI/Controls/nls/hi/Address',{});
},
'Sage/MainView/ActivityMgr/nls/hi/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hi/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/hi/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/OwnerControlDesigner',{});
},
'Sage/UI/nls/hi/UserType':function(){
define('Sage/UI/nls/hi/UserType',{});
},
'Sage/QuickForms/Design/nls/hi/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/hi/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/hi/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/hi/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/hi/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/hi/ActivityList':function(){
define('Sage/UI/nls/hi/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/hi/CalendarUsersListPane':function(){
define('Sage/UI/nls/hi/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/hi/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/hi/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/hi/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/hi/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/hi/Attachment':function(){
define('Sage/Utility/File/nls/hi/Attachment',{});
},
'Sage/QuickForms/Design/nls/hi/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hi/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/hi/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/hi/Helper':function(){
define('Sage/MailMerge/nls/hi/Helper',{});
},
'Sage/UI/Dashboard/nls/hi/Dashboard':function(){
define('Sage/UI/Dashboard/nls/hi/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/hi/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hi/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/hi/PickList':function(){
define('Sage/UI/Controls/nls/hi/PickList',{});
},
'Sage/Utility/nls/hi/Email':function(){
define('Sage/Utility/nls/hi/Email',{});
},
'Sage/TaskPane/nls/hi/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/hi/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/hi/TimeZoneItem':function(){
define('Sage/UI/nls/hi/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/hi/SlxEdit':function(){
define('Sage/UI/Columns/nls/hi/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/hi/LogOffButton':function(){
define('Sage/UI/Controls/nls/hi/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/hi/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hi/EditEventEditor',{});
},
'Sage/MailMerge/nls/hi/Loader':function(){
define('Sage/MailMerge/nls/hi/Loader',{});
},
'Sage/UI/Controls/nls/hi/DateTimePicker':function(){
define('Sage/UI/Controls/nls/hi/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/hi/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/hi/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/hi/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hi/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hi/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/hi/Lookup':function(){
define('Sage/UI/Controls/nls/hi/Lookup',{});
},
'Sage/Utility/File/nls/hi/DescriptionsForm':function(){
define('Sage/Utility/File/nls/hi/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/hi/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hi/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/hi/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/hi/CommonTasksTasklet',{});
},
'Sage/Utility/nls/hi/Dashboard':function(){
define('Sage/Utility/nls/hi/Dashboard',{});
}}});
define("Sage/nls/Sage_hi", [], 1);
