define(
        ({
            newTabText: 'Neue Registerkarte',
            addContentText: 'Inhalt hinzufügen',
            editOptionsText: 'Optionen bearbeiten',
            hideTabText: 'Registerkarte ausblenden',
            closeText: 'Schließen',
            copyTabText: 'Registerkarte kopieren',
            showTabText: 'Registerkarte anzeigen',
            shareTabText: 'Registerkarte freigeben',
            deleteTabText: 'Registerkarte löschen',
            deleteTabConfirmText: 'Möchten Sie diese Registerkarte wirklich löschen?',
            descriptionText: 'Beschreibung',
            everyoneText: 'Alle',
            saveTabText: 'Registerkarte speichern',
            helpText: 'Hilfe',
            addText: 'Hinzufügen',
            invalidMessage: 'Ungültiges Zeichen',
            invalidDuplicateMessage: 'Titel muss eindeutig sein.',
            deleteText: 'Löschen',
            titleText: 'Titel:',
            chooseTemplateText: 'Wählen Sie die gewünschte Vorlage aus:',
            oneColumnText: 'Eine Spalte',
            twoColumnText: 'Unterteilung in zwei Spalten',
            fatLeftText: 'Zweispaltig, links größer',
            fatRightText: 'Zweispaltig, rechts größer',
            makeDefaultText: 'Als Standard festlegen',
            releaseFetchErrorText: 'Fehler beim Abrufen der Freigabeliste.',
            releaseDeleteNoneSelected: 'Kein Einträge ausgewählt.',
            releasedToText: 'Freigegeben für:',
            typeText: 'Typ',
            addLookup: 'Hinzufügen',
            okButton: 'OK',
            errorText: 'Fehler',
            warningText: 'Warnung',
            permissionErrorText: 'Fehler: Benutzer ist nicht zum Durchführen dieser Aktion berechtigt.',
            permissionErrorPerformCopyText: 'Möchten Sie eine persönliche Kopie der Seite erstellen?',
            yesText: 'Ja',
            noText: 'Nein'
        })
);