require({cache:{
'dojox/grid/enhanced/nls/en/Filter':function(){
define('dojox/grid/enhanced/nls/en/Filter',{});
},
'dojox/grid/enhanced/nls/en-ca/Filter':function(){
define('dojox/grid/enhanced/nls/en-ca/Filter',{});
},
'dojox/grid/enhanced/nls/en/EnhancedGrid':function(){
define('dojox/grid/enhanced/nls/en/EnhancedGrid',{});
},
'dojox/grid/enhanced/nls/en-ca/EnhancedGrid':function(){
define('dojox/grid/enhanced/nls/en-ca/EnhancedGrid',{});
},
'dojox/grid/enhanced/nls/en/Pagination':function(){
define('dojox/grid/enhanced/nls/en/Pagination',{});
},
'dojox/grid/enhanced/nls/en-ca/Pagination':function(){
define('dojox/grid/enhanced/nls/en-ca/Pagination',{});
},
'dojox/form/nls/en/Uploader':function(){
define('dojox/form/nls/en/Uploader',{});
},
'dojox/form/nls/en-ca/Uploader':function(){
define('dojox/form/nls/en-ca/Uploader',{});
}}});
define("dojox/nls/dojox_en-ca", [], 1);
