define(
    ({
        dialogCaption: "Dettagli Fattura",
        loadingText: "caricamento...",
        lblInvoiceCaption: "Fattura:",
        lblNetTotalCaption: "Importo Fattura:",
        lblInvoiceDateCaption: "Data Fattura:",
        lblInvoiceDiscountAmountCaption: "Sconto:",
        lblDueDateCaption: "Scadenza:",
        lblInvoiceDiscountPercentCaption: "Percentuale Sconto:",
        lblCustomerPOCaption: "Num. Ordine del Cliente:",
        lblCarrierTotalPriceCaption: "Spedizione:",
        lblSettlementDiscountPercentCaption: "Percentuale Liquidazione Sconto:",
        lblTaxCaption: "Tassa:",
        lblSettlementDiscountTermsCaption: "Termini di Pagamento:",
        lblNotesCaption: "Commenti:",
        lblOperatingCompanyCurrencyCaption: "Valuta Sigla Contabile:",
        lblCostTotalCaption: "Costo Totale:",
        lblOperatingCompanyCurrencyExchangeRateDateCaption: "Data Tasso di Cambio:",
        lblProfitTotalCaption: "Profitto Totale:",
        lblOperatingCompanyCurrencyExchangeRateCaption: "Tasso di Cambio:",
        lblPriceListCaption: "Prezzo di Listino:",
        lblOCCurrencyCaption: "Valuta Sigla Contabile:",
        lblCurrencyCaption: "Valuta:",
        lblSalesPersonCaption: "Agente di Vendite:",
        detailsTabTitle: "Dettagli",
        addressTabTitle: "Indirizzi",
        invoiceLinesTabTitle: "Linee Fattura",
        paymentsTabTitle: "Pagamenti",
        deliveriesTabTitle: "Consegne",
        grdInvoice_Name: "Fattura #",
        grdInvoice_Date: "Data Fattura",
        grdInvoice_Amount: "Importo Fattura",
        grdInvoice_PO: "Num. Ordine del Cliente",
        grdInvoice_PaymentTerms: "Termini di Pagamento",
        grdInvoice_NetTotal: "Totale Netto",
        grdInvoice_Tax: "Tassa",
        grdAddress_Name: "Descrizione",
        grdAddress_address1: "Indirizzo 1",
        grdAddress_address2: "Indirizzo 2",
        grdAddress_City: "Città",
        grdAddress_State: "Status",
        grdAddress_Zip: "Cap",
        grdItems_ActualPrice: "Prezzo Attuale",
        grdItems_ChargesTotal: "Totale Oneri",
        grdItems_Commodity: "Merce",
        grdItems_CommodityDimension: "Dimensione",
        grdItems_CommodityVariant: "Variante",
        grdItems_DiscountTotal: "Totale Sconto",
        grdItems_GrossTotal: "Totale Lordo",
        grdItems_InitialPrice: "Prezzo Iniziale",
        grdItems_Line: "Numero Linea",
        grdItems_NetTotal: "Totale Netto",
        grdItems_Quantity: "Quantità",
        grdItems_Status: "Status",
        grdItems_TaxTotal: "Totale Tassa",
        grdItems_Type: "Tipo Linea",
        grdItems_UnitOfMeasure: "Unità",
        grdPayments_Charges: "Oneri",
        grdPayments_Currency: "Valuta",
        grdPayments_Date: "Data",
        grdPayments_Discounts: "Sconti",
        grdPayments_GrossTotal: "Totale Lordo",
        grdPayments_Name: "Nome",
        grdPayments_NetTotal: "Totale Netto",
        grdPayments_ProcessDate: "Data Elaborata",
        grdPayments_Status: "Status",
        grdPayments_Tax: "Tasse",
        grdPayments_TenderReference: "Riferimento Offerta",
        grdPayments_TenderType: "Tipo Offerta",
        grdPayments_Type: "Tipo",
        grdDeliveries_ActualDate: "Data Attuale",
        grdDeliveries_ActualTime: "Orario Attuale",
        grdDeliveries_Carrier: "Vettore",
        grdDeliveries_CarrierReference: "Riferimento Vettore",
        grdDeliveries_DeliveredQuantity: "Quantità Consegnata",
        grdDeliveries_ExceptionReason: "Motivo Eccezione",
        grdDeliveries_Method: "Metodo",
        grdDeliveries_Number: "Numero",
        grdDeliveries_RequestedDate: "Data Richiesta",
        grdDeliveries_RequestedQuantity: "Quantità Richiesta",
        grdDeliveries_Status: "Status",
        grdDeliveries_Type: "Tipo",
        btnCloseCaption: "Chiudi"
    })
);