require({cache:{
'Sage/Utility/File/nls/rm/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/rm/FallbackFilePicker',{});
},
'Sage/UI/nls/rm/Boolean':function(){
define('Sage/UI/nls/rm/Boolean',{});
},
'Sage/Services/nls/rm/ActivityService':function(){
define('Sage/Services/nls/rm/ActivityService',{});
},
'Sage/UI/Controls/nls/rm/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/rm/CopyToClipboard',{});
},
'Sage/Utility/nls/rm/Activity':function(){
define('Sage/Utility/nls/rm/Activity',{});
},
'Sage/QuickForms/Design/nls/rm/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/rm/DesignPanel',{});
},
'Sage/UI/nls/rm/TimelessActivitiesPane':function(){
define('Sage/UI/nls/rm/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/rm/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/rm/ActivityEditor',{});
},
'Sage/MainView/nls/rm/ActivityManager':function(){
define('Sage/MainView/nls/rm/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/rm/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/_PropertyEditor',{});
},
'Sage/Services/nls/rm/ActivityActionProcessor':function(){
define('Sage/Services/nls/rm/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/rm/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/rm/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/rm/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/rm/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/rm/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/rm/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/rm/AlarmPane':function(){
define('Sage/UI/Alarms/nls/rm/AlarmPane',{});
},
'Sage/TaskPane/nls/rm/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/rm/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/rm/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/rm/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/rm/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/rm/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/rm/FilterPanel':function(){
define('Sage/UI/Filters/nls/rm/FilterPanel',{});
},
'Sage/TaskPane/nls/rm/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/rm/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/rm/OwnerType':function(){
define('Sage/UI/nls/rm/OwnerType',{});
},
'Sage/TaskPane/nls/rm/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/rm/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/rm/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/rm/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/rm/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/rm/InvoiceRTDV',{});
},
'Sage/UI/nls/rm/SDataLookup':function(){
define('Sage/UI/nls/rm/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/rm/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/RowDesigner',{});
},
'Sage/TaskPane/nls/rm/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/rm/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/rm/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/rm/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/rm/LibraryDocument':function(){
define('Sage/Utility/File/nls/rm/LibraryDocument',{});
},
'Sage/UI/nls/rm/ConditionManager':function(){
define('Sage/UI/nls/rm/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/rm/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/rm/WidgetDefinition',{});
},
'Sage/UI/nls/rm/SearchConditionWidget':function(){
define('Sage/UI/nls/rm/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/rm/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/rm/DataSourcePanel',{});
},
'Sage/UI/nls/rm/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/rm/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/rm/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/rm/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/rm/Name':function(){
define('Sage/UI/Controls/nls/rm/Name',{});
},
'Sage/QuickForms/Design/nls/rm/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/rm/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/rm/UpdateLeads',{});
},
'Sage/UI/nls/rm/ListPanel':function(){
define('Sage/UI/nls/rm/ListPanel',{});
},
'Sage/UI/Filters/nls/rm/EditFilters':function(){
define('Sage/UI/Filters/nls/rm/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/rm/DurationSelect':function(){
define('Sage/UI/Controls/nls/rm/DurationSelect',{});
},
'Sage/UI/Alarms/nls/rm/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/rm/AlarmCountDown',{});
},
'Sage/UI/nls/rm/AttachmentList':function(){
define('Sage/UI/nls/rm/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/rm/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/rm/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/rm/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/rm/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/rm/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/rm/Dialogs':function(){
define('Sage/UI/nls/rm/Dialogs',{});
},
'Sage/TaskPane/nls/rm/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/rm/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/rm/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/rm/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/rm/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/rm/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/rm/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/UserControlDesigner',{});
},
'Sage/Groups/nls/rm/GroupNavigator':function(){
define('Sage/Groups/nls/rm/GroupNavigator',{});
},
'Sage/Utility/File/nls/rm/AddURLAttachment':function(){
define('Sage/Utility/File/nls/rm/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/rm/EditFilterItems':function(){
define('Sage/UI/Filters/nls/rm/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/rm/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/rm/DesignSurface',{});
},
'Sage/Utility/File/nls/rm/DragDropWatcher':function(){
define('Sage/Utility/File/nls/rm/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/rm/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/rm/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/rm/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/rm/EventListPanelConfig',{});
},
'Sage/UI/nls/rm/ActivityScheduler':function(){
define('Sage/UI/nls/rm/ActivityScheduler',{});
},
'Sage/MainView/nls/rm/SecurityManager':function(){
define('Sage/MainView/nls/rm/SecurityManager',{});
},
'Sage/TaskPane/nls/rm/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/rm/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/rm/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/rm/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/rm/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/rm/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/rm/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/rm/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/rm/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/rm/HelpMenu':function(){
define('Sage/UI/Controls/nls/rm/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/rm/UserTasklet':function(){
define('Sage/TaskPane/nls/rm/UserTasklet',{});
},
'Sage/UI/Alarms/nls/rm/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/rm/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/rm/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/rm/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/rm/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/rm/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/rm/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/ColumnDesigner',{});
},
'Sage/UI/nls/rm/SearchMenuItem':function(){
define('Sage/UI/nls/rm/SearchMenuItem',{});
},
'Sage/UI/nls/rm/NotesHistoryList':function(){
define('Sage/UI/nls/rm/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/rm/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/rm/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/rm/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/rm/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/rm/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/rm/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/rm/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/rm/HistoryEditor',{});
},
'Sage/Groups/nls/rm/GroupManager':function(){
define('Sage/Groups/nls/rm/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/rm/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/rm/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/rm/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/rm/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/rm/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/rm/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/rm/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/rm/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/rm/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/rm/EditableGrid':function(){
define('Sage/UI/nls/rm/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/rm/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/rm/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/rm/SpeedSearch':function(){
define('Sage/UI/nls/rm/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/rm/SLXPreviewGrid':function(){
define('Sage/UI/nls/rm/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/rm/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/rm/UnconfirmedPane',{});
},
'Sage/Utility/nls/rm/Utility':function(){
define('Sage/Utility/nls/rm/Utility',{});
},
'Sage/QuickForms/Design/nls/rm/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/ControlDesigner',{});
},
'Sage/UI/Controls/nls/rm/Address':function(){
define('Sage/UI/Controls/nls/rm/Address',{});
},
'Sage/MainView/ActivityMgr/nls/rm/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/rm/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/rm/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/OwnerControlDesigner',{});
},
'Sage/UI/nls/rm/UserType':function(){
define('Sage/UI/nls/rm/UserType',{});
},
'Sage/QuickForms/Design/nls/rm/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/rm/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/rm/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/rm/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/rm/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/rm/ActivityList':function(){
define('Sage/UI/nls/rm/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/rm/CalendarUsersListPane':function(){
define('Sage/UI/nls/rm/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/rm/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/rm/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/rm/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/rm/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/rm/Attachment':function(){
define('Sage/Utility/File/nls/rm/Attachment',{});
},
'Sage/QuickForms/Design/nls/rm/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/rm/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/rm/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/rm/Helper':function(){
define('Sage/MailMerge/nls/rm/Helper',{});
},
'Sage/UI/Dashboard/nls/rm/Dashboard':function(){
define('Sage/UI/Dashboard/nls/rm/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/rm/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/rm/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/rm/PickList':function(){
define('Sage/UI/Controls/nls/rm/PickList',{});
},
'Sage/Utility/nls/rm/Email':function(){
define('Sage/Utility/nls/rm/Email',{});
},
'Sage/TaskPane/nls/rm/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/rm/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/rm/TimeZoneItem':function(){
define('Sage/UI/nls/rm/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/rm/SlxEdit':function(){
define('Sage/UI/Columns/nls/rm/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/rm/LogOffButton':function(){
define('Sage/UI/Controls/nls/rm/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/rm/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/rm/EditEventEditor',{});
},
'Sage/MailMerge/nls/rm/Loader':function(){
define('Sage/MailMerge/nls/rm/Loader',{});
},
'Sage/UI/Controls/nls/rm/DateTimePicker':function(){
define('Sage/UI/Controls/nls/rm/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/rm/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/rm/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/rm/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/rm/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/rm/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/rm/Lookup':function(){
define('Sage/UI/Controls/nls/rm/Lookup',{});
},
'Sage/Utility/File/nls/rm/DescriptionsForm':function(){
define('Sage/Utility/File/nls/rm/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/rm/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/rm/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/rm/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/rm/CommonTasksTasklet',{});
},
'Sage/Utility/nls/rm/Dashboard':function(){
define('Sage/Utility/nls/rm/Dashboard',{});
}}});
define("Sage/nls/Sage_rm", [], 1);
