require({cache:{
'Sage/Utility/File/nls/no/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/no/FallbackFilePicker',{});
},
'Sage/UI/nls/no/Boolean':function(){
define('Sage/UI/nls/no/Boolean',{});
},
'Sage/UI/Controls/nls/no/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/no/CopyToClipboard',{});
},
'Sage/Services/nls/no/ActivityService':function(){
define('Sage/Services/nls/no/ActivityService',{});
},
'Sage/Utility/nls/no/Activity':function(){
define('Sage/Utility/nls/no/Activity',{});
},
'Sage/UI/nls/no/TimelessActivitiesPane':function(){
define('Sage/UI/nls/no/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/no/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/no/ActivityEditor',{});
},
'Sage/MainView/nls/no/ActivityManager':function(){
define('Sage/MainView/nls/no/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/no/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/no/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/no/Service':function(){
define('Sage/Reporting/nls/no/Service',{});
},
'Sage/Utility/File/nls/no/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/no/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/no/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/no/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/no/AlarmPane':function(){
define('Sage/UI/Alarms/nls/no/AlarmPane',{});
},
'Sage/TaskPane/nls/no/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/no/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/no/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/no/DashboardWidget',{});
},
'Sage/UI/Filters/nls/no/FilterPanel':function(){
define('Sage/UI/Filters/nls/no/FilterPanel',{});
},
'Sage/TaskPane/nls/no/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/no/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/no/OwnerType':function(){
define('Sage/UI/nls/no/OwnerType',{});
},
'Sage/TaskPane/nls/no/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/no/LeadTasksTasklet',{});
},
'Sage/UI/nls/no/SDataLookup':function(){
define('Sage/UI/nls/no/SDataLookup',{});
},
'Sage/TaskPane/nls/no/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/no/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/no/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/no/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/no/LibraryDocument':function(){
define('Sage/Utility/File/nls/no/LibraryDocument',{});
},
'Sage/UI/nls/no/ConditionManager':function(){
define('Sage/UI/nls/no/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/no/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/no/WidgetDefinition',{});
},
'Sage/UI/nls/no/SearchConditionWidget':function(){
define('Sage/UI/nls/no/SearchConditionWidget',{});
},
'Sage/UI/nls/no/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/no/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/no/Name':function(){
define('Sage/UI/Controls/nls/no/Name',{});
},
'Sage/MainView/Lead/nls/no/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/no/UpdateLeads',{});
},
'Sage/UI/nls/no/ListPanel':function(){
define('Sage/UI/nls/no/ListPanel',{});
},
'Sage/UI/Filters/nls/no/EditFilters':function(){
define('Sage/UI/Filters/nls/no/EditFilters',{});
},
'Sage/UI/Controls/nls/no/DurationSelect':function(){
define('Sage/UI/Controls/nls/no/DurationSelect',{});
},
'Sage/UI/Alarms/nls/no/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/no/AlarmCountDown',{});
},
'Sage/UI/nls/no/AttachmentList':function(){
define('Sage/UI/nls/no/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/no/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/no/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/no/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/no/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/no/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/no/DashboardTabController',{});
},
'Sage/Groups/nls/no/GroupNavigator':function(){
define('Sage/Groups/nls/no/GroupNavigator',{});
},
'Sage/Utility/File/nls/no/AddURLAttachment':function(){
define('Sage/Utility/File/nls/no/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/no/EditFilterItems':function(){
define('Sage/UI/Filters/nls/no/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/no/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/no/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/no/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/no/EventListPanelConfig',{});
},
'Sage/UI/nls/no/ActivityScheduler':function(){
define('Sage/UI/nls/no/ActivityScheduler',{});
},
'Sage/MainView/nls/no/SecurityManager':function(){
define('Sage/MainView/nls/no/SecurityManager',{});
},
'Sage/TaskPane/nls/no/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/no/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/no/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/no/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/no/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/no/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/no/HelpMenu':function(){
define('Sage/UI/Controls/nls/no/HelpMenu',{});
},
'Sage/TaskPane/nls/no/UserTasklet':function(){
define('Sage/TaskPane/nls/no/UserTasklet',{});
},
'Sage/UI/Alarms/nls/no/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/no/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/no/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/no/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/no/MenuHelper':function(){
define('Sage/MailMerge/nls/no/MenuHelper',{});
},
'Sage/UI/nls/no/SearchMenuItem':function(){
define('Sage/UI/nls/no/SearchMenuItem',{});
},
'Sage/UI/nls/no/NotesHistoryList':function(){
define('Sage/UI/nls/no/NotesHistoryList',{});
},
'Sage/Utility/File/nls/no/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/no/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/no/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/no/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/no/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/no/HistoryEditor',{});
},
'Sage/Groups/nls/no/GroupManager':function(){
define('Sage/Groups/nls/no/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/no/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/no/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/no/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/no/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/no/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/no/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/no/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/no/AccountingTasksTasklet',{});
},
'Sage/UI/nls/no/EditableGrid':function(){
define('Sage/UI/nls/no/EditableGrid',{});
},
'Sage/UI/nls/no/SpeedSearch':function(){
define('Sage/UI/nls/no/SpeedSearch',{});
},
'Sage/UI/nls/no/SLXPreviewGrid':function(){
define('Sage/UI/nls/no/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/no/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/no/UnconfirmedPane',{});
},
'Sage/Utility/nls/no/Utility':function(){
define('Sage/Utility/nls/no/Utility',{});
},
'Sage/UI/Controls/nls/no/Address':function(){
define('Sage/UI/Controls/nls/no/Address',{});
},
'Sage/MainView/ActivityMgr/nls/no/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/no/BaseListPanelConfig',{});
},
'Sage/UI/nls/no/UserType':function(){
define('Sage/UI/nls/no/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/no/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/no/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/no/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/no/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/no/ActivityList':function(){
define('Sage/UI/nls/no/ActivityList',{});
},
'Sage/UI/nls/no/CalendarUsersListPane':function(){
define('Sage/UI/nls/no/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/no/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/no/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/no/Attachment':function(){
define('Sage/Utility/File/nls/no/Attachment',{});
},
'Sage/MailMerge/nls/no/Helper':function(){
define('Sage/MailMerge/nls/no/Helper',{});
},
'Sage/UI/Dashboard/nls/no/Dashboard':function(){
define('Sage/UI/Dashboard/nls/no/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/no/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/no/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/no/PickList':function(){
define('Sage/UI/Controls/nls/no/PickList',{});
},
'Sage/Utility/nls/no/Email':function(){
define('Sage/Utility/nls/no/Email',{});
},
'Sage/UI/nls/no/TimeZoneItem':function(){
define('Sage/UI/nls/no/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/no/SlxEdit':function(){
define('Sage/UI/Columns/nls/no/SlxEdit',{});
},
'Sage/UI/Controls/nls/no/LogOffButton':function(){
define('Sage/UI/Controls/nls/no/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/no/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/no/EditEventEditor',{});
},
'Sage/MailMerge/nls/no/Loader':function(){
define('Sage/MailMerge/nls/no/Loader',{});
},
'Sage/UI/Controls/nls/no/DateTimePicker':function(){
define('Sage/UI/Controls/nls/no/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/no/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/no/AlarmPopup',{});
},
'Sage/UI/Controls/nls/no/Lookup':function(){
define('Sage/UI/Controls/nls/no/Lookup',{});
},
'Sage/Utility/File/nls/no/DescriptionsForm':function(){
define('Sage/Utility/File/nls/no/DescriptionsForm',{});
},
'Sage/TaskPane/nls/no/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/no/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_no", [], 1);
