require({cache:{
'Sage/Utility/File/nls/tn/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/tn/FallbackFilePicker',{});
},
'Sage/UI/nls/tn/Boolean':function(){
define('Sage/UI/nls/tn/Boolean',{});
},
'Sage/Services/nls/tn/ActivityService':function(){
define('Sage/Services/nls/tn/ActivityService',{});
},
'Sage/UI/Controls/nls/tn/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/tn/CopyToClipboard',{});
},
'Sage/Utility/nls/tn/Activity':function(){
define('Sage/Utility/nls/tn/Activity',{});
},
'Sage/QuickForms/Design/nls/tn/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/tn/DesignPanel',{});
},
'Sage/UI/nls/tn/TimelessActivitiesPane':function(){
define('Sage/UI/nls/tn/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/tn/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tn/ActivityEditor',{});
},
'Sage/MainView/nls/tn/ActivityManager':function(){
define('Sage/MainView/nls/tn/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/tn/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/_PropertyEditor',{});
},
'Sage/Services/nls/tn/ActivityActionProcessor':function(){
define('Sage/Services/nls/tn/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/tn/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tn/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/tn/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/tn/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/tn/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/tn/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/tn/AlarmPane':function(){
define('Sage/UI/Alarms/nls/tn/AlarmPane',{});
},
'Sage/TaskPane/nls/tn/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/tn/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/tn/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/tn/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/tn/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/tn/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/tn/FilterPanel':function(){
define('Sage/UI/Filters/nls/tn/FilterPanel',{});
},
'Sage/TaskPane/nls/tn/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/tn/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/tn/OwnerType':function(){
define('Sage/UI/nls/tn/OwnerType',{});
},
'Sage/TaskPane/nls/tn/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/tn/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/tn/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/tn/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/tn/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/tn/InvoiceRTDV',{});
},
'Sage/UI/nls/tn/SDataLookup':function(){
define('Sage/UI/nls/tn/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/tn/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/RowDesigner',{});
},
'Sage/TaskPane/nls/tn/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/tn/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/tn/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/tn/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/tn/LibraryDocument':function(){
define('Sage/Utility/File/nls/tn/LibraryDocument',{});
},
'Sage/UI/nls/tn/ConditionManager':function(){
define('Sage/UI/nls/tn/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/tn/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/tn/WidgetDefinition',{});
},
'Sage/UI/nls/tn/SearchConditionWidget':function(){
define('Sage/UI/nls/tn/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/tn/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/tn/DataSourcePanel',{});
},
'Sage/UI/nls/tn/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/tn/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/tn/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/tn/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/tn/Name':function(){
define('Sage/UI/Controls/nls/tn/Name',{});
},
'Sage/QuickForms/Design/nls/tn/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/tn/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/tn/UpdateLeads',{});
},
'Sage/UI/nls/tn/ListPanel':function(){
define('Sage/UI/nls/tn/ListPanel',{});
},
'Sage/UI/Filters/nls/tn/EditFilters':function(){
define('Sage/UI/Filters/nls/tn/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/tn/DurationSelect':function(){
define('Sage/UI/Controls/nls/tn/DurationSelect',{});
},
'Sage/UI/Alarms/nls/tn/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/tn/AlarmCountDown',{});
},
'Sage/UI/nls/tn/AttachmentList':function(){
define('Sage/UI/nls/tn/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/tn/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tn/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tn/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/tn/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/tn/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/tn/Dialogs':function(){
define('Sage/UI/nls/tn/Dialogs',{});
},
'Sage/TaskPane/nls/tn/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/tn/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/tn/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/tn/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/tn/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/tn/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/tn/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/UserControlDesigner',{});
},
'Sage/Groups/nls/tn/GroupNavigator':function(){
define('Sage/Groups/nls/tn/GroupNavigator',{});
},
'Sage/Utility/File/nls/tn/AddURLAttachment':function(){
define('Sage/Utility/File/nls/tn/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/tn/EditFilterItems':function(){
define('Sage/UI/Filters/nls/tn/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/tn/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/tn/DesignSurface',{});
},
'Sage/Utility/File/nls/tn/DragDropWatcher':function(){
define('Sage/Utility/File/nls/tn/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/tn/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tn/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/tn/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tn/EventListPanelConfig',{});
},
'Sage/UI/nls/tn/ActivityScheduler':function(){
define('Sage/UI/nls/tn/ActivityScheduler',{});
},
'Sage/MainView/nls/tn/SecurityManager':function(){
define('Sage/MainView/nls/tn/SecurityManager',{});
},
'Sage/TaskPane/nls/tn/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/tn/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/tn/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/tn/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/tn/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/tn/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/tn/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/tn/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/tn/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/tn/HelpMenu':function(){
define('Sage/UI/Controls/nls/tn/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/tn/UserTasklet':function(){
define('Sage/TaskPane/nls/tn/UserTasklet',{});
},
'Sage/UI/Alarms/nls/tn/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/tn/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/tn/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/tn/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/tn/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/tn/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/tn/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/ColumnDesigner',{});
},
'Sage/UI/nls/tn/SearchMenuItem':function(){
define('Sage/UI/nls/tn/SearchMenuItem',{});
},
'Sage/UI/nls/tn/NotesHistoryList':function(){
define('Sage/UI/nls/tn/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/tn/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/tn/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/tn/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/tn/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/tn/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tn/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/tn/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tn/HistoryEditor',{});
},
'Sage/Groups/nls/tn/GroupManager':function(){
define('Sage/Groups/nls/tn/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/tn/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tn/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/tn/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tn/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tn/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/tn/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/tn/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/tn/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/tn/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/tn/EditableGrid':function(){
define('Sage/UI/nls/tn/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/tn/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/tn/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/tn/SpeedSearch':function(){
define('Sage/UI/nls/tn/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/tn/SLXPreviewGrid':function(){
define('Sage/UI/nls/tn/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/tn/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/tn/UnconfirmedPane',{});
},
'Sage/Utility/nls/tn/Utility':function(){
define('Sage/Utility/nls/tn/Utility',{});
},
'Sage/QuickForms/Design/nls/tn/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/ControlDesigner',{});
},
'Sage/UI/Controls/nls/tn/Address':function(){
define('Sage/UI/Controls/nls/tn/Address',{});
},
'Sage/MainView/ActivityMgr/nls/tn/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tn/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/tn/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/OwnerControlDesigner',{});
},
'Sage/UI/nls/tn/UserType':function(){
define('Sage/UI/nls/tn/UserType',{});
},
'Sage/QuickForms/Design/nls/tn/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/tn/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/tn/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/tn/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/tn/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/tn/ActivityList':function(){
define('Sage/UI/nls/tn/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/tn/CalendarUsersListPane':function(){
define('Sage/UI/nls/tn/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/tn/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/tn/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/tn/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/tn/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/tn/Attachment':function(){
define('Sage/Utility/File/nls/tn/Attachment',{});
},
'Sage/QuickForms/Design/nls/tn/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tn/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/tn/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/tn/Helper':function(){
define('Sage/MailMerge/nls/tn/Helper',{});
},
'Sage/UI/Dashboard/nls/tn/Dashboard':function(){
define('Sage/UI/Dashboard/nls/tn/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/tn/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/tn/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/tn/PickList':function(){
define('Sage/UI/Controls/nls/tn/PickList',{});
},
'Sage/Utility/nls/tn/Email':function(){
define('Sage/Utility/nls/tn/Email',{});
},
'Sage/TaskPane/nls/tn/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/tn/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/tn/TimeZoneItem':function(){
define('Sage/UI/nls/tn/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/tn/SlxEdit':function(){
define('Sage/UI/Columns/nls/tn/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/tn/LogOffButton':function(){
define('Sage/UI/Controls/nls/tn/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/tn/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/tn/EditEventEditor',{});
},
'Sage/MailMerge/nls/tn/Loader':function(){
define('Sage/MailMerge/nls/tn/Loader',{});
},
'Sage/UI/Controls/nls/tn/DateTimePicker':function(){
define('Sage/UI/Controls/nls/tn/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/tn/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/tn/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/tn/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/tn/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/tn/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/tn/Lookup':function(){
define('Sage/UI/Controls/nls/tn/Lookup',{});
},
'Sage/Utility/File/nls/tn/DescriptionsForm':function(){
define('Sage/Utility/File/nls/tn/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/tn/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/tn/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/tn/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/tn/CommonTasksTasklet',{});
},
'Sage/Utility/nls/tn/Dashboard':function(){
define('Sage/Utility/nls/tn/Dashboard',{});
}}});
define("Sage/nls/Sage_tn", [], 1);
