require({cache:{
'Sage/Utility/File/nls/ca/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ca/FallbackFilePicker',{});
},
'Sage/UI/nls/ca/Boolean':function(){
define('Sage/UI/nls/ca/Boolean',{});
},
'Sage/Services/nls/ca/ActivityService':function(){
define('Sage/Services/nls/ca/ActivityService',{});
},
'Sage/UI/Controls/nls/ca/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ca/CopyToClipboard',{});
},
'Sage/Utility/nls/ca/Activity':function(){
define('Sage/Utility/nls/ca/Activity',{});
},
'Sage/QuickForms/Design/nls/ca/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/ca/DesignPanel',{});
},
'Sage/UI/nls/ca/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ca/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ca/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ca/ActivityEditor',{});
},
'Sage/MainView/nls/ca/ActivityManager':function(){
define('Sage/MainView/nls/ca/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/ca/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/_PropertyEditor',{});
},
'Sage/Services/nls/ca/ActivityActionProcessor':function(){
define('Sage/Services/nls/ca/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ca/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ca/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/ca/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ca/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ca/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ca/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ca/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ca/AlarmPane',{});
},
'Sage/TaskPane/nls/ca/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ca/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ca/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ca/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ca/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ca/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/ca/FilterPanel':function(){
define('Sage/UI/Filters/nls/ca/FilterPanel',{});
},
'Sage/TaskPane/nls/ca/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ca/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/ca/OwnerType':function(){
define('Sage/UI/nls/ca/OwnerType',{});
},
'Sage/TaskPane/nls/ca/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ca/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/ca/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/ca/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ca/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ca/InvoiceRTDV',{});
},
'Sage/UI/nls/ca/SDataLookup':function(){
define('Sage/UI/nls/ca/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/ca/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/RowDesigner',{});
},
'Sage/TaskPane/nls/ca/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ca/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ca/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ca/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ca/LibraryDocument':function(){
define('Sage/Utility/File/nls/ca/LibraryDocument',{});
},
'Sage/UI/nls/ca/ConditionManager':function(){
define('Sage/UI/nls/ca/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ca/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ca/WidgetDefinition',{});
},
'Sage/UI/nls/ca/SearchConditionWidget':function(){
define('Sage/UI/nls/ca/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/ca/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/ca/DataSourcePanel',{});
},
'Sage/UI/nls/ca/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ca/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/ca/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/ca/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/ca/Name':function(){
define('Sage/UI/Controls/nls/ca/Name',{});
},
'Sage/QuickForms/Design/nls/ca/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/ca/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ca/UpdateLeads',{});
},
'Sage/UI/nls/ca/ListPanel':function(){
define('Sage/UI/nls/ca/ListPanel',{});
},
'Sage/UI/Filters/nls/ca/EditFilters':function(){
define('Sage/UI/Filters/nls/ca/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/ca/DurationSelect':function(){
define('Sage/UI/Controls/nls/ca/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ca/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ca/AlarmCountDown',{});
},
'Sage/UI/nls/ca/AttachmentList':function(){
define('Sage/UI/nls/ca/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/ca/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ca/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ca/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/ca/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ca/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/ca/Dialogs':function(){
define('Sage/UI/nls/ca/Dialogs',{});
},
'Sage/TaskPane/nls/ca/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ca/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ca/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ca/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/ca/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/ca/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/ca/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/UserControlDesigner',{});
},
'Sage/Groups/nls/ca/GroupNavigator':function(){
define('Sage/Groups/nls/ca/GroupNavigator',{});
},
'Sage/Utility/File/nls/ca/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ca/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ca/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ca/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/ca/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/ca/DesignSurface',{});
},
'Sage/Utility/File/nls/ca/DragDropWatcher':function(){
define('Sage/Utility/File/nls/ca/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/ca/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ca/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ca/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ca/EventListPanelConfig',{});
},
'Sage/UI/nls/ca/ActivityScheduler':function(){
define('Sage/UI/nls/ca/ActivityScheduler',{});
},
'Sage/MainView/nls/ca/SecurityManager':function(){
define('Sage/MainView/nls/ca/SecurityManager',{});
},
'Sage/TaskPane/nls/ca/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ca/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/ca/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/ca/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/ca/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ca/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/ca/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ca/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/ca/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/ca/HelpMenu':function(){
define('Sage/UI/Controls/nls/ca/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/ca/UserTasklet':function(){
define('Sage/TaskPane/nls/ca/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ca/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ca/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ca/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ca/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/ca/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/ca/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/ca/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/ColumnDesigner',{});
},
'Sage/UI/nls/ca/SearchMenuItem':function(){
define('Sage/UI/nls/ca/SearchMenuItem',{});
},
'Sage/UI/nls/ca/NotesHistoryList':function(){
define('Sage/UI/nls/ca/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/ca/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/ca/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ca/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/ca/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ca/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ca/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ca/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ca/HistoryEditor',{});
},
'Sage/Groups/nls/ca/GroupManager':function(){
define('Sage/Groups/nls/ca/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ca/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ca/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/ca/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ca/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ca/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/ca/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ca/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ca/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ca/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/ca/EditableGrid':function(){
define('Sage/UI/nls/ca/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/ca/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/ca/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ca/SpeedSearch':function(){
define('Sage/UI/nls/ca/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ca/SLXPreviewGrid':function(){
define('Sage/UI/nls/ca/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ca/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ca/UnconfirmedPane',{});
},
'Sage/Utility/nls/ca/Utility':function(){
define('Sage/Utility/nls/ca/Utility',{});
},
'Sage/QuickForms/Design/nls/ca/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/ControlDesigner',{});
},
'Sage/UI/Controls/nls/ca/Address':function(){
define('Sage/UI/Controls/nls/ca/Address',{});
},
'Sage/MainView/ActivityMgr/nls/ca/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ca/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/ca/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/OwnerControlDesigner',{});
},
'Sage/UI/nls/ca/UserType':function(){
define('Sage/UI/nls/ca/UserType',{});
},
'Sage/QuickForms/Design/nls/ca/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/ca/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ca/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/ca/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ca/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ca/ActivityList':function(){
define('Sage/UI/nls/ca/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/ca/CalendarUsersListPane':function(){
define('Sage/UI/nls/ca/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/ca/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/ca/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ca/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ca/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ca/Attachment':function(){
define('Sage/Utility/File/nls/ca/Attachment',{});
},
'Sage/QuickForms/Design/nls/ca/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ca/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/ca/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/ca/Helper':function(){
define('Sage/MailMerge/nls/ca/Helper',{});
},
'Sage/UI/Dashboard/nls/ca/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ca/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ca/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ca/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ca/PickList':function(){
define('Sage/UI/Controls/nls/ca/PickList',{});
},
'Sage/Utility/nls/ca/Email':function(){
define('Sage/Utility/nls/ca/Email',{});
},
'Sage/TaskPane/nls/ca/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/ca/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/ca/TimeZoneItem':function(){
define('Sage/UI/nls/ca/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ca/SlxEdit':function(){
define('Sage/UI/Columns/nls/ca/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/ca/LogOffButton':function(){
define('Sage/UI/Controls/nls/ca/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ca/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ca/EditEventEditor',{});
},
'Sage/MailMerge/nls/ca/Loader':function(){
define('Sage/MailMerge/nls/ca/Loader',{});
},
'Sage/UI/Controls/nls/ca/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ca/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/ca/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ca/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/ca/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/ca/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/ca/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/ca/Lookup':function(){
define('Sage/UI/Controls/nls/ca/Lookup',{});
},
'Sage/Utility/File/nls/ca/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ca/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/ca/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/ca/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/ca/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ca/CommonTasksTasklet',{});
},
'Sage/Utility/nls/ca/Dashboard':function(){
define('Sage/Utility/nls/ca/Dashboard',{});
}}});
define("Sage/nls/Sage_ca", [], 1);
