require({cache:{
'Sage/Utility/File/nls/sq/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/sq/FallbackFilePicker',{});
},
'Sage/UI/nls/sq/Boolean':function(){
define('Sage/UI/nls/sq/Boolean',{});
},
'Sage/Services/nls/sq/ActivityService':function(){
define('Sage/Services/nls/sq/ActivityService',{});
},
'Sage/UI/Controls/nls/sq/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/sq/CopyToClipboard',{});
},
'Sage/Utility/nls/sq/Activity':function(){
define('Sage/Utility/nls/sq/Activity',{});
},
'Sage/QuickForms/Design/nls/sq/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/sq/DesignPanel',{});
},
'Sage/UI/nls/sq/TimelessActivitiesPane':function(){
define('Sage/UI/nls/sq/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/sq/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sq/ActivityEditor',{});
},
'Sage/MainView/nls/sq/ActivityManager':function(){
define('Sage/MainView/nls/sq/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/sq/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/_PropertyEditor',{});
},
'Sage/Services/nls/sq/ActivityActionProcessor':function(){
define('Sage/Services/nls/sq/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sq/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sq/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/sq/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/sq/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/sq/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/sq/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/sq/AlarmPane':function(){
define('Sage/UI/Alarms/nls/sq/AlarmPane',{});
},
'Sage/TaskPane/nls/sq/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/sq/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/sq/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/sq/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sq/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sq/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/sq/FilterPanel':function(){
define('Sage/UI/Filters/nls/sq/FilterPanel',{});
},
'Sage/TaskPane/nls/sq/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/sq/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/sq/OwnerType':function(){
define('Sage/UI/nls/sq/OwnerType',{});
},
'Sage/TaskPane/nls/sq/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/sq/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/sq/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/sq/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sq/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sq/InvoiceRTDV',{});
},
'Sage/UI/nls/sq/SDataLookup':function(){
define('Sage/UI/nls/sq/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/sq/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/RowDesigner',{});
},
'Sage/TaskPane/nls/sq/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/sq/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/sq/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/sq/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/sq/LibraryDocument':function(){
define('Sage/Utility/File/nls/sq/LibraryDocument',{});
},
'Sage/UI/nls/sq/ConditionManager':function(){
define('Sage/UI/nls/sq/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/sq/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/sq/WidgetDefinition',{});
},
'Sage/UI/nls/sq/SearchConditionWidget':function(){
define('Sage/UI/nls/sq/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/sq/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/sq/DataSourcePanel',{});
},
'Sage/UI/nls/sq/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/sq/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/sq/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/sq/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/sq/Name':function(){
define('Sage/UI/Controls/nls/sq/Name',{});
},
'Sage/QuickForms/Design/nls/sq/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/sq/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/sq/UpdateLeads',{});
},
'Sage/UI/nls/sq/ListPanel':function(){
define('Sage/UI/nls/sq/ListPanel',{});
},
'Sage/UI/Filters/nls/sq/EditFilters':function(){
define('Sage/UI/Filters/nls/sq/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/sq/DurationSelect':function(){
define('Sage/UI/Controls/nls/sq/DurationSelect',{});
},
'Sage/UI/Alarms/nls/sq/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/sq/AlarmCountDown',{});
},
'Sage/UI/nls/sq/AttachmentList':function(){
define('Sage/UI/nls/sq/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/sq/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sq/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sq/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/sq/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/sq/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/sq/Dialogs':function(){
define('Sage/UI/nls/sq/Dialogs',{});
},
'Sage/TaskPane/nls/sq/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/sq/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/sq/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/sq/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/sq/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/sq/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/sq/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/UserControlDesigner',{});
},
'Sage/Groups/nls/sq/GroupNavigator':function(){
define('Sage/Groups/nls/sq/GroupNavigator',{});
},
'Sage/Utility/File/nls/sq/AddURLAttachment':function(){
define('Sage/Utility/File/nls/sq/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/sq/EditFilterItems':function(){
define('Sage/UI/Filters/nls/sq/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/sq/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/sq/DesignSurface',{});
},
'Sage/Utility/File/nls/sq/DragDropWatcher':function(){
define('Sage/Utility/File/nls/sq/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/sq/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sq/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sq/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sq/EventListPanelConfig',{});
},
'Sage/UI/nls/sq/ActivityScheduler':function(){
define('Sage/UI/nls/sq/ActivityScheduler',{});
},
'Sage/MainView/nls/sq/SecurityManager':function(){
define('Sage/MainView/nls/sq/SecurityManager',{});
},
'Sage/TaskPane/nls/sq/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/sq/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/sq/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/sq/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/sq/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/sq/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/sq/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/sq/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/sq/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/sq/HelpMenu':function(){
define('Sage/UI/Controls/nls/sq/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/sq/UserTasklet':function(){
define('Sage/TaskPane/nls/sq/UserTasklet',{});
},
'Sage/UI/Alarms/nls/sq/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/sq/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/sq/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/sq/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/sq/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/sq/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/sq/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/ColumnDesigner',{});
},
'Sage/UI/nls/sq/SearchMenuItem':function(){
define('Sage/UI/nls/sq/SearchMenuItem',{});
},
'Sage/UI/nls/sq/NotesHistoryList':function(){
define('Sage/UI/nls/sq/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/sq/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/sq/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/sq/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/sq/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sq/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sq/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sq/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sq/HistoryEditor',{});
},
'Sage/Groups/nls/sq/GroupManager':function(){
define('Sage/Groups/nls/sq/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sq/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sq/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/sq/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sq/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sq/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/sq/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/sq/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sq/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/sq/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/sq/EditableGrid':function(){
define('Sage/UI/nls/sq/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/sq/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/sq/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sq/SpeedSearch':function(){
define('Sage/UI/nls/sq/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sq/SLXPreviewGrid':function(){
define('Sage/UI/nls/sq/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/sq/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/sq/UnconfirmedPane',{});
},
'Sage/Utility/nls/sq/Utility':function(){
define('Sage/Utility/nls/sq/Utility',{});
},
'Sage/QuickForms/Design/nls/sq/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/ControlDesigner',{});
},
'Sage/UI/Controls/nls/sq/Address':function(){
define('Sage/UI/Controls/nls/sq/Address',{});
},
'Sage/MainView/ActivityMgr/nls/sq/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sq/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/sq/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/OwnerControlDesigner',{});
},
'Sage/UI/nls/sq/UserType':function(){
define('Sage/UI/nls/sq/UserType',{});
},
'Sage/QuickForms/Design/nls/sq/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/sq/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/sq/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/sq/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/sq/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sq/ActivityList':function(){
define('Sage/UI/nls/sq/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/sq/CalendarUsersListPane':function(){
define('Sage/UI/nls/sq/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/sq/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/sq/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sq/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/sq/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/sq/Attachment':function(){
define('Sage/Utility/File/nls/sq/Attachment',{});
},
'Sage/QuickForms/Design/nls/sq/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sq/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/sq/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/sq/Helper':function(){
define('Sage/MailMerge/nls/sq/Helper',{});
},
'Sage/UI/Dashboard/nls/sq/Dashboard':function(){
define('Sage/UI/Dashboard/nls/sq/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/sq/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sq/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/sq/PickList':function(){
define('Sage/UI/Controls/nls/sq/PickList',{});
},
'Sage/Utility/nls/sq/Email':function(){
define('Sage/Utility/nls/sq/Email',{});
},
'Sage/TaskPane/nls/sq/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/sq/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/sq/TimeZoneItem':function(){
define('Sage/UI/nls/sq/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/sq/SlxEdit':function(){
define('Sage/UI/Columns/nls/sq/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/sq/LogOffButton':function(){
define('Sage/UI/Controls/nls/sq/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/sq/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sq/EditEventEditor',{});
},
'Sage/MailMerge/nls/sq/Loader':function(){
define('Sage/MailMerge/nls/sq/Loader',{});
},
'Sage/UI/Controls/nls/sq/DateTimePicker':function(){
define('Sage/UI/Controls/nls/sq/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/sq/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/sq/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/sq/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/sq/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/sq/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/sq/Lookup':function(){
define('Sage/UI/Controls/nls/sq/Lookup',{});
},
'Sage/Utility/File/nls/sq/DescriptionsForm':function(){
define('Sage/Utility/File/nls/sq/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/sq/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/sq/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/sq/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/sq/CommonTasksTasklet',{});
},
'Sage/Utility/nls/sq/Dashboard':function(){
define('Sage/Utility/nls/sq/Dashboard',{});
}}});
define("Sage/nls/Sage_sq", [], 1);
