require({cache:{
'Sage/Utility/File/nls/pl/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/pl/FallbackFilePicker',{});
},
'Sage/UI/nls/pl/Boolean':function(){
define('Sage/UI/nls/pl/Boolean',{});
},
'Sage/Services/nls/pl/ActivityService':function(){
define('Sage/Services/nls/pl/ActivityService',{});
},
'Sage/UI/Controls/nls/pl/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/pl/CopyToClipboard',{});
},
'Sage/Utility/nls/pl/Activity':function(){
define('Sage/Utility/nls/pl/Activity',{});
},
'Sage/QuickForms/Design/nls/pl/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/pl/DesignPanel',{});
},
'Sage/UI/nls/pl/TimelessActivitiesPane':function(){
define('Sage/UI/nls/pl/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/pl/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pl/ActivityEditor',{});
},
'Sage/MainView/nls/pl/ActivityManager':function(){
define('Sage/MainView/nls/pl/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/pl/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/_PropertyEditor',{});
},
'Sage/Services/nls/pl/ActivityActionProcessor':function(){
define('Sage/Services/nls/pl/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pl/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pl/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/pl/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/pl/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/pl/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/pl/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/pl/AlarmPane':function(){
define('Sage/UI/Alarms/nls/pl/AlarmPane',{});
},
'Sage/TaskPane/nls/pl/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/pl/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/pl/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/pl/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/pl/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pl/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/pl/FilterPanel':function(){
define('Sage/UI/Filters/nls/pl/FilterPanel',{});
},
'Sage/TaskPane/nls/pl/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/pl/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/pl/OwnerType':function(){
define('Sage/UI/nls/pl/OwnerType',{});
},
'Sage/TaskPane/nls/pl/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/pl/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/pl/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/pl/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/pl/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pl/InvoiceRTDV',{});
},
'Sage/UI/nls/pl/SDataLookup':function(){
define('Sage/UI/nls/pl/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/pl/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/RowDesigner',{});
},
'Sage/TaskPane/nls/pl/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/pl/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/pl/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/pl/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/pl/LibraryDocument':function(){
define('Sage/Utility/File/nls/pl/LibraryDocument',{});
},
'Sage/UI/nls/pl/ConditionManager':function(){
define('Sage/UI/nls/pl/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/pl/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/pl/WidgetDefinition',{});
},
'Sage/UI/nls/pl/SearchConditionWidget':function(){
define('Sage/UI/nls/pl/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/pl/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/pl/DataSourcePanel',{});
},
'Sage/UI/nls/pl/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/pl/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/pl/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/pl/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/pl/Name':function(){
define('Sage/UI/Controls/nls/pl/Name',{});
},
'Sage/QuickForms/Design/nls/pl/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/pl/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/pl/UpdateLeads',{});
},
'Sage/UI/nls/pl/ListPanel':function(){
define('Sage/UI/nls/pl/ListPanel',{});
},
'Sage/UI/Filters/nls/pl/EditFilters':function(){
define('Sage/UI/Filters/nls/pl/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/pl/DurationSelect':function(){
define('Sage/UI/Controls/nls/pl/DurationSelect',{});
},
'Sage/UI/Alarms/nls/pl/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/pl/AlarmCountDown',{});
},
'Sage/UI/nls/pl/AttachmentList':function(){
define('Sage/UI/nls/pl/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/pl/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pl/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pl/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/pl/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/pl/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/pl/Dialogs':function(){
define('Sage/UI/nls/pl/Dialogs',{});
},
'Sage/TaskPane/nls/pl/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/pl/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/pl/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/pl/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/pl/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pl/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/pl/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/UserControlDesigner',{});
},
'Sage/Groups/nls/pl/GroupNavigator':function(){
define('Sage/Groups/nls/pl/GroupNavigator',{});
},
'Sage/Utility/File/nls/pl/AddURLAttachment':function(){
define('Sage/Utility/File/nls/pl/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/pl/EditFilterItems':function(){
define('Sage/UI/Filters/nls/pl/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/pl/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/pl/DesignSurface',{});
},
'Sage/Utility/File/nls/pl/DragDropWatcher':function(){
define('Sage/Utility/File/nls/pl/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/pl/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pl/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pl/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pl/EventListPanelConfig',{});
},
'Sage/UI/nls/pl/ActivityScheduler':function(){
define('Sage/UI/nls/pl/ActivityScheduler',{});
},
'Sage/MainView/nls/pl/SecurityManager':function(){
define('Sage/MainView/nls/pl/SecurityManager',{});
},
'Sage/TaskPane/nls/pl/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/pl/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/pl/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/pl/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/pl/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/pl/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/pl/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/pl/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/pl/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/pl/HelpMenu':function(){
define('Sage/UI/Controls/nls/pl/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/pl/UserTasklet':function(){
define('Sage/TaskPane/nls/pl/UserTasklet',{});
},
'Sage/UI/Alarms/nls/pl/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/pl/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/pl/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/pl/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/pl/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/pl/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/pl/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/ColumnDesigner',{});
},
'Sage/UI/nls/pl/SearchMenuItem':function(){
define('Sage/UI/nls/pl/SearchMenuItem',{});
},
'Sage/UI/nls/pl/NotesHistoryList':function(){
define('Sage/UI/nls/pl/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/pl/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/pl/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/pl/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/pl/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/pl/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pl/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pl/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pl/HistoryEditor',{});
},
'Sage/Groups/nls/pl/GroupManager':function(){
define('Sage/Groups/nls/pl/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pl/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pl/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/pl/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pl/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pl/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/pl/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/pl/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/pl/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/pl/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/pl/EditableGrid':function(){
define('Sage/UI/nls/pl/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/pl/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/pl/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/pl/SpeedSearch':function(){
define('Sage/UI/nls/pl/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/pl/SLXPreviewGrid':function(){
define('Sage/UI/nls/pl/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/pl/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/pl/UnconfirmedPane',{});
},
'Sage/Utility/nls/pl/Utility':function(){
define('Sage/Utility/nls/pl/Utility',{});
},
'Sage/QuickForms/Design/nls/pl/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/ControlDesigner',{});
},
'Sage/UI/Controls/nls/pl/Address':function(){
define('Sage/UI/Controls/nls/pl/Address',{});
},
'Sage/MainView/ActivityMgr/nls/pl/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pl/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/pl/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/OwnerControlDesigner',{});
},
'Sage/UI/nls/pl/UserType':function(){
define('Sage/UI/nls/pl/UserType',{});
},
'Sage/QuickForms/Design/nls/pl/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/pl/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/pl/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/pl/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/pl/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/pl/ActivityList':function(){
define('Sage/UI/nls/pl/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/pl/CalendarUsersListPane':function(){
define('Sage/UI/nls/pl/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/pl/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/pl/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pl/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/pl/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/pl/Attachment':function(){
define('Sage/Utility/File/nls/pl/Attachment',{});
},
'Sage/QuickForms/Design/nls/pl/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pl/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/pl/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/pl/Helper':function(){
define('Sage/MailMerge/nls/pl/Helper',{});
},
'Sage/UI/Dashboard/nls/pl/Dashboard':function(){
define('Sage/UI/Dashboard/nls/pl/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/pl/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pl/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/pl/PickList':function(){
define('Sage/UI/Controls/nls/pl/PickList',{});
},
'Sage/Utility/nls/pl/Email':function(){
define('Sage/Utility/nls/pl/Email',{});
},
'Sage/TaskPane/nls/pl/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/pl/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/pl/TimeZoneItem':function(){
define('Sage/UI/nls/pl/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/pl/SlxEdit':function(){
define('Sage/UI/Columns/nls/pl/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/pl/LogOffButton':function(){
define('Sage/UI/Controls/nls/pl/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pl/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pl/EditEventEditor',{});
},
'Sage/MailMerge/nls/pl/Loader':function(){
define('Sage/MailMerge/nls/pl/Loader',{});
},
'Sage/UI/Controls/nls/pl/DateTimePicker':function(){
define('Sage/UI/Controls/nls/pl/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/pl/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/pl/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/pl/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pl/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pl/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/pl/Lookup':function(){
define('Sage/UI/Controls/nls/pl/Lookup',{});
},
'Sage/Utility/File/nls/pl/DescriptionsForm':function(){
define('Sage/Utility/File/nls/pl/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/pl/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pl/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/pl/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/pl/CommonTasksTasklet',{});
},
'Sage/Utility/nls/pl/Dashboard':function(){
define('Sage/Utility/nls/pl/Dashboard',{});
}}});
define("Sage/nls/Sage_pl", [], 1);
