require({cache:{
'Sage/Utility/File/nls/ar/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/ar-ye/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar-ye/FallbackFilePicker',{});
},
'Sage/UI/nls/ar/Boolean':function(){
define('Sage/UI/nls/ar/Boolean',{});
},
'Sage/UI/nls/ar-ye/Boolean':function(){
define('Sage/UI/nls/ar-ye/Boolean',{});
},
'Sage/UI/Controls/nls/ar/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/ar-ye/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar-ye/CopyToClipboard',{});
},
'Sage/Services/nls/ar/ActivityService':function(){
define('Sage/Services/nls/ar/ActivityService',{});
},
'Sage/Services/nls/ar-ye/ActivityService':function(){
define('Sage/Services/nls/ar-ye/ActivityService',{});
},
'Sage/Utility/nls/ar/Activity':function(){
define('Sage/Utility/nls/ar/Activity',{});
},
'Sage/Utility/nls/ar-ye/Activity':function(){
define('Sage/Utility/nls/ar-ye/Activity',{});
},
'Sage/UI/nls/ar/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar/TimelessActivitiesPane',{});
},
'Sage/UI/nls/ar-ye/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar-ye/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ye/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ye/ActivityEditor',{});
},
'Sage/MainView/nls/ar/ActivityManager':function(){
define('Sage/MainView/nls/ar/ActivityManager',{});
},
'Sage/MainView/nls/ar-ye/ActivityManager':function(){
define('Sage/MainView/nls/ar-ye/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ye/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ye/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/ar/Service':function(){
define('Sage/Reporting/nls/ar/Service',{});
},
'Sage/Reporting/nls/ar-ye/Service':function(){
define('Sage/Reporting/nls/ar-ye/Service',{});
},
'Sage/Utility/File/nls/ar/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar-ye/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar-ye/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/ar-ye/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar-ye/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPane',{});
},
'Sage/UI/Alarms/nls/ar-ye/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar-ye/AlarmPane',{});
},
'Sage/TaskPane/nls/ar/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/ar-ye/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar-ye/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/ar-ye/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar-ye/DashboardWidget',{});
},
'Sage/UI/Filters/nls/ar/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar/FilterPanel',{});
},
'Sage/UI/Filters/nls/ar-ye/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar-ye/FilterPanel',{});
},
'Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/ar-ye/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar-ye/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/ar/OwnerType':function(){
define('Sage/UI/nls/ar/OwnerType',{});
},
'Sage/UI/nls/ar-ye/OwnerType':function(){
define('Sage/UI/nls/ar-ye/OwnerType',{});
},
'Sage/TaskPane/nls/ar/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ye/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ye/LeadTasksTasklet',{});
},
'Sage/UI/nls/ar/SDataLookup':function(){
define('Sage/UI/nls/ar/SDataLookup',{});
},
'Sage/UI/nls/ar-ye/SDataLookup':function(){
define('Sage/UI/nls/ar-ye/SDataLookup',{});
},
'Sage/TaskPane/nls/ar/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ye/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ye/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ar/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/ar-ye/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar-ye/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ar/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar/LibraryDocument',{});
},
'Sage/Utility/File/nls/ar-ye/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar-ye/LibraryDocument',{});
},
'Sage/UI/nls/ar/ConditionManager':function(){
define('Sage/UI/nls/ar/ConditionManager',{});
},
'Sage/UI/nls/ar-ye/ConditionManager':function(){
define('Sage/UI/nls/ar-ye/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ar/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/ar-ye/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar-ye/WidgetDefinition',{});
},
'Sage/UI/nls/ar/SearchConditionWidget':function(){
define('Sage/UI/nls/ar/SearchConditionWidget',{});
},
'Sage/UI/nls/ar-ye/SearchConditionWidget':function(){
define('Sage/UI/nls/ar-ye/SearchConditionWidget',{});
},
'Sage/UI/nls/ar/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/ar-ye/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar-ye/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/ar/Name':function(){
define('Sage/UI/Controls/nls/ar/Name',{});
},
'Sage/UI/Controls/nls/ar-ye/Name':function(){
define('Sage/UI/Controls/nls/ar-ye/Name',{});
},
'Sage/MainView/Lead/nls/ar/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/ar-ye/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar-ye/UpdateLeads',{});
},
'Sage/UI/nls/ar/ListPanel':function(){
define('Sage/UI/nls/ar/ListPanel',{});
},
'Sage/UI/nls/ar-ye/ListPanel':function(){
define('Sage/UI/nls/ar-ye/ListPanel',{});
},
'Sage/UI/Filters/nls/ar/EditFilters':function(){
define('Sage/UI/Filters/nls/ar/EditFilters',{});
},
'Sage/UI/Filters/nls/ar-ye/EditFilters':function(){
define('Sage/UI/Filters/nls/ar-ye/EditFilters',{});
},
'Sage/UI/Controls/nls/ar/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar/DurationSelect',{});
},
'Sage/UI/Controls/nls/ar-ye/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar-ye/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ar/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/ar-ye/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar-ye/AlarmCountDown',{});
},
'Sage/UI/nls/ar/AttachmentList':function(){
define('Sage/UI/nls/ar/AttachmentList',{});
},
'Sage/UI/nls/ar-ye/AttachmentList':function(){
define('Sage/UI/nls/ar-ye/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/ar-ye/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar-ye/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/ar/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/ar-ye/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar-ye/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/ar-ye/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar-ye/DashboardTabController',{});
},
'Sage/Groups/nls/ar/GroupNavigator':function(){
define('Sage/Groups/nls/ar/GroupNavigator',{});
},
'Sage/Groups/nls/ar-ye/GroupNavigator':function(){
define('Sage/Groups/nls/ar-ye/GroupNavigator',{});
},
'Sage/Utility/File/nls/ar/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar/AddURLAttachment',{});
},
'Sage/Utility/File/nls/ar-ye/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar-ye/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ar/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar/EditFilterItems',{});
},
'Sage/UI/Filters/nls/ar-ye/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar-ye/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ye/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ye/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ye/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ye/EventListPanelConfig',{});
},
'Sage/UI/nls/ar/ActivityScheduler':function(){
define('Sage/UI/nls/ar/ActivityScheduler',{});
},
'Sage/UI/nls/ar-ye/ActivityScheduler':function(){
define('Sage/UI/nls/ar-ye/ActivityScheduler',{});
},
'Sage/MainView/nls/ar/SecurityManager':function(){
define('Sage/MainView/nls/ar/SecurityManager',{});
},
'Sage/MainView/nls/ar-ye/SecurityManager':function(){
define('Sage/MainView/nls/ar-ye/SecurityManager',{});
},
'Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/ar-ye/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar-ye/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ye/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ye/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/ar/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/ar-ye/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar-ye/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/ar/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar/HelpMenu',{});
},
'Sage/UI/Controls/nls/ar-ye/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar-ye/HelpMenu',{});
},
'Sage/TaskPane/nls/ar/UserTasklet':function(){
define('Sage/TaskPane/nls/ar/UserTasklet',{});
},
'Sage/TaskPane/nls/ar-ye/UserTasklet':function(){
define('Sage/TaskPane/nls/ar-ye/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ar/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/ar-ye/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar-ye/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ar/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/ar-ye/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar-ye/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/ar/MenuHelper':function(){
define('Sage/MailMerge/nls/ar/MenuHelper',{});
},
'Sage/MailMerge/nls/ar-ye/MenuHelper':function(){
define('Sage/MailMerge/nls/ar-ye/MenuHelper',{});
},
'Sage/UI/nls/ar/SearchMenuItem':function(){
define('Sage/UI/nls/ar/SearchMenuItem',{});
},
'Sage/UI/nls/ar-ye/SearchMenuItem':function(){
define('Sage/UI/nls/ar-ye/SearchMenuItem',{});
},
'Sage/UI/nls/ar/NotesHistoryList':function(){
define('Sage/UI/nls/ar/NotesHistoryList',{});
},
'Sage/UI/nls/ar-ye/NotesHistoryList':function(){
define('Sage/UI/nls/ar-ye/NotesHistoryList',{});
},
'Sage/Utility/File/nls/ar/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/ar-ye/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar-ye/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ye/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ye/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ye/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ye/HistoryEditor',{});
},
'Sage/Groups/nls/ar/GroupManager':function(){
define('Sage/Groups/nls/ar/GroupManager',{});
},
'Sage/Groups/nls/ar-ye/GroupManager':function(){
define('Sage/Groups/nls/ar-ye/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/ar/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ye/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ye/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedAlarm',{});
},
'Sage/UI/Alarms/nls/ar-ye/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/ar-ye/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/ar-ye/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar-ye/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/ar/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ye/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ye/AccountingTasksTasklet',{});
},
'Sage/UI/nls/ar/EditableGrid':function(){
define('Sage/UI/nls/ar/EditableGrid',{});
},
'Sage/UI/nls/ar-ye/EditableGrid':function(){
define('Sage/UI/nls/ar-ye/EditableGrid',{});
},
'Sage/UI/nls/ar/SpeedSearch':function(){
define('Sage/UI/nls/ar/SpeedSearch',{});
},
'Sage/UI/nls/ar-ye/SpeedSearch':function(){
define('Sage/UI/nls/ar-ye/SpeedSearch',{});
},
'Sage/UI/nls/ar/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar/SLXPreviewGrid',{});
},
'Sage/UI/nls/ar-ye/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar-ye/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/ar-ye/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar-ye/UnconfirmedPane',{});
},
'Sage/Utility/nls/ar/Utility':function(){
define('Sage/Utility/nls/ar/Utility',{});
},
'Sage/Utility/nls/ar-ye/Utility':function(){
define('Sage/Utility/nls/ar-ye/Utility',{});
},
'Sage/UI/Controls/nls/ar/Address':function(){
define('Sage/UI/Controls/nls/ar/Address',{});
},
'Sage/UI/Controls/nls/ar-ye/Address':function(){
define('Sage/UI/Controls/nls/ar-ye/Address',{});
},
'Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ye/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ye/BaseListPanelConfig',{});
},
'Sage/UI/nls/ar/UserType':function(){
define('Sage/UI/nls/ar/UserType',{});
},
'Sage/UI/nls/ar-ye/UserType':function(){
define('Sage/UI/nls/ar-ye/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ye/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ye/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/ar/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/ar-ye/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar-ye/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/ar/ActivityList':function(){
define('Sage/UI/nls/ar/ActivityList',{});
},
'Sage/UI/nls/ar-ye/ActivityList':function(){
define('Sage/UI/nls/ar-ye/ActivityList',{});
},
'Sage/UI/nls/ar/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar/CalendarUsersListPane',{});
},
'Sage/UI/nls/ar-ye/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar-ye/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ye/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ye/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ar/Attachment':function(){
define('Sage/Utility/File/nls/ar/Attachment',{});
},
'Sage/Utility/File/nls/ar-ye/Attachment':function(){
define('Sage/Utility/File/nls/ar-ye/Attachment',{});
},
'Sage/MailMerge/nls/ar/Helper':function(){
define('Sage/MailMerge/nls/ar/Helper',{});
},
'Sage/MailMerge/nls/ar-ye/Helper':function(){
define('Sage/MailMerge/nls/ar-ye/Helper',{});
},
'Sage/UI/Dashboard/nls/ar/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar/Dashboard',{});
},
'Sage/UI/Dashboard/nls/ar-ye/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar-ye/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ye/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ye/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ar/PickList':function(){
define('Sage/UI/Controls/nls/ar/PickList',{});
},
'Sage/UI/Controls/nls/ar-ye/PickList':function(){
define('Sage/UI/Controls/nls/ar-ye/PickList',{});
},
'Sage/Utility/nls/ar/Email':function(){
define('Sage/Utility/nls/ar/Email',{});
},
'Sage/Utility/nls/ar-ye/Email':function(){
define('Sage/Utility/nls/ar-ye/Email',{});
},
'Sage/UI/nls/ar/TimeZoneItem':function(){
define('Sage/UI/nls/ar/TimeZoneItem',{});
},
'Sage/UI/nls/ar-ye/TimeZoneItem':function(){
define('Sage/UI/nls/ar-ye/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ar/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar/SlxEdit',{});
},
'Sage/UI/Columns/nls/ar-ye/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar-ye/SlxEdit',{});
},
'Sage/UI/Controls/nls/ar/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar/LogOffButton',{});
},
'Sage/UI/Controls/nls/ar-ye/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar-ye/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-ye/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-ye/EditEventEditor',{});
},
'Sage/MailMerge/nls/ar/Loader':function(){
define('Sage/MailMerge/nls/ar/Loader',{});
},
'Sage/MailMerge/nls/ar-ye/Loader':function(){
define('Sage/MailMerge/nls/ar-ye/Loader',{});
},
'Sage/UI/Controls/nls/ar/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar/DateTimePicker',{});
},
'Sage/UI/Controls/nls/ar-ye/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar-ye/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/ar-ye/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar-ye/AlarmPopup',{});
},
'Sage/UI/Controls/nls/ar/Lookup':function(){
define('Sage/UI/Controls/nls/ar/Lookup',{});
},
'Sage/UI/Controls/nls/ar-ye/Lookup':function(){
define('Sage/UI/Controls/nls/ar-ye/Lookup',{});
},
'Sage/Utility/File/nls/ar/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar/DescriptionsForm',{});
},
'Sage/Utility/File/nls/ar-ye/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar-ye/DescriptionsForm',{});
},
'Sage/TaskPane/nls/ar/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-ye/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-ye/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_ar-ye", [], 1);
