require({cache:{
'Sage/Utility/File/nls/mk/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/mk/FallbackFilePicker',{});
},
'Sage/UI/nls/mk/Boolean':function(){
define('Sage/UI/nls/mk/Boolean',{});
},
'Sage/Services/nls/mk/ActivityService':function(){
define('Sage/Services/nls/mk/ActivityService',{});
},
'Sage/UI/Controls/nls/mk/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/mk/CopyToClipboard',{});
},
'Sage/Utility/nls/mk/Activity':function(){
define('Sage/Utility/nls/mk/Activity',{});
},
'Sage/QuickForms/Design/nls/mk/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/mk/DesignPanel',{});
},
'Sage/UI/nls/mk/TimelessActivitiesPane':function(){
define('Sage/UI/nls/mk/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/mk/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mk/ActivityEditor',{});
},
'Sage/MainView/nls/mk/ActivityManager':function(){
define('Sage/MainView/nls/mk/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/mk/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/_PropertyEditor',{});
},
'Sage/Services/nls/mk/ActivityActionProcessor':function(){
define('Sage/Services/nls/mk/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/mk/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mk/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/mk/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/mk/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/mk/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/mk/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/mk/AlarmPane':function(){
define('Sage/UI/Alarms/nls/mk/AlarmPane',{});
},
'Sage/TaskPane/nls/mk/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/mk/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/mk/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/mk/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/mk/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/mk/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/mk/FilterPanel':function(){
define('Sage/UI/Filters/nls/mk/FilterPanel',{});
},
'Sage/TaskPane/nls/mk/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/mk/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/mk/OwnerType':function(){
define('Sage/UI/nls/mk/OwnerType',{});
},
'Sage/TaskPane/nls/mk/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/mk/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/mk/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/mk/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/mk/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/mk/InvoiceRTDV',{});
},
'Sage/UI/nls/mk/SDataLookup':function(){
define('Sage/UI/nls/mk/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/mk/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/RowDesigner',{});
},
'Sage/TaskPane/nls/mk/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/mk/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/mk/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/mk/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/mk/LibraryDocument':function(){
define('Sage/Utility/File/nls/mk/LibraryDocument',{});
},
'Sage/UI/nls/mk/ConditionManager':function(){
define('Sage/UI/nls/mk/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/mk/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/mk/WidgetDefinition',{});
},
'Sage/UI/nls/mk/SearchConditionWidget':function(){
define('Sage/UI/nls/mk/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/mk/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/mk/DataSourcePanel',{});
},
'Sage/UI/nls/mk/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/mk/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/mk/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/mk/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/mk/Name':function(){
define('Sage/UI/Controls/nls/mk/Name',{});
},
'Sage/QuickForms/Design/nls/mk/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/mk/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/mk/UpdateLeads',{});
},
'Sage/UI/nls/mk/ListPanel':function(){
define('Sage/UI/nls/mk/ListPanel',{});
},
'Sage/UI/Filters/nls/mk/EditFilters':function(){
define('Sage/UI/Filters/nls/mk/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/mk/DurationSelect':function(){
define('Sage/UI/Controls/nls/mk/DurationSelect',{});
},
'Sage/UI/Alarms/nls/mk/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/mk/AlarmCountDown',{});
},
'Sage/UI/nls/mk/AttachmentList':function(){
define('Sage/UI/nls/mk/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/mk/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mk/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mk/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/mk/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/mk/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/mk/Dialogs':function(){
define('Sage/UI/nls/mk/Dialogs',{});
},
'Sage/TaskPane/nls/mk/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/mk/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/mk/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/mk/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/mk/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/mk/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/mk/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/UserControlDesigner',{});
},
'Sage/Groups/nls/mk/GroupNavigator':function(){
define('Sage/Groups/nls/mk/GroupNavigator',{});
},
'Sage/Utility/File/nls/mk/AddURLAttachment':function(){
define('Sage/Utility/File/nls/mk/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/mk/EditFilterItems':function(){
define('Sage/UI/Filters/nls/mk/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/mk/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/mk/DesignSurface',{});
},
'Sage/Utility/File/nls/mk/DragDropWatcher':function(){
define('Sage/Utility/File/nls/mk/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/mk/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mk/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/mk/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mk/EventListPanelConfig',{});
},
'Sage/UI/nls/mk/ActivityScheduler':function(){
define('Sage/UI/nls/mk/ActivityScheduler',{});
},
'Sage/MainView/nls/mk/SecurityManager':function(){
define('Sage/MainView/nls/mk/SecurityManager',{});
},
'Sage/TaskPane/nls/mk/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/mk/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/mk/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/mk/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/mk/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/mk/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/mk/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/mk/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/mk/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/mk/HelpMenu':function(){
define('Sage/UI/Controls/nls/mk/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/mk/UserTasklet':function(){
define('Sage/TaskPane/nls/mk/UserTasklet',{});
},
'Sage/UI/Alarms/nls/mk/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/mk/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/mk/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/mk/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/mk/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/mk/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/mk/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/ColumnDesigner',{});
},
'Sage/UI/nls/mk/SearchMenuItem':function(){
define('Sage/UI/nls/mk/SearchMenuItem',{});
},
'Sage/UI/nls/mk/NotesHistoryList':function(){
define('Sage/UI/nls/mk/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/mk/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/mk/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/mk/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/mk/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/mk/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mk/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/mk/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mk/HistoryEditor',{});
},
'Sage/Groups/nls/mk/GroupManager':function(){
define('Sage/Groups/nls/mk/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/mk/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mk/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/mk/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mk/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mk/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/mk/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/mk/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/mk/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/mk/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/mk/EditableGrid':function(){
define('Sage/UI/nls/mk/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/mk/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/mk/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/mk/SpeedSearch':function(){
define('Sage/UI/nls/mk/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/mk/SLXPreviewGrid':function(){
define('Sage/UI/nls/mk/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/mk/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/mk/UnconfirmedPane',{});
},
'Sage/Utility/nls/mk/Utility':function(){
define('Sage/Utility/nls/mk/Utility',{});
},
'Sage/QuickForms/Design/nls/mk/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/ControlDesigner',{});
},
'Sage/UI/Controls/nls/mk/Address':function(){
define('Sage/UI/Controls/nls/mk/Address',{});
},
'Sage/MainView/ActivityMgr/nls/mk/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mk/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/mk/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/OwnerControlDesigner',{});
},
'Sage/UI/nls/mk/UserType':function(){
define('Sage/UI/nls/mk/UserType',{});
},
'Sage/QuickForms/Design/nls/mk/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/mk/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/mk/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/mk/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/mk/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/mk/ActivityList':function(){
define('Sage/UI/nls/mk/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/mk/CalendarUsersListPane':function(){
define('Sage/UI/nls/mk/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/mk/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/mk/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/mk/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/mk/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/mk/Attachment':function(){
define('Sage/Utility/File/nls/mk/Attachment',{});
},
'Sage/QuickForms/Design/nls/mk/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mk/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/mk/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/mk/Helper':function(){
define('Sage/MailMerge/nls/mk/Helper',{});
},
'Sage/UI/Dashboard/nls/mk/Dashboard':function(){
define('Sage/UI/Dashboard/nls/mk/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/mk/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/mk/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/mk/PickList':function(){
define('Sage/UI/Controls/nls/mk/PickList',{});
},
'Sage/Utility/nls/mk/Email':function(){
define('Sage/Utility/nls/mk/Email',{});
},
'Sage/TaskPane/nls/mk/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/mk/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/mk/TimeZoneItem':function(){
define('Sage/UI/nls/mk/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/mk/SlxEdit':function(){
define('Sage/UI/Columns/nls/mk/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/mk/LogOffButton':function(){
define('Sage/UI/Controls/nls/mk/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/mk/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/mk/EditEventEditor',{});
},
'Sage/MailMerge/nls/mk/Loader':function(){
define('Sage/MailMerge/nls/mk/Loader',{});
},
'Sage/UI/Controls/nls/mk/DateTimePicker':function(){
define('Sage/UI/Controls/nls/mk/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/mk/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/mk/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/mk/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/mk/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/mk/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/mk/Lookup':function(){
define('Sage/UI/Controls/nls/mk/Lookup',{});
},
'Sage/Utility/File/nls/mk/DescriptionsForm':function(){
define('Sage/Utility/File/nls/mk/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/mk/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/mk/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/mk/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/mk/CommonTasksTasklet',{});
},
'Sage/Utility/nls/mk/Dashboard':function(){
define('Sage/Utility/nls/mk/Dashboard',{});
}}});
define("Sage/nls/Sage_mk", [], 1);
