require({cache:{
'Sage/Utility/File/nls/kk/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/kk/FallbackFilePicker',{});
},
'Sage/UI/nls/kk/Boolean':function(){
define('Sage/UI/nls/kk/Boolean',{});
},
'Sage/Services/nls/kk/ActivityService':function(){
define('Sage/Services/nls/kk/ActivityService',{});
},
'Sage/UI/Controls/nls/kk/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/kk/CopyToClipboard',{});
},
'Sage/Utility/nls/kk/Activity':function(){
define('Sage/Utility/nls/kk/Activity',{});
},
'Sage/QuickForms/Design/nls/kk/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/kk/DesignPanel',{});
},
'Sage/UI/nls/kk/TimelessActivitiesPane':function(){
define('Sage/UI/nls/kk/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ActivityEditor',{});
},
'Sage/MainView/nls/kk/ActivityManager':function(){
define('Sage/MainView/nls/kk/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/kk/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/_PropertyEditor',{});
},
'Sage/Services/nls/kk/ActivityActionProcessor':function(){
define('Sage/Services/nls/kk/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/kk/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/kk/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/kk/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/kk/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/kk/AlarmPane':function(){
define('Sage/UI/Alarms/nls/kk/AlarmPane',{});
},
'Sage/TaskPane/nls/kk/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/kk/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/kk/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/kk/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/kk/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/kk/FilterPanel':function(){
define('Sage/UI/Filters/nls/kk/FilterPanel',{});
},
'Sage/TaskPane/nls/kk/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/kk/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/kk/OwnerType':function(){
define('Sage/UI/nls/kk/OwnerType',{});
},
'Sage/TaskPane/nls/kk/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/kk/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/kk/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/kk/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk/InvoiceRTDV',{});
},
'Sage/UI/nls/kk/SDataLookup':function(){
define('Sage/UI/nls/kk/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/kk/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/RowDesigner',{});
},
'Sage/TaskPane/nls/kk/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/kk/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/kk/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/kk/LibraryDocument':function(){
define('Sage/Utility/File/nls/kk/LibraryDocument',{});
},
'Sage/UI/nls/kk/ConditionManager':function(){
define('Sage/UI/nls/kk/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/kk/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/kk/WidgetDefinition',{});
},
'Sage/UI/nls/kk/SearchConditionWidget':function(){
define('Sage/UI/nls/kk/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/kk/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/kk/DataSourcePanel',{});
},
'Sage/UI/nls/kk/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/kk/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/kk/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/kk/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/kk/Name':function(){
define('Sage/UI/Controls/nls/kk/Name',{});
},
'Sage/QuickForms/Design/nls/kk/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/kk/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/kk/UpdateLeads',{});
},
'Sage/UI/nls/kk/ListPanel':function(){
define('Sage/UI/nls/kk/ListPanel',{});
},
'Sage/UI/Filters/nls/kk/EditFilters':function(){
define('Sage/UI/Filters/nls/kk/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/kk/DurationSelect':function(){
define('Sage/UI/Controls/nls/kk/DurationSelect',{});
},
'Sage/UI/Alarms/nls/kk/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/kk/AlarmCountDown',{});
},
'Sage/UI/nls/kk/AttachmentList':function(){
define('Sage/UI/nls/kk/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/kk/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/kk/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/kk/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/kk/Dialogs':function(){
define('Sage/UI/nls/kk/Dialogs',{});
},
'Sage/TaskPane/nls/kk/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/kk/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/kk/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/kk/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/kk/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/kk/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/kk/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/UserControlDesigner',{});
},
'Sage/Groups/nls/kk/GroupNavigator':function(){
define('Sage/Groups/nls/kk/GroupNavigator',{});
},
'Sage/Utility/File/nls/kk/AddURLAttachment':function(){
define('Sage/Utility/File/nls/kk/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/kk/EditFilterItems':function(){
define('Sage/UI/Filters/nls/kk/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/kk/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/kk/DesignSurface',{});
},
'Sage/Utility/File/nls/kk/DragDropWatcher':function(){
define('Sage/Utility/File/nls/kk/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/EventListPanelConfig',{});
},
'Sage/UI/nls/kk/ActivityScheduler':function(){
define('Sage/UI/nls/kk/ActivityScheduler',{});
},
'Sage/MainView/nls/kk/SecurityManager':function(){
define('Sage/MainView/nls/kk/SecurityManager',{});
},
'Sage/TaskPane/nls/kk/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/kk/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/kk/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/kk/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/kk/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/kk/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/kk/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/kk/HelpMenu':function(){
define('Sage/UI/Controls/nls/kk/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/kk/UserTasklet':function(){
define('Sage/TaskPane/nls/kk/UserTasklet',{});
},
'Sage/UI/Alarms/nls/kk/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/kk/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/kk/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/kk/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/kk/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/kk/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/kk/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/ColumnDesigner',{});
},
'Sage/UI/nls/kk/SearchMenuItem':function(){
define('Sage/UI/nls/kk/SearchMenuItem',{});
},
'Sage/UI/nls/kk/NotesHistoryList':function(){
define('Sage/UI/nls/kk/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/kk/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/kk/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/kk/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/kk/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/kk/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/kk/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/HistoryEditor',{});
},
'Sage/Groups/nls/kk/GroupManager':function(){
define('Sage/Groups/nls/kk/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/kk/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/kk/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/kk/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/kk/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/kk/EditableGrid':function(){
define('Sage/UI/nls/kk/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/kk/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/kk/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/kk/SpeedSearch':function(){
define('Sage/UI/nls/kk/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/kk/SLXPreviewGrid':function(){
define('Sage/UI/nls/kk/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/kk/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/kk/UnconfirmedPane',{});
},
'Sage/Utility/nls/kk/Utility':function(){
define('Sage/Utility/nls/kk/Utility',{});
},
'Sage/QuickForms/Design/nls/kk/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/ControlDesigner',{});
},
'Sage/UI/Controls/nls/kk/Address':function(){
define('Sage/UI/Controls/nls/kk/Address',{});
},
'Sage/MainView/ActivityMgr/nls/kk/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/kk/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/OwnerControlDesigner',{});
},
'Sage/UI/nls/kk/UserType':function(){
define('Sage/UI/nls/kk/UserType',{});
},
'Sage/QuickForms/Design/nls/kk/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/kk/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/kk/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/kk/ActivityList':function(){
define('Sage/UI/nls/kk/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/kk/CalendarUsersListPane':function(){
define('Sage/UI/nls/kk/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/kk/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/kk/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/kk/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/kk/Attachment':function(){
define('Sage/Utility/File/nls/kk/Attachment',{});
},
'Sage/QuickForms/Design/nls/kk/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/kk/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/kk/Helper':function(){
define('Sage/MailMerge/nls/kk/Helper',{});
},
'Sage/UI/Dashboard/nls/kk/Dashboard':function(){
define('Sage/UI/Dashboard/nls/kk/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/kk/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/kk/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/kk/PickList':function(){
define('Sage/UI/Controls/nls/kk/PickList',{});
},
'Sage/Utility/nls/kk/Email':function(){
define('Sage/Utility/nls/kk/Email',{});
},
'Sage/TaskPane/nls/kk/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/kk/TimeZoneItem':function(){
define('Sage/UI/nls/kk/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/kk/SlxEdit':function(){
define('Sage/UI/Columns/nls/kk/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/kk/LogOffButton':function(){
define('Sage/UI/Controls/nls/kk/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/kk/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/kk/EditEventEditor',{});
},
'Sage/MailMerge/nls/kk/Loader':function(){
define('Sage/MailMerge/nls/kk/Loader',{});
},
'Sage/UI/Controls/nls/kk/DateTimePicker':function(){
define('Sage/UI/Controls/nls/kk/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/kk/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/kk/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/kk/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/kk/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/kk/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/kk/Lookup':function(){
define('Sage/UI/Controls/nls/kk/Lookup',{});
},
'Sage/Utility/File/nls/kk/DescriptionsForm':function(){
define('Sage/Utility/File/nls/kk/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/kk/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/kk/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/kk/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/kk/CommonTasksTasklet',{});
},
'Sage/Utility/nls/kk/Dashboard':function(){
define('Sage/Utility/nls/kk/Dashboard',{});
}}});
define("Sage/nls/Sage_kk", [], 1);
