require({cache:{
'Sage/Utility/File/nls/zh/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zh/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/zh-sg/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zh-sg/FallbackFilePicker',{});
},
'Sage/UI/nls/zh/Boolean':function(){
define('Sage/UI/nls/zh/Boolean',{});
},
'Sage/UI/nls/zh-sg/Boolean':function(){
define('Sage/UI/nls/zh-sg/Boolean',{});
},
'Sage/Services/nls/zh/ActivityService':function(){
define('Sage/Services/nls/zh/ActivityService',{});
},
'Sage/Services/nls/zh-sg/ActivityService':function(){
define('Sage/Services/nls/zh-sg/ActivityService',{});
},
'Sage/UI/Controls/nls/zh/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zh/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/zh-sg/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zh-sg/CopyToClipboard',{});
},
'Sage/Utility/nls/zh/Activity':function(){
define('Sage/Utility/nls/zh/Activity',{});
},
'Sage/Utility/nls/zh-sg/Activity':function(){
define('Sage/Utility/nls/zh-sg/Activity',{});
},
'Sage/QuickForms/Design/nls/zh/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/zh/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/zh-sg/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/zh-sg/DesignPanel',{});
},
'Sage/UI/nls/zh/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zh/TimelessActivitiesPane',{});
},
'Sage/UI/nls/zh-sg/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zh-sg/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-sg/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-sg/ActivityEditor',{});
},
'Sage/MainView/nls/zh/ActivityManager':function(){
define('Sage/MainView/nls/zh/ActivityManager',{});
},
'Sage/MainView/nls/zh-sg/ActivityManager':function(){
define('Sage/MainView/nls/zh-sg/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/zh/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/_PropertyEditor',{});
},
'Sage/Services/nls/zh/ActivityActionProcessor':function(){
define('Sage/Services/nls/zh/ActivityActionProcessor',{});
},
'Sage/Services/nls/zh-sg/ActivityActionProcessor':function(){
define('Sage/Services/nls/zh-sg/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-sg/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-sg/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/zh/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zh/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/zh-sg/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zh-sg/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/zh/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zh/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/zh-sg/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zh-sg/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/zh/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zh/AlarmPane',{});
},
'Sage/UI/Alarms/nls/zh-sg/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zh-sg/AlarmPane',{});
},
'Sage/TaskPane/nls/zh/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zh/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/zh-sg/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zh-sg/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/zh-sg/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zh-sg/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zh-sg/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh-sg/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/zh/FilterPanel':function(){
define('Sage/UI/Filters/nls/zh/FilterPanel',{});
},
'Sage/UI/Filters/nls/zh-sg/FilterPanel':function(){
define('Sage/UI/Filters/nls/zh-sg/FilterPanel',{});
},
'Sage/TaskPane/nls/zh/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zh/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/zh-sg/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zh-sg/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/zh/OwnerType':function(){
define('Sage/UI/nls/zh/OwnerType',{});
},
'Sage/UI/nls/zh-sg/OwnerType':function(){
define('Sage/UI/nls/zh-sg/OwnerType',{});
},
'Sage/TaskPane/nls/zh/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-sg/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-sg/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/zh/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/zh/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/zh-sg/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/zh-sg/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zh-sg/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh-sg/InvoiceRTDV',{});
},
'Sage/UI/nls/zh/SDataLookup':function(){
define('Sage/UI/nls/zh/SDataLookup',{});
},
'Sage/UI/nls/zh-sg/SDataLookup':function(){
define('Sage/UI/nls/zh-sg/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/zh/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/RowDesigner',{});
},
'Sage/TaskPane/nls/zh/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-sg/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-sg/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/zh/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zh/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/zh-sg/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zh-sg/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/zh/LibraryDocument':function(){
define('Sage/Utility/File/nls/zh/LibraryDocument',{});
},
'Sage/Utility/File/nls/zh-sg/LibraryDocument':function(){
define('Sage/Utility/File/nls/zh-sg/LibraryDocument',{});
},
'Sage/UI/nls/zh/ConditionManager':function(){
define('Sage/UI/nls/zh/ConditionManager',{});
},
'Sage/UI/nls/zh-sg/ConditionManager':function(){
define('Sage/UI/nls/zh-sg/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/zh/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zh/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/zh-sg/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zh-sg/WidgetDefinition',{});
},
'Sage/UI/nls/zh/SearchConditionWidget':function(){
define('Sage/UI/nls/zh/SearchConditionWidget',{});
},
'Sage/UI/nls/zh-sg/SearchConditionWidget':function(){
define('Sage/UI/nls/zh-sg/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/zh/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/zh-sg/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/zh-sg/DataSourcePanel',{});
},
'Sage/UI/nls/zh/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zh/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/zh-sg/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zh-sg/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/zh/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/zh/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/zh-sg/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/zh-sg/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/zh/Name':function(){
define('Sage/UI/Controls/nls/zh/Name',{});
},
'Sage/UI/Controls/nls/zh-sg/Name':function(){
define('Sage/UI/Controls/nls/zh-sg/Name',{});
},
'Sage/QuickForms/Design/nls/zh/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/zh/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zh/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/zh-sg/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zh-sg/UpdateLeads',{});
},
'Sage/UI/nls/zh/ListPanel':function(){
define('Sage/UI/nls/zh/ListPanel',{});
},
'Sage/UI/nls/zh-sg/ListPanel':function(){
define('Sage/UI/nls/zh-sg/ListPanel',{});
},
'Sage/UI/Filters/nls/zh/EditFilters':function(){
define('Sage/UI/Filters/nls/zh/EditFilters',{});
},
'Sage/UI/Filters/nls/zh-sg/EditFilters':function(){
define('Sage/UI/Filters/nls/zh-sg/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/zh/DurationSelect':function(){
define('Sage/UI/Controls/nls/zh/DurationSelect',{});
},
'Sage/UI/Controls/nls/zh-sg/DurationSelect':function(){
define('Sage/UI/Controls/nls/zh-sg/DurationSelect',{});
},
'Sage/UI/Alarms/nls/zh/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zh/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/zh-sg/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zh-sg/AlarmCountDown',{});
},
'Sage/UI/nls/zh/AttachmentList':function(){
define('Sage/UI/nls/zh/AttachmentList',{});
},
'Sage/UI/nls/zh-sg/AttachmentList':function(){
define('Sage/UI/nls/zh-sg/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/zh-sg/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zh-sg/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/zh/Dialogs':function(){
define('Sage/UI/nls/zh/Dialogs',{});
},
'Sage/UI/nls/zh-sg/Dialogs':function(){
define('Sage/UI/nls/zh-sg/Dialogs',{});
},
'Sage/TaskPane/nls/zh/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zh/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/zh-sg/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zh-sg/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/zh-sg/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zh-sg/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/zh/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zh-sg/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh-sg/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/zh/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/UserControlDesigner',{});
},
'Sage/Groups/nls/zh/GroupNavigator':function(){
define('Sage/Groups/nls/zh/GroupNavigator',{});
},
'Sage/Groups/nls/zh-sg/GroupNavigator':function(){
define('Sage/Groups/nls/zh-sg/GroupNavigator',{});
},
'Sage/Utility/File/nls/zh/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zh/AddURLAttachment',{});
},
'Sage/Utility/File/nls/zh-sg/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zh-sg/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/zh/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zh/EditFilterItems',{});
},
'Sage/UI/Filters/nls/zh-sg/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zh-sg/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/zh/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/zh/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/zh-sg/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/zh-sg/DesignSurface',{});
},
'Sage/Utility/File/nls/zh/DragDropWatcher':function(){
define('Sage/Utility/File/nls/zh/DragDropWatcher',{});
},
'Sage/Utility/File/nls/zh-sg/DragDropWatcher':function(){
define('Sage/Utility/File/nls/zh-sg/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-sg/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-sg/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-sg/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-sg/EventListPanelConfig',{});
},
'Sage/UI/nls/zh/ActivityScheduler':function(){
define('Sage/UI/nls/zh/ActivityScheduler',{});
},
'Sage/UI/nls/zh-sg/ActivityScheduler':function(){
define('Sage/UI/nls/zh-sg/ActivityScheduler',{});
},
'Sage/MainView/nls/zh/SecurityManager':function(){
define('Sage/MainView/nls/zh/SecurityManager',{});
},
'Sage/MainView/nls/zh-sg/SecurityManager':function(){
define('Sage/MainView/nls/zh-sg/SecurityManager',{});
},
'Sage/TaskPane/nls/zh/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zh/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/zh-sg/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zh-sg/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/zh/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/zh/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/zh-sg/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/zh-sg/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/zh-sg/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zh-sg/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/zh/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zh/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/zh-sg/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zh-sg/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/zh/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/HelpMenu':function(){
define('Sage/UI/Controls/nls/zh/HelpMenu',{});
},
'Sage/UI/Controls/nls/zh-sg/HelpMenu':function(){
define('Sage/UI/Controls/nls/zh-sg/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/UserTasklet':function(){
define('Sage/TaskPane/nls/zh/UserTasklet',{});
},
'Sage/TaskPane/nls/zh-sg/UserTasklet':function(){
define('Sage/TaskPane/nls/zh-sg/UserTasklet',{});
},
'Sage/UI/Alarms/nls/zh/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zh/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/zh-sg/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zh-sg/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/zh/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zh/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/zh-sg/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zh-sg/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/zh/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/zh/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/zh-sg/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/zh-sg/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/zh/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/ColumnDesigner',{});
},
'Sage/UI/nls/zh/SearchMenuItem':function(){
define('Sage/UI/nls/zh/SearchMenuItem',{});
},
'Sage/UI/nls/zh-sg/SearchMenuItem':function(){
define('Sage/UI/nls/zh-sg/SearchMenuItem',{});
},
'Sage/UI/nls/zh/NotesHistoryList':function(){
define('Sage/UI/nls/zh/NotesHistoryList',{});
},
'Sage/UI/nls/zh-sg/NotesHistoryList':function(){
define('Sage/UI/nls/zh-sg/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/zh/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/zh/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zh/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/zh-sg/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zh-sg/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/zh/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zh/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-sg/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-sg/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-sg/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-sg/HistoryEditor',{});
},
'Sage/Groups/nls/zh/GroupManager':function(){
define('Sage/Groups/nls/zh/GroupManager',{});
},
'Sage/Groups/nls/zh-sg/GroupManager':function(){
define('Sage/Groups/nls/zh-sg/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-sg/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-sg/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/zh/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zh/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/zh-sg/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zh-sg/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-sg/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-sg/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/zh/EditableGrid':function(){
define('Sage/UI/nls/zh/EditableGrid',{});
},
'Sage/UI/nls/zh-sg/EditableGrid':function(){
define('Sage/UI/nls/zh-sg/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/zh/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/zh/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/zh-sg/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/zh-sg/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/SpeedSearch':function(){
define('Sage/UI/nls/zh/SpeedSearch',{});
},
'Sage/UI/nls/zh-sg/SpeedSearch':function(){
define('Sage/UI/nls/zh-sg/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/SLXPreviewGrid':function(){
define('Sage/UI/nls/zh/SLXPreviewGrid',{});
},
'Sage/UI/nls/zh-sg/SLXPreviewGrid':function(){
define('Sage/UI/nls/zh-sg/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/zh/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zh/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/zh-sg/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zh-sg/UnconfirmedPane',{});
},
'Sage/Utility/nls/zh/Utility':function(){
define('Sage/Utility/nls/zh/Utility',{});
},
'Sage/Utility/nls/zh-sg/Utility':function(){
define('Sage/Utility/nls/zh-sg/Utility',{});
},
'Sage/QuickForms/Design/nls/zh/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/ControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/Address':function(){
define('Sage/UI/Controls/nls/zh/Address',{});
},
'Sage/UI/Controls/nls/zh-sg/Address':function(){
define('Sage/UI/Controls/nls/zh-sg/Address',{});
},
'Sage/MainView/ActivityMgr/nls/zh/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-sg/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-sg/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zh/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/OwnerControlDesigner',{});
},
'Sage/UI/nls/zh/UserType':function(){
define('Sage/UI/nls/zh/UserType',{});
},
'Sage/UI/nls/zh-sg/UserType':function(){
define('Sage/UI/nls/zh-sg/UserType',{});
},
'Sage/QuickForms/Design/nls/zh/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/zh-sg/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zh-sg/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/zh/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zh/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/zh-sg/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zh-sg/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/ActivityList':function(){
define('Sage/UI/nls/zh/ActivityList',{});
},
'Sage/UI/nls/zh-sg/ActivityList':function(){
define('Sage/UI/nls/zh-sg/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/CalendarUsersListPane':function(){
define('Sage/UI/nls/zh/CalendarUsersListPane',{});
},
'Sage/UI/nls/zh-sg/CalendarUsersListPane':function(){
define('Sage/UI/nls/zh-sg/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/zh/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/zh-sg/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/zh-sg/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zh/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/zh-sg/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zh-sg/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/zh/Attachment':function(){
define('Sage/Utility/File/nls/zh/Attachment',{});
},
'Sage/Utility/File/nls/zh-sg/Attachment':function(){
define('Sage/Utility/File/nls/zh-sg/Attachment',{});
},
'Sage/QuickForms/Design/nls/zh/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/zh/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/zh-sg/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/zh-sg/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/zh/Helper':function(){
define('Sage/MailMerge/nls/zh/Helper',{});
},
'Sage/MailMerge/nls/zh-sg/Helper':function(){
define('Sage/MailMerge/nls/zh-sg/Helper',{});
},
'Sage/UI/Dashboard/nls/zh/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zh/Dashboard',{});
},
'Sage/UI/Dashboard/nls/zh-sg/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zh-sg/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-sg/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-sg/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/zh/PickList':function(){
define('Sage/UI/Controls/nls/zh/PickList',{});
},
'Sage/UI/Controls/nls/zh-sg/PickList':function(){
define('Sage/UI/Controls/nls/zh-sg/PickList',{});
},
'Sage/Utility/nls/zh/Email':function(){
define('Sage/Utility/nls/zh/Email',{});
},
'Sage/Utility/nls/zh-sg/Email':function(){
define('Sage/Utility/nls/zh-sg/Email',{});
},
'Sage/TaskPane/nls/zh/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-sg/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-sg/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/zh/TimeZoneItem':function(){
define('Sage/UI/nls/zh/TimeZoneItem',{});
},
'Sage/UI/nls/zh-sg/TimeZoneItem':function(){
define('Sage/UI/nls/zh-sg/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/zh/SlxEdit':function(){
define('Sage/UI/Columns/nls/zh/SlxEdit',{});
},
'Sage/UI/Columns/nls/zh-sg/SlxEdit':function(){
define('Sage/UI/Columns/nls/zh-sg/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/zh/LogOffButton':function(){
define('Sage/UI/Controls/nls/zh/LogOffButton',{});
},
'Sage/UI/Controls/nls/zh-sg/LogOffButton':function(){
define('Sage/UI/Controls/nls/zh-sg/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-sg/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-sg/EditEventEditor',{});
},
'Sage/MailMerge/nls/zh/Loader':function(){
define('Sage/MailMerge/nls/zh/Loader',{});
},
'Sage/MailMerge/nls/zh-sg/Loader':function(){
define('Sage/MailMerge/nls/zh-sg/Loader',{});
},
'Sage/UI/Controls/nls/zh/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zh/DateTimePicker',{});
},
'Sage/UI/Controls/nls/zh-sg/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zh-sg/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/zh/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zh/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/zh-sg/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zh-sg/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-sg/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-sg/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/Lookup':function(){
define('Sage/UI/Controls/nls/zh/Lookup',{});
},
'Sage/UI/Controls/nls/zh-sg/Lookup':function(){
define('Sage/UI/Controls/nls/zh-sg/Lookup',{});
},
'Sage/Utility/File/nls/zh/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zh/DescriptionsForm',{});
},
'Sage/Utility/File/nls/zh-sg/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zh-sg/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-sg/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-sg/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-sg/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-sg/CommonTasksTasklet',{});
},
'Sage/Utility/nls/zh/Dashboard':function(){
define('Sage/Utility/nls/zh/Dashboard',{});
},
'Sage/Utility/nls/zh-sg/Dashboard':function(){
define('Sage/Utility/nls/zh-sg/Dashboard',{});
}}});
define("Sage/nls/Sage_zh-sg", [], 1);
