require({cache:{
'Sage/Utility/File/nls/ar/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/ar-qa/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar-qa/FallbackFilePicker',{});
},
'Sage/UI/nls/ar/Boolean':function(){
define('Sage/UI/nls/ar/Boolean',{});
},
'Sage/UI/nls/ar-qa/Boolean':function(){
define('Sage/UI/nls/ar-qa/Boolean',{});
},
'Sage/UI/Controls/nls/ar/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/ar-qa/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar-qa/CopyToClipboard',{});
},
'Sage/Services/nls/ar/ActivityService':function(){
define('Sage/Services/nls/ar/ActivityService',{});
},
'Sage/Services/nls/ar-qa/ActivityService':function(){
define('Sage/Services/nls/ar-qa/ActivityService',{});
},
'Sage/Utility/nls/ar/Activity':function(){
define('Sage/Utility/nls/ar/Activity',{});
},
'Sage/Utility/nls/ar-qa/Activity':function(){
define('Sage/Utility/nls/ar-qa/Activity',{});
},
'Sage/UI/nls/ar/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar/TimelessActivitiesPane',{});
},
'Sage/UI/nls/ar-qa/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar-qa/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/ActivityEditor',{});
},
'Sage/MainView/nls/ar/ActivityManager':function(){
define('Sage/MainView/nls/ar/ActivityManager',{});
},
'Sage/MainView/nls/ar-qa/ActivityManager':function(){
define('Sage/MainView/nls/ar-qa/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/ar/Service':function(){
define('Sage/Reporting/nls/ar/Service',{});
},
'Sage/Reporting/nls/ar-qa/Service':function(){
define('Sage/Reporting/nls/ar-qa/Service',{});
},
'Sage/Utility/File/nls/ar/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar-qa/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar-qa/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/ar-qa/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar-qa/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPane',{});
},
'Sage/UI/Alarms/nls/ar-qa/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar-qa/AlarmPane',{});
},
'Sage/TaskPane/nls/ar/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/ar-qa/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar-qa/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/ar-qa/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar-qa/DashboardWidget',{});
},
'Sage/UI/Filters/nls/ar/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar/FilterPanel',{});
},
'Sage/UI/Filters/nls/ar-qa/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar-qa/FilterPanel',{});
},
'Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/ar/OwnerType':function(){
define('Sage/UI/nls/ar/OwnerType',{});
},
'Sage/UI/nls/ar-qa/OwnerType':function(){
define('Sage/UI/nls/ar-qa/OwnerType',{});
},
'Sage/TaskPane/nls/ar/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/LeadTasksTasklet',{});
},
'Sage/UI/nls/ar/SDataLookup':function(){
define('Sage/UI/nls/ar/SDataLookup',{});
},
'Sage/UI/nls/ar-qa/SDataLookup':function(){
define('Sage/UI/nls/ar-qa/SDataLookup',{});
},
'Sage/TaskPane/nls/ar/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ar/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/ar-qa/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar-qa/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ar/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar/LibraryDocument',{});
},
'Sage/Utility/File/nls/ar-qa/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar-qa/LibraryDocument',{});
},
'Sage/UI/nls/ar/ConditionManager':function(){
define('Sage/UI/nls/ar/ConditionManager',{});
},
'Sage/UI/nls/ar-qa/ConditionManager':function(){
define('Sage/UI/nls/ar-qa/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ar/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/ar-qa/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar-qa/WidgetDefinition',{});
},
'Sage/UI/nls/ar/SearchConditionWidget':function(){
define('Sage/UI/nls/ar/SearchConditionWidget',{});
},
'Sage/UI/nls/ar-qa/SearchConditionWidget':function(){
define('Sage/UI/nls/ar-qa/SearchConditionWidget',{});
},
'Sage/UI/nls/ar/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/ar-qa/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar-qa/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/ar/Name':function(){
define('Sage/UI/Controls/nls/ar/Name',{});
},
'Sage/UI/Controls/nls/ar-qa/Name':function(){
define('Sage/UI/Controls/nls/ar-qa/Name',{});
},
'Sage/MainView/Lead/nls/ar/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/ar-qa/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar-qa/UpdateLeads',{});
},
'Sage/UI/nls/ar/ListPanel':function(){
define('Sage/UI/nls/ar/ListPanel',{});
},
'Sage/UI/nls/ar-qa/ListPanel':function(){
define('Sage/UI/nls/ar-qa/ListPanel',{});
},
'Sage/UI/Filters/nls/ar/EditFilters':function(){
define('Sage/UI/Filters/nls/ar/EditFilters',{});
},
'Sage/UI/Filters/nls/ar-qa/EditFilters':function(){
define('Sage/UI/Filters/nls/ar-qa/EditFilters',{});
},
'Sage/UI/Controls/nls/ar/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar/DurationSelect',{});
},
'Sage/UI/Controls/nls/ar-qa/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar-qa/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ar/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/ar-qa/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar-qa/AlarmCountDown',{});
},
'Sage/UI/nls/ar/AttachmentList':function(){
define('Sage/UI/nls/ar/AttachmentList',{});
},
'Sage/UI/nls/ar-qa/AttachmentList':function(){
define('Sage/UI/nls/ar-qa/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/ar-qa/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar-qa/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/ar/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/ar-qa/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar-qa/DashboardTabController',{});
},
'Sage/Groups/nls/ar/GroupNavigator':function(){
define('Sage/Groups/nls/ar/GroupNavigator',{});
},
'Sage/Groups/nls/ar-qa/GroupNavigator':function(){
define('Sage/Groups/nls/ar-qa/GroupNavigator',{});
},
'Sage/Utility/File/nls/ar/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar/AddURLAttachment',{});
},
'Sage/Utility/File/nls/ar-qa/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar-qa/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ar/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar/EditFilterItems',{});
},
'Sage/UI/Filters/nls/ar-qa/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar-qa/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/EventListPanelConfig',{});
},
'Sage/UI/nls/ar/ActivityScheduler':function(){
define('Sage/UI/nls/ar/ActivityScheduler',{});
},
'Sage/UI/nls/ar-qa/ActivityScheduler':function(){
define('Sage/UI/nls/ar-qa/ActivityScheduler',{});
},
'Sage/MainView/nls/ar/SecurityManager':function(){
define('Sage/MainView/nls/ar/SecurityManager',{});
},
'Sage/MainView/nls/ar-qa/SecurityManager':function(){
define('Sage/MainView/nls/ar-qa/SecurityManager',{});
},
'Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/ar-qa/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar-qa/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/ar/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/ar-qa/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar-qa/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/ar/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar/HelpMenu',{});
},
'Sage/UI/Controls/nls/ar-qa/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar-qa/HelpMenu',{});
},
'Sage/TaskPane/nls/ar/UserTasklet':function(){
define('Sage/TaskPane/nls/ar/UserTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/UserTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ar/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/ar-qa/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar-qa/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ar/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/ar-qa/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar-qa/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/ar/MenuHelper':function(){
define('Sage/MailMerge/nls/ar/MenuHelper',{});
},
'Sage/MailMerge/nls/ar-qa/MenuHelper':function(){
define('Sage/MailMerge/nls/ar-qa/MenuHelper',{});
},
'Sage/UI/nls/ar/SearchMenuItem':function(){
define('Sage/UI/nls/ar/SearchMenuItem',{});
},
'Sage/UI/nls/ar-qa/SearchMenuItem':function(){
define('Sage/UI/nls/ar-qa/SearchMenuItem',{});
},
'Sage/UI/nls/ar/NotesHistoryList':function(){
define('Sage/UI/nls/ar/NotesHistoryList',{});
},
'Sage/UI/nls/ar-qa/NotesHistoryList':function(){
define('Sage/UI/nls/ar-qa/NotesHistoryList',{});
},
'Sage/Utility/File/nls/ar/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/ar-qa/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar-qa/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/HistoryEditor',{});
},
'Sage/Groups/nls/ar/GroupManager':function(){
define('Sage/Groups/nls/ar/GroupManager',{});
},
'Sage/Groups/nls/ar-qa/GroupManager':function(){
define('Sage/Groups/nls/ar-qa/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/ar/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedAlarm',{});
},
'Sage/UI/Alarms/nls/ar-qa/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/ar-qa/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/ar-qa/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar-qa/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/ar/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/AccountingTasksTasklet',{});
},
'Sage/UI/nls/ar/EditableGrid':function(){
define('Sage/UI/nls/ar/EditableGrid',{});
},
'Sage/UI/nls/ar-qa/EditableGrid':function(){
define('Sage/UI/nls/ar-qa/EditableGrid',{});
},
'Sage/UI/nls/ar/SpeedSearch':function(){
define('Sage/UI/nls/ar/SpeedSearch',{});
},
'Sage/UI/nls/ar-qa/SpeedSearch':function(){
define('Sage/UI/nls/ar-qa/SpeedSearch',{});
},
'Sage/UI/nls/ar/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar/SLXPreviewGrid',{});
},
'Sage/UI/nls/ar-qa/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar-qa/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/ar-qa/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar-qa/UnconfirmedPane',{});
},
'Sage/Utility/nls/ar/Utility':function(){
define('Sage/Utility/nls/ar/Utility',{});
},
'Sage/Utility/nls/ar-qa/Utility':function(){
define('Sage/Utility/nls/ar-qa/Utility',{});
},
'Sage/UI/Controls/nls/ar/Address':function(){
define('Sage/UI/Controls/nls/ar/Address',{});
},
'Sage/UI/Controls/nls/ar-qa/Address':function(){
define('Sage/UI/Controls/nls/ar-qa/Address',{});
},
'Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/BaseListPanelConfig',{});
},
'Sage/UI/nls/ar/UserType':function(){
define('Sage/UI/nls/ar/UserType',{});
},
'Sage/UI/nls/ar-qa/UserType':function(){
define('Sage/UI/nls/ar-qa/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/ar/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/ar-qa/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar-qa/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/ar/ActivityList':function(){
define('Sage/UI/nls/ar/ActivityList',{});
},
'Sage/UI/nls/ar-qa/ActivityList':function(){
define('Sage/UI/nls/ar-qa/ActivityList',{});
},
'Sage/UI/nls/ar/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar/CalendarUsersListPane',{});
},
'Sage/UI/nls/ar-qa/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar-qa/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ar/Attachment':function(){
define('Sage/Utility/File/nls/ar/Attachment',{});
},
'Sage/Utility/File/nls/ar-qa/Attachment':function(){
define('Sage/Utility/File/nls/ar-qa/Attachment',{});
},
'Sage/MailMerge/nls/ar/Helper':function(){
define('Sage/MailMerge/nls/ar/Helper',{});
},
'Sage/MailMerge/nls/ar-qa/Helper':function(){
define('Sage/MailMerge/nls/ar-qa/Helper',{});
},
'Sage/UI/Dashboard/nls/ar/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar/Dashboard',{});
},
'Sage/UI/Dashboard/nls/ar-qa/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar-qa/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ar/PickList':function(){
define('Sage/UI/Controls/nls/ar/PickList',{});
},
'Sage/UI/Controls/nls/ar-qa/PickList':function(){
define('Sage/UI/Controls/nls/ar-qa/PickList',{});
},
'Sage/Utility/nls/ar/Email':function(){
define('Sage/Utility/nls/ar/Email',{});
},
'Sage/Utility/nls/ar-qa/Email':function(){
define('Sage/Utility/nls/ar-qa/Email',{});
},
'Sage/UI/nls/ar/TimeZoneItem':function(){
define('Sage/UI/nls/ar/TimeZoneItem',{});
},
'Sage/UI/nls/ar-qa/TimeZoneItem':function(){
define('Sage/UI/nls/ar-qa/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ar/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar/SlxEdit',{});
},
'Sage/UI/Columns/nls/ar-qa/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar-qa/SlxEdit',{});
},
'Sage/UI/Controls/nls/ar/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar/LogOffButton',{});
},
'Sage/UI/Controls/nls/ar-qa/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar-qa/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-qa/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-qa/EditEventEditor',{});
},
'Sage/MailMerge/nls/ar/Loader':function(){
define('Sage/MailMerge/nls/ar/Loader',{});
},
'Sage/MailMerge/nls/ar-qa/Loader':function(){
define('Sage/MailMerge/nls/ar-qa/Loader',{});
},
'Sage/UI/Controls/nls/ar/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar/DateTimePicker',{});
},
'Sage/UI/Controls/nls/ar-qa/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar-qa/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/ar-qa/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar-qa/AlarmPopup',{});
},
'Sage/UI/Controls/nls/ar/Lookup':function(){
define('Sage/UI/Controls/nls/ar/Lookup',{});
},
'Sage/UI/Controls/nls/ar-qa/Lookup':function(){
define('Sage/UI/Controls/nls/ar-qa/Lookup',{});
},
'Sage/Utility/File/nls/ar/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar/DescriptionsForm',{});
},
'Sage/Utility/File/nls/ar-qa/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar-qa/DescriptionsForm',{});
},
'Sage/TaskPane/nls/ar/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-qa/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-qa/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_ar-qa", [], 1);
