require({cache:{
'Sage/Utility/File/nls/af/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/af/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/af-za/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/af-za/FallbackFilePicker',{});
},
'Sage/UI/nls/af/Boolean':function(){
define('Sage/UI/nls/af/Boolean',{});
},
'Sage/UI/nls/af-za/Boolean':function(){
define('Sage/UI/nls/af-za/Boolean',{});
},
'Sage/UI/Controls/nls/af/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/af/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/af-za/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/af-za/CopyToClipboard',{});
},
'Sage/Services/nls/af/ActivityService':function(){
define('Sage/Services/nls/af/ActivityService',{});
},
'Sage/Services/nls/af-za/ActivityService':function(){
define('Sage/Services/nls/af-za/ActivityService',{});
},
'Sage/Utility/nls/af/Activity':function(){
define('Sage/Utility/nls/af/Activity',{});
},
'Sage/Utility/nls/af-za/Activity':function(){
define('Sage/Utility/nls/af-za/Activity',{});
},
'Sage/UI/nls/af/TimelessActivitiesPane':function(){
define('Sage/UI/nls/af/TimelessActivitiesPane',{});
},
'Sage/UI/nls/af-za/TimelessActivitiesPane':function(){
define('Sage/UI/nls/af-za/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/af/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/ActivityEditor',{});
},
'Sage/MainView/nls/af/ActivityManager':function(){
define('Sage/MainView/nls/af/ActivityManager',{});
},
'Sage/MainView/nls/af-za/ActivityManager':function(){
define('Sage/MainView/nls/af-za/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/af/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/af/Service':function(){
define('Sage/Reporting/nls/af/Service',{});
},
'Sage/Reporting/nls/af-za/Service':function(){
define('Sage/Reporting/nls/af-za/Service',{});
},
'Sage/Utility/File/nls/af/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/af/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/af-za/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/af-za/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/af/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/af/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/af-za/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/af-za/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/af/AlarmPane':function(){
define('Sage/UI/Alarms/nls/af/AlarmPane',{});
},
'Sage/UI/Alarms/nls/af-za/AlarmPane':function(){
define('Sage/UI/Alarms/nls/af-za/AlarmPane',{});
},
'Sage/TaskPane/nls/af/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/af/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/af-za/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/af-za/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/af/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/af/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/af-za/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/af-za/DashboardWidget',{});
},
'Sage/UI/Filters/nls/af/FilterPanel':function(){
define('Sage/UI/Filters/nls/af/FilterPanel',{});
},
'Sage/UI/Filters/nls/af-za/FilterPanel':function(){
define('Sage/UI/Filters/nls/af-za/FilterPanel',{});
},
'Sage/TaskPane/nls/af/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/af/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/af-za/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/af-za/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/af/OwnerType':function(){
define('Sage/UI/nls/af/OwnerType',{});
},
'Sage/UI/nls/af-za/OwnerType':function(){
define('Sage/UI/nls/af-za/OwnerType',{});
},
'Sage/TaskPane/nls/af/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/af/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/af-za/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/af-za/LeadTasksTasklet',{});
},
'Sage/UI/nls/af/SDataLookup':function(){
define('Sage/UI/nls/af/SDataLookup',{});
},
'Sage/UI/nls/af-za/SDataLookup':function(){
define('Sage/UI/nls/af-za/SDataLookup',{});
},
'Sage/TaskPane/nls/af/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/af/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/af-za/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/af-za/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/af/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/af/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/af-za/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/af-za/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/af/LibraryDocument':function(){
define('Sage/Utility/File/nls/af/LibraryDocument',{});
},
'Sage/Utility/File/nls/af-za/LibraryDocument':function(){
define('Sage/Utility/File/nls/af-za/LibraryDocument',{});
},
'Sage/UI/nls/af/ConditionManager':function(){
define('Sage/UI/nls/af/ConditionManager',{});
},
'Sage/UI/nls/af-za/ConditionManager':function(){
define('Sage/UI/nls/af-za/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/af/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/af/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/af-za/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/af-za/WidgetDefinition',{});
},
'Sage/UI/nls/af/SearchConditionWidget':function(){
define('Sage/UI/nls/af/SearchConditionWidget',{});
},
'Sage/UI/nls/af-za/SearchConditionWidget':function(){
define('Sage/UI/nls/af-za/SearchConditionWidget',{});
},
'Sage/UI/nls/af/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/af/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/af-za/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/af-za/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/af/Name':function(){
define('Sage/UI/Controls/nls/af/Name',{});
},
'Sage/UI/Controls/nls/af-za/Name':function(){
define('Sage/UI/Controls/nls/af-za/Name',{});
},
'Sage/MainView/Lead/nls/af/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/af/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/af-za/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/af-za/UpdateLeads',{});
},
'Sage/UI/nls/af/ListPanel':function(){
define('Sage/UI/nls/af/ListPanel',{});
},
'Sage/UI/nls/af-za/ListPanel':function(){
define('Sage/UI/nls/af-za/ListPanel',{});
},
'Sage/UI/Filters/nls/af/EditFilters':function(){
define('Sage/UI/Filters/nls/af/EditFilters',{});
},
'Sage/UI/Filters/nls/af-za/EditFilters':function(){
define('Sage/UI/Filters/nls/af-za/EditFilters',{});
},
'Sage/UI/Controls/nls/af/DurationSelect':function(){
define('Sage/UI/Controls/nls/af/DurationSelect',{});
},
'Sage/UI/Controls/nls/af-za/DurationSelect':function(){
define('Sage/UI/Controls/nls/af-za/DurationSelect',{});
},
'Sage/UI/Alarms/nls/af/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/af/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/af-za/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/af-za/AlarmCountDown',{});
},
'Sage/UI/nls/af/AttachmentList':function(){
define('Sage/UI/nls/af/AttachmentList',{});
},
'Sage/UI/nls/af-za/AttachmentList':function(){
define('Sage/UI/nls/af-za/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/af/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/af/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/af-za/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/af-za/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/af/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/af/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/af-za/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/af-za/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/af/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/af/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/af-za/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/af-za/DashboardTabController',{});
},
'Sage/Groups/nls/af/GroupNavigator':function(){
define('Sage/Groups/nls/af/GroupNavigator',{});
},
'Sage/Groups/nls/af-za/GroupNavigator':function(){
define('Sage/Groups/nls/af-za/GroupNavigator',{});
},
'Sage/Utility/File/nls/af/AddURLAttachment':function(){
define('Sage/Utility/File/nls/af/AddURLAttachment',{});
},
'Sage/Utility/File/nls/af-za/AddURLAttachment':function(){
define('Sage/Utility/File/nls/af-za/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/af/EditFilterItems':function(){
define('Sage/UI/Filters/nls/af/EditFilterItems',{});
},
'Sage/UI/Filters/nls/af-za/EditFilterItems':function(){
define('Sage/UI/Filters/nls/af-za/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/af/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/EventListPanelConfig',{});
},
'Sage/UI/nls/af/ActivityScheduler':function(){
define('Sage/UI/nls/af/ActivityScheduler',{});
},
'Sage/UI/nls/af-za/ActivityScheduler':function(){
define('Sage/UI/nls/af-za/ActivityScheduler',{});
},
'Sage/MainView/nls/af/SecurityManager':function(){
define('Sage/MainView/nls/af/SecurityManager',{});
},
'Sage/MainView/nls/af-za/SecurityManager':function(){
define('Sage/MainView/nls/af-za/SecurityManager',{});
},
'Sage/TaskPane/nls/af/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/af/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/af-za/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/af-za/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/af/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/af/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/af/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/af/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/af-za/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/af-za/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/af/HelpMenu':function(){
define('Sage/UI/Controls/nls/af/HelpMenu',{});
},
'Sage/UI/Controls/nls/af-za/HelpMenu':function(){
define('Sage/UI/Controls/nls/af-za/HelpMenu',{});
},
'Sage/TaskPane/nls/af/UserTasklet':function(){
define('Sage/TaskPane/nls/af/UserTasklet',{});
},
'Sage/TaskPane/nls/af-za/UserTasklet':function(){
define('Sage/TaskPane/nls/af-za/UserTasklet',{});
},
'Sage/UI/Alarms/nls/af/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/af/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/af-za/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/af-za/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/af/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/af/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/af-za/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/af-za/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/af/MenuHelper':function(){
define('Sage/MailMerge/nls/af/MenuHelper',{});
},
'Sage/MailMerge/nls/af-za/MenuHelper':function(){
define('Sage/MailMerge/nls/af-za/MenuHelper',{});
},
'Sage/UI/nls/af/SearchMenuItem':function(){
define('Sage/UI/nls/af/SearchMenuItem',{});
},
'Sage/UI/nls/af-za/SearchMenuItem':function(){
define('Sage/UI/nls/af-za/SearchMenuItem',{});
},
'Sage/UI/nls/af/NotesHistoryList':function(){
define('Sage/UI/nls/af/NotesHistoryList',{});
},
'Sage/UI/nls/af-za/NotesHistoryList':function(){
define('Sage/UI/nls/af-za/NotesHistoryList',{});
},
'Sage/Utility/File/nls/af/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/af/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/af-za/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/af-za/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/af/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/HistoryEditor',{});
},
'Sage/Groups/nls/af/GroupManager':function(){
define('Sage/Groups/nls/af/GroupManager',{});
},
'Sage/Groups/nls/af-za/GroupManager':function(){
define('Sage/Groups/nls/af-za/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/af/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/af/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/af/UnconfirmedAlarm',{});
},
'Sage/UI/Alarms/nls/af-za/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/af-za/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/af/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/af/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/af-za/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/af-za/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/af/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/af/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/af-za/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/af-za/AccountingTasksTasklet',{});
},
'Sage/UI/nls/af/EditableGrid':function(){
define('Sage/UI/nls/af/EditableGrid',{});
},
'Sage/UI/nls/af-za/EditableGrid':function(){
define('Sage/UI/nls/af-za/EditableGrid',{});
},
'Sage/UI/nls/af/SpeedSearch':function(){
define('Sage/UI/nls/af/SpeedSearch',{});
},
'Sage/UI/nls/af-za/SpeedSearch':function(){
define('Sage/UI/nls/af-za/SpeedSearch',{});
},
'Sage/UI/nls/af/SLXPreviewGrid':function(){
define('Sage/UI/nls/af/SLXPreviewGrid',{});
},
'Sage/UI/nls/af-za/SLXPreviewGrid':function(){
define('Sage/UI/nls/af-za/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/af/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/af/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/af-za/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/af-za/UnconfirmedPane',{});
},
'Sage/Utility/nls/af/Utility':function(){
define('Sage/Utility/nls/af/Utility',{});
},
'Sage/Utility/nls/af-za/Utility':function(){
define('Sage/Utility/nls/af-za/Utility',{});
},
'Sage/UI/Controls/nls/af/Address':function(){
define('Sage/UI/Controls/nls/af/Address',{});
},
'Sage/UI/Controls/nls/af-za/Address':function(){
define('Sage/UI/Controls/nls/af-za/Address',{});
},
'Sage/MainView/ActivityMgr/nls/af/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/BaseListPanelConfig',{});
},
'Sage/UI/nls/af/UserType':function(){
define('Sage/UI/nls/af/UserType',{});
},
'Sage/UI/nls/af-za/UserType':function(){
define('Sage/UI/nls/af-za/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/af/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/af/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/af/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/af/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/af-za/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/af-za/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/af/ActivityList':function(){
define('Sage/UI/nls/af/ActivityList',{});
},
'Sage/UI/nls/af-za/ActivityList':function(){
define('Sage/UI/nls/af-za/ActivityList',{});
},
'Sage/UI/nls/af/CalendarUsersListPane':function(){
define('Sage/UI/nls/af/CalendarUsersListPane',{});
},
'Sage/UI/nls/af-za/CalendarUsersListPane':function(){
define('Sage/UI/nls/af-za/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/af/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/af/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/af/Attachment':function(){
define('Sage/Utility/File/nls/af/Attachment',{});
},
'Sage/Utility/File/nls/af-za/Attachment':function(){
define('Sage/Utility/File/nls/af-za/Attachment',{});
},
'Sage/MailMerge/nls/af/Helper':function(){
define('Sage/MailMerge/nls/af/Helper',{});
},
'Sage/MailMerge/nls/af-za/Helper':function(){
define('Sage/MailMerge/nls/af-za/Helper',{});
},
'Sage/UI/Dashboard/nls/af/Dashboard':function(){
define('Sage/UI/Dashboard/nls/af/Dashboard',{});
},
'Sage/UI/Dashboard/nls/af-za/Dashboard':function(){
define('Sage/UI/Dashboard/nls/af-za/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/af/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/af/PickList':function(){
define('Sage/UI/Controls/nls/af/PickList',{});
},
'Sage/UI/Controls/nls/af-za/PickList':function(){
define('Sage/UI/Controls/nls/af-za/PickList',{});
},
'Sage/Utility/nls/af/Email':function(){
define('Sage/Utility/nls/af/Email',{});
},
'Sage/Utility/nls/af-za/Email':function(){
define('Sage/Utility/nls/af-za/Email',{});
},
'Sage/UI/nls/af/TimeZoneItem':function(){
define('Sage/UI/nls/af/TimeZoneItem',{});
},
'Sage/UI/nls/af-za/TimeZoneItem':function(){
define('Sage/UI/nls/af-za/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/af/SlxEdit':function(){
define('Sage/UI/Columns/nls/af/SlxEdit',{});
},
'Sage/UI/Columns/nls/af-za/SlxEdit':function(){
define('Sage/UI/Columns/nls/af-za/SlxEdit',{});
},
'Sage/UI/Controls/nls/af/LogOffButton':function(){
define('Sage/UI/Controls/nls/af/LogOffButton',{});
},
'Sage/UI/Controls/nls/af-za/LogOffButton':function(){
define('Sage/UI/Controls/nls/af-za/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/af/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af-za/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af-za/EditEventEditor',{});
},
'Sage/MailMerge/nls/af/Loader':function(){
define('Sage/MailMerge/nls/af/Loader',{});
},
'Sage/MailMerge/nls/af-za/Loader':function(){
define('Sage/MailMerge/nls/af-za/Loader',{});
},
'Sage/UI/Controls/nls/af/DateTimePicker':function(){
define('Sage/UI/Controls/nls/af/DateTimePicker',{});
},
'Sage/UI/Controls/nls/af-za/DateTimePicker':function(){
define('Sage/UI/Controls/nls/af-za/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/af/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/af/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/af-za/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/af-za/AlarmPopup',{});
},
'Sage/UI/Controls/nls/af/Lookup':function(){
define('Sage/UI/Controls/nls/af/Lookup',{});
},
'Sage/UI/Controls/nls/af-za/Lookup':function(){
define('Sage/UI/Controls/nls/af-za/Lookup',{});
},
'Sage/Utility/File/nls/af/DescriptionsForm':function(){
define('Sage/Utility/File/nls/af/DescriptionsForm',{});
},
'Sage/Utility/File/nls/af-za/DescriptionsForm':function(){
define('Sage/Utility/File/nls/af-za/DescriptionsForm',{});
},
'Sage/TaskPane/nls/af/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/af/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/af-za/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/af-za/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_af-za", [], 1);
