require({cache:{
'Sage/Utility/File/nls/uk/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/uk/FallbackFilePicker',{});
},
'Sage/UI/nls/uk/Boolean':function(){
define('Sage/UI/nls/uk/Boolean',{});
},
'Sage/Services/nls/uk/ActivityService':function(){
define('Sage/Services/nls/uk/ActivityService',{});
},
'Sage/UI/Controls/nls/uk/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/uk/CopyToClipboard',{});
},
'Sage/Utility/nls/uk/Activity':function(){
define('Sage/Utility/nls/uk/Activity',{});
},
'Sage/QuickForms/Design/nls/uk/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/uk/DesignPanel',{});
},
'Sage/UI/nls/uk/TimelessActivitiesPane':function(){
define('Sage/UI/nls/uk/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/uk/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/uk/ActivityEditor',{});
},
'Sage/MainView/nls/uk/ActivityManager':function(){
define('Sage/MainView/nls/uk/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/uk/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/_PropertyEditor',{});
},
'Sage/Services/nls/uk/ActivityActionProcessor':function(){
define('Sage/Services/nls/uk/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/uk/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/uk/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/uk/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/uk/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/uk/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/uk/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/uk/AlarmPane':function(){
define('Sage/UI/Alarms/nls/uk/AlarmPane',{});
},
'Sage/TaskPane/nls/uk/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/uk/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/uk/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/uk/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/uk/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/uk/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/uk/FilterPanel':function(){
define('Sage/UI/Filters/nls/uk/FilterPanel',{});
},
'Sage/TaskPane/nls/uk/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/uk/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/uk/OwnerType':function(){
define('Sage/UI/nls/uk/OwnerType',{});
},
'Sage/TaskPane/nls/uk/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/uk/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/uk/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/uk/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/uk/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/uk/InvoiceRTDV',{});
},
'Sage/UI/nls/uk/SDataLookup':function(){
define('Sage/UI/nls/uk/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/uk/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/RowDesigner',{});
},
'Sage/TaskPane/nls/uk/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/uk/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/uk/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/uk/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/uk/LibraryDocument':function(){
define('Sage/Utility/File/nls/uk/LibraryDocument',{});
},
'Sage/UI/nls/uk/ConditionManager':function(){
define('Sage/UI/nls/uk/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/uk/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/uk/WidgetDefinition',{});
},
'Sage/UI/nls/uk/SearchConditionWidget':function(){
define('Sage/UI/nls/uk/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/uk/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/uk/DataSourcePanel',{});
},
'Sage/UI/nls/uk/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/uk/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/uk/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/uk/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/uk/Name':function(){
define('Sage/UI/Controls/nls/uk/Name',{});
},
'Sage/QuickForms/Design/nls/uk/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/uk/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/uk/UpdateLeads',{});
},
'Sage/UI/nls/uk/ListPanel':function(){
define('Sage/UI/nls/uk/ListPanel',{});
},
'Sage/UI/Filters/nls/uk/EditFilters':function(){
define('Sage/UI/Filters/nls/uk/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/uk/DurationSelect':function(){
define('Sage/UI/Controls/nls/uk/DurationSelect',{});
},
'Sage/UI/Alarms/nls/uk/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/uk/AlarmCountDown',{});
},
'Sage/UI/nls/uk/AttachmentList':function(){
define('Sage/UI/nls/uk/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/uk/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/uk/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/uk/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/uk/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/uk/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/uk/Dialogs':function(){
define('Sage/UI/nls/uk/Dialogs',{});
},
'Sage/TaskPane/nls/uk/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/uk/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/uk/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/uk/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/uk/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/uk/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/uk/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/UserControlDesigner',{});
},
'Sage/Groups/nls/uk/GroupNavigator':function(){
define('Sage/Groups/nls/uk/GroupNavigator',{});
},
'Sage/Utility/File/nls/uk/AddURLAttachment':function(){
define('Sage/Utility/File/nls/uk/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/uk/EditFilterItems':function(){
define('Sage/UI/Filters/nls/uk/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/uk/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/uk/DesignSurface',{});
},
'Sage/Utility/File/nls/uk/DragDropWatcher':function(){
define('Sage/Utility/File/nls/uk/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/uk/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/uk/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/uk/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/uk/EventListPanelConfig',{});
},
'Sage/UI/nls/uk/ActivityScheduler':function(){
define('Sage/UI/nls/uk/ActivityScheduler',{});
},
'Sage/MainView/nls/uk/SecurityManager':function(){
define('Sage/MainView/nls/uk/SecurityManager',{});
},
'Sage/TaskPane/nls/uk/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/uk/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/uk/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/uk/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/uk/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/uk/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/uk/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/uk/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/uk/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/uk/HelpMenu':function(){
define('Sage/UI/Controls/nls/uk/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/uk/UserTasklet':function(){
define('Sage/TaskPane/nls/uk/UserTasklet',{});
},
'Sage/UI/Alarms/nls/uk/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/uk/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/uk/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/uk/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/uk/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/uk/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/uk/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/ColumnDesigner',{});
},
'Sage/UI/nls/uk/SearchMenuItem':function(){
define('Sage/UI/nls/uk/SearchMenuItem',{});
},
'Sage/UI/nls/uk/NotesHistoryList':function(){
define('Sage/UI/nls/uk/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/uk/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/uk/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/uk/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/uk/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/uk/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/uk/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/uk/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/uk/HistoryEditor',{});
},
'Sage/Groups/nls/uk/GroupManager':function(){
define('Sage/Groups/nls/uk/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/uk/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/uk/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/uk/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/uk/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/uk/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/uk/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/uk/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/uk/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/uk/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/uk/EditableGrid':function(){
define('Sage/UI/nls/uk/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/uk/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/uk/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/uk/SpeedSearch':function(){
define('Sage/UI/nls/uk/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/uk/SLXPreviewGrid':function(){
define('Sage/UI/nls/uk/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/uk/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/uk/UnconfirmedPane',{});
},
'Sage/Utility/nls/uk/Utility':function(){
define('Sage/Utility/nls/uk/Utility',{});
},
'Sage/QuickForms/Design/nls/uk/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/ControlDesigner',{});
},
'Sage/UI/Controls/nls/uk/Address':function(){
define('Sage/UI/Controls/nls/uk/Address',{});
},
'Sage/MainView/ActivityMgr/nls/uk/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/uk/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/uk/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/OwnerControlDesigner',{});
},
'Sage/UI/nls/uk/UserType':function(){
define('Sage/UI/nls/uk/UserType',{});
},
'Sage/QuickForms/Design/nls/uk/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/uk/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/uk/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/uk/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/uk/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/uk/ActivityList':function(){
define('Sage/UI/nls/uk/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/uk/CalendarUsersListPane':function(){
define('Sage/UI/nls/uk/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/uk/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/uk/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/uk/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/uk/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/uk/Attachment':function(){
define('Sage/Utility/File/nls/uk/Attachment',{});
},
'Sage/QuickForms/Design/nls/uk/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/uk/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/uk/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/uk/Helper':function(){
define('Sage/MailMerge/nls/uk/Helper',{});
},
'Sage/UI/Dashboard/nls/uk/Dashboard':function(){
define('Sage/UI/Dashboard/nls/uk/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/uk/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/uk/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/uk/PickList':function(){
define('Sage/UI/Controls/nls/uk/PickList',{});
},
'Sage/Utility/nls/uk/Email':function(){
define('Sage/Utility/nls/uk/Email',{});
},
'Sage/TaskPane/nls/uk/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/uk/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/uk/TimeZoneItem':function(){
define('Sage/UI/nls/uk/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/uk/SlxEdit':function(){
define('Sage/UI/Columns/nls/uk/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/uk/LogOffButton':function(){
define('Sage/UI/Controls/nls/uk/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/uk/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/uk/EditEventEditor',{});
},
'Sage/MailMerge/nls/uk/Loader':function(){
define('Sage/MailMerge/nls/uk/Loader',{});
},
'Sage/UI/Controls/nls/uk/DateTimePicker':function(){
define('Sage/UI/Controls/nls/uk/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/uk/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/uk/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/uk/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/uk/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/uk/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/uk/Lookup':function(){
define('Sage/UI/Controls/nls/uk/Lookup',{});
},
'Sage/Utility/File/nls/uk/DescriptionsForm':function(){
define('Sage/Utility/File/nls/uk/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/uk/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/uk/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/uk/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/uk/CommonTasksTasklet',{});
},
'Sage/Utility/nls/uk/Dashboard':function(){
define('Sage/Utility/nls/uk/Dashboard',{});
}}});
define("Sage/nls/Sage_uk", [], 1);
