require({cache:{
'Sage/Utility/File/nls/fa/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/fa/FallbackFilePicker',{});
},
'Sage/UI/nls/fa/Boolean':function(){
define('Sage/UI/nls/fa/Boolean',{});
},
'Sage/Services/nls/fa/ActivityService':function(){
define('Sage/Services/nls/fa/ActivityService',{});
},
'Sage/UI/Controls/nls/fa/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/fa/CopyToClipboard',{});
},
'Sage/Utility/nls/fa/Activity':function(){
define('Sage/Utility/nls/fa/Activity',{});
},
'Sage/QuickForms/Design/nls/fa/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/fa/DesignPanel',{});
},
'Sage/UI/nls/fa/TimelessActivitiesPane':function(){
define('Sage/UI/nls/fa/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/fa/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fa/ActivityEditor',{});
},
'Sage/MainView/nls/fa/ActivityManager':function(){
define('Sage/MainView/nls/fa/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/fa/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/_PropertyEditor',{});
},
'Sage/Services/nls/fa/ActivityActionProcessor':function(){
define('Sage/Services/nls/fa/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/fa/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fa/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/fa/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/fa/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/fa/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/fa/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/fa/AlarmPane':function(){
define('Sage/UI/Alarms/nls/fa/AlarmPane',{});
},
'Sage/TaskPane/nls/fa/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/fa/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/fa/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/fa/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/fa/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/fa/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/fa/FilterPanel':function(){
define('Sage/UI/Filters/nls/fa/FilterPanel',{});
},
'Sage/TaskPane/nls/fa/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/fa/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/fa/OwnerType':function(){
define('Sage/UI/nls/fa/OwnerType',{});
},
'Sage/TaskPane/nls/fa/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/fa/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/fa/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/fa/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/fa/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/fa/InvoiceRTDV',{});
},
'Sage/UI/nls/fa/SDataLookup':function(){
define('Sage/UI/nls/fa/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/fa/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/RowDesigner',{});
},
'Sage/TaskPane/nls/fa/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/fa/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/fa/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/fa/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/fa/LibraryDocument':function(){
define('Sage/Utility/File/nls/fa/LibraryDocument',{});
},
'Sage/UI/nls/fa/ConditionManager':function(){
define('Sage/UI/nls/fa/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/fa/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/fa/WidgetDefinition',{});
},
'Sage/UI/nls/fa/SearchConditionWidget':function(){
define('Sage/UI/nls/fa/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/fa/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/fa/DataSourcePanel',{});
},
'Sage/UI/nls/fa/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/fa/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/fa/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/fa/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/fa/Name':function(){
define('Sage/UI/Controls/nls/fa/Name',{});
},
'Sage/QuickForms/Design/nls/fa/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/fa/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/fa/UpdateLeads',{});
},
'Sage/UI/nls/fa/ListPanel':function(){
define('Sage/UI/nls/fa/ListPanel',{});
},
'Sage/UI/Filters/nls/fa/EditFilters':function(){
define('Sage/UI/Filters/nls/fa/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/fa/DurationSelect':function(){
define('Sage/UI/Controls/nls/fa/DurationSelect',{});
},
'Sage/UI/Alarms/nls/fa/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/fa/AlarmCountDown',{});
},
'Sage/UI/nls/fa/AttachmentList':function(){
define('Sage/UI/nls/fa/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/fa/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fa/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fa/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/fa/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/fa/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/fa/Dialogs':function(){
define('Sage/UI/nls/fa/Dialogs',{});
},
'Sage/TaskPane/nls/fa/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/fa/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/fa/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/fa/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/fa/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/fa/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/fa/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/UserControlDesigner',{});
},
'Sage/Groups/nls/fa/GroupNavigator':function(){
define('Sage/Groups/nls/fa/GroupNavigator',{});
},
'Sage/Utility/File/nls/fa/AddURLAttachment':function(){
define('Sage/Utility/File/nls/fa/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/fa/EditFilterItems':function(){
define('Sage/UI/Filters/nls/fa/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/fa/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/fa/DesignSurface',{});
},
'Sage/Utility/File/nls/fa/DragDropWatcher':function(){
define('Sage/Utility/File/nls/fa/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/fa/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fa/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/fa/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fa/EventListPanelConfig',{});
},
'Sage/UI/nls/fa/ActivityScheduler':function(){
define('Sage/UI/nls/fa/ActivityScheduler',{});
},
'Sage/MainView/nls/fa/SecurityManager':function(){
define('Sage/MainView/nls/fa/SecurityManager',{});
},
'Sage/TaskPane/nls/fa/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/fa/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/fa/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/fa/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/fa/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/fa/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/fa/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/fa/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/fa/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/fa/HelpMenu':function(){
define('Sage/UI/Controls/nls/fa/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/fa/UserTasklet':function(){
define('Sage/TaskPane/nls/fa/UserTasklet',{});
},
'Sage/UI/Alarms/nls/fa/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/fa/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/fa/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/fa/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/fa/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/fa/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/fa/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/ColumnDesigner',{});
},
'Sage/UI/nls/fa/SearchMenuItem':function(){
define('Sage/UI/nls/fa/SearchMenuItem',{});
},
'Sage/UI/nls/fa/NotesHistoryList':function(){
define('Sage/UI/nls/fa/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/fa/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/fa/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/fa/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/fa/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/fa/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fa/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/fa/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fa/HistoryEditor',{});
},
'Sage/Groups/nls/fa/GroupManager':function(){
define('Sage/Groups/nls/fa/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/fa/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fa/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/fa/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fa/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fa/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/fa/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/fa/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/fa/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/fa/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/fa/EditableGrid':function(){
define('Sage/UI/nls/fa/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/fa/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/fa/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/fa/SpeedSearch':function(){
define('Sage/UI/nls/fa/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/fa/SLXPreviewGrid':function(){
define('Sage/UI/nls/fa/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/fa/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/fa/UnconfirmedPane',{});
},
'Sage/Utility/nls/fa/Utility':function(){
define('Sage/Utility/nls/fa/Utility',{});
},
'Sage/QuickForms/Design/nls/fa/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/ControlDesigner',{});
},
'Sage/UI/Controls/nls/fa/Address':function(){
define('Sage/UI/Controls/nls/fa/Address',{});
},
'Sage/MainView/ActivityMgr/nls/fa/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fa/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/fa/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/OwnerControlDesigner',{});
},
'Sage/UI/nls/fa/UserType':function(){
define('Sage/UI/nls/fa/UserType',{});
},
'Sage/QuickForms/Design/nls/fa/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/fa/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/fa/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/fa/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/fa/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/fa/ActivityList':function(){
define('Sage/UI/nls/fa/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/fa/CalendarUsersListPane':function(){
define('Sage/UI/nls/fa/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/fa/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/fa/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/fa/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/fa/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/fa/Attachment':function(){
define('Sage/Utility/File/nls/fa/Attachment',{});
},
'Sage/QuickForms/Design/nls/fa/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fa/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/fa/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/fa/Helper':function(){
define('Sage/MailMerge/nls/fa/Helper',{});
},
'Sage/UI/Dashboard/nls/fa/Dashboard':function(){
define('Sage/UI/Dashboard/nls/fa/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/fa/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/fa/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/fa/PickList':function(){
define('Sage/UI/Controls/nls/fa/PickList',{});
},
'Sage/Utility/nls/fa/Email':function(){
define('Sage/Utility/nls/fa/Email',{});
},
'Sage/TaskPane/nls/fa/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/fa/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/fa/TimeZoneItem':function(){
define('Sage/UI/nls/fa/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/fa/SlxEdit':function(){
define('Sage/UI/Columns/nls/fa/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/fa/LogOffButton':function(){
define('Sage/UI/Controls/nls/fa/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/fa/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/fa/EditEventEditor',{});
},
'Sage/MailMerge/nls/fa/Loader':function(){
define('Sage/MailMerge/nls/fa/Loader',{});
},
'Sage/UI/Controls/nls/fa/DateTimePicker':function(){
define('Sage/UI/Controls/nls/fa/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/fa/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/fa/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/fa/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/fa/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/fa/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/fa/Lookup':function(){
define('Sage/UI/Controls/nls/fa/Lookup',{});
},
'Sage/Utility/File/nls/fa/DescriptionsForm':function(){
define('Sage/Utility/File/nls/fa/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/fa/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/fa/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/fa/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/fa/CommonTasksTasklet',{});
},
'Sage/Utility/nls/fa/Dashboard':function(){
define('Sage/Utility/nls/fa/Dashboard',{});
}}});
define("Sage/nls/Sage_fa", [], 1);
