require({cache:{
'Sage/Utility/File/nls/ro/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ro/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/ro-mo/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ro-mo/FallbackFilePicker',{});
},
'Sage/UI/nls/ro/Boolean':function(){
define('Sage/UI/nls/ro/Boolean',{});
},
'Sage/UI/nls/ro-mo/Boolean':function(){
define('Sage/UI/nls/ro-mo/Boolean',{});
},
'Sage/UI/Controls/nls/ro/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ro/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/ro-mo/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ro-mo/CopyToClipboard',{});
},
'Sage/Services/nls/ro/ActivityService':function(){
define('Sage/Services/nls/ro/ActivityService',{});
},
'Sage/Services/nls/ro-mo/ActivityService':function(){
define('Sage/Services/nls/ro-mo/ActivityService',{});
},
'Sage/Utility/nls/ro/Activity':function(){
define('Sage/Utility/nls/ro/Activity',{});
},
'Sage/Utility/nls/ro-mo/Activity':function(){
define('Sage/Utility/nls/ro-mo/Activity',{});
},
'Sage/UI/nls/ro/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ro/TimelessActivitiesPane',{});
},
'Sage/UI/nls/ro-mo/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ro-mo/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/ActivityEditor',{});
},
'Sage/MainView/nls/ro/ActivityManager':function(){
define('Sage/MainView/nls/ro/ActivityManager',{});
},
'Sage/MainView/nls/ro-mo/ActivityManager':function(){
define('Sage/MainView/nls/ro-mo/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/ro/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/ro/Service':function(){
define('Sage/Reporting/nls/ro/Service',{});
},
'Sage/Reporting/nls/ro-mo/Service':function(){
define('Sage/Reporting/nls/ro-mo/Service',{});
},
'Sage/Utility/File/nls/ro/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ro/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ro-mo/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ro-mo/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ro/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ro/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/ro-mo/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ro-mo/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ro/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ro/AlarmPane',{});
},
'Sage/UI/Alarms/nls/ro-mo/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ro-mo/AlarmPane',{});
},
'Sage/TaskPane/nls/ro/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ro/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/ro-mo/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ro-mo/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ro/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ro/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/ro-mo/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ro-mo/DashboardWidget',{});
},
'Sage/UI/Filters/nls/ro/FilterPanel':function(){
define('Sage/UI/Filters/nls/ro/FilterPanel',{});
},
'Sage/UI/Filters/nls/ro-mo/FilterPanel':function(){
define('Sage/UI/Filters/nls/ro-mo/FilterPanel',{});
},
'Sage/TaskPane/nls/ro/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ro/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/ro/OwnerType':function(){
define('Sage/UI/nls/ro/OwnerType',{});
},
'Sage/UI/nls/ro-mo/OwnerType':function(){
define('Sage/UI/nls/ro-mo/OwnerType',{});
},
'Sage/TaskPane/nls/ro/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/LeadTasksTasklet',{});
},
'Sage/UI/nls/ro/SDataLookup':function(){
define('Sage/UI/nls/ro/SDataLookup',{});
},
'Sage/UI/nls/ro-mo/SDataLookup':function(){
define('Sage/UI/nls/ro-mo/SDataLookup',{});
},
'Sage/TaskPane/nls/ro/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ro/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ro/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/ro-mo/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ro-mo/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ro/LibraryDocument':function(){
define('Sage/Utility/File/nls/ro/LibraryDocument',{});
},
'Sage/Utility/File/nls/ro-mo/LibraryDocument':function(){
define('Sage/Utility/File/nls/ro-mo/LibraryDocument',{});
},
'Sage/UI/nls/ro/ConditionManager':function(){
define('Sage/UI/nls/ro/ConditionManager',{});
},
'Sage/UI/nls/ro-mo/ConditionManager':function(){
define('Sage/UI/nls/ro-mo/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ro/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ro/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/ro-mo/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ro-mo/WidgetDefinition',{});
},
'Sage/UI/nls/ro/SearchConditionWidget':function(){
define('Sage/UI/nls/ro/SearchConditionWidget',{});
},
'Sage/UI/nls/ro-mo/SearchConditionWidget':function(){
define('Sage/UI/nls/ro-mo/SearchConditionWidget',{});
},
'Sage/UI/nls/ro/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ro/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/ro-mo/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ro-mo/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/ro/Name':function(){
define('Sage/UI/Controls/nls/ro/Name',{});
},
'Sage/UI/Controls/nls/ro-mo/Name':function(){
define('Sage/UI/Controls/nls/ro-mo/Name',{});
},
'Sage/MainView/Lead/nls/ro/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ro/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/ro-mo/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ro-mo/UpdateLeads',{});
},
'Sage/UI/nls/ro/ListPanel':function(){
define('Sage/UI/nls/ro/ListPanel',{});
},
'Sage/UI/nls/ro-mo/ListPanel':function(){
define('Sage/UI/nls/ro-mo/ListPanel',{});
},
'Sage/UI/Filters/nls/ro/EditFilters':function(){
define('Sage/UI/Filters/nls/ro/EditFilters',{});
},
'Sage/UI/Filters/nls/ro-mo/EditFilters':function(){
define('Sage/UI/Filters/nls/ro-mo/EditFilters',{});
},
'Sage/UI/Controls/nls/ro/DurationSelect':function(){
define('Sage/UI/Controls/nls/ro/DurationSelect',{});
},
'Sage/UI/Controls/nls/ro-mo/DurationSelect':function(){
define('Sage/UI/Controls/nls/ro-mo/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ro/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ro/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/ro-mo/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ro-mo/AlarmCountDown',{});
},
'Sage/UI/nls/ro/AttachmentList':function(){
define('Sage/UI/nls/ro/AttachmentList',{});
},
'Sage/UI/nls/ro-mo/AttachmentList':function(){
define('Sage/UI/nls/ro-mo/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/ro/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ro/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/ro-mo/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ro-mo/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/ro/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ro/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ro/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ro/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/ro-mo/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ro-mo/DashboardTabController',{});
},
'Sage/Groups/nls/ro/GroupNavigator':function(){
define('Sage/Groups/nls/ro/GroupNavigator',{});
},
'Sage/Groups/nls/ro-mo/GroupNavigator':function(){
define('Sage/Groups/nls/ro-mo/GroupNavigator',{});
},
'Sage/Utility/File/nls/ro/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ro/AddURLAttachment',{});
},
'Sage/Utility/File/nls/ro-mo/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ro-mo/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ro/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ro/EditFilterItems',{});
},
'Sage/UI/Filters/nls/ro-mo/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ro-mo/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/EventListPanelConfig',{});
},
'Sage/UI/nls/ro/ActivityScheduler':function(){
define('Sage/UI/nls/ro/ActivityScheduler',{});
},
'Sage/UI/nls/ro-mo/ActivityScheduler':function(){
define('Sage/UI/nls/ro-mo/ActivityScheduler',{});
},
'Sage/MainView/nls/ro/SecurityManager':function(){
define('Sage/MainView/nls/ro/SecurityManager',{});
},
'Sage/MainView/nls/ro-mo/SecurityManager':function(){
define('Sage/MainView/nls/ro-mo/SecurityManager',{});
},
'Sage/TaskPane/nls/ro/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ro/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/ro-mo/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ro-mo/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/ro/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ro/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/ro-mo/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ro-mo/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/ro/HelpMenu':function(){
define('Sage/UI/Controls/nls/ro/HelpMenu',{});
},
'Sage/UI/Controls/nls/ro-mo/HelpMenu':function(){
define('Sage/UI/Controls/nls/ro-mo/HelpMenu',{});
},
'Sage/TaskPane/nls/ro/UserTasklet':function(){
define('Sage/TaskPane/nls/ro/UserTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/UserTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ro/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ro/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/ro-mo/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ro-mo/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ro/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ro/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/ro-mo/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ro-mo/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/ro/MenuHelper':function(){
define('Sage/MailMerge/nls/ro/MenuHelper',{});
},
'Sage/MailMerge/nls/ro-mo/MenuHelper':function(){
define('Sage/MailMerge/nls/ro-mo/MenuHelper',{});
},
'Sage/UI/nls/ro/SearchMenuItem':function(){
define('Sage/UI/nls/ro/SearchMenuItem',{});
},
'Sage/UI/nls/ro-mo/SearchMenuItem':function(){
define('Sage/UI/nls/ro-mo/SearchMenuItem',{});
},
'Sage/UI/nls/ro/NotesHistoryList':function(){
define('Sage/UI/nls/ro/NotesHistoryList',{});
},
'Sage/UI/nls/ro-mo/NotesHistoryList':function(){
define('Sage/UI/nls/ro-mo/NotesHistoryList',{});
},
'Sage/Utility/File/nls/ro/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ro/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/ro-mo/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ro-mo/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/ro/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/HistoryEditor',{});
},
'Sage/Groups/nls/ro/GroupManager':function(){
define('Sage/Groups/nls/ro/GroupManager',{});
},
'Sage/Groups/nls/ro-mo/GroupManager':function(){
define('Sage/Groups/nls/ro-mo/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/ro/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/ro/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/ro/UnconfirmedAlarm',{});
},
'Sage/UI/Alarms/nls/ro-mo/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/ro-mo/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/ro/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ro/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/ro-mo/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ro-mo/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/ro/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/AccountingTasksTasklet',{});
},
'Sage/UI/nls/ro/EditableGrid':function(){
define('Sage/UI/nls/ro/EditableGrid',{});
},
'Sage/UI/nls/ro-mo/EditableGrid':function(){
define('Sage/UI/nls/ro-mo/EditableGrid',{});
},
'Sage/UI/nls/ro/SpeedSearch':function(){
define('Sage/UI/nls/ro/SpeedSearch',{});
},
'Sage/UI/nls/ro-mo/SpeedSearch':function(){
define('Sage/UI/nls/ro-mo/SpeedSearch',{});
},
'Sage/UI/nls/ro/SLXPreviewGrid':function(){
define('Sage/UI/nls/ro/SLXPreviewGrid',{});
},
'Sage/UI/nls/ro-mo/SLXPreviewGrid':function(){
define('Sage/UI/nls/ro-mo/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ro/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ro/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/ro-mo/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ro-mo/UnconfirmedPane',{});
},
'Sage/Utility/nls/ro/Utility':function(){
define('Sage/Utility/nls/ro/Utility',{});
},
'Sage/Utility/nls/ro-mo/Utility':function(){
define('Sage/Utility/nls/ro-mo/Utility',{});
},
'Sage/UI/Controls/nls/ro/Address':function(){
define('Sage/UI/Controls/nls/ro/Address',{});
},
'Sage/UI/Controls/nls/ro-mo/Address':function(){
define('Sage/UI/Controls/nls/ro-mo/Address',{});
},
'Sage/MainView/ActivityMgr/nls/ro/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/BaseListPanelConfig',{});
},
'Sage/UI/nls/ro/UserType':function(){
define('Sage/UI/nls/ro/UserType',{});
},
'Sage/UI/nls/ro-mo/UserType':function(){
define('Sage/UI/nls/ro-mo/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/ro/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ro/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/ro-mo/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ro-mo/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/ro/ActivityList':function(){
define('Sage/UI/nls/ro/ActivityList',{});
},
'Sage/UI/nls/ro-mo/ActivityList':function(){
define('Sage/UI/nls/ro-mo/ActivityList',{});
},
'Sage/UI/nls/ro/CalendarUsersListPane':function(){
define('Sage/UI/nls/ro/CalendarUsersListPane',{});
},
'Sage/UI/nls/ro-mo/CalendarUsersListPane':function(){
define('Sage/UI/nls/ro-mo/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/ro/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ro/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ro/Attachment':function(){
define('Sage/Utility/File/nls/ro/Attachment',{});
},
'Sage/Utility/File/nls/ro-mo/Attachment':function(){
define('Sage/Utility/File/nls/ro-mo/Attachment',{});
},
'Sage/MailMerge/nls/ro/Helper':function(){
define('Sage/MailMerge/nls/ro/Helper',{});
},
'Sage/MailMerge/nls/ro-mo/Helper':function(){
define('Sage/MailMerge/nls/ro-mo/Helper',{});
},
'Sage/UI/Dashboard/nls/ro/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ro/Dashboard',{});
},
'Sage/UI/Dashboard/nls/ro-mo/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ro-mo/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ro/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ro/PickList':function(){
define('Sage/UI/Controls/nls/ro/PickList',{});
},
'Sage/UI/Controls/nls/ro-mo/PickList':function(){
define('Sage/UI/Controls/nls/ro-mo/PickList',{});
},
'Sage/Utility/nls/ro/Email':function(){
define('Sage/Utility/nls/ro/Email',{});
},
'Sage/Utility/nls/ro-mo/Email':function(){
define('Sage/Utility/nls/ro-mo/Email',{});
},
'Sage/UI/nls/ro/TimeZoneItem':function(){
define('Sage/UI/nls/ro/TimeZoneItem',{});
},
'Sage/UI/nls/ro-mo/TimeZoneItem':function(){
define('Sage/UI/nls/ro-mo/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ro/SlxEdit':function(){
define('Sage/UI/Columns/nls/ro/SlxEdit',{});
},
'Sage/UI/Columns/nls/ro-mo/SlxEdit':function(){
define('Sage/UI/Columns/nls/ro-mo/SlxEdit',{});
},
'Sage/UI/Controls/nls/ro/LogOffButton':function(){
define('Sage/UI/Controls/nls/ro/LogOffButton',{});
},
'Sage/UI/Controls/nls/ro-mo/LogOffButton':function(){
define('Sage/UI/Controls/nls/ro-mo/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/ro/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ro-mo/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ro-mo/EditEventEditor',{});
},
'Sage/MailMerge/nls/ro/Loader':function(){
define('Sage/MailMerge/nls/ro/Loader',{});
},
'Sage/MailMerge/nls/ro-mo/Loader':function(){
define('Sage/MailMerge/nls/ro-mo/Loader',{});
},
'Sage/UI/Controls/nls/ro/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ro/DateTimePicker',{});
},
'Sage/UI/Controls/nls/ro-mo/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ro-mo/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/ro/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ro/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/ro-mo/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ro-mo/AlarmPopup',{});
},
'Sage/UI/Controls/nls/ro/Lookup':function(){
define('Sage/UI/Controls/nls/ro/Lookup',{});
},
'Sage/UI/Controls/nls/ro-mo/Lookup':function(){
define('Sage/UI/Controls/nls/ro-mo/Lookup',{});
},
'Sage/Utility/File/nls/ro/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ro/DescriptionsForm',{});
},
'Sage/Utility/File/nls/ro-mo/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ro-mo/DescriptionsForm',{});
},
'Sage/TaskPane/nls/ro/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ro/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/ro-mo/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ro-mo/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_ro-mo", [], 1);
