require({cache:{
'Sage/Utility/File/nls/sz/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/sz/FallbackFilePicker',{});
},
'Sage/UI/nls/sz/Boolean':function(){
define('Sage/UI/nls/sz/Boolean',{});
},
'Sage/UI/Controls/nls/sz/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/sz/CopyToClipboard',{});
},
'Sage/Services/nls/sz/ActivityService':function(){
define('Sage/Services/nls/sz/ActivityService',{});
},
'Sage/Utility/nls/sz/Activity':function(){
define('Sage/Utility/nls/sz/Activity',{});
},
'Sage/UI/nls/sz/TimelessActivitiesPane':function(){
define('Sage/UI/nls/sz/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/sz/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sz/ActivityEditor',{});
},
'Sage/MainView/nls/sz/ActivityManager':function(){
define('Sage/MainView/nls/sz/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/sz/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sz/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/sz/Service':function(){
define('Sage/Reporting/nls/sz/Service',{});
},
'Sage/Utility/File/nls/sz/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/sz/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/sz/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/sz/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/sz/AlarmPane':function(){
define('Sage/UI/Alarms/nls/sz/AlarmPane',{});
},
'Sage/TaskPane/nls/sz/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/sz/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/sz/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/sz/DashboardWidget',{});
},
'Sage/UI/Filters/nls/sz/FilterPanel':function(){
define('Sage/UI/Filters/nls/sz/FilterPanel',{});
},
'Sage/TaskPane/nls/sz/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/sz/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/sz/OwnerType':function(){
define('Sage/UI/nls/sz/OwnerType',{});
},
'Sage/TaskPane/nls/sz/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/sz/LeadTasksTasklet',{});
},
'Sage/UI/nls/sz/SDataLookup':function(){
define('Sage/UI/nls/sz/SDataLookup',{});
},
'Sage/TaskPane/nls/sz/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/sz/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/sz/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/sz/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/sz/LibraryDocument':function(){
define('Sage/Utility/File/nls/sz/LibraryDocument',{});
},
'Sage/UI/nls/sz/ConditionManager':function(){
define('Sage/UI/nls/sz/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/sz/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/sz/WidgetDefinition',{});
},
'Sage/UI/nls/sz/SearchConditionWidget':function(){
define('Sage/UI/nls/sz/SearchConditionWidget',{});
},
'Sage/UI/nls/sz/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/sz/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/sz/Name':function(){
define('Sage/UI/Controls/nls/sz/Name',{});
},
'Sage/MainView/Lead/nls/sz/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/sz/UpdateLeads',{});
},
'Sage/UI/nls/sz/ListPanel':function(){
define('Sage/UI/nls/sz/ListPanel',{});
},
'Sage/UI/Filters/nls/sz/EditFilters':function(){
define('Sage/UI/Filters/nls/sz/EditFilters',{});
},
'Sage/UI/Controls/nls/sz/DurationSelect':function(){
define('Sage/UI/Controls/nls/sz/DurationSelect',{});
},
'Sage/UI/Alarms/nls/sz/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/sz/AlarmCountDown',{});
},
'Sage/UI/nls/sz/AttachmentList':function(){
define('Sage/UI/nls/sz/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/sz/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/sz/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/sz/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/sz/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/sz/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/sz/DashboardTabController',{});
},
'Sage/Groups/nls/sz/GroupNavigator':function(){
define('Sage/Groups/nls/sz/GroupNavigator',{});
},
'Sage/Utility/File/nls/sz/AddURLAttachment':function(){
define('Sage/Utility/File/nls/sz/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/sz/EditFilterItems':function(){
define('Sage/UI/Filters/nls/sz/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/sz/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sz/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sz/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sz/EventListPanelConfig',{});
},
'Sage/UI/nls/sz/ActivityScheduler':function(){
define('Sage/UI/nls/sz/ActivityScheduler',{});
},
'Sage/MainView/nls/sz/SecurityManager':function(){
define('Sage/MainView/nls/sz/SecurityManager',{});
},
'Sage/TaskPane/nls/sz/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/sz/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/sz/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/sz/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/sz/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/sz/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/sz/HelpMenu':function(){
define('Sage/UI/Controls/nls/sz/HelpMenu',{});
},
'Sage/TaskPane/nls/sz/UserTasklet':function(){
define('Sage/TaskPane/nls/sz/UserTasklet',{});
},
'Sage/UI/Alarms/nls/sz/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/sz/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/sz/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/sz/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/sz/MenuHelper':function(){
define('Sage/MailMerge/nls/sz/MenuHelper',{});
},
'Sage/UI/nls/sz/SearchMenuItem':function(){
define('Sage/UI/nls/sz/SearchMenuItem',{});
},
'Sage/UI/nls/sz/NotesHistoryList':function(){
define('Sage/UI/nls/sz/NotesHistoryList',{});
},
'Sage/Utility/File/nls/sz/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/sz/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/sz/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sz/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sz/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sz/HistoryEditor',{});
},
'Sage/Groups/nls/sz/GroupManager':function(){
define('Sage/Groups/nls/sz/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/sz/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sz/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/sz/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/sz/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/sz/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/sz/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/sz/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/sz/AccountingTasksTasklet',{});
},
'Sage/UI/nls/sz/EditableGrid':function(){
define('Sage/UI/nls/sz/EditableGrid',{});
},
'Sage/UI/nls/sz/SpeedSearch':function(){
define('Sage/UI/nls/sz/SpeedSearch',{});
},
'Sage/UI/nls/sz/SLXPreviewGrid':function(){
define('Sage/UI/nls/sz/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/sz/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/sz/UnconfirmedPane',{});
},
'Sage/Utility/nls/sz/Utility':function(){
define('Sage/Utility/nls/sz/Utility',{});
},
'Sage/UI/Controls/nls/sz/Address':function(){
define('Sage/UI/Controls/nls/sz/Address',{});
},
'Sage/MainView/ActivityMgr/nls/sz/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sz/BaseListPanelConfig',{});
},
'Sage/UI/nls/sz/UserType':function(){
define('Sage/UI/nls/sz/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/sz/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/sz/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/sz/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/sz/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/sz/ActivityList':function(){
define('Sage/UI/nls/sz/ActivityList',{});
},
'Sage/UI/nls/sz/CalendarUsersListPane':function(){
define('Sage/UI/nls/sz/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/sz/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/sz/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/sz/Attachment':function(){
define('Sage/Utility/File/nls/sz/Attachment',{});
},
'Sage/MailMerge/nls/sz/Helper':function(){
define('Sage/MailMerge/nls/sz/Helper',{});
},
'Sage/UI/Dashboard/nls/sz/Dashboard':function(){
define('Sage/UI/Dashboard/nls/sz/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/sz/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sz/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/sz/PickList':function(){
define('Sage/UI/Controls/nls/sz/PickList',{});
},
'Sage/Utility/nls/sz/Email':function(){
define('Sage/Utility/nls/sz/Email',{});
},
'Sage/UI/nls/sz/TimeZoneItem':function(){
define('Sage/UI/nls/sz/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/sz/SlxEdit':function(){
define('Sage/UI/Columns/nls/sz/SlxEdit',{});
},
'Sage/UI/Controls/nls/sz/LogOffButton':function(){
define('Sage/UI/Controls/nls/sz/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/sz/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sz/EditEventEditor',{});
},
'Sage/MailMerge/nls/sz/Loader':function(){
define('Sage/MailMerge/nls/sz/Loader',{});
},
'Sage/UI/Controls/nls/sz/DateTimePicker':function(){
define('Sage/UI/Controls/nls/sz/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/sz/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/sz/AlarmPopup',{});
},
'Sage/UI/Controls/nls/sz/Lookup':function(){
define('Sage/UI/Controls/nls/sz/Lookup',{});
},
'Sage/Utility/File/nls/sz/DescriptionsForm':function(){
define('Sage/Utility/File/nls/sz/DescriptionsForm',{});
},
'Sage/TaskPane/nls/sz/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/sz/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_sz", [], 1);
