require({cache:{
'Sage/Utility/File/nls/es/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/es-sv/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es-sv/FallbackFilePicker',{});
},
'Sage/UI/nls/es/Boolean':function(){
define('Sage/UI/nls/es/Boolean',{});
},
'Sage/UI/nls/es-sv/Boolean':function(){
define('Sage/UI/nls/es-sv/Boolean',{});
},
'Sage/UI/Controls/nls/es/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/es-sv/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es-sv/CopyToClipboard',{});
},
'Sage/Services/nls/es/ActivityService':function(){
define('Sage/Services/nls/es/ActivityService',{});
},
'Sage/Services/nls/es-sv/ActivityService':function(){
define('Sage/Services/nls/es-sv/ActivityService',{});
},
'Sage/Utility/nls/es/Activity':function(){
define('Sage/Utility/nls/es/Activity',{});
},
'Sage/Utility/nls/es-sv/Activity':function(){
define('Sage/Utility/nls/es-sv/Activity',{});
},
'Sage/UI/nls/es/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es/TimelessActivitiesPane',{});
},
'Sage/UI/nls/es-sv/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es-sv/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-sv/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-sv/ActivityEditor',{});
},
'Sage/MainView/nls/es/ActivityManager':function(){
define('Sage/MainView/nls/es/ActivityManager',{});
},
'Sage/MainView/nls/es-sv/ActivityManager':function(){
define('Sage/MainView/nls/es-sv/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-sv/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-sv/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/es/Service':function(){
define('Sage/Reporting/nls/es/Service',{});
},
'Sage/Reporting/nls/es-sv/Service':function(){
define('Sage/Reporting/nls/es-sv/Service',{});
},
'Sage/Utility/File/nls/es/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es-sv/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es-sv/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/es-sv/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es-sv/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/es/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es/AlarmPane',{});
},
'Sage/UI/Alarms/nls/es-sv/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es-sv/AlarmPane',{});
},
'Sage/TaskPane/nls/es/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/es-sv/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es-sv/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/es-sv/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es-sv/DashboardWidget',{});
},
'Sage/UI/Filters/nls/es/FilterPanel':function(){
define('Sage/UI/Filters/nls/es/FilterPanel',{});
},
'Sage/UI/Filters/nls/es-sv/FilterPanel':function(){
define('Sage/UI/Filters/nls/es-sv/FilterPanel',{});
},
'Sage/TaskPane/nls/es/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/es-sv/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es-sv/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/es/OwnerType':function(){
define('Sage/UI/nls/es/OwnerType',{});
},
'Sage/UI/nls/es-sv/OwnerType':function(){
define('Sage/UI/nls/es-sv/OwnerType',{});
},
'Sage/TaskPane/nls/es/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/es-sv/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es-sv/LeadTasksTasklet',{});
},
'Sage/UI/nls/es/SDataLookup':function(){
define('Sage/UI/nls/es/SDataLookup',{});
},
'Sage/UI/nls/es-sv/SDataLookup':function(){
define('Sage/UI/nls/es-sv/SDataLookup',{});
},
'Sage/TaskPane/nls/es/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/es-sv/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es-sv/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/es/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/es-sv/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es-sv/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/es/LibraryDocument':function(){
define('Sage/Utility/File/nls/es/LibraryDocument',{});
},
'Sage/Utility/File/nls/es-sv/LibraryDocument':function(){
define('Sage/Utility/File/nls/es-sv/LibraryDocument',{});
},
'Sage/UI/nls/es/ConditionManager':function(){
define('Sage/UI/nls/es/ConditionManager',{});
},
'Sage/UI/nls/es-sv/ConditionManager':function(){
define('Sage/UI/nls/es-sv/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/es/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/es-sv/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es-sv/WidgetDefinition',{});
},
'Sage/UI/nls/es/SearchConditionWidget':function(){
define('Sage/UI/nls/es/SearchConditionWidget',{});
},
'Sage/UI/nls/es-sv/SearchConditionWidget':function(){
define('Sage/UI/nls/es-sv/SearchConditionWidget',{});
},
'Sage/UI/nls/es/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/es-sv/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es-sv/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/es/Name':function(){
define('Sage/UI/Controls/nls/es/Name',{});
},
'Sage/UI/Controls/nls/es-sv/Name':function(){
define('Sage/UI/Controls/nls/es-sv/Name',{});
},
'Sage/MainView/Lead/nls/es/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/es-sv/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es-sv/UpdateLeads',{});
},
'Sage/UI/nls/es/ListPanel':function(){
define('Sage/UI/nls/es/ListPanel',{});
},
'Sage/UI/nls/es-sv/ListPanel':function(){
define('Sage/UI/nls/es-sv/ListPanel',{});
},
'Sage/UI/Filters/nls/es/EditFilters':function(){
define('Sage/UI/Filters/nls/es/EditFilters',{});
},
'Sage/UI/Filters/nls/es-sv/EditFilters':function(){
define('Sage/UI/Filters/nls/es-sv/EditFilters',{});
},
'Sage/UI/Controls/nls/es/DurationSelect':function(){
define('Sage/UI/Controls/nls/es/DurationSelect',{});
},
'Sage/UI/Controls/nls/es-sv/DurationSelect':function(){
define('Sage/UI/Controls/nls/es-sv/DurationSelect',{});
},
'Sage/UI/Alarms/nls/es/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/es-sv/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es-sv/AlarmCountDown',{});
},
'Sage/UI/nls/es/AttachmentList':function(){
define('Sage/UI/nls/es/AttachmentList',{});
},
'Sage/UI/nls/es-sv/AttachmentList':function(){
define('Sage/UI/nls/es-sv/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/es-sv/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es-sv/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/es/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/es-sv/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es-sv/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/es/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/es-sv/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es-sv/DashboardTabController',{});
},
'Sage/Groups/nls/es/GroupNavigator':function(){
define('Sage/Groups/nls/es/GroupNavigator',{});
},
'Sage/Groups/nls/es-sv/GroupNavigator':function(){
define('Sage/Groups/nls/es-sv/GroupNavigator',{});
},
'Sage/Utility/File/nls/es/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es/AddURLAttachment',{});
},
'Sage/Utility/File/nls/es-sv/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es-sv/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/es/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es/EditFilterItems',{});
},
'Sage/UI/Filters/nls/es-sv/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es-sv/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-sv/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-sv/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-sv/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-sv/EventListPanelConfig',{});
},
'Sage/UI/nls/es/ActivityScheduler':function(){
define('Sage/UI/nls/es/ActivityScheduler',{});
},
'Sage/UI/nls/es-sv/ActivityScheduler':function(){
define('Sage/UI/nls/es-sv/ActivityScheduler',{});
},
'Sage/MainView/nls/es/SecurityManager':function(){
define('Sage/MainView/nls/es/SecurityManager',{});
},
'Sage/MainView/nls/es-sv/SecurityManager':function(){
define('Sage/MainView/nls/es-sv/SecurityManager',{});
},
'Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/es-sv/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es-sv/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es-sv/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es-sv/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/es/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/es-sv/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es-sv/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/es/HelpMenu':function(){
define('Sage/UI/Controls/nls/es/HelpMenu',{});
},
'Sage/UI/Controls/nls/es-sv/HelpMenu':function(){
define('Sage/UI/Controls/nls/es-sv/HelpMenu',{});
},
'Sage/TaskPane/nls/es/UserTasklet':function(){
define('Sage/TaskPane/nls/es/UserTasklet',{});
},
'Sage/TaskPane/nls/es-sv/UserTasklet':function(){
define('Sage/TaskPane/nls/es-sv/UserTasklet',{});
},
'Sage/UI/Alarms/nls/es/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/es-sv/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es-sv/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/es/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/es-sv/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es-sv/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/es/MenuHelper':function(){
define('Sage/MailMerge/nls/es/MenuHelper',{});
},
'Sage/MailMerge/nls/es-sv/MenuHelper':function(){
define('Sage/MailMerge/nls/es-sv/MenuHelper',{});
},
'Sage/UI/nls/es/SearchMenuItem':function(){
define('Sage/UI/nls/es/SearchMenuItem',{});
},
'Sage/UI/nls/es-sv/SearchMenuItem':function(){
define('Sage/UI/nls/es-sv/SearchMenuItem',{});
},
'Sage/UI/nls/es/NotesHistoryList':function(){
define('Sage/UI/nls/es/NotesHistoryList',{});
},
'Sage/UI/nls/es-sv/NotesHistoryList':function(){
define('Sage/UI/nls/es-sv/NotesHistoryList',{});
},
'Sage/Utility/File/nls/es/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/es-sv/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es-sv/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-sv/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-sv/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-sv/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-sv/HistoryEditor',{});
},
'Sage/Groups/nls/es/GroupManager':function(){
define('Sage/Groups/nls/es/GroupManager',{});
},
'Sage/Groups/nls/es-sv/GroupManager':function(){
define('Sage/Groups/nls/es-sv/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/es/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-sv/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-sv/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/es/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/es/UnconfirmedAlarm',{});
},
'Sage/UI/Alarms/nls/es-sv/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/es-sv/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/es/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/es-sv/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es-sv/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/es/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/es-sv/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es-sv/AccountingTasksTasklet',{});
},
'Sage/UI/nls/es/EditableGrid':function(){
define('Sage/UI/nls/es/EditableGrid',{});
},
'Sage/UI/nls/es-sv/EditableGrid':function(){
define('Sage/UI/nls/es-sv/EditableGrid',{});
},
'Sage/UI/nls/es/SpeedSearch':function(){
define('Sage/UI/nls/es/SpeedSearch',{});
},
'Sage/UI/nls/es-sv/SpeedSearch':function(){
define('Sage/UI/nls/es-sv/SpeedSearch',{});
},
'Sage/UI/nls/es/SLXPreviewGrid':function(){
define('Sage/UI/nls/es/SLXPreviewGrid',{});
},
'Sage/UI/nls/es-sv/SLXPreviewGrid':function(){
define('Sage/UI/nls/es-sv/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/es/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/es-sv/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es-sv/UnconfirmedPane',{});
},
'Sage/Utility/nls/es/Utility':function(){
define('Sage/Utility/nls/es/Utility',{});
},
'Sage/Utility/nls/es-sv/Utility':function(){
define('Sage/Utility/nls/es-sv/Utility',{});
},
'Sage/UI/Controls/nls/es/Address':function(){
define('Sage/UI/Controls/nls/es/Address',{});
},
'Sage/UI/Controls/nls/es-sv/Address':function(){
define('Sage/UI/Controls/nls/es-sv/Address',{});
},
'Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-sv/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-sv/BaseListPanelConfig',{});
},
'Sage/UI/nls/es/UserType':function(){
define('Sage/UI/nls/es/UserType',{});
},
'Sage/UI/nls/es-sv/UserType':function(){
define('Sage/UI/nls/es-sv/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/es-sv/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es-sv/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/es/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/es-sv/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es-sv/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/es/ActivityList':function(){
define('Sage/UI/nls/es/ActivityList',{});
},
'Sage/UI/nls/es-sv/ActivityList':function(){
define('Sage/UI/nls/es-sv/ActivityList',{});
},
'Sage/UI/nls/es/CalendarUsersListPane':function(){
define('Sage/UI/nls/es/CalendarUsersListPane',{});
},
'Sage/UI/nls/es-sv/CalendarUsersListPane':function(){
define('Sage/UI/nls/es-sv/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/es-sv/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es-sv/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/es/Attachment':function(){
define('Sage/Utility/File/nls/es/Attachment',{});
},
'Sage/Utility/File/nls/es-sv/Attachment':function(){
define('Sage/Utility/File/nls/es-sv/Attachment',{});
},
'Sage/MailMerge/nls/es/Helper':function(){
define('Sage/MailMerge/nls/es/Helper',{});
},
'Sage/MailMerge/nls/es-sv/Helper':function(){
define('Sage/MailMerge/nls/es-sv/Helper',{});
},
'Sage/UI/Dashboard/nls/es/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es/Dashboard',{});
},
'Sage/UI/Dashboard/nls/es-sv/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es-sv/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-sv/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-sv/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/es/PickList':function(){
define('Sage/UI/Controls/nls/es/PickList',{});
},
'Sage/UI/Controls/nls/es-sv/PickList':function(){
define('Sage/UI/Controls/nls/es-sv/PickList',{});
},
'Sage/Utility/nls/es/Email':function(){
define('Sage/Utility/nls/es/Email',{});
},
'Sage/Utility/nls/es-sv/Email':function(){
define('Sage/Utility/nls/es-sv/Email',{});
},
'Sage/UI/nls/es/TimeZoneItem':function(){
define('Sage/UI/nls/es/TimeZoneItem',{});
},
'Sage/UI/nls/es-sv/TimeZoneItem':function(){
define('Sage/UI/nls/es-sv/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/es/SlxEdit':function(){
define('Sage/UI/Columns/nls/es/SlxEdit',{});
},
'Sage/UI/Columns/nls/es-sv/SlxEdit':function(){
define('Sage/UI/Columns/nls/es-sv/SlxEdit',{});
},
'Sage/UI/Controls/nls/es/LogOffButton':function(){
define('Sage/UI/Controls/nls/es/LogOffButton',{});
},
'Sage/UI/Controls/nls/es-sv/LogOffButton':function(){
define('Sage/UI/Controls/nls/es-sv/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/es/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-sv/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-sv/EditEventEditor',{});
},
'Sage/MailMerge/nls/es/Loader':function(){
define('Sage/MailMerge/nls/es/Loader',{});
},
'Sage/MailMerge/nls/es-sv/Loader':function(){
define('Sage/MailMerge/nls/es-sv/Loader',{});
},
'Sage/UI/Controls/nls/es/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es/DateTimePicker',{});
},
'Sage/UI/Controls/nls/es-sv/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es-sv/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/es/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/es-sv/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es-sv/AlarmPopup',{});
},
'Sage/UI/Controls/nls/es/Lookup':function(){
define('Sage/UI/Controls/nls/es/Lookup',{});
},
'Sage/UI/Controls/nls/es-sv/Lookup':function(){
define('Sage/UI/Controls/nls/es-sv/Lookup',{});
},
'Sage/Utility/File/nls/es/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es/DescriptionsForm',{});
},
'Sage/Utility/File/nls/es-sv/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es-sv/DescriptionsForm',{});
},
'Sage/TaskPane/nls/es/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/es-sv/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es-sv/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_es-sv", [], 1);
