require({cache:{
'Sage/Utility/File/nls/ar/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/ar-sa/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/ar-sa/FallbackFilePicker',{});
},
'Sage/UI/nls/ar/Boolean':function(){
define('Sage/UI/nls/ar/Boolean',{});
},
'Sage/UI/nls/ar-sa/Boolean':function(){
define('Sage/UI/nls/ar-sa/Boolean',{});
},
'Sage/UI/Controls/nls/ar/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/ar-sa/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/ar-sa/CopyToClipboard',{});
},
'Sage/Services/nls/ar/ActivityService':function(){
define('Sage/Services/nls/ar/ActivityService',{});
},
'Sage/Services/nls/ar-sa/ActivityService':function(){
define('Sage/Services/nls/ar-sa/ActivityService',{});
},
'Sage/Utility/nls/ar/Activity':function(){
define('Sage/Utility/nls/ar/Activity',{});
},
'Sage/Utility/nls/ar-sa/Activity':function(){
define('Sage/Utility/nls/ar-sa/Activity',{});
},
'Sage/UI/nls/ar/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar/TimelessActivitiesPane',{});
},
'Sage/UI/nls/ar-sa/TimelessActivitiesPane':function(){
define('Sage/UI/nls/ar-sa/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-sa/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-sa/ActivityEditor',{});
},
'Sage/MainView/nls/ar/ActivityManager':function(){
define('Sage/MainView/nls/ar/ActivityManager',{});
},
'Sage/MainView/nls/ar-sa/ActivityManager':function(){
define('Sage/MainView/nls/ar-sa/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-sa/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-sa/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/ar/Service':function(){
define('Sage/Reporting/nls/ar/Service',{});
},
'Sage/Reporting/nls/ar-sa/Service':function(){
define('Sage/Reporting/nls/ar-sa/Service',{});
},
'Sage/Utility/File/nls/ar/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar-sa/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/ar-sa/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/ar-sa/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/ar-sa/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPane',{});
},
'Sage/UI/Alarms/nls/ar-sa/AlarmPane':function(){
define('Sage/UI/Alarms/nls/ar-sa/AlarmPane',{});
},
'Sage/TaskPane/nls/ar/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/ar-sa/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/ar-sa/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/ar-sa/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/ar-sa/DashboardWidget',{});
},
'Sage/UI/Filters/nls/ar/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar/FilterPanel',{});
},
'Sage/UI/Filters/nls/ar-sa/FilterPanel':function(){
define('Sage/UI/Filters/nls/ar-sa/FilterPanel',{});
},
'Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/ar-sa/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/ar-sa/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/ar/OwnerType':function(){
define('Sage/UI/nls/ar/OwnerType',{});
},
'Sage/UI/nls/ar-sa/OwnerType':function(){
define('Sage/UI/nls/ar-sa/OwnerType',{});
},
'Sage/TaskPane/nls/ar/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-sa/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-sa/LeadTasksTasklet',{});
},
'Sage/UI/nls/ar/SDataLookup':function(){
define('Sage/UI/nls/ar/SDataLookup',{});
},
'Sage/UI/nls/ar-sa/SDataLookup':function(){
define('Sage/UI/nls/ar-sa/SDataLookup',{});
},
'Sage/TaskPane/nls/ar/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-sa/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-sa/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/ar/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/ar-sa/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/ar-sa/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/ar/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar/LibraryDocument',{});
},
'Sage/Utility/File/nls/ar-sa/LibraryDocument':function(){
define('Sage/Utility/File/nls/ar-sa/LibraryDocument',{});
},
'Sage/UI/nls/ar/ConditionManager':function(){
define('Sage/UI/nls/ar/ConditionManager',{});
},
'Sage/UI/nls/ar-sa/ConditionManager':function(){
define('Sage/UI/nls/ar-sa/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/ar/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/ar-sa/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/ar-sa/WidgetDefinition',{});
},
'Sage/UI/nls/ar/SearchConditionWidget':function(){
define('Sage/UI/nls/ar/SearchConditionWidget',{});
},
'Sage/UI/nls/ar-sa/SearchConditionWidget':function(){
define('Sage/UI/nls/ar-sa/SearchConditionWidget',{});
},
'Sage/UI/nls/ar/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/ar-sa/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/ar-sa/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/ar/Name':function(){
define('Sage/UI/Controls/nls/ar/Name',{});
},
'Sage/UI/Controls/nls/ar-sa/Name':function(){
define('Sage/UI/Controls/nls/ar-sa/Name',{});
},
'Sage/MainView/Lead/nls/ar/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/ar-sa/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/ar-sa/UpdateLeads',{});
},
'Sage/UI/nls/ar/ListPanel':function(){
define('Sage/UI/nls/ar/ListPanel',{});
},
'Sage/UI/nls/ar-sa/ListPanel':function(){
define('Sage/UI/nls/ar-sa/ListPanel',{});
},
'Sage/UI/Filters/nls/ar/EditFilters':function(){
define('Sage/UI/Filters/nls/ar/EditFilters',{});
},
'Sage/UI/Filters/nls/ar-sa/EditFilters':function(){
define('Sage/UI/Filters/nls/ar-sa/EditFilters',{});
},
'Sage/UI/Controls/nls/ar/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar/DurationSelect',{});
},
'Sage/UI/Controls/nls/ar-sa/DurationSelect':function(){
define('Sage/UI/Controls/nls/ar-sa/DurationSelect',{});
},
'Sage/UI/Alarms/nls/ar/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/ar-sa/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/ar-sa/AlarmCountDown',{});
},
'Sage/UI/nls/ar/AttachmentList':function(){
define('Sage/UI/nls/ar/AttachmentList',{});
},
'Sage/UI/nls/ar-sa/AttachmentList':function(){
define('Sage/UI/nls/ar-sa/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/ar-sa/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/ar-sa/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/ar/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/ar-sa/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/ar-sa/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/ar/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/ar-sa/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/ar-sa/DashboardTabController',{});
},
'Sage/Groups/nls/ar/GroupNavigator':function(){
define('Sage/Groups/nls/ar/GroupNavigator',{});
},
'Sage/Groups/nls/ar-sa/GroupNavigator':function(){
define('Sage/Groups/nls/ar-sa/GroupNavigator',{});
},
'Sage/Utility/File/nls/ar/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar/AddURLAttachment',{});
},
'Sage/Utility/File/nls/ar-sa/AddURLAttachment':function(){
define('Sage/Utility/File/nls/ar-sa/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/ar/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar/EditFilterItems',{});
},
'Sage/UI/Filters/nls/ar-sa/EditFilterItems':function(){
define('Sage/UI/Filters/nls/ar-sa/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-sa/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-sa/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-sa/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-sa/EventListPanelConfig',{});
},
'Sage/UI/nls/ar/ActivityScheduler':function(){
define('Sage/UI/nls/ar/ActivityScheduler',{});
},
'Sage/UI/nls/ar-sa/ActivityScheduler':function(){
define('Sage/UI/nls/ar-sa/ActivityScheduler',{});
},
'Sage/MainView/nls/ar/SecurityManager':function(){
define('Sage/MainView/nls/ar/SecurityManager',{});
},
'Sage/MainView/nls/ar-sa/SecurityManager':function(){
define('Sage/MainView/nls/ar-sa/SecurityManager',{});
},
'Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/ar-sa/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/ar-sa/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/ar-sa/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/ar-sa/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/ar/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/ar-sa/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/ar-sa/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/ar/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar/HelpMenu',{});
},
'Sage/UI/Controls/nls/ar-sa/HelpMenu':function(){
define('Sage/UI/Controls/nls/ar-sa/HelpMenu',{});
},
'Sage/TaskPane/nls/ar/UserTasklet':function(){
define('Sage/TaskPane/nls/ar/UserTasklet',{});
},
'Sage/TaskPane/nls/ar-sa/UserTasklet':function(){
define('Sage/TaskPane/nls/ar-sa/UserTasklet',{});
},
'Sage/UI/Alarms/nls/ar/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/ar-sa/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/ar-sa/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/ar/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/ar-sa/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/ar-sa/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/ar/MenuHelper':function(){
define('Sage/MailMerge/nls/ar/MenuHelper',{});
},
'Sage/MailMerge/nls/ar-sa/MenuHelper':function(){
define('Sage/MailMerge/nls/ar-sa/MenuHelper',{});
},
'Sage/UI/nls/ar/SearchMenuItem':function(){
define('Sage/UI/nls/ar/SearchMenuItem',{});
},
'Sage/UI/nls/ar-sa/SearchMenuItem':function(){
define('Sage/UI/nls/ar-sa/SearchMenuItem',{});
},
'Sage/UI/nls/ar/NotesHistoryList':function(){
define('Sage/UI/nls/ar/NotesHistoryList',{});
},
'Sage/UI/nls/ar-sa/NotesHistoryList':function(){
define('Sage/UI/nls/ar-sa/NotesHistoryList',{});
},
'Sage/Utility/File/nls/ar/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/ar-sa/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/ar-sa/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-sa/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-sa/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-sa/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-sa/HistoryEditor',{});
},
'Sage/Groups/nls/ar/GroupManager':function(){
define('Sage/Groups/nls/ar/GroupManager',{});
},
'Sage/Groups/nls/ar-sa/GroupManager':function(){
define('Sage/Groups/nls/ar-sa/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/ar/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-sa/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-sa/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedAlarm',{});
},
'Sage/UI/Alarms/nls/ar-sa/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/ar-sa/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/ar-sa/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/ar-sa/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/ar/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-sa/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-sa/AccountingTasksTasklet',{});
},
'Sage/UI/nls/ar/EditableGrid':function(){
define('Sage/UI/nls/ar/EditableGrid',{});
},
'Sage/UI/nls/ar-sa/EditableGrid':function(){
define('Sage/UI/nls/ar-sa/EditableGrid',{});
},
'Sage/UI/nls/ar/SpeedSearch':function(){
define('Sage/UI/nls/ar/SpeedSearch',{});
},
'Sage/UI/nls/ar-sa/SpeedSearch':function(){
define('Sage/UI/nls/ar-sa/SpeedSearch',{});
},
'Sage/UI/nls/ar/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar/SLXPreviewGrid',{});
},
'Sage/UI/nls/ar-sa/SLXPreviewGrid':function(){
define('Sage/UI/nls/ar-sa/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/ar/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/ar-sa/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/ar-sa/UnconfirmedPane',{});
},
'Sage/Utility/nls/ar/Utility':function(){
define('Sage/Utility/nls/ar/Utility',{});
},
'Sage/Utility/nls/ar-sa/Utility':function(){
define('Sage/Utility/nls/ar-sa/Utility',{});
},
'Sage/UI/Controls/nls/ar/Address':function(){
define('Sage/UI/Controls/nls/ar/Address',{});
},
'Sage/UI/Controls/nls/ar-sa/Address':function(){
define('Sage/UI/Controls/nls/ar-sa/Address',{});
},
'Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-sa/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-sa/BaseListPanelConfig',{});
},
'Sage/UI/nls/ar/UserType':function(){
define('Sage/UI/nls/ar/UserType',{});
},
'Sage/UI/nls/ar-sa/UserType':function(){
define('Sage/UI/nls/ar-sa/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/ar-sa/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/ar-sa/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/ar/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/ar-sa/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/ar-sa/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/ar/ActivityList':function(){
define('Sage/UI/nls/ar/ActivityList',{});
},
'Sage/UI/nls/ar-sa/ActivityList':function(){
define('Sage/UI/nls/ar-sa/ActivityList',{});
},
'Sage/UI/nls/ar/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar/CalendarUsersListPane',{});
},
'Sage/UI/nls/ar-sa/CalendarUsersListPane':function(){
define('Sage/UI/nls/ar-sa/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/ar-sa/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/ar-sa/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/ar/Attachment':function(){
define('Sage/Utility/File/nls/ar/Attachment',{});
},
'Sage/Utility/File/nls/ar-sa/Attachment':function(){
define('Sage/Utility/File/nls/ar-sa/Attachment',{});
},
'Sage/MailMerge/nls/ar/Helper':function(){
define('Sage/MailMerge/nls/ar/Helper',{});
},
'Sage/MailMerge/nls/ar-sa/Helper':function(){
define('Sage/MailMerge/nls/ar-sa/Helper',{});
},
'Sage/UI/Dashboard/nls/ar/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar/Dashboard',{});
},
'Sage/UI/Dashboard/nls/ar-sa/Dashboard':function(){
define('Sage/UI/Dashboard/nls/ar-sa/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/ar-sa/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/ar-sa/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/ar/PickList':function(){
define('Sage/UI/Controls/nls/ar/PickList',{});
},
'Sage/UI/Controls/nls/ar-sa/PickList':function(){
define('Sage/UI/Controls/nls/ar-sa/PickList',{});
},
'Sage/Utility/nls/ar/Email':function(){
define('Sage/Utility/nls/ar/Email',{});
},
'Sage/Utility/nls/ar-sa/Email':function(){
define('Sage/Utility/nls/ar-sa/Email',{});
},
'Sage/UI/nls/ar/TimeZoneItem':function(){
define('Sage/UI/nls/ar/TimeZoneItem',{});
},
'Sage/UI/nls/ar-sa/TimeZoneItem':function(){
define('Sage/UI/nls/ar-sa/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/ar/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar/SlxEdit',{});
},
'Sage/UI/Columns/nls/ar-sa/SlxEdit':function(){
define('Sage/UI/Columns/nls/ar-sa/SlxEdit',{});
},
'Sage/UI/Controls/nls/ar/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar/LogOffButton',{});
},
'Sage/UI/Controls/nls/ar-sa/LogOffButton':function(){
define('Sage/UI/Controls/nls/ar-sa/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/ar/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/ar-sa/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/ar-sa/EditEventEditor',{});
},
'Sage/MailMerge/nls/ar/Loader':function(){
define('Sage/MailMerge/nls/ar/Loader',{});
},
'Sage/MailMerge/nls/ar-sa/Loader':function(){
define('Sage/MailMerge/nls/ar-sa/Loader',{});
},
'Sage/UI/Controls/nls/ar/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar/DateTimePicker',{});
},
'Sage/UI/Controls/nls/ar-sa/DateTimePicker':function(){
define('Sage/UI/Controls/nls/ar-sa/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/ar/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/ar-sa/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/ar-sa/AlarmPopup',{});
},
'Sage/UI/Controls/nls/ar/Lookup':function(){
define('Sage/UI/Controls/nls/ar/Lookup',{});
},
'Sage/UI/Controls/nls/ar-sa/Lookup':function(){
define('Sage/UI/Controls/nls/ar-sa/Lookup',{});
},
'Sage/Utility/File/nls/ar/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar/DescriptionsForm',{});
},
'Sage/Utility/File/nls/ar-sa/DescriptionsForm':function(){
define('Sage/Utility/File/nls/ar-sa/DescriptionsForm',{});
},
'Sage/TaskPane/nls/ar/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/ar-sa/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/ar-sa/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_ar-sa", [], 1);
