require({cache:{
'Sage/Utility/File/nls/es/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/es-ni/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/es-ni/FallbackFilePicker',{});
},
'Sage/UI/nls/es/Boolean':function(){
define('Sage/UI/nls/es/Boolean',{});
},
'Sage/UI/nls/es-ni/Boolean':function(){
define('Sage/UI/nls/es-ni/Boolean',{});
},
'Sage/UI/Controls/nls/es/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/es-ni/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/es-ni/CopyToClipboard',{});
},
'Sage/Services/nls/es/ActivityService':function(){
define('Sage/Services/nls/es/ActivityService',{});
},
'Sage/Services/nls/es-ni/ActivityService':function(){
define('Sage/Services/nls/es-ni/ActivityService',{});
},
'Sage/Utility/nls/es/Activity':function(){
define('Sage/Utility/nls/es/Activity',{});
},
'Sage/Utility/nls/es-ni/Activity':function(){
define('Sage/Utility/nls/es-ni/Activity',{});
},
'Sage/UI/nls/es/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es/TimelessActivitiesPane',{});
},
'Sage/UI/nls/es-ni/TimelessActivitiesPane':function(){
define('Sage/UI/nls/es-ni/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/ActivityEditor',{});
},
'Sage/MainView/nls/es/ActivityManager':function(){
define('Sage/MainView/nls/es/ActivityManager',{});
},
'Sage/MainView/nls/es-ni/ActivityManager':function(){
define('Sage/MainView/nls/es-ni/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/es/Service':function(){
define('Sage/Reporting/nls/es/Service',{});
},
'Sage/Reporting/nls/es-ni/Service':function(){
define('Sage/Reporting/nls/es-ni/Service',{});
},
'Sage/Utility/File/nls/es/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es-ni/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/es-ni/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/es/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/es-ni/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/es-ni/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/es/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es/AlarmPane',{});
},
'Sage/UI/Alarms/nls/es-ni/AlarmPane':function(){
define('Sage/UI/Alarms/nls/es-ni/AlarmPane',{});
},
'Sage/TaskPane/nls/es/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/es-ni/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/es-ni/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/es-ni/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/es-ni/DashboardWidget',{});
},
'Sage/UI/Filters/nls/es/FilterPanel':function(){
define('Sage/UI/Filters/nls/es/FilterPanel',{});
},
'Sage/UI/Filters/nls/es-ni/FilterPanel':function(){
define('Sage/UI/Filters/nls/es-ni/FilterPanel',{});
},
'Sage/TaskPane/nls/es/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/es-ni/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/es-ni/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/es/OwnerType':function(){
define('Sage/UI/nls/es/OwnerType',{});
},
'Sage/UI/nls/es-ni/OwnerType':function(){
define('Sage/UI/nls/es-ni/OwnerType',{});
},
'Sage/TaskPane/nls/es/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ni/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ni/LeadTasksTasklet',{});
},
'Sage/UI/nls/es/SDataLookup':function(){
define('Sage/UI/nls/es/SDataLookup',{});
},
'Sage/UI/nls/es-ni/SDataLookup':function(){
define('Sage/UI/nls/es-ni/SDataLookup',{});
},
'Sage/TaskPane/nls/es/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ni/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ni/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/es/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/es-ni/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/es-ni/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/es/LibraryDocument':function(){
define('Sage/Utility/File/nls/es/LibraryDocument',{});
},
'Sage/Utility/File/nls/es-ni/LibraryDocument':function(){
define('Sage/Utility/File/nls/es-ni/LibraryDocument',{});
},
'Sage/UI/nls/es/ConditionManager':function(){
define('Sage/UI/nls/es/ConditionManager',{});
},
'Sage/UI/nls/es-ni/ConditionManager':function(){
define('Sage/UI/nls/es-ni/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/es/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/es-ni/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/es-ni/WidgetDefinition',{});
},
'Sage/UI/nls/es/SearchConditionWidget':function(){
define('Sage/UI/nls/es/SearchConditionWidget',{});
},
'Sage/UI/nls/es-ni/SearchConditionWidget':function(){
define('Sage/UI/nls/es-ni/SearchConditionWidget',{});
},
'Sage/UI/nls/es/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/es-ni/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/es-ni/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/es/Name':function(){
define('Sage/UI/Controls/nls/es/Name',{});
},
'Sage/UI/Controls/nls/es-ni/Name':function(){
define('Sage/UI/Controls/nls/es-ni/Name',{});
},
'Sage/MainView/Lead/nls/es/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/es-ni/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/es-ni/UpdateLeads',{});
},
'Sage/UI/nls/es/ListPanel':function(){
define('Sage/UI/nls/es/ListPanel',{});
},
'Sage/UI/nls/es-ni/ListPanel':function(){
define('Sage/UI/nls/es-ni/ListPanel',{});
},
'Sage/UI/Filters/nls/es/EditFilters':function(){
define('Sage/UI/Filters/nls/es/EditFilters',{});
},
'Sage/UI/Filters/nls/es-ni/EditFilters':function(){
define('Sage/UI/Filters/nls/es-ni/EditFilters',{});
},
'Sage/UI/Controls/nls/es/DurationSelect':function(){
define('Sage/UI/Controls/nls/es/DurationSelect',{});
},
'Sage/UI/Controls/nls/es-ni/DurationSelect':function(){
define('Sage/UI/Controls/nls/es-ni/DurationSelect',{});
},
'Sage/UI/Alarms/nls/es/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/es-ni/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/es-ni/AlarmCountDown',{});
},
'Sage/UI/nls/es/AttachmentList':function(){
define('Sage/UI/nls/es/AttachmentList',{});
},
'Sage/UI/nls/es-ni/AttachmentList':function(){
define('Sage/UI/nls/es-ni/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/es/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/es-ni/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/es-ni/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/es/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/es-ni/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/es-ni/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/es/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/es-ni/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/es-ni/DashboardTabController',{});
},
'Sage/Groups/nls/es/GroupNavigator':function(){
define('Sage/Groups/nls/es/GroupNavigator',{});
},
'Sage/Groups/nls/es-ni/GroupNavigator':function(){
define('Sage/Groups/nls/es-ni/GroupNavigator',{});
},
'Sage/Utility/File/nls/es/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es/AddURLAttachment',{});
},
'Sage/Utility/File/nls/es-ni/AddURLAttachment':function(){
define('Sage/Utility/File/nls/es-ni/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/es/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es/EditFilterItems',{});
},
'Sage/UI/Filters/nls/es-ni/EditFilterItems':function(){
define('Sage/UI/Filters/nls/es-ni/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/EventListPanelConfig',{});
},
'Sage/UI/nls/es/ActivityScheduler':function(){
define('Sage/UI/nls/es/ActivityScheduler',{});
},
'Sage/UI/nls/es-ni/ActivityScheduler':function(){
define('Sage/UI/nls/es-ni/ActivityScheduler',{});
},
'Sage/MainView/nls/es/SecurityManager':function(){
define('Sage/MainView/nls/es/SecurityManager',{});
},
'Sage/MainView/nls/es-ni/SecurityManager':function(){
define('Sage/MainView/nls/es-ni/SecurityManager',{});
},
'Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/es-ni/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/es-ni/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/es/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/es-ni/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/es-ni/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/es/HelpMenu':function(){
define('Sage/UI/Controls/nls/es/HelpMenu',{});
},
'Sage/UI/Controls/nls/es-ni/HelpMenu':function(){
define('Sage/UI/Controls/nls/es-ni/HelpMenu',{});
},
'Sage/TaskPane/nls/es/UserTasklet':function(){
define('Sage/TaskPane/nls/es/UserTasklet',{});
},
'Sage/TaskPane/nls/es-ni/UserTasklet':function(){
define('Sage/TaskPane/nls/es-ni/UserTasklet',{});
},
'Sage/UI/Alarms/nls/es/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/es-ni/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/es-ni/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/es/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/es-ni/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/es-ni/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/es/MenuHelper':function(){
define('Sage/MailMerge/nls/es/MenuHelper',{});
},
'Sage/MailMerge/nls/es-ni/MenuHelper':function(){
define('Sage/MailMerge/nls/es-ni/MenuHelper',{});
},
'Sage/UI/nls/es/SearchMenuItem':function(){
define('Sage/UI/nls/es/SearchMenuItem',{});
},
'Sage/UI/nls/es-ni/SearchMenuItem':function(){
define('Sage/UI/nls/es-ni/SearchMenuItem',{});
},
'Sage/UI/nls/es/NotesHistoryList':function(){
define('Sage/UI/nls/es/NotesHistoryList',{});
},
'Sage/UI/nls/es-ni/NotesHistoryList':function(){
define('Sage/UI/nls/es-ni/NotesHistoryList',{});
},
'Sage/Utility/File/nls/es/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/es-ni/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/es-ni/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/HistoryEditor',{});
},
'Sage/Groups/nls/es/GroupManager':function(){
define('Sage/Groups/nls/es/GroupManager',{});
},
'Sage/Groups/nls/es-ni/GroupManager':function(){
define('Sage/Groups/nls/es-ni/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/es/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/es/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/es/UnconfirmedAlarm',{});
},
'Sage/UI/Alarms/nls/es-ni/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/es-ni/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/es/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/es-ni/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/es-ni/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/es/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ni/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ni/AccountingTasksTasklet',{});
},
'Sage/UI/nls/es/EditableGrid':function(){
define('Sage/UI/nls/es/EditableGrid',{});
},
'Sage/UI/nls/es-ni/EditableGrid':function(){
define('Sage/UI/nls/es-ni/EditableGrid',{});
},
'Sage/UI/nls/es/SpeedSearch':function(){
define('Sage/UI/nls/es/SpeedSearch',{});
},
'Sage/UI/nls/es-ni/SpeedSearch':function(){
define('Sage/UI/nls/es-ni/SpeedSearch',{});
},
'Sage/UI/nls/es/SLXPreviewGrid':function(){
define('Sage/UI/nls/es/SLXPreviewGrid',{});
},
'Sage/UI/nls/es-ni/SLXPreviewGrid':function(){
define('Sage/UI/nls/es-ni/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/es/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/es-ni/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/es-ni/UnconfirmedPane',{});
},
'Sage/Utility/nls/es/Utility':function(){
define('Sage/Utility/nls/es/Utility',{});
},
'Sage/Utility/nls/es-ni/Utility':function(){
define('Sage/Utility/nls/es-ni/Utility',{});
},
'Sage/UI/Controls/nls/es/Address':function(){
define('Sage/UI/Controls/nls/es/Address',{});
},
'Sage/UI/Controls/nls/es-ni/Address':function(){
define('Sage/UI/Controls/nls/es-ni/Address',{});
},
'Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/BaseListPanelConfig',{});
},
'Sage/UI/nls/es/UserType':function(){
define('Sage/UI/nls/es/UserType',{});
},
'Sage/UI/nls/es-ni/UserType':function(){
define('Sage/UI/nls/es-ni/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/es/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/es-ni/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/es-ni/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/es/ActivityList':function(){
define('Sage/UI/nls/es/ActivityList',{});
},
'Sage/UI/nls/es-ni/ActivityList':function(){
define('Sage/UI/nls/es-ni/ActivityList',{});
},
'Sage/UI/nls/es/CalendarUsersListPane':function(){
define('Sage/UI/nls/es/CalendarUsersListPane',{});
},
'Sage/UI/nls/es-ni/CalendarUsersListPane':function(){
define('Sage/UI/nls/es-ni/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/es/Attachment':function(){
define('Sage/Utility/File/nls/es/Attachment',{});
},
'Sage/Utility/File/nls/es-ni/Attachment':function(){
define('Sage/Utility/File/nls/es-ni/Attachment',{});
},
'Sage/MailMerge/nls/es/Helper':function(){
define('Sage/MailMerge/nls/es/Helper',{});
},
'Sage/MailMerge/nls/es-ni/Helper':function(){
define('Sage/MailMerge/nls/es-ni/Helper',{});
},
'Sage/UI/Dashboard/nls/es/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es/Dashboard',{});
},
'Sage/UI/Dashboard/nls/es-ni/Dashboard':function(){
define('Sage/UI/Dashboard/nls/es-ni/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/es/PickList':function(){
define('Sage/UI/Controls/nls/es/PickList',{});
},
'Sage/UI/Controls/nls/es-ni/PickList':function(){
define('Sage/UI/Controls/nls/es-ni/PickList',{});
},
'Sage/Utility/nls/es/Email':function(){
define('Sage/Utility/nls/es/Email',{});
},
'Sage/Utility/nls/es-ni/Email':function(){
define('Sage/Utility/nls/es-ni/Email',{});
},
'Sage/UI/nls/es/TimeZoneItem':function(){
define('Sage/UI/nls/es/TimeZoneItem',{});
},
'Sage/UI/nls/es-ni/TimeZoneItem':function(){
define('Sage/UI/nls/es-ni/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/es/SlxEdit':function(){
define('Sage/UI/Columns/nls/es/SlxEdit',{});
},
'Sage/UI/Columns/nls/es-ni/SlxEdit':function(){
define('Sage/UI/Columns/nls/es-ni/SlxEdit',{});
},
'Sage/UI/Controls/nls/es/LogOffButton':function(){
define('Sage/UI/Controls/nls/es/LogOffButton',{});
},
'Sage/UI/Controls/nls/es-ni/LogOffButton':function(){
define('Sage/UI/Controls/nls/es-ni/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/es/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/es-ni/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/es-ni/EditEventEditor',{});
},
'Sage/MailMerge/nls/es/Loader':function(){
define('Sage/MailMerge/nls/es/Loader',{});
},
'Sage/MailMerge/nls/es-ni/Loader':function(){
define('Sage/MailMerge/nls/es-ni/Loader',{});
},
'Sage/UI/Controls/nls/es/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es/DateTimePicker',{});
},
'Sage/UI/Controls/nls/es-ni/DateTimePicker':function(){
define('Sage/UI/Controls/nls/es-ni/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/es/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/es-ni/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/es-ni/AlarmPopup',{});
},
'Sage/UI/Controls/nls/es/Lookup':function(){
define('Sage/UI/Controls/nls/es/Lookup',{});
},
'Sage/UI/Controls/nls/es-ni/Lookup':function(){
define('Sage/UI/Controls/nls/es-ni/Lookup',{});
},
'Sage/Utility/File/nls/es/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es/DescriptionsForm',{});
},
'Sage/Utility/File/nls/es-ni/DescriptionsForm':function(){
define('Sage/Utility/File/nls/es-ni/DescriptionsForm',{});
},
'Sage/TaskPane/nls/es/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/es-ni/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/es-ni/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_es-ni", [], 1);
