require({cache:{
'Sage/Utility/File/nls/pt/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/pt/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/pt-pt/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/pt-pt/FallbackFilePicker',{});
},
'Sage/UI/nls/pt/Boolean':function(){
define('Sage/UI/nls/pt/Boolean',{});
},
'Sage/UI/nls/pt-pt/Boolean':function(){
define('Sage/UI/nls/pt-pt/Boolean',{});
},
'Sage/Services/nls/pt/ActivityService':function(){
define('Sage/Services/nls/pt/ActivityService',{});
},
'Sage/Services/nls/pt-pt/ActivityService':function(){
define('Sage/Services/nls/pt-pt/ActivityService',{});
},
'Sage/UI/Controls/nls/pt/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/pt/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/pt-pt/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/pt-pt/CopyToClipboard',{});
},
'Sage/Utility/nls/pt/Activity':function(){
define('Sage/Utility/nls/pt/Activity',{});
},
'Sage/Utility/nls/pt-pt/Activity':function(){
define('Sage/Utility/nls/pt-pt/Activity',{});
},
'Sage/QuickForms/Design/nls/pt/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/pt/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/pt-pt/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/pt-pt/DesignPanel',{});
},
'Sage/UI/nls/pt/TimelessActivitiesPane':function(){
define('Sage/UI/nls/pt/TimelessActivitiesPane',{});
},
'Sage/UI/nls/pt-pt/TimelessActivitiesPane':function(){
define('Sage/UI/nls/pt-pt/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt-pt/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt-pt/ActivityEditor',{});
},
'Sage/MainView/nls/pt/ActivityManager':function(){
define('Sage/MainView/nls/pt/ActivityManager',{});
},
'Sage/MainView/nls/pt-pt/ActivityManager':function(){
define('Sage/MainView/nls/pt-pt/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/pt/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/_PropertyEditor',{});
},
'Sage/Services/nls/pt/ActivityActionProcessor':function(){
define('Sage/Services/nls/pt/ActivityActionProcessor',{});
},
'Sage/Services/nls/pt-pt/ActivityActionProcessor':function(){
define('Sage/Services/nls/pt-pt/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt-pt/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt-pt/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/pt/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/pt/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/pt-pt/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/pt-pt/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/pt/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/pt/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/pt-pt/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/pt-pt/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/pt/AlarmPane':function(){
define('Sage/UI/Alarms/nls/pt/AlarmPane',{});
},
'Sage/UI/Alarms/nls/pt-pt/AlarmPane':function(){
define('Sage/UI/Alarms/nls/pt-pt/AlarmPane',{});
},
'Sage/TaskPane/nls/pt/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/pt/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/pt-pt/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/pt-pt/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/pt/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/pt/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/pt-pt/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/pt-pt/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/pt/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/pt-pt/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt-pt/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/pt/FilterPanel':function(){
define('Sage/UI/Filters/nls/pt/FilterPanel',{});
},
'Sage/UI/Filters/nls/pt-pt/FilterPanel':function(){
define('Sage/UI/Filters/nls/pt-pt/FilterPanel',{});
},
'Sage/TaskPane/nls/pt/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/pt/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/pt-pt/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/pt-pt/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/pt/OwnerType':function(){
define('Sage/UI/nls/pt/OwnerType',{});
},
'Sage/UI/nls/pt-pt/OwnerType':function(){
define('Sage/UI/nls/pt-pt/OwnerType',{});
},
'Sage/TaskPane/nls/pt/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/pt-pt/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/pt-pt/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/pt/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/pt/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/pt-pt/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/pt-pt/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/pt/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/pt-pt/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt-pt/InvoiceRTDV',{});
},
'Sage/UI/nls/pt/SDataLookup':function(){
define('Sage/UI/nls/pt/SDataLookup',{});
},
'Sage/UI/nls/pt-pt/SDataLookup':function(){
define('Sage/UI/nls/pt-pt/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/pt/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/RowDesigner',{});
},
'Sage/TaskPane/nls/pt/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/pt-pt/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/pt-pt/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/pt/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/pt/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/pt-pt/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/pt-pt/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/pt/LibraryDocument':function(){
define('Sage/Utility/File/nls/pt/LibraryDocument',{});
},
'Sage/Utility/File/nls/pt-pt/LibraryDocument':function(){
define('Sage/Utility/File/nls/pt-pt/LibraryDocument',{});
},
'Sage/UI/nls/pt/ConditionManager':function(){
define('Sage/UI/nls/pt/ConditionManager',{});
},
'Sage/UI/nls/pt-pt/ConditionManager':function(){
define('Sage/UI/nls/pt-pt/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/pt/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/pt/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/pt-pt/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/pt-pt/WidgetDefinition',{});
},
'Sage/UI/nls/pt/SearchConditionWidget':function(){
define('Sage/UI/nls/pt/SearchConditionWidget',{});
},
'Sage/UI/nls/pt-pt/SearchConditionWidget':function(){
define('Sage/UI/nls/pt-pt/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/pt/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/pt/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/pt-pt/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/pt-pt/DataSourcePanel',{});
},
'Sage/UI/nls/pt/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/pt/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/pt-pt/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/pt-pt/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/pt/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/pt/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/pt-pt/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/pt-pt/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/pt/Name':function(){
define('Sage/UI/Controls/nls/pt/Name',{});
},
'Sage/UI/Controls/nls/pt-pt/Name':function(){
define('Sage/UI/Controls/nls/pt-pt/Name',{});
},
'Sage/QuickForms/Design/nls/pt/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/pt/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/pt/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/pt-pt/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/pt-pt/UpdateLeads',{});
},
'Sage/UI/nls/pt/ListPanel':function(){
define('Sage/UI/nls/pt/ListPanel',{});
},
'Sage/UI/nls/pt-pt/ListPanel':function(){
define('Sage/UI/nls/pt-pt/ListPanel',{});
},
'Sage/UI/Filters/nls/pt/EditFilters':function(){
define('Sage/UI/Filters/nls/pt/EditFilters',{});
},
'Sage/UI/Filters/nls/pt-pt/EditFilters':function(){
define('Sage/UI/Filters/nls/pt-pt/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/pt/DurationSelect':function(){
define('Sage/UI/Controls/nls/pt/DurationSelect',{});
},
'Sage/UI/Controls/nls/pt-pt/DurationSelect':function(){
define('Sage/UI/Controls/nls/pt-pt/DurationSelect',{});
},
'Sage/UI/Alarms/nls/pt/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/pt/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/pt-pt/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/pt-pt/AlarmCountDown',{});
},
'Sage/UI/nls/pt/AttachmentList':function(){
define('Sage/UI/nls/pt/AttachmentList',{});
},
'Sage/UI/nls/pt-pt/AttachmentList':function(){
define('Sage/UI/nls/pt-pt/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/pt/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/pt/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/pt/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/pt-pt/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/pt-pt/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/pt/Dialogs':function(){
define('Sage/UI/nls/pt/Dialogs',{});
},
'Sage/UI/nls/pt-pt/Dialogs':function(){
define('Sage/UI/nls/pt-pt/Dialogs',{});
},
'Sage/TaskPane/nls/pt/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/pt/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/pt-pt/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/pt-pt/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/pt/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/pt/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/pt-pt/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/pt-pt/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/pt/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/pt-pt/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/pt-pt/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/pt/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/UserControlDesigner',{});
},
'Sage/Groups/nls/pt/GroupNavigator':function(){
define('Sage/Groups/nls/pt/GroupNavigator',{});
},
'Sage/Groups/nls/pt-pt/GroupNavigator':function(){
define('Sage/Groups/nls/pt-pt/GroupNavigator',{});
},
'Sage/Utility/File/nls/pt/AddURLAttachment':function(){
define('Sage/Utility/File/nls/pt/AddURLAttachment',{});
},
'Sage/Utility/File/nls/pt-pt/AddURLAttachment':function(){
define('Sage/Utility/File/nls/pt-pt/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/pt/EditFilterItems':function(){
define('Sage/UI/Filters/nls/pt/EditFilterItems',{});
},
'Sage/UI/Filters/nls/pt-pt/EditFilterItems':function(){
define('Sage/UI/Filters/nls/pt-pt/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/pt/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/pt/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/pt-pt/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/pt-pt/DesignSurface',{});
},
'Sage/Utility/File/nls/pt/DragDropWatcher':function(){
define('Sage/Utility/File/nls/pt/DragDropWatcher',{});
},
'Sage/Utility/File/nls/pt-pt/DragDropWatcher':function(){
define('Sage/Utility/File/nls/pt-pt/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt-pt/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt-pt/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt-pt/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt-pt/EventListPanelConfig',{});
},
'Sage/UI/nls/pt/ActivityScheduler':function(){
define('Sage/UI/nls/pt/ActivityScheduler',{});
},
'Sage/UI/nls/pt-pt/ActivityScheduler':function(){
define('Sage/UI/nls/pt-pt/ActivityScheduler',{});
},
'Sage/MainView/nls/pt/SecurityManager':function(){
define('Sage/MainView/nls/pt/SecurityManager',{});
},
'Sage/MainView/nls/pt-pt/SecurityManager':function(){
define('Sage/MainView/nls/pt-pt/SecurityManager',{});
},
'Sage/TaskPane/nls/pt/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/pt/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/pt-pt/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/pt-pt/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/pt/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/pt/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/pt-pt/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/pt-pt/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/pt-pt/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/pt-pt/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/pt/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/pt/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/pt-pt/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/pt-pt/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/pt/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/pt/HelpMenu':function(){
define('Sage/UI/Controls/nls/pt/HelpMenu',{});
},
'Sage/UI/Controls/nls/pt-pt/HelpMenu':function(){
define('Sage/UI/Controls/nls/pt-pt/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/pt/UserTasklet':function(){
define('Sage/TaskPane/nls/pt/UserTasklet',{});
},
'Sage/TaskPane/nls/pt-pt/UserTasklet':function(){
define('Sage/TaskPane/nls/pt-pt/UserTasklet',{});
},
'Sage/UI/Alarms/nls/pt/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/pt/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/pt-pt/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/pt-pt/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/pt/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/pt/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/pt-pt/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/pt-pt/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/pt/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/pt/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/pt-pt/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/pt-pt/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/pt/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/ColumnDesigner',{});
},
'Sage/UI/nls/pt/SearchMenuItem':function(){
define('Sage/UI/nls/pt/SearchMenuItem',{});
},
'Sage/UI/nls/pt-pt/SearchMenuItem':function(){
define('Sage/UI/nls/pt-pt/SearchMenuItem',{});
},
'Sage/UI/nls/pt/NotesHistoryList':function(){
define('Sage/UI/nls/pt/NotesHistoryList',{});
},
'Sage/UI/nls/pt-pt/NotesHistoryList':function(){
define('Sage/UI/nls/pt-pt/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/pt/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/pt/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/pt/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/pt-pt/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/pt-pt/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/pt/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/pt/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt-pt/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt-pt/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt-pt/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt-pt/HistoryEditor',{});
},
'Sage/Groups/nls/pt/GroupManager':function(){
define('Sage/Groups/nls/pt/GroupManager',{});
},
'Sage/Groups/nls/pt-pt/GroupManager':function(){
define('Sage/Groups/nls/pt-pt/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt-pt/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt-pt/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/pt/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/pt/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/pt/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/pt-pt/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/pt-pt/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/pt/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/pt-pt/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/pt-pt/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/pt/EditableGrid':function(){
define('Sage/UI/nls/pt/EditableGrid',{});
},
'Sage/UI/nls/pt-pt/EditableGrid':function(){
define('Sage/UI/nls/pt-pt/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/pt/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/pt/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/pt-pt/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/pt-pt/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/pt/SpeedSearch':function(){
define('Sage/UI/nls/pt/SpeedSearch',{});
},
'Sage/UI/nls/pt-pt/SpeedSearch':function(){
define('Sage/UI/nls/pt-pt/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/pt/SLXPreviewGrid':function(){
define('Sage/UI/nls/pt/SLXPreviewGrid',{});
},
'Sage/UI/nls/pt-pt/SLXPreviewGrid':function(){
define('Sage/UI/nls/pt-pt/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/pt/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/pt/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/pt-pt/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/pt-pt/UnconfirmedPane',{});
},
'Sage/Utility/nls/pt/Utility':function(){
define('Sage/Utility/nls/pt/Utility',{});
},
'Sage/Utility/nls/pt-pt/Utility':function(){
define('Sage/Utility/nls/pt-pt/Utility',{});
},
'Sage/QuickForms/Design/nls/pt/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/ControlDesigner',{});
},
'Sage/UI/Controls/nls/pt/Address':function(){
define('Sage/UI/Controls/nls/pt/Address',{});
},
'Sage/UI/Controls/nls/pt-pt/Address':function(){
define('Sage/UI/Controls/nls/pt-pt/Address',{});
},
'Sage/MainView/ActivityMgr/nls/pt/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt-pt/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt-pt/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/pt/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/OwnerControlDesigner',{});
},
'Sage/UI/nls/pt/UserType':function(){
define('Sage/UI/nls/pt/UserType',{});
},
'Sage/UI/nls/pt-pt/UserType':function(){
define('Sage/UI/nls/pt-pt/UserType',{});
},
'Sage/QuickForms/Design/nls/pt/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/pt-pt/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/pt-pt/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/pt/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/pt/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/pt-pt/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/pt-pt/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/pt/ActivityList':function(){
define('Sage/UI/nls/pt/ActivityList',{});
},
'Sage/UI/nls/pt-pt/ActivityList':function(){
define('Sage/UI/nls/pt-pt/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/pt/CalendarUsersListPane':function(){
define('Sage/UI/nls/pt/CalendarUsersListPane',{});
},
'Sage/UI/nls/pt-pt/CalendarUsersListPane':function(){
define('Sage/UI/nls/pt-pt/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/pt/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/pt/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/pt-pt/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/pt-pt/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/pt/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/pt-pt/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/pt-pt/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/pt/Attachment':function(){
define('Sage/Utility/File/nls/pt/Attachment',{});
},
'Sage/Utility/File/nls/pt-pt/Attachment':function(){
define('Sage/Utility/File/nls/pt-pt/Attachment',{});
},
'Sage/QuickForms/Design/nls/pt/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/pt/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/pt-pt/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/pt-pt/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/pt/Helper':function(){
define('Sage/MailMerge/nls/pt/Helper',{});
},
'Sage/MailMerge/nls/pt-pt/Helper':function(){
define('Sage/MailMerge/nls/pt-pt/Helper',{});
},
'Sage/UI/Dashboard/nls/pt/Dashboard':function(){
define('Sage/UI/Dashboard/nls/pt/Dashboard',{});
},
'Sage/UI/Dashboard/nls/pt-pt/Dashboard':function(){
define('Sage/UI/Dashboard/nls/pt-pt/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/pt/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/pt-pt/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/pt-pt/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/pt/PickList':function(){
define('Sage/UI/Controls/nls/pt/PickList',{});
},
'Sage/UI/Controls/nls/pt-pt/PickList':function(){
define('Sage/UI/Controls/nls/pt-pt/PickList',{});
},
'Sage/Utility/nls/pt/Email':function(){
define('Sage/Utility/nls/pt/Email',{});
},
'Sage/Utility/nls/pt-pt/Email':function(){
define('Sage/Utility/nls/pt-pt/Email',{});
},
'Sage/TaskPane/nls/pt/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/pt-pt/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/pt-pt/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/pt/TimeZoneItem':function(){
define('Sage/UI/nls/pt/TimeZoneItem',{});
},
'Sage/UI/nls/pt-pt/TimeZoneItem':function(){
define('Sage/UI/nls/pt-pt/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/pt/SlxEdit':function(){
define('Sage/UI/Columns/nls/pt/SlxEdit',{});
},
'Sage/UI/Columns/nls/pt-pt/SlxEdit':function(){
define('Sage/UI/Columns/nls/pt-pt/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/pt/LogOffButton':function(){
define('Sage/UI/Controls/nls/pt/LogOffButton',{});
},
'Sage/UI/Controls/nls/pt-pt/LogOffButton':function(){
define('Sage/UI/Controls/nls/pt-pt/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/pt-pt/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/pt-pt/EditEventEditor',{});
},
'Sage/MailMerge/nls/pt/Loader':function(){
define('Sage/MailMerge/nls/pt/Loader',{});
},
'Sage/MailMerge/nls/pt-pt/Loader':function(){
define('Sage/MailMerge/nls/pt-pt/Loader',{});
},
'Sage/UI/Controls/nls/pt/DateTimePicker':function(){
define('Sage/UI/Controls/nls/pt/DateTimePicker',{});
},
'Sage/UI/Controls/nls/pt-pt/DateTimePicker':function(){
define('Sage/UI/Controls/nls/pt-pt/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/pt/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/pt/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/pt-pt/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/pt-pt/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/pt/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/pt-pt/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/pt-pt/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/pt/Lookup':function(){
define('Sage/UI/Controls/nls/pt/Lookup',{});
},
'Sage/UI/Controls/nls/pt-pt/Lookup':function(){
define('Sage/UI/Controls/nls/pt-pt/Lookup',{});
},
'Sage/Utility/File/nls/pt/DescriptionsForm':function(){
define('Sage/Utility/File/nls/pt/DescriptionsForm',{});
},
'Sage/Utility/File/nls/pt-pt/DescriptionsForm':function(){
define('Sage/Utility/File/nls/pt-pt/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/pt/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/pt-pt/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/pt-pt/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/pt/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/pt/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/pt-pt/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/pt-pt/CommonTasksTasklet',{});
},
'Sage/Utility/nls/pt/Dashboard':function(){
define('Sage/Utility/nls/pt/Dashboard',{});
},
'Sage/Utility/nls/pt-pt/Dashboard':function(){
define('Sage/Utility/nls/pt-pt/Dashboard',{});
}}});
define("Sage/nls/Sage_pt-pt", [], 1);
