require({cache:{
'Sage/Utility/File/nls/af/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/af/FallbackFilePicker',{});
},
'Sage/UI/nls/af/Boolean':function(){
define('Sage/UI/nls/af/Boolean',{});
},
'Sage/Services/nls/af/ActivityService':function(){
define('Sage/Services/nls/af/ActivityService',{});
},
'Sage/UI/Controls/nls/af/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/af/CopyToClipboard',{});
},
'Sage/Utility/nls/af/Activity':function(){
define('Sage/Utility/nls/af/Activity',{});
},
'Sage/QuickForms/Design/nls/af/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/af/DesignPanel',{});
},
'Sage/UI/nls/af/TimelessActivitiesPane':function(){
define('Sage/UI/nls/af/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/af/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/ActivityEditor',{});
},
'Sage/MainView/nls/af/ActivityManager':function(){
define('Sage/MainView/nls/af/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/af/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/af/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/_PropertyEditor',{});
},
'Sage/Services/nls/af/ActivityActionProcessor':function(){
define('Sage/Services/nls/af/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/af/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/af/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/af/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/af/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/af/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/af/AlarmPane':function(){
define('Sage/UI/Alarms/nls/af/AlarmPane',{});
},
'Sage/TaskPane/nls/af/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/af/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/af/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/af/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/af/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/af/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/af/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/af/FilterPanel':function(){
define('Sage/UI/Filters/nls/af/FilterPanel',{});
},
'Sage/TaskPane/nls/af/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/af/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/af/OwnerType':function(){
define('Sage/UI/nls/af/OwnerType',{});
},
'Sage/TaskPane/nls/af/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/af/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/af/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/af/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/af/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/af/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/af/InvoiceRTDV',{});
},
'Sage/UI/nls/af/SDataLookup':function(){
define('Sage/UI/nls/af/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/af/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/af/RowDesigner',{});
},
'Sage/TaskPane/nls/af/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/af/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/af/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/af/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/af/LibraryDocument':function(){
define('Sage/Utility/File/nls/af/LibraryDocument',{});
},
'Sage/UI/nls/af/ConditionManager':function(){
define('Sage/UI/nls/af/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/af/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/af/WidgetDefinition',{});
},
'Sage/UI/nls/af/SearchConditionWidget':function(){
define('Sage/UI/nls/af/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/af/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/af/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/af/DataSourcePanel',{});
},
'Sage/UI/nls/af/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/af/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/af/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/af/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/af/Name':function(){
define('Sage/UI/Controls/nls/af/Name',{});
},
'Sage/QuickForms/Design/nls/af/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/af/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/af/UpdateLeads',{});
},
'Sage/UI/nls/af/ListPanel':function(){
define('Sage/UI/nls/af/ListPanel',{});
},
'Sage/UI/Filters/nls/af/EditFilters':function(){
define('Sage/UI/Filters/nls/af/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/af/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/af/DurationSelect':function(){
define('Sage/UI/Controls/nls/af/DurationSelect',{});
},
'Sage/UI/Alarms/nls/af/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/af/AlarmCountDown',{});
},
'Sage/UI/nls/af/AttachmentList':function(){
define('Sage/UI/nls/af/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/af/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/af/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/af/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/af/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/af/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/af/Dialogs':function(){
define('Sage/UI/nls/af/Dialogs',{});
},
'Sage/TaskPane/nls/af/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/af/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/af/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/af/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/af/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/af/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/af/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/UserControlDesigner',{});
},
'Sage/Groups/nls/af/GroupNavigator':function(){
define('Sage/Groups/nls/af/GroupNavigator',{});
},
'Sage/Utility/File/nls/af/AddURLAttachment':function(){
define('Sage/Utility/File/nls/af/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/af/EditFilterItems':function(){
define('Sage/UI/Filters/nls/af/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/af/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/af/DesignSurface',{});
},
'Sage/Utility/File/nls/af/DragDropWatcher':function(){
define('Sage/Utility/File/nls/af/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/af/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/af/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/EventListPanelConfig',{});
},
'Sage/UI/nls/af/ActivityScheduler':function(){
define('Sage/UI/nls/af/ActivityScheduler',{});
},
'Sage/MainView/nls/af/SecurityManager':function(){
define('Sage/MainView/nls/af/SecurityManager',{});
},
'Sage/TaskPane/nls/af/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/af/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/af/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/af/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/af/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/af/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/af/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/af/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/af/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/af/HelpMenu':function(){
define('Sage/UI/Controls/nls/af/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/af/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/af/UserTasklet':function(){
define('Sage/TaskPane/nls/af/UserTasklet',{});
},
'Sage/UI/Alarms/nls/af/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/af/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/af/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/af/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/af/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/af/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/af/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/af/ColumnDesigner',{});
},
'Sage/UI/nls/af/SearchMenuItem':function(){
define('Sage/UI/nls/af/SearchMenuItem',{});
},
'Sage/UI/nls/af/NotesHistoryList':function(){
define('Sage/UI/nls/af/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/af/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/af/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/af/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/af/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/af/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/af/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/HistoryEditor',{});
},
'Sage/Groups/nls/af/GroupManager':function(){
define('Sage/Groups/nls/af/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/af/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/af/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/af/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/af/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/af/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/af/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/af/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/af/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/af/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/af/EditableGrid':function(){
define('Sage/UI/nls/af/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/af/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/af/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/af/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/af/SpeedSearch':function(){
define('Sage/UI/nls/af/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/af/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/af/SLXPreviewGrid':function(){
define('Sage/UI/nls/af/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/af/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/af/UnconfirmedPane',{});
},
'Sage/Utility/nls/af/Utility':function(){
define('Sage/Utility/nls/af/Utility',{});
},
'Sage/QuickForms/Design/nls/af/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/ControlDesigner',{});
},
'Sage/UI/Controls/nls/af/Address':function(){
define('Sage/UI/Controls/nls/af/Address',{});
},
'Sage/MainView/ActivityMgr/nls/af/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/af/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/OwnerControlDesigner',{});
},
'Sage/UI/nls/af/UserType':function(){
define('Sage/UI/nls/af/UserType',{});
},
'Sage/QuickForms/Design/nls/af/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/af/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/af/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/af/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/af/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/af/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/af/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/af/ActivityList':function(){
define('Sage/UI/nls/af/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/af/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/af/CalendarUsersListPane':function(){
define('Sage/UI/nls/af/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/af/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/af/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/af/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/af/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/af/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/af/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/af/Attachment':function(){
define('Sage/Utility/File/nls/af/Attachment',{});
},
'Sage/QuickForms/Design/nls/af/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/af/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/af/Helper':function(){
define('Sage/MailMerge/nls/af/Helper',{});
},
'Sage/UI/Dashboard/nls/af/Dashboard':function(){
define('Sage/UI/Dashboard/nls/af/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/af/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/af/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/af/PickList':function(){
define('Sage/UI/Controls/nls/af/PickList',{});
},
'Sage/Utility/nls/af/Email':function(){
define('Sage/Utility/nls/af/Email',{});
},
'Sage/TaskPane/nls/af/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/af/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/af/TimeZoneItem':function(){
define('Sage/UI/nls/af/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/af/SlxEdit':function(){
define('Sage/UI/Columns/nls/af/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/af/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/af/LogOffButton':function(){
define('Sage/UI/Controls/nls/af/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/af/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/af/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/af/EditEventEditor',{});
},
'Sage/MailMerge/nls/af/Loader':function(){
define('Sage/MailMerge/nls/af/Loader',{});
},
'Sage/UI/Controls/nls/af/DateTimePicker':function(){
define('Sage/UI/Controls/nls/af/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/af/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/af/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/af/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/af/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/af/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/af/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/af/Lookup':function(){
define('Sage/UI/Controls/nls/af/Lookup',{});
},
'Sage/Utility/File/nls/af/DescriptionsForm':function(){
define('Sage/Utility/File/nls/af/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/af/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/af/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/af/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/af/CommonTasksTasklet',{});
},
'Sage/Utility/nls/af/Dashboard':function(){
define('Sage/Utility/nls/af/Dashboard',{});
}}});
define("Sage/nls/Sage_af", [], 1);
