require({cache:{
'Sage/Utility/File/nls/zh/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zh/FallbackFilePicker',{});
},
'Sage/Utility/File/nls/zh-cn/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/zh-cn/FallbackFilePicker',{});
},
'Sage/UI/nls/zh/Boolean':function(){
define('Sage/UI/nls/zh/Boolean',{});
},
'Sage/UI/nls/zh-cn/Boolean':function(){
define('Sage/UI/nls/zh-cn/Boolean',{});
},
'Sage/Services/nls/zh/ActivityService':function(){
define('Sage/Services/nls/zh/ActivityService',{});
},
'Sage/Services/nls/zh-cn/ActivityService':function(){
define('Sage/Services/nls/zh-cn/ActivityService',{});
},
'Sage/UI/Controls/nls/zh/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zh/CopyToClipboard',{});
},
'Sage/UI/Controls/nls/zh-cn/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/zh-cn/CopyToClipboard',{});
},
'Sage/Utility/nls/zh/Activity':function(){
define('Sage/Utility/nls/zh/Activity',{});
},
'Sage/Utility/nls/zh-cn/Activity':function(){
define('Sage/Utility/nls/zh-cn/Activity',{});
},
'Sage/QuickForms/Design/nls/zh/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/zh/DesignPanel',{});
},
'Sage/QuickForms/Design/nls/zh-cn/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/zh-cn/DesignPanel',{});
},
'Sage/UI/nls/zh/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zh/TimelessActivitiesPane',{});
},
'Sage/UI/nls/zh-cn/TimelessActivitiesPane':function(){
define('Sage/UI/nls/zh-cn/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-cn/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-cn/ActivityEditor',{});
},
'Sage/MainView/nls/zh/ActivityManager':function(){
define('Sage/MainView/nls/zh/ActivityManager',{});
},
'Sage/MainView/nls/zh-cn/ActivityManager':function(){
define('Sage/MainView/nls/zh-cn/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/zh/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/_PropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/_PropertyEditor',{});
},
'Sage/Services/nls/zh/ActivityActionProcessor':function(){
define('Sage/Services/nls/zh/ActivityActionProcessor',{});
},
'Sage/Services/nls/zh-cn/ActivityActionProcessor':function(){
define('Sage/Services/nls/zh-cn/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/TextBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/QuickCompleteEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-cn/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-cn/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/zh/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zh/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/zh-cn/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/zh-cn/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/zh/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zh/AttachmentPropertiesEditForm',{});
},
'Sage/Utility/File/nls/zh-cn/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/zh-cn/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/zh/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zh/AlarmPane',{});
},
'Sage/UI/Alarms/nls/zh-cn/AlarmPane':function(){
define('Sage/UI/Alarms/nls/zh-cn/AlarmPane',{});
},
'Sage/TaskPane/nls/zh/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zh/LiteratureManagementTasks',{});
},
'Sage/TaskPane/nls/zh-cn/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/zh-cn/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardWidget',{});
},
'Sage/UI/Dashboard/nls/zh-cn/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/zh-cn/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NumericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/CustomerPaymentsRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zh-cn/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh-cn/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/zh/FilterPanel':function(){
define('Sage/UI/Filters/nls/zh/FilterPanel',{});
},
'Sage/UI/Filters/nls/zh-cn/FilterPanel':function(){
define('Sage/UI/Filters/nls/zh-cn/FilterPanel',{});
},
'Sage/TaskPane/nls/zh/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zh/_BaseTaskPaneTasklet',{});
},
'Sage/TaskPane/nls/zh-cn/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/zh-cn/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/zh/OwnerType':function(){
define('Sage/UI/nls/zh/OwnerType',{});
},
'Sage/UI/nls/zh-cn/OwnerType':function(){
define('Sage/UI/nls/zh-cn/OwnerType',{});
},
'Sage/TaskPane/nls/zh/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/LeadTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-cn/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-cn/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/zh/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/zh/SnoozeOptions',{});
},
'Sage/MainView/ActivityMgr/nls/zh-cn/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/zh-cn/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/InvoiceRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zh-cn/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh-cn/InvoiceRTDV',{});
},
'Sage/UI/nls/zh/SDataLookup':function(){
define('Sage/UI/nls/zh/SDataLookup',{});
},
'Sage/UI/nls/zh-cn/SDataLookup':function(){
define('Sage/UI/nls/zh-cn/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/zh/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/RowDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/RowDesigner',{});
},
'Sage/TaskPane/nls/zh/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/OpportunityTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-cn/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-cn/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/zh/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zh/CheckBoxFilter',{});
},
'Sage/UI/Filters/nls/zh-cn/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/zh-cn/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/zh/LibraryDocument':function(){
define('Sage/Utility/File/nls/zh/LibraryDocument',{});
},
'Sage/Utility/File/nls/zh-cn/LibraryDocument':function(){
define('Sage/Utility/File/nls/zh-cn/LibraryDocument',{});
},
'Sage/UI/nls/zh/ConditionManager':function(){
define('Sage/UI/nls/zh/ConditionManager',{});
},
'Sage/UI/nls/zh-cn/ConditionManager':function(){
define('Sage/UI/nls/zh-cn/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/zh/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zh/WidgetDefinition',{});
},
'Sage/UI/Dashboard/nls/zh-cn/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/zh-cn/WidgetDefinition',{});
},
'Sage/UI/nls/zh/SearchConditionWidget':function(){
define('Sage/UI/nls/zh/SearchConditionWidget',{});
},
'Sage/UI/nls/zh-cn/SearchConditionWidget':function(){
define('Sage/UI/nls/zh-cn/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/zh/DataSourcePanel',{});
},
'Sage/QuickForms/Design/nls/zh-cn/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/zh-cn/DataSourcePanel',{});
},
'Sage/UI/nls/zh/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zh/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/nls/zh-cn/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/zh-cn/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/zh/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/zh/NonVisibleControlContainer',{});
},
'Sage/QuickForms/Design/nls/zh-cn/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/zh-cn/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/zh/Name':function(){
define('Sage/UI/Controls/nls/zh/Name',{});
},
'Sage/UI/Controls/nls/zh-cn/Name':function(){
define('Sage/UI/Controls/nls/zh-cn/Name',{});
},
'Sage/QuickForms/Design/nls/zh/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/PhoneControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/zh/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zh/UpdateLeads',{});
},
'Sage/MainView/Lead/nls/zh-cn/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/zh-cn/UpdateLeads',{});
},
'Sage/UI/nls/zh/ListPanel':function(){
define('Sage/UI/nls/zh/ListPanel',{});
},
'Sage/UI/nls/zh-cn/ListPanel':function(){
define('Sage/UI/nls/zh-cn/ListPanel',{});
},
'Sage/UI/Filters/nls/zh/EditFilters':function(){
define('Sage/UI/Filters/nls/zh/EditFilters',{});
},
'Sage/UI/Filters/nls/zh-cn/EditFilters':function(){
define('Sage/UI/Filters/nls/zh-cn/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormUsagesPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/zh/DurationSelect':function(){
define('Sage/UI/Controls/nls/zh/DurationSelect',{});
},
'Sage/UI/Controls/nls/zh-cn/DurationSelect':function(){
define('Sage/UI/Controls/nls/zh-cn/DurationSelect',{});
},
'Sage/UI/Alarms/nls/zh/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zh/AlarmCountDown',{});
},
'Sage/UI/Alarms/nls/zh-cn/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/zh-cn/AlarmCountDown',{});
},
'Sage/UI/nls/zh/AttachmentList':function(){
define('Sage/UI/nls/zh/AttachmentList',{});
},
'Sage/UI/nls/zh-cn/AttachmentList':function(){
define('Sage/UI/nls/zh-cn/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/HiddenControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardWidgetCell',{});
},
'Sage/UI/Dashboard/nls/zh-cn/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/zh-cn/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/UserBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/zh/Dialogs':function(){
define('Sage/UI/nls/zh/Dialogs',{});
},
'Sage/UI/nls/zh-cn/Dialogs':function(){
define('Sage/UI/nls/zh-cn/Dialogs',{});
},
'Sage/TaskPane/nls/zh/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zh/SecuredActionTasklet',{});
},
'Sage/TaskPane/nls/zh-cn/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/zh-cn/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/zh/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zh/DashboardTabController',{});
},
'Sage/UI/Dashboard/nls/zh-cn/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/zh-cn/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/zh/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh/SalesOrderRTDV',{});
},
'Sage/MainView/IntegrationContract/nls/zh-cn/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/zh-cn/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/zh/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/UserControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/UserControlDesigner',{});
},
'Sage/Groups/nls/zh/GroupNavigator':function(){
define('Sage/Groups/nls/zh/GroupNavigator',{});
},
'Sage/Groups/nls/zh-cn/GroupNavigator':function(){
define('Sage/Groups/nls/zh-cn/GroupNavigator',{});
},
'Sage/Utility/File/nls/zh/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zh/AddURLAttachment',{});
},
'Sage/Utility/File/nls/zh-cn/AddURLAttachment':function(){
define('Sage/Utility/File/nls/zh-cn/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/zh/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zh/EditFilterItems',{});
},
'Sage/UI/Filters/nls/zh-cn/EditFilterItems':function(){
define('Sage/UI/Filters/nls/zh-cn/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/zh/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/zh/DesignSurface',{});
},
'Sage/QuickForms/Design/nls/zh-cn/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/zh-cn/DesignSurface',{});
},
'Sage/Utility/File/nls/zh/DragDropWatcher':function(){
define('Sage/Utility/File/nls/zh/DragDropWatcher',{});
},
'Sage/Utility/File/nls/zh-cn/DragDropWatcher':function(){
define('Sage/Utility/File/nls/zh-cn/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-cn/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-cn/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/EventListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-cn/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-cn/EventListPanelConfig',{});
},
'Sage/UI/nls/zh/ActivityScheduler':function(){
define('Sage/UI/nls/zh/ActivityScheduler',{});
},
'Sage/UI/nls/zh-cn/ActivityScheduler':function(){
define('Sage/UI/nls/zh-cn/ActivityScheduler',{});
},
'Sage/MainView/nls/zh/SecurityManager':function(){
define('Sage/MainView/nls/zh/SecurityManager',{});
},
'Sage/MainView/nls/zh-cn/SecurityManager':function(){
define('Sage/MainView/nls/zh-cn/SecurityManager',{});
},
'Sage/TaskPane/nls/zh/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zh/ActivityTaskConfigurationProvider',{});
},
'Sage/TaskPane/nls/zh-cn/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/zh-cn/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/zh/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/zh/EntityInfoToolTip',{});
},
'Sage/UI/Controls/nls/zh-cn/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/zh-cn/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityGroupContextService',{});
},
'Sage/MainView/ActivityMgr/nls/zh-cn/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/zh-cn/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/zh/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zh/UpdateOpportunities',{});
},
'Sage/MainView/Opportunity/nls/zh-cn/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/zh-cn/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/zh/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/DateTimePickerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/HelpMenu':function(){
define('Sage/UI/Controls/nls/zh/HelpMenu',{});
},
'Sage/UI/Controls/nls/zh-cn/HelpMenu':function(){
define('Sage/UI/Controls/nls/zh-cn/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/LayoutPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/UserTasklet':function(){
define('Sage/TaskPane/nls/zh/UserTasklet',{});
},
'Sage/TaskPane/nls/zh-cn/UserTasklet':function(){
define('Sage/TaskPane/nls/zh-cn/UserTasklet',{});
},
'Sage/UI/Alarms/nls/zh/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zh/ActivityAlarm',{});
},
'Sage/UI/Alarms/nls/zh-cn/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/zh-cn/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/zh/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zh/OpportunityStatistics',{});
},
'Sage/MainView/Opportunity/nls/zh-cn/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/zh-cn/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/zh/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/zh/AdvancedSearchOptions',{});
},
'Sage/MainView/IntegrationContract/nls/zh-cn/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/zh-cn/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/zh/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ColumnDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/ColumnDesigner',{});
},
'Sage/UI/nls/zh/SearchMenuItem':function(){
define('Sage/UI/nls/zh/SearchMenuItem',{});
},
'Sage/UI/nls/zh-cn/SearchMenuItem':function(){
define('Sage/UI/nls/zh-cn/SearchMenuItem',{});
},
'Sage/UI/nls/zh/NotesHistoryList':function(){
define('Sage/UI/nls/zh/NotesHistoryList',{});
},
'Sage/UI/nls/zh-cn/NotesHistoryList':function(){
define('Sage/UI/nls/zh-cn/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/zh/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/UrlControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/zh/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zh/GoogleDocPicker',{});
},
'Sage/Utility/File/nls/zh-cn/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/zh-cn/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/zh/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ComboBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zh/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-cn/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-cn/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/HistoryEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-cn/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-cn/HistoryEditor',{});
},
'Sage/Groups/nls/zh/GroupManager':function(){
define('Sage/Groups/nls/zh/GroupManager',{});
},
'Sage/Groups/nls/zh-cn/GroupManager':function(){
define('Sage/Groups/nls/zh-cn/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ComboBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/RecurringEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-cn/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-cn/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/zh/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zh/ContactSearchForDuplicates',{});
},
'Sage/MainView/Contact/nls/zh-cn/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/zh-cn/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DateTimePickerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/AccountingTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-cn/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-cn/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CurrencyBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/zh/EditableGrid':function(){
define('Sage/UI/nls/zh/EditableGrid',{});
},
'Sage/UI/nls/zh-cn/EditableGrid':function(){
define('Sage/UI/nls/zh-cn/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/zh/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/zh/SecurityProfile',{});
},
'Sage/MainView/SecurityMgr/nls/zh-cn/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/zh-cn/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/UserAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/SpeedSearch':function(){
define('Sage/UI/nls/zh/SpeedSearch',{});
},
'Sage/UI/nls/zh-cn/SpeedSearch':function(){
define('Sage/UI/nls/zh-cn/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CurrencyAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/SLXPreviewGrid':function(){
define('Sage/UI/nls/zh/SLXPreviewGrid',{});
},
'Sage/UI/nls/zh-cn/SLXPreviewGrid':function(){
define('Sage/UI/nls/zh-cn/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/zh/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zh/UnconfirmedPane',{});
},
'Sage/UI/Alarms/nls/zh-cn/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/zh-cn/UnconfirmedPane',{});
},
'Sage/Utility/nls/zh/Utility':function(){
define('Sage/Utility/nls/zh/Utility',{});
},
'Sage/Utility/nls/zh-cn/Utility':function(){
define('Sage/Utility/nls/zh-cn/Utility',{});
},
'Sage/QuickForms/Design/nls/zh/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/ControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/ControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/Address':function(){
define('Sage/UI/Controls/nls/zh/Address',{});
},
'Sage/UI/Controls/nls/zh-cn/Address':function(){
define('Sage/UI/Controls/nls/zh-cn/Address',{});
},
'Sage/MainView/ActivityMgr/nls/zh/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/BaseListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-cn/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-cn/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/zh/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/OwnerControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/OwnerControlDesigner',{});
},
'Sage/UI/nls/zh/UserType':function(){
define('Sage/UI/nls/zh/UserType',{});
},
'Sage/UI/nls/zh-cn/UserType':function(){
define('Sage/UI/nls/zh-cn/UserType',{});
},
'Sage/QuickForms/Design/nls/zh/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/FormDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityCalendar',{});
},
'Sage/MainView/ActivityMgr/nls/zh-cn/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/zh-cn/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/zh/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zh/_DialogHelpIconMixin',{});
},
'Sage/UI/Controls/nls/zh-cn/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/zh-cn/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/PickListAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/ActivityList':function(){
define('Sage/UI/nls/zh/ActivityList',{});
},
'Sage/UI/nls/zh-cn/ActivityList':function(){
define('Sage/UI/nls/zh-cn/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/GenericAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/zh/CalendarUsersListPane':function(){
define('Sage/UI/nls/zh/CalendarUsersListPane',{});
},
'Sage/UI/nls/zh-cn/CalendarUsersListPane':function(){
define('Sage/UI/nls/zh-cn/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/ColumnBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/zh/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/zh/MatchingOptionsConfig',{});
},
'Sage/MainView/IntegrationContract/nls/zh-cn/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/zh-cn/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/FormBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zh/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/MainView/ActivityMgr/nls/zh-cn/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/zh-cn/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/zh/Attachment':function(){
define('Sage/Utility/File/nls/zh/Attachment',{});
},
'Sage/Utility/File/nls/zh-cn/Attachment':function(){
define('Sage/Utility/File/nls/zh-cn/Attachment',{});
},
'Sage/QuickForms/Design/nls/zh/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/zh/PropertyEditorContainer',{});
},
'Sage/QuickForms/Design/nls/zh-cn/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/zh-cn/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/zh/Helper':function(){
define('Sage/MailMerge/nls/zh/Helper',{});
},
'Sage/MailMerge/nls/zh-cn/Helper':function(){
define('Sage/MailMerge/nls/zh-cn/Helper',{});
},
'Sage/UI/Dashboard/nls/zh/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zh/Dashboard',{});
},
'Sage/UI/Dashboard/nls/zh-cn/Dashboard':function(){
define('Sage/UI/Dashboard/nls/zh-cn/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/zh/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh/ActivityListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/zh-cn/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/zh-cn/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/zh/PickList':function(){
define('Sage/UI/Controls/nls/zh/PickList',{});
},
'Sage/UI/Controls/nls/zh-cn/PickList':function(){
define('Sage/UI/Controls/nls/zh-cn/PickList',{});
},
'Sage/Utility/nls/zh/Email':function(){
define('Sage/Utility/nls/zh/Email',{});
},
'Sage/Utility/nls/zh-cn/Email':function(){
define('Sage/Utility/nls/zh-cn/Email',{});
},
'Sage/TaskPane/nls/zh/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/SecurityManagerTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-cn/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-cn/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/zh/TimeZoneItem':function(){
define('Sage/UI/nls/zh/TimeZoneItem',{});
},
'Sage/UI/nls/zh-cn/TimeZoneItem':function(){
define('Sage/UI/nls/zh-cn/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/zh/SlxEdit':function(){
define('Sage/UI/Columns/nls/zh/SlxEdit',{});
},
'Sage/UI/Columns/nls/zh-cn/SlxEdit':function(){
define('Sage/UI/Columns/nls/zh-cn/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/zh/LogOffButton':function(){
define('Sage/UI/Controls/nls/zh/LogOffButton',{});
},
'Sage/UI/Controls/nls/zh-cn/LogOffButton':function(){
define('Sage/UI/Controls/nls/zh-cn/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/TextBoxAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh/EditEventEditor',{});
},
'Sage/MainView/ActivityMgr/nls/zh-cn/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/zh-cn/EditEventEditor',{});
},
'Sage/MailMerge/nls/zh/Loader':function(){
define('Sage/MailMerge/nls/zh/Loader',{});
},
'Sage/MailMerge/nls/zh-cn/Loader':function(){
define('Sage/MailMerge/nls/zh-cn/Loader',{});
},
'Sage/UI/Controls/nls/zh/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zh/DateTimePicker',{});
},
'Sage/UI/Controls/nls/zh-cn/DateTimePicker':function(){
define('Sage/UI/Controls/nls/zh-cn/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/zh/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zh/AlarmPopup',{});
},
'Sage/UI/Alarms/nls/zh-cn/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/zh-cn/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/zh/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh/EmailControlDesigner',{});
},
'Sage/QuickForms/Design/nls/zh-cn/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/zh-cn/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/zh/Lookup':function(){
define('Sage/UI/Controls/nls/zh/Lookup',{});
},
'Sage/UI/Controls/nls/zh-cn/Lookup':function(){
define('Sage/UI/Controls/nls/zh-cn/Lookup',{});
},
'Sage/Utility/File/nls/zh/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zh/DescriptionsForm',{});
},
'Sage/Utility/File/nls/zh-cn/DescriptionsForm':function(){
define('Sage/Utility/File/nls/zh-cn/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/zh/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh/NumericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/zh-cn/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/zh-cn/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/zh/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zh/CommonTasksTasklet',{});
},
'Sage/TaskPane/nls/zh-cn/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/zh-cn/CommonTasksTasklet',{});
},
'Sage/Utility/nls/zh/Dashboard':function(){
define('Sage/Utility/nls/zh/Dashboard',{});
},
'Sage/Utility/nls/zh-cn/Dashboard':function(){
define('Sage/Utility/nls/zh-cn/Dashboard',{});
}}});
define("Sage/nls/Sage_zh-cn", [], 1);
