require({cache:{
'Sage/Utility/File/nls/el/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/el/FallbackFilePicker',{});
},
'Sage/UI/nls/el/Boolean':function(){
define('Sage/UI/nls/el/Boolean',{});
},
'Sage/Services/nls/el/ActivityService':function(){
define('Sage/Services/nls/el/ActivityService',{});
},
'Sage/UI/Controls/nls/el/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/el/CopyToClipboard',{});
},
'Sage/Utility/nls/el/Activity':function(){
define('Sage/Utility/nls/el/Activity',{});
},
'Sage/QuickForms/Design/nls/el/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/el/DesignPanel',{});
},
'Sage/UI/nls/el/TimelessActivitiesPane':function(){
define('Sage/UI/nls/el/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/el/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/el/ActivityEditor',{});
},
'Sage/MainView/nls/el/ActivityManager':function(){
define('Sage/MainView/nls/el/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/el/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/el/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/_PropertyEditor',{});
},
'Sage/Services/nls/el/ActivityActionProcessor':function(){
define('Sage/Services/nls/el/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/el/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/el/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/el/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/el/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/el/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/el/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/el/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/el/AlarmPane':function(){
define('Sage/UI/Alarms/nls/el/AlarmPane',{});
},
'Sage/TaskPane/nls/el/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/el/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/el/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/el/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/el/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/el/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/el/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/el/FilterPanel':function(){
define('Sage/UI/Filters/nls/el/FilterPanel',{});
},
'Sage/TaskPane/nls/el/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/el/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/el/OwnerType':function(){
define('Sage/UI/nls/el/OwnerType',{});
},
'Sage/TaskPane/nls/el/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/el/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/el/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/el/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/el/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/el/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/el/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/el/InvoiceRTDV',{});
},
'Sage/UI/nls/el/SDataLookup':function(){
define('Sage/UI/nls/el/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/el/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/el/RowDesigner',{});
},
'Sage/TaskPane/nls/el/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/el/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/el/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/el/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/el/LibraryDocument':function(){
define('Sage/Utility/File/nls/el/LibraryDocument',{});
},
'Sage/UI/nls/el/ConditionManager':function(){
define('Sage/UI/nls/el/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/el/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/el/WidgetDefinition',{});
},
'Sage/UI/nls/el/SearchConditionWidget':function(){
define('Sage/UI/nls/el/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/el/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/el/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/el/DataSourcePanel',{});
},
'Sage/UI/nls/el/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/el/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/el/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/el/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/el/Name':function(){
define('Sage/UI/Controls/nls/el/Name',{});
},
'Sage/QuickForms/Design/nls/el/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/el/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/el/UpdateLeads',{});
},
'Sage/UI/nls/el/ListPanel':function(){
define('Sage/UI/nls/el/ListPanel',{});
},
'Sage/UI/Filters/nls/el/EditFilters':function(){
define('Sage/UI/Filters/nls/el/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/el/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/el/DurationSelect':function(){
define('Sage/UI/Controls/nls/el/DurationSelect',{});
},
'Sage/UI/Alarms/nls/el/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/el/AlarmCountDown',{});
},
'Sage/UI/nls/el/AttachmentList':function(){
define('Sage/UI/nls/el/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/el/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/el/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/el/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/el/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/el/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/el/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/el/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/el/Dialogs':function(){
define('Sage/UI/nls/el/Dialogs',{});
},
'Sage/TaskPane/nls/el/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/el/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/el/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/el/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/el/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/el/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/el/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/UserControlDesigner',{});
},
'Sage/Groups/nls/el/GroupNavigator':function(){
define('Sage/Groups/nls/el/GroupNavigator',{});
},
'Sage/Utility/File/nls/el/AddURLAttachment':function(){
define('Sage/Utility/File/nls/el/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/el/EditFilterItems':function(){
define('Sage/UI/Filters/nls/el/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/el/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/el/DesignSurface',{});
},
'Sage/Utility/File/nls/el/DragDropWatcher':function(){
define('Sage/Utility/File/nls/el/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/el/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/el/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/el/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/el/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/el/EventListPanelConfig',{});
},
'Sage/UI/nls/el/ActivityScheduler':function(){
define('Sage/UI/nls/el/ActivityScheduler',{});
},
'Sage/MainView/nls/el/SecurityManager':function(){
define('Sage/MainView/nls/el/SecurityManager',{});
},
'Sage/TaskPane/nls/el/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/el/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/el/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/el/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/el/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/el/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/el/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/el/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/el/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/el/HelpMenu':function(){
define('Sage/UI/Controls/nls/el/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/el/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/el/UserTasklet':function(){
define('Sage/TaskPane/nls/el/UserTasklet',{});
},
'Sage/UI/Alarms/nls/el/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/el/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/el/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/el/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/el/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/el/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/el/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/el/ColumnDesigner',{});
},
'Sage/UI/nls/el/SearchMenuItem':function(){
define('Sage/UI/nls/el/SearchMenuItem',{});
},
'Sage/UI/nls/el/NotesHistoryList':function(){
define('Sage/UI/nls/el/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/el/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/el/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/el/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/el/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/el/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/el/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/el/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/el/HistoryEditor',{});
},
'Sage/Groups/nls/el/GroupManager':function(){
define('Sage/Groups/nls/el/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/el/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/el/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/el/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/el/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/el/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/el/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/el/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/el/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/el/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/el/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/el/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/el/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/el/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/el/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/el/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/el/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/el/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/el/EditableGrid':function(){
define('Sage/UI/nls/el/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/el/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/el/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/el/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/el/SpeedSearch':function(){
define('Sage/UI/nls/el/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/el/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/el/SLXPreviewGrid':function(){
define('Sage/UI/nls/el/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/el/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/el/UnconfirmedPane',{});
},
'Sage/Utility/nls/el/Utility':function(){
define('Sage/Utility/nls/el/Utility',{});
},
'Sage/QuickForms/Design/nls/el/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/ControlDesigner',{});
},
'Sage/UI/Controls/nls/el/Address':function(){
define('Sage/UI/Controls/nls/el/Address',{});
},
'Sage/MainView/ActivityMgr/nls/el/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/el/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/el/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/OwnerControlDesigner',{});
},
'Sage/UI/nls/el/UserType':function(){
define('Sage/UI/nls/el/UserType',{});
},
'Sage/QuickForms/Design/nls/el/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/el/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/el/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/el/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/el/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/el/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/el/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/el/ActivityList':function(){
define('Sage/UI/nls/el/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/el/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/el/CalendarUsersListPane':function(){
define('Sage/UI/nls/el/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/el/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/el/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/el/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/el/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/el/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/el/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/el/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/el/Attachment':function(){
define('Sage/Utility/File/nls/el/Attachment',{});
},
'Sage/QuickForms/Design/nls/el/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/el/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/el/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/el/Helper':function(){
define('Sage/MailMerge/nls/el/Helper',{});
},
'Sage/UI/Dashboard/nls/el/Dashboard':function(){
define('Sage/UI/Dashboard/nls/el/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/el/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/el/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/el/PickList':function(){
define('Sage/UI/Controls/nls/el/PickList',{});
},
'Sage/Utility/nls/el/Email':function(){
define('Sage/Utility/nls/el/Email',{});
},
'Sage/TaskPane/nls/el/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/el/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/el/TimeZoneItem':function(){
define('Sage/UI/nls/el/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/el/SlxEdit':function(){
define('Sage/UI/Columns/nls/el/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/el/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/el/LogOffButton':function(){
define('Sage/UI/Controls/nls/el/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/el/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/el/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/el/EditEventEditor',{});
},
'Sage/MailMerge/nls/el/Loader':function(){
define('Sage/MailMerge/nls/el/Loader',{});
},
'Sage/UI/Controls/nls/el/DateTimePicker':function(){
define('Sage/UI/Controls/nls/el/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/el/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/el/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/el/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/el/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/el/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/el/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/el/Lookup':function(){
define('Sage/UI/Controls/nls/el/Lookup',{});
},
'Sage/Utility/File/nls/el/DescriptionsForm':function(){
define('Sage/Utility/File/nls/el/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/el/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/el/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/el/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/el/CommonTasksTasklet',{});
},
'Sage/Utility/nls/el/Dashboard':function(){
define('Sage/Utility/nls/el/Dashboard',{});
}}});
define("Sage/nls/Sage_el", [], 1);
