require({cache:{
'Sage/Utility/File/nls/da/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/da/FallbackFilePicker',{});
},
'Sage/UI/nls/da/Boolean':function(){
define('Sage/UI/nls/da/Boolean',{});
},
'Sage/Services/nls/da/ActivityService':function(){
define('Sage/Services/nls/da/ActivityService',{});
},
'Sage/UI/Controls/nls/da/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/da/CopyToClipboard',{});
},
'Sage/Utility/nls/da/Activity':function(){
define('Sage/Utility/nls/da/Activity',{});
},
'Sage/QuickForms/Design/nls/da/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/da/DesignPanel',{});
},
'Sage/UI/nls/da/TimelessActivitiesPane':function(){
define('Sage/UI/nls/da/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/da/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/da/ActivityEditor',{});
},
'Sage/MainView/nls/da/ActivityManager':function(){
define('Sage/MainView/nls/da/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/da/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/da/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/_PropertyEditor',{});
},
'Sage/Services/nls/da/ActivityActionProcessor':function(){
define('Sage/Services/nls/da/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/da/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/da/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/da/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/da/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/da/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/da/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/da/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/da/AlarmPane':function(){
define('Sage/UI/Alarms/nls/da/AlarmPane',{});
},
'Sage/TaskPane/nls/da/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/da/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/da/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/da/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/da/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/da/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/da/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/da/FilterPanel':function(){
define('Sage/UI/Filters/nls/da/FilterPanel',{});
},
'Sage/TaskPane/nls/da/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/da/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/da/OwnerType':function(){
define('Sage/UI/nls/da/OwnerType',{});
},
'Sage/TaskPane/nls/da/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/da/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/da/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/da/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/da/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/da/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/da/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/da/InvoiceRTDV',{});
},
'Sage/UI/nls/da/SDataLookup':function(){
define('Sage/UI/nls/da/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/da/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/da/RowDesigner',{});
},
'Sage/TaskPane/nls/da/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/da/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/da/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/da/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/da/LibraryDocument':function(){
define('Sage/Utility/File/nls/da/LibraryDocument',{});
},
'Sage/UI/nls/da/ConditionManager':function(){
define('Sage/UI/nls/da/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/da/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/da/WidgetDefinition',{});
},
'Sage/UI/nls/da/SearchConditionWidget':function(){
define('Sage/UI/nls/da/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/da/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/da/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/da/DataSourcePanel',{});
},
'Sage/UI/nls/da/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/da/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/da/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/da/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/da/Name':function(){
define('Sage/UI/Controls/nls/da/Name',{});
},
'Sage/QuickForms/Design/nls/da/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/da/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/da/UpdateLeads',{});
},
'Sage/UI/nls/da/ListPanel':function(){
define('Sage/UI/nls/da/ListPanel',{});
},
'Sage/UI/Filters/nls/da/EditFilters':function(){
define('Sage/UI/Filters/nls/da/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/da/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/da/DurationSelect':function(){
define('Sage/UI/Controls/nls/da/DurationSelect',{});
},
'Sage/UI/Alarms/nls/da/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/da/AlarmCountDown',{});
},
'Sage/UI/nls/da/AttachmentList':function(){
define('Sage/UI/nls/da/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/da/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/da/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/da/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/da/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/da/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/da/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/da/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/da/Dialogs':function(){
define('Sage/UI/nls/da/Dialogs',{});
},
'Sage/TaskPane/nls/da/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/da/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/da/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/da/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/da/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/da/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/da/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/UserControlDesigner',{});
},
'Sage/Groups/nls/da/GroupNavigator':function(){
define('Sage/Groups/nls/da/GroupNavigator',{});
},
'Sage/Utility/File/nls/da/AddURLAttachment':function(){
define('Sage/Utility/File/nls/da/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/da/EditFilterItems':function(){
define('Sage/UI/Filters/nls/da/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/da/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/da/DesignSurface',{});
},
'Sage/Utility/File/nls/da/DragDropWatcher':function(){
define('Sage/Utility/File/nls/da/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/da/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/da/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/da/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/da/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/da/EventListPanelConfig',{});
},
'Sage/UI/nls/da/ActivityScheduler':function(){
define('Sage/UI/nls/da/ActivityScheduler',{});
},
'Sage/MainView/nls/da/SecurityManager':function(){
define('Sage/MainView/nls/da/SecurityManager',{});
},
'Sage/TaskPane/nls/da/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/da/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/da/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/da/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/da/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/da/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/da/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/da/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/da/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/da/HelpMenu':function(){
define('Sage/UI/Controls/nls/da/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/da/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/da/UserTasklet':function(){
define('Sage/TaskPane/nls/da/UserTasklet',{});
},
'Sage/UI/Alarms/nls/da/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/da/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/da/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/da/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/da/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/da/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/da/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/da/ColumnDesigner',{});
},
'Sage/UI/nls/da/SearchMenuItem':function(){
define('Sage/UI/nls/da/SearchMenuItem',{});
},
'Sage/UI/nls/da/NotesHistoryList':function(){
define('Sage/UI/nls/da/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/da/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/da/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/da/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/da/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/da/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/da/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/da/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/da/HistoryEditor',{});
},
'Sage/Groups/nls/da/GroupManager':function(){
define('Sage/Groups/nls/da/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/da/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/da/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/da/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/da/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/da/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/da/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/da/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/da/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/da/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/da/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/da/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/da/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/da/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/da/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/da/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/da/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/da/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/da/EditableGrid':function(){
define('Sage/UI/nls/da/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/da/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/da/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/da/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/da/SpeedSearch':function(){
define('Sage/UI/nls/da/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/da/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/da/SLXPreviewGrid':function(){
define('Sage/UI/nls/da/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/da/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/da/UnconfirmedPane',{});
},
'Sage/Utility/nls/da/Utility':function(){
define('Sage/Utility/nls/da/Utility',{});
},
'Sage/QuickForms/Design/nls/da/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/ControlDesigner',{});
},
'Sage/UI/Controls/nls/da/Address':function(){
define('Sage/UI/Controls/nls/da/Address',{});
},
'Sage/MainView/ActivityMgr/nls/da/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/da/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/da/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/OwnerControlDesigner',{});
},
'Sage/UI/nls/da/UserType':function(){
define('Sage/UI/nls/da/UserType',{});
},
'Sage/QuickForms/Design/nls/da/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/da/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/da/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/da/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/da/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/da/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/da/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/da/ActivityList':function(){
define('Sage/UI/nls/da/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/da/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/da/CalendarUsersListPane':function(){
define('Sage/UI/nls/da/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/da/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/da/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/da/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/da/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/da/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/da/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/da/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/da/Attachment':function(){
define('Sage/Utility/File/nls/da/Attachment',{});
},
'Sage/QuickForms/Design/nls/da/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/da/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/da/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/da/Helper':function(){
define('Sage/MailMerge/nls/da/Helper',{});
},
'Sage/UI/Dashboard/nls/da/Dashboard':function(){
define('Sage/UI/Dashboard/nls/da/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/da/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/da/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/da/PickList':function(){
define('Sage/UI/Controls/nls/da/PickList',{});
},
'Sage/Utility/nls/da/Email':function(){
define('Sage/Utility/nls/da/Email',{});
},
'Sage/TaskPane/nls/da/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/da/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/da/TimeZoneItem':function(){
define('Sage/UI/nls/da/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/da/SlxEdit':function(){
define('Sage/UI/Columns/nls/da/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/da/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/da/LogOffButton':function(){
define('Sage/UI/Controls/nls/da/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/da/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/da/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/da/EditEventEditor',{});
},
'Sage/MailMerge/nls/da/Loader':function(){
define('Sage/MailMerge/nls/da/Loader',{});
},
'Sage/UI/Controls/nls/da/DateTimePicker':function(){
define('Sage/UI/Controls/nls/da/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/da/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/da/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/da/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/da/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/da/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/da/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/da/Lookup':function(){
define('Sage/UI/Controls/nls/da/Lookup',{});
},
'Sage/Utility/File/nls/da/DescriptionsForm':function(){
define('Sage/Utility/File/nls/da/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/da/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/da/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/da/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/da/CommonTasksTasklet',{});
},
'Sage/Utility/nls/da/Dashboard':function(){
define('Sage/Utility/nls/da/Dashboard',{});
}}});
define("Sage/nls/Sage_da", [], 1);
