require({cache:{
'Sage/Utility/File/nls/hu/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/hu/FallbackFilePicker',{});
},
'Sage/UI/nls/hu/Boolean':function(){
define('Sage/UI/nls/hu/Boolean',{});
},
'Sage/Services/nls/hu/ActivityService':function(){
define('Sage/Services/nls/hu/ActivityService',{});
},
'Sage/UI/Controls/nls/hu/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/hu/CopyToClipboard',{});
},
'Sage/Utility/nls/hu/Activity':function(){
define('Sage/Utility/nls/hu/Activity',{});
},
'Sage/QuickForms/Design/nls/hu/DesignPanel':function(){
define('Sage/QuickForms/Design/nls/hu/DesignPanel',{});
},
'Sage/UI/nls/hu/TimelessActivitiesPane':function(){
define('Sage/UI/nls/hu/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/hu/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hu/ActivityEditor',{});
},
'Sage/MainView/nls/hu/ActivityManager':function(){
define('Sage/MainView/nls/hu/ActivityManager',{});
},
'Sage/QuickForms/Design/nls/hu/NumericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/NumericControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/_PropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/_PropertyEditor',{});
},
'Sage/Services/nls/hu/ActivityActionProcessor':function(){
define('Sage/Services/nls/hu/ActivityActionProcessor',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/TextBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/TextBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/hu/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hu/QuickCompleteEditor',{});
},
'Sage/Utility/File/nls/hu/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/hu/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/hu/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/hu/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/hu/AlarmPane':function(){
define('Sage/UI/Alarms/nls/hu/AlarmPane',{});
},
'Sage/TaskPane/nls/hu/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/hu/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/hu/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/hu/DashboardWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/NumericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/NumericAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/hu/CustomerPaymentsRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/hu/CustomerPaymentsRTDV',{});
},
'Sage/UI/Filters/nls/hu/FilterPanel':function(){
define('Sage/UI/Filters/nls/hu/FilterPanel',{});
},
'Sage/TaskPane/nls/hu/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/hu/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/hu/OwnerType':function(){
define('Sage/UI/nls/hu/OwnerType',{});
},
'Sage/TaskPane/nls/hu/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/hu/LeadTasksTasklet',{});
},
'Sage/MainView/ActivityMgr/nls/hu/SnoozeOptions':function(){
define('Sage/MainView/ActivityMgr/nls/hu/SnoozeOptions',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/OwnerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/OwnerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/NonVisibleAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/NonVisibleAdvancedPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/hu/InvoiceRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/hu/InvoiceRTDV',{});
},
'Sage/UI/nls/hu/SDataLookup':function(){
define('Sage/UI/nls/hu/SDataLookup',{});
},
'Sage/QuickForms/Design/nls/hu/RowDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/RowDesigner',{});
},
'Sage/TaskPane/nls/hu/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/hu/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/hu/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/hu/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/hu/LibraryDocument':function(){
define('Sage/Utility/File/nls/hu/LibraryDocument',{});
},
'Sage/UI/nls/hu/ConditionManager':function(){
define('Sage/UI/nls/hu/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/hu/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/hu/WidgetDefinition',{});
},
'Sage/UI/nls/hu/SearchConditionWidget':function(){
define('Sage/UI/nls/hu/SearchConditionWidget',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/GenericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/GenericBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/hu/DataSourcePanel':function(){
define('Sage/QuickForms/Design/nls/hu/DataSourcePanel',{});
},
'Sage/UI/nls/hu/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/hu/GroupsTitlePaneConfigProvider',{});
},
'Sage/QuickForms/Design/nls/hu/NonVisibleControlContainer':function(){
define('Sage/QuickForms/Design/nls/hu/NonVisibleControlContainer',{});
},
'Sage/UI/Controls/nls/hu/Name':function(){
define('Sage/UI/Controls/nls/hu/Name',{});
},
'Sage/QuickForms/Design/nls/hu/PhoneControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/PhoneControlDesigner',{});
},
'Sage/MainView/Lead/nls/hu/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/hu/UpdateLeads',{});
},
'Sage/UI/nls/hu/ListPanel':function(){
define('Sage/UI/nls/hu/ListPanel',{});
},
'Sage/UI/Filters/nls/hu/EditFilters':function(){
define('Sage/UI/Filters/nls/hu/EditFilters',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/FormUsagesPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/FormUsagesPropertyEditor',{});
},
'Sage/UI/Controls/nls/hu/DurationSelect':function(){
define('Sage/UI/Controls/nls/hu/DurationSelect',{});
},
'Sage/UI/Alarms/nls/hu/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/hu/AlarmCountDown',{});
},
'Sage/UI/nls/hu/AttachmentList':function(){
define('Sage/UI/nls/hu/AttachmentList',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/RowBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/RowBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/hu/CheckBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/CheckBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hu/EditableGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/EditableGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hu/HiddenControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/HiddenControlDesigner',{});
},
'Sage/UI/Dashboard/nls/hu/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/hu/DashboardWidgetCell',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/UserBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/UserBasicPropertyEditor',{});
},
'Sage/UI/nls/hu/Dialogs':function(){
define('Sage/UI/nls/hu/Dialogs',{});
},
'Sage/TaskPane/nls/hu/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/hu/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/hu/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/hu/DashboardTabController',{});
},
'Sage/MainView/IntegrationContract/nls/hu/SalesOrderRTDV':function(){
define('Sage/MainView/IntegrationContract/nls/hu/SalesOrderRTDV',{});
},
'Sage/QuickForms/Design/nls/hu/UserControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/UserControlDesigner',{});
},
'Sage/Groups/nls/hu/GroupNavigator':function(){
define('Sage/Groups/nls/hu/GroupNavigator',{});
},
'Sage/Utility/File/nls/hu/AddURLAttachment':function(){
define('Sage/Utility/File/nls/hu/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/hu/EditFilterItems':function(){
define('Sage/UI/Filters/nls/hu/EditFilterItems',{});
},
'Sage/QuickForms/Design/nls/hu/DesignSurface':function(){
define('Sage/QuickForms/Design/nls/hu/DesignSurface',{});
},
'Sage/Utility/File/nls/hu/DragDropWatcher':function(){
define('Sage/Utility/File/nls/hu/DragDropWatcher',{});
},
'Sage/MainView/ActivityMgr/nls/hu/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hu/ConfirmListPanelConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/FormAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/FormAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/hu/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hu/EventListPanelConfig',{});
},
'Sage/UI/nls/hu/ActivityScheduler':function(){
define('Sage/UI/nls/hu/ActivityScheduler',{});
},
'Sage/MainView/nls/hu/SecurityManager':function(){
define('Sage/MainView/nls/hu/SecurityManager',{});
},
'Sage/TaskPane/nls/hu/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/hu/ActivityTaskConfigurationProvider',{});
},
'Sage/UI/Controls/nls/hu/EntityInfoToolTip':function(){
define('Sage/UI/Controls/nls/hu/EntityInfoToolTip',{});
},
'Sage/MainView/ActivityMgr/nls/hu/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/hu/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/hu/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/hu/UpdateOpportunities',{});
},
'Sage/QuickForms/Design/nls/hu/DateTimePickerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/DateTimePickerControlDesigner',{});
},
'Sage/UI/Controls/nls/hu/HelpMenu':function(){
define('Sage/UI/Controls/nls/hu/HelpMenu',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/LayoutPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/LayoutPropertyEditor',{});
},
'Sage/TaskPane/nls/hu/UserTasklet':function(){
define('Sage/TaskPane/nls/hu/UserTasklet',{});
},
'Sage/UI/Alarms/nls/hu/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/hu/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/hu/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/hu/OpportunityStatistics',{});
},
'Sage/MainView/IntegrationContract/nls/hu/AdvancedSearchOptions':function(){
define('Sage/MainView/IntegrationContract/nls/hu/AdvancedSearchOptions',{});
},
'Sage/QuickForms/Design/nls/hu/ColumnDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/ColumnDesigner',{});
},
'Sage/UI/nls/hu/SearchMenuItem':function(){
define('Sage/UI/nls/hu/SearchMenuItem',{});
},
'Sage/UI/nls/hu/NotesHistoryList':function(){
define('Sage/UI/nls/hu/NotesHistoryList',{});
},
'Sage/QuickForms/Design/nls/hu/UrlControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/UrlControlDesigner',{});
},
'Sage/Utility/File/nls/hu/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/hu/GoogleDocPicker',{});
},
'Sage/QuickForms/Design/nls/hu/ComboBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/ComboBoxControlDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/hu/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hu/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/hu/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hu/HistoryEditor',{});
},
'Sage/Groups/nls/hu/GroupManager':function(){
define('Sage/Groups/nls/hu/GroupManager',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/DateTimePickerAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/DateTimePickerAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/ComboBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/ComboBoxBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/hu/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hu/RecurringEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/DataGridAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/DataGridAdvancedPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/hu/CurrencyControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/CurrencyControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hu/DataGridControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/DataGridControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hu/PickListControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/PickListControlDesigner',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/CheckBoxBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/CheckBoxBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/ComboBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/ComboBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/Contact/nls/hu/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/hu/ContactSearchForDuplicates',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/DateTimePickerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/DateTimePickerBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/hu/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/hu/AccountingTasksTasklet',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/DataGridBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/DataGridBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/CurrencyBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/CurrencyBasicPropertyEditor',{});
},
'Sage/UI/nls/hu/EditableGrid':function(){
define('Sage/UI/nls/hu/EditableGrid',{});
},
'Sage/MainView/SecurityMgr/nls/hu/SecurityProfile':function(){
define('Sage/MainView/SecurityMgr/nls/hu/SecurityProfile',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/UserAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/UserAdvancedPropertyEditor',{});
},
'Sage/UI/nls/hu/SpeedSearch':function(){
define('Sage/UI/nls/hu/SpeedSearch',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/CurrencyAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/CurrencyAdvancedPropertyEditor',{});
},
'Sage/UI/nls/hu/SLXPreviewGrid':function(){
define('Sage/UI/nls/hu/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/hu/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/hu/UnconfirmedPane',{});
},
'Sage/Utility/nls/hu/Utility':function(){
define('Sage/Utility/nls/hu/Utility',{});
},
'Sage/QuickForms/Design/nls/hu/ControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/ControlDesigner',{});
},
'Sage/UI/Controls/nls/hu/Address':function(){
define('Sage/UI/Controls/nls/hu/Address',{});
},
'Sage/MainView/ActivityMgr/nls/hu/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hu/BaseListPanelConfig',{});
},
'Sage/QuickForms/Design/nls/hu/OwnerControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/OwnerControlDesigner',{});
},
'Sage/UI/nls/hu/UserType':function(){
define('Sage/UI/nls/hu/UserType',{});
},
'Sage/QuickForms/Design/nls/hu/FormDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/FormDesigner',{});
},
'Sage/MainView/ActivityMgr/nls/hu/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/hu/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/hu/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/hu/_DialogHelpIconMixin',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/PickListAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/PickListAdvancedPropertyEditor',{});
},
'Sage/UI/nls/hu/ActivityList':function(){
define('Sage/UI/nls/hu/ActivityList',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/GenericAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/GenericAdvancedPropertyEditor',{});
},
'Sage/UI/nls/hu/CalendarUsersListPane':function(){
define('Sage/UI/nls/hu/CalendarUsersListPane',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/PickListBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/PickListBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/ColumnBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/ColumnBasicPropertyEditor',{});
},
'Sage/MainView/IntegrationContract/nls/hu/MatchingOptionsConfig':function(){
define('Sage/MainView/IntegrationContract/nls/hu/MatchingOptionsConfig',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/FormBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/FormBasicPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/hu/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/hu/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/hu/Attachment':function(){
define('Sage/Utility/File/nls/hu/Attachment',{});
},
'Sage/QuickForms/Design/nls/hu/GenericControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/GenericControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hu/PropertyEditorContainer':function(){
define('Sage/QuickForms/Design/nls/hu/PropertyEditorContainer',{});
},
'Sage/MailMerge/nls/hu/Helper':function(){
define('Sage/MailMerge/nls/hu/Helper',{});
},
'Sage/UI/Dashboard/nls/hu/Dashboard':function(){
define('Sage/UI/Dashboard/nls/hu/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/hu/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/hu/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/hu/PickList':function(){
define('Sage/UI/Controls/nls/hu/PickList',{});
},
'Sage/Utility/nls/hu/Email':function(){
define('Sage/Utility/nls/hu/Email',{});
},
'Sage/TaskPane/nls/hu/SecurityManagerTasksTasklet':function(){
define('Sage/TaskPane/nls/hu/SecurityManagerTasksTasklet',{});
},
'Sage/UI/nls/hu/TimeZoneItem':function(){
define('Sage/UI/nls/hu/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/hu/SlxEdit':function(){
define('Sage/UI/Columns/nls/hu/SlxEdit',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/CheckBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/CheckBoxAdvancedPropertyEditor',{});
},
'Sage/UI/Controls/nls/hu/LogOffButton':function(){
define('Sage/UI/Controls/nls/hu/LogOffButton',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/TextBoxAdvancedPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/TextBoxAdvancedPropertyEditor',{});
},
'Sage/MainView/ActivityMgr/nls/hu/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/hu/EditEventEditor',{});
},
'Sage/MailMerge/nls/hu/Loader':function(){
define('Sage/MailMerge/nls/hu/Loader',{});
},
'Sage/UI/Controls/nls/hu/DateTimePicker':function(){
define('Sage/UI/Controls/nls/hu/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/hu/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/hu/AlarmPopup',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/OwnerBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/OwnerBasicPropertyEditor',{});
},
'Sage/QuickForms/Design/nls/hu/TextBoxControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/TextBoxControlDesigner',{});
},
'Sage/QuickForms/Design/nls/hu/EmailControlDesigner':function(){
define('Sage/QuickForms/Design/nls/hu/EmailControlDesigner',{});
},
'Sage/UI/Controls/nls/hu/Lookup':function(){
define('Sage/UI/Controls/nls/hu/Lookup',{});
},
'Sage/Utility/File/nls/hu/DescriptionsForm':function(){
define('Sage/Utility/File/nls/hu/DescriptionsForm',{});
},
'Sage/QuickForms/Design/Editors/nls/hu/NumericBasicPropertyEditor':function(){
define('Sage/QuickForms/Design/Editors/nls/hu/NumericBasicPropertyEditor',{});
},
'Sage/TaskPane/nls/hu/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/hu/CommonTasksTasklet',{});
},
'Sage/Utility/nls/hu/Dashboard':function(){
define('Sage/Utility/nls/hu/Dashboard',{});
}}});
define("Sage/nls/Sage_hu", [], 1);
