require({cache:{
'Sage/Utility/File/nls/sx/FallbackFilePicker':function(){
define('Sage/Utility/File/nls/sx/FallbackFilePicker',{});
},
'Sage/UI/nls/sx/Boolean':function(){
define('Sage/UI/nls/sx/Boolean',{});
},
'Sage/UI/Controls/nls/sx/CopyToClipboard':function(){
define('Sage/UI/Controls/nls/sx/CopyToClipboard',{});
},
'Sage/Services/nls/sx/ActivityService':function(){
define('Sage/Services/nls/sx/ActivityService',{});
},
'Sage/Utility/nls/sx/Activity':function(){
define('Sage/Utility/nls/sx/Activity',{});
},
'Sage/UI/nls/sx/TimelessActivitiesPane':function(){
define('Sage/UI/nls/sx/TimelessActivitiesPane',{});
},
'Sage/MainView/ActivityMgr/nls/sx/ActivityEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sx/ActivityEditor',{});
},
'Sage/MainView/nls/sx/ActivityManager':function(){
define('Sage/MainView/nls/sx/ActivityManager',{});
},
'Sage/MainView/ActivityMgr/nls/sx/QuickCompleteEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sx/QuickCompleteEditor',{});
},
'Sage/Reporting/nls/sx/Service':function(){
define('Sage/Reporting/nls/sx/Service',{});
},
'Sage/Utility/File/nls/sx/DefaultDropHandler':function(){
define('Sage/Utility/File/nls/sx/DefaultDropHandler',{});
},
'Sage/Utility/File/nls/sx/AttachmentPropertiesEditForm':function(){
define('Sage/Utility/File/nls/sx/AttachmentPropertiesEditForm',{});
},
'Sage/UI/Alarms/nls/sx/AlarmPane':function(){
define('Sage/UI/Alarms/nls/sx/AlarmPane',{});
},
'Sage/TaskPane/nls/sx/LiteratureManagementTasks':function(){
define('Sage/TaskPane/nls/sx/LiteratureManagementTasks',{});
},
'Sage/UI/Dashboard/nls/sx/DashboardWidget':function(){
define('Sage/UI/Dashboard/nls/sx/DashboardWidget',{});
},
'Sage/UI/Filters/nls/sx/FilterPanel':function(){
define('Sage/UI/Filters/nls/sx/FilterPanel',{});
},
'Sage/TaskPane/nls/sx/_BaseTaskPaneTasklet':function(){
define('Sage/TaskPane/nls/sx/_BaseTaskPaneTasklet',{});
},
'Sage/UI/nls/sx/OwnerType':function(){
define('Sage/UI/nls/sx/OwnerType',{});
},
'Sage/TaskPane/nls/sx/LeadTasksTasklet':function(){
define('Sage/TaskPane/nls/sx/LeadTasksTasklet',{});
},
'Sage/UI/nls/sx/SDataLookup':function(){
define('Sage/UI/nls/sx/SDataLookup',{});
},
'Sage/TaskPane/nls/sx/OpportunityTasksTasklet':function(){
define('Sage/TaskPane/nls/sx/OpportunityTasksTasklet',{});
},
'Sage/UI/Filters/nls/sx/CheckBoxFilter':function(){
define('Sage/UI/Filters/nls/sx/CheckBoxFilter',{});
},
'Sage/Utility/File/nls/sx/LibraryDocument':function(){
define('Sage/Utility/File/nls/sx/LibraryDocument',{});
},
'Sage/UI/nls/sx/ConditionManager':function(){
define('Sage/UI/nls/sx/ConditionManager',{});
},
'Sage/UI/Dashboard/nls/sx/WidgetDefinition':function(){
define('Sage/UI/Dashboard/nls/sx/WidgetDefinition',{});
},
'Sage/UI/nls/sx/SearchConditionWidget':function(){
define('Sage/UI/nls/sx/SearchConditionWidget',{});
},
'Sage/UI/nls/sx/GroupsTitlePaneConfigProvider':function(){
define('Sage/UI/nls/sx/GroupsTitlePaneConfigProvider',{});
},
'Sage/UI/Controls/nls/sx/Name':function(){
define('Sage/UI/Controls/nls/sx/Name',{});
},
'Sage/MainView/Lead/nls/sx/UpdateLeads':function(){
define('Sage/MainView/Lead/nls/sx/UpdateLeads',{});
},
'Sage/UI/nls/sx/ListPanel':function(){
define('Sage/UI/nls/sx/ListPanel',{});
},
'Sage/UI/Filters/nls/sx/EditFilters':function(){
define('Sage/UI/Filters/nls/sx/EditFilters',{});
},
'Sage/UI/Controls/nls/sx/DurationSelect':function(){
define('Sage/UI/Controls/nls/sx/DurationSelect',{});
},
'Sage/UI/Alarms/nls/sx/AlarmCountDown':function(){
define('Sage/UI/Alarms/nls/sx/AlarmCountDown',{});
},
'Sage/UI/nls/sx/AttachmentList':function(){
define('Sage/UI/nls/sx/AttachmentList',{});
},
'Sage/UI/Dashboard/nls/sx/DashboardWidgetCell':function(){
define('Sage/UI/Dashboard/nls/sx/DashboardWidgetCell',{});
},
'Sage/TaskPane/nls/sx/SecuredActionTasklet':function(){
define('Sage/TaskPane/nls/sx/SecuredActionTasklet',{});
},
'Sage/UI/Dashboard/nls/sx/DashboardTabController':function(){
define('Sage/UI/Dashboard/nls/sx/DashboardTabController',{});
},
'Sage/Groups/nls/sx/GroupNavigator':function(){
define('Sage/Groups/nls/sx/GroupNavigator',{});
},
'Sage/Utility/File/nls/sx/AddURLAttachment':function(){
define('Sage/Utility/File/nls/sx/AddURLAttachment',{});
},
'Sage/UI/Filters/nls/sx/EditFilterItems':function(){
define('Sage/UI/Filters/nls/sx/EditFilterItems',{});
},
'Sage/MainView/ActivityMgr/nls/sx/ConfirmListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sx/ConfirmListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sx/EventListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sx/EventListPanelConfig',{});
},
'Sage/UI/nls/sx/ActivityScheduler':function(){
define('Sage/UI/nls/sx/ActivityScheduler',{});
},
'Sage/MainView/nls/sx/SecurityManager':function(){
define('Sage/MainView/nls/sx/SecurityManager',{});
},
'Sage/TaskPane/nls/sx/ActivityTaskConfigurationProvider':function(){
define('Sage/TaskPane/nls/sx/ActivityTaskConfigurationProvider',{});
},
'Sage/MainView/ActivityMgr/nls/sx/ActivityGroupContextService':function(){
define('Sage/MainView/ActivityMgr/nls/sx/ActivityGroupContextService',{});
},
'Sage/MainView/Opportunity/nls/sx/UpdateOpportunities':function(){
define('Sage/MainView/Opportunity/nls/sx/UpdateOpportunities',{});
},
'Sage/UI/Controls/nls/sx/HelpMenu':function(){
define('Sage/UI/Controls/nls/sx/HelpMenu',{});
},
'Sage/TaskPane/nls/sx/UserTasklet':function(){
define('Sage/TaskPane/nls/sx/UserTasklet',{});
},
'Sage/UI/Alarms/nls/sx/ActivityAlarm':function(){
define('Sage/UI/Alarms/nls/sx/ActivityAlarm',{});
},
'Sage/MainView/Opportunity/nls/sx/OpportunityStatistics':function(){
define('Sage/MainView/Opportunity/nls/sx/OpportunityStatistics',{});
},
'Sage/MailMerge/nls/sx/MenuHelper':function(){
define('Sage/MailMerge/nls/sx/MenuHelper',{});
},
'Sage/UI/nls/sx/SearchMenuItem':function(){
define('Sage/UI/nls/sx/SearchMenuItem',{});
},
'Sage/UI/nls/sx/NotesHistoryList':function(){
define('Sage/UI/nls/sx/NotesHistoryList',{});
},
'Sage/Utility/File/nls/sx/GoogleDocPicker':function(){
define('Sage/Utility/File/nls/sx/GoogleDocPicker',{});
},
'Sage/MainView/ActivityMgr/nls/sx/LitRequestListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sx/LitRequestListPanelConfig',{});
},
'Sage/MainView/ActivityMgr/nls/sx/HistoryEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sx/HistoryEditor',{});
},
'Sage/Groups/nls/sx/GroupManager':function(){
define('Sage/Groups/nls/sx/GroupManager',{});
},
'Sage/MainView/ActivityMgr/nls/sx/RecurringEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sx/RecurringEditor',{});
},
'Sage/UI/Alarms/nls/sx/UnconfirmedAlarm':function(){
define('Sage/UI/Alarms/nls/sx/UnconfirmedAlarm',{});
},
'Sage/MainView/Contact/nls/sx/ContactSearchForDuplicates':function(){
define('Sage/MainView/Contact/nls/sx/ContactSearchForDuplicates',{});
},
'Sage/TaskPane/nls/sx/AccountingTasksTasklet':function(){
define('Sage/TaskPane/nls/sx/AccountingTasksTasklet',{});
},
'Sage/UI/nls/sx/EditableGrid':function(){
define('Sage/UI/nls/sx/EditableGrid',{});
},
'Sage/UI/nls/sx/SpeedSearch':function(){
define('Sage/UI/nls/sx/SpeedSearch',{});
},
'Sage/UI/nls/sx/SLXPreviewGrid':function(){
define('Sage/UI/nls/sx/SLXPreviewGrid',{});
},
'Sage/UI/Alarms/nls/sx/UnconfirmedPane':function(){
define('Sage/UI/Alarms/nls/sx/UnconfirmedPane',{});
},
'Sage/Utility/nls/sx/Utility':function(){
define('Sage/Utility/nls/sx/Utility',{});
},
'Sage/UI/Controls/nls/sx/Address':function(){
define('Sage/UI/Controls/nls/sx/Address',{});
},
'Sage/MainView/ActivityMgr/nls/sx/BaseListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sx/BaseListPanelConfig',{});
},
'Sage/UI/nls/sx/UserType':function(){
define('Sage/UI/nls/sx/UserType',{});
},
'Sage/MainView/ActivityMgr/nls/sx/ActivityCalendar':function(){
define('Sage/MainView/ActivityMgr/nls/sx/ActivityCalendar',{});
},
'Sage/UI/Controls/nls/sx/_DialogHelpIconMixin':function(){
define('Sage/UI/Controls/nls/sx/_DialogHelpIconMixin',{});
},
'Sage/UI/nls/sx/ActivityList':function(){
define('Sage/UI/nls/sx/ActivityList',{});
},
'Sage/UI/nls/sx/CalendarUsersListPane':function(){
define('Sage/UI/nls/sx/CalendarUsersListPane',{});
},
'Sage/MainView/ActivityMgr/nls/sx/OccurrenceOrSeriesQueryDlg':function(){
define('Sage/MainView/ActivityMgr/nls/sx/OccurrenceOrSeriesQueryDlg',{});
},
'Sage/Utility/File/nls/sx/Attachment':function(){
define('Sage/Utility/File/nls/sx/Attachment',{});
},
'Sage/MailMerge/nls/sx/Helper':function(){
define('Sage/MailMerge/nls/sx/Helper',{});
},
'Sage/UI/Dashboard/nls/sx/Dashboard':function(){
define('Sage/UI/Dashboard/nls/sx/Dashboard',{});
},
'Sage/MainView/ActivityMgr/nls/sx/ActivityListPanelConfig':function(){
define('Sage/MainView/ActivityMgr/nls/sx/ActivityListPanelConfig',{});
},
'Sage/UI/Controls/nls/sx/PickList':function(){
define('Sage/UI/Controls/nls/sx/PickList',{});
},
'Sage/Utility/nls/sx/Email':function(){
define('Sage/Utility/nls/sx/Email',{});
},
'Sage/UI/nls/sx/TimeZoneItem':function(){
define('Sage/UI/nls/sx/TimeZoneItem',{});
},
'Sage/UI/Columns/nls/sx/SlxEdit':function(){
define('Sage/UI/Columns/nls/sx/SlxEdit',{});
},
'Sage/UI/Controls/nls/sx/LogOffButton':function(){
define('Sage/UI/Controls/nls/sx/LogOffButton',{});
},
'Sage/MainView/ActivityMgr/nls/sx/EditEventEditor':function(){
define('Sage/MainView/ActivityMgr/nls/sx/EditEventEditor',{});
},
'Sage/MailMerge/nls/sx/Loader':function(){
define('Sage/MailMerge/nls/sx/Loader',{});
},
'Sage/UI/Controls/nls/sx/DateTimePicker':function(){
define('Sage/UI/Controls/nls/sx/DateTimePicker',{});
},
'Sage/UI/Alarms/nls/sx/AlarmPopup':function(){
define('Sage/UI/Alarms/nls/sx/AlarmPopup',{});
},
'Sage/UI/Controls/nls/sx/Lookup':function(){
define('Sage/UI/Controls/nls/sx/Lookup',{});
},
'Sage/Utility/File/nls/sx/DescriptionsForm':function(){
define('Sage/Utility/File/nls/sx/DescriptionsForm',{});
},
'Sage/TaskPane/nls/sx/CommonTasksTasklet':function(){
define('Sage/TaskPane/nls/sx/CommonTasksTasklet',{});
}}});
define("Sage/nls/Sage_sx", [], 1);
