define(
        ({
           txtStartDate_Caption:"Anfangsdatum:",
           txtEndDate_Caption:"Enddatum:",
           txtLocation_Caption:"Standort:",
           txtUser_Caption:"Benutzer:",
           txtDescription_Caption:"Beschreibung:"           
         })
);