define(
        ({
            defaultWidgetText: 'Widget-Einstellungen bearbeiten',
            settingsText: 'Einstellungen',
            viewGroupText: 'Gruppe anzeigen',
            Bar_Chart: 'Balkendiagramm',
            Column_Chart: 'Spaltendiagramm',
            Group_List: 'Gruppenliste',
            Pie_Chart: 'Kreisdiagramm',
            Funnel_Chart: 'Trichterdiagramm',
            Line_Chart: 'Liniendiagramm',
            Default: 'Standard',
            Links: 'Verknüpfung',
            Recently_Viewed: 'Zuletzt angezeigt',
            Todays_Activities: 'Aktivitäten von heute',
            Today_s_Activities: 'Aktivitäten von heute',
            Welcome: 'Willkommen',
            Closing_Opportunities: 'Verkaufschancen werden geschlossen',
            Quick_Actions: 'Schnellaktionen',
            Do_You_Know___: 'Wussten Sie schon...',
            All_Leads: 'Alle Interessenten',
            My_Notes: 'Eigene Notizen',
            Open_Opportunities: 'Offene Verkaufschancen',
            Recent_Lead_Creation_History: 'Historie zuletzt erstellter Interessenten',
            My_Activity_trend: 'Eigene Aktivitäten - Trend',
            My_Completed_Activities_by_Type: 'Eigene abgeschlossene Aktivitäten nach Typ',
            Active_Campaigns: 'Aktive Kampagnen',
            All_Open_Opportunities: 'Alle offenen Verkaufschancen',
            Top_Opportunities: 'Beste Verkaufschancen',
            Open_Defect_Distribution: 'Verteilung nicht behobener Fehler',
            My_Dashboard: 'Eigenes Cockpit',
            Sales: 'Vertrieb',
            Group_List_Description: 'Zeigt eine Liste mit Gruppendatensätzen nach Entität an. Z. B. eine Gruppe aktiver Kampagnen.',
            Welcome_Description: 'Zeigt eine Einführung in Sage SalesLogix mit einem Link zum Hilfethema "Einführung in Sage SalesLogix für Web“.',
            Line_Chart_Description: 'Zeigt Daten als Reihe von Datenpunkten an, die durch eine Linie verbunden sind. Sinnvoll, wenn die Daten viele Gruppen oder Kategorien darstellen.',
            Bar_Chart_Description: 'Zeigt Daten als Gruppe waagerechter Balken an. Sinnvoll beim Vergleichen verschiedener Datenmengen.',
            Column_Chart_Description: 'Zeigt Daten als Gruppe senkrechter Balken nach Kategorie gruppiert an. Sinnvoll zum Aufzeigen von Datenänderungen über einen Zeitraum oder zum Veranschaulichen von Vergleichen zwischen Elementen.',
            Funnel_Chart_Description: 'Zeigt Daten als progressiv abnehmende Verhältnisse in Trichterform an. Die Daten werden als Anteile von 100 % ohne Achsen dargestellt.',
            Pie_Chart_Description: 'Zeigt Daten als Anteile des Ganzen an. Jeder Wert wird als Prozentsatz des Ganzen berechnet. Dieses Diagramm weist keine Achsen auf.',
            Recently_Viewed_Description: 'Zeigt Verknüpfungen zu zuletzt angezeigten Datensätzen mit einem Symbol an, das den Typ angibt. Z. B. Firma oder Kontakt.',
            Todays_Activities_Description: 'Zeigt Verknüpfungen zu Ihren Aktivitäten für den heutigen Tag an.',
            Links_Description: 'Zeigt von Ihnen erstellte Verknüpfungen an. Z. B. Verknüpfungen zu einer Detailansicht in Sage SalesLogix oder zu einer externen Website.'
        })
);