define(
        ({
           txtPhone_Caption:"Telefono:",
           lnkOpportunity_Caption:"Opportunità:",
           txtStartTime_Caption:"Ora iniziale:",
           lnkContactName_Caption:"Contatto:",
           lnkLeadName_Caption:"Nominativo:",
           lnkTicket_Caption:"Ticket:",
           txtLocation_Caption:"Posizione:",
           txtLeader_Caption:"Responsabile:",
           txtDuration_Caption:"Durata:",
           lnkAccountName_Caption:"Azienda:",
           lnkCompanyName_Caption:"Società:",
           txtNotes_Caption:"Note:",
           btnComplete_Caption:"Completa",
           txtFromUser_Caption:"Da:",
           btnDelete_Caption:"Elimina",
           btnDecline_Caption:"Rifiuta",
           btnAccept_Caption:"Accetta"
         })
);