define(
    ({
        labelWidth: '120',
        tabNameGeneralText: 'Général',
        tabNameAttachmentsText: 'Pièces jointes',
        scheduleText: 'Planification',
        startTimeText: 'Planifié',
        completedDateText: 'Terminé',
        timeLessText: 'Heure indéfinie',
        durationText: 'Durée',
        contactText: 'Contact',
        accountText: 'Compte',
        leadText: 'Lead',
        opportunityText: 'Opportunité',
        ticketText: 'Ticket',
        companyText: 'Société',
        regardingText: 'Objet',
        resultText: 'Résultat',
        notesText: 'Notes',
        priorityText: 'Priorité',
        leaderText: 'Responsable',
        categoryText: 'Catégorie',
        locationText: 'Emplacement',
        scheduledByFormatText: 'Planifié par ${user} le ${date}',
        cancelText: 'Annuler',
        okText: 'OK',
        deleteText: 'Supprimer',
        lookupActText: 'Rechercher un compte',
        lookupContactText: 'Rechercher un contact',
        lookupOpportunityText: 'Rechercher une opportunité',
        lookupTicketText: 'Rechercher un ticket',
        lookupLeadText: 'Recherche un lead',
        lookupLeaderText: 'Rechercher le responsable',
        lookupResourcesText: 'Recherche',
        mainPhoneText: 'Tél. principal',
        typeText: 'Type',
        subTypeText: 'Sous-Type',
        nameText: 'Nom',
        cityText: 'Ville',
        stateText: 'Département',
        workphoneText: 'Téléphone professionnel',
        emailText: 'E-mail',
        acctMgrText: 'Resp. du compte',
        descriptionText: 'Description',
        stageText: 'Phase',
        statusText: 'Etat',
        ownerText: 'Propriétaire',
        ticketNumberText: 'Numéro de ticket',
        phoneText: 'Téléphone',
        urgencyText: 'Priorité',
        areaText: 'Zone',
        recurringText: 'Périodicité',
        followupText: 'Suivi',
        noneText: 'Aucun',
        carryOverAttachmentsText: 'Reporter les pièces jointes',
        carryOverNotesText: 'Reporter les notes',
        asScheduledText: 'Telle que planifiée',
        insertText: 'Insérer',
        couldNotSaveErrorText: 'Impossible de sauvegarder l\'historique car une erreur s\'est produite.',
        deleteMessage: 'Vous êtes sur le point de supprimer définitivement cet enregistrement.',
        deleteTitle: 'Supprimer l\'historique',
        postalText: 'Code postal',
        couldNotDeleteErrorText: 'Impossible de supprimer l\'historique car une erreur s\'est produite.'
       
    })
);
