define(
    ({
        dialogCaption: "Détails de la facture",
        loadingText: "chargement en cours...",
        lblInvoiceCaption: "Facture :",
        lblNetTotalCaption: "Montant de la facture :",
        lblInvoiceDateCaption: "Date de la facture :",
        lblInvoiceDiscountAmountCaption: "Remise :",
        lblDueDateCaption: "Date d'échéance :",
        lblInvoiceDiscountPercentCaption: "Pourcentage de remise :",
        lblCustomerPOCaption: "Commande client :",
        lblCarrierTotalPriceCaption: "Expédition :",
        lblSettlementDiscountPercentCaption: "Pourcentage de remise accordée :",
        lblTaxCaption: "Taxe :",
        lblSettlementDiscountTermsCaption: "Conditions de paiement :",
        lblNotesCaption: "Commentaires :",
        lblOperatingCompanyCurrencyCaption: "Devise de la société d'exploitation :",
        lblCostTotalCaption: "Coût total :",
        lblOperatingCompanyCurrencyExchangeRateDateCaption: "Date du taux de change :",
        lblProfitTotalCaption: "Total des bénéfices :",
        lblOperatingCompanyCurrencyExchangeRateCaption: "Taux de change :",
        lblPriceListCaption: "Liste de prix :",
        lblOCCurrencyCaption: "Devise de la société d'exploitation :",
        lblCurrencyCaption: "Devise :",
        lblSalesPersonCaption: "Représentant commercial :",
        detailsTabTitle: "Détails",
        addressTabTitle: "Adresses",
        invoiceLinesTabTitle: "Lignes de la facture",
        paymentsTabTitle: "Paiements",
        deliveriesTabTitle: "Livraisons",
        grdInvoice_Name: "Facture N°",
        grdInvoice_Date: "Date de la facture",
        grdInvoice_Amount: "Montant de la facture",
        grdInvoice_PO: "Commande client",
        grdInvoice_PaymentTerms: "Conditions de paiement",
        grdInvoice_NetTotal: "Total net",
        grdInvoice_Tax: "TVA",
        grdAddress_Name: "Description",
        grdAddress_address1: "Adresse 1",
        grdAddress_address2: "Adresse 2",
        grdAddress_City: "Ville",
        grdAddress_State: "Département",
        grdAddress_Zip: "Code postal",
        grdItems_ActualPrice: "Prix réel",
        grdItems_ChargesTotal: "Total des frais",
        grdItems_Commodity: "Marchandise",
        grdItems_CommodityDimension: "Dimension",
        grdItems_CommodityVariant: "Variable",
        grdItems_DiscountTotal: "Total de la remise",
        grdItems_GrossTotal: "Total brut",
        grdItems_InitialPrice: "Prix d'origine",
        grdItems_Line: "Numéro de la ligne",
        grdItems_NetTotal: "Total net",
        grdItems_Quantity: "Quantité",
        grdItems_Status: "Etat",
        grdItems_TaxTotal: "Montant de la taxe",
        grdItems_Type: "Type de la ligne",
        grdItems_UnitOfMeasure: "Unité",
        grdPayments_Charges: "Frais",
        grdPayments_Currency: "Devise",
        grdPayments_Date: "Date",
        grdPayments_Discounts: "Remises",
        grdPayments_GrossTotal: "Total brut",
        grdPayments_Name: "Nom",
        grdPayments_NetTotal: "Total net",
        grdPayments_ProcessDate: "Date de traitement",
        grdPayments_Status: "Etat",
        grdPayments_Tax: "Taxes",
        grdPayments_TenderReference: "Référence de l'appel d'offre",
        grdPayments_TenderType: "Type de l'appel d'offre",
        grdPayments_Type: "Type",
        grdDeliveries_ActualDate: "Date réelle",
        grdDeliveries_ActualTime: "Heure réelle",
        grdDeliveries_Carrier: "Transporteur",
        grdDeliveries_CarrierReference: "Référence du transporteur",
        grdDeliveries_DeliveredQuantity: "Quantité livrée",
        grdDeliveries_ExceptionReason: "Motif de l'exception",
        grdDeliveries_Method: "Méthode",
        grdDeliveries_Number: "Nombre",
        grdDeliveries_RequestedDate: "Date de la demande",
        grdDeliveries_RequestedQuantity: "Quantité demandée",
        grdDeliveries_Status: "Etat",
        grdDeliveries_Type: "Type",
        btnCloseCaption: "Fermer"
    })
);