define(
        ({
            labelWidth: '100',
            tabNameGeneralText: 'Allgemein',
            tabNameAvailabilityText: 'Verfügbarkeit',
            tabNameAssociationsText: 'Beziehungen',
            tabNameRecurringText: 'Wiederkehrend',
            tabNameAttachmentsText: 'Anlagen',
            tabNameNotesText: 'Notizen',
            scheduleText: 'Planen',
            startTimeText: 'Anfangszeit',
            timeLessText: 'Ohne Zeitangabe',
            alarmText: 'Alarm',
            durationText: 'Dauer',
            rolloverText: 'Automatisch auf nächsten Tag ausdehnen',
            contactText: 'Kontakt',
            accountText: 'Firma',
            leadText: 'Interessent',
            opportunityText: 'Verkaufschance',
            ticketText: 'Ticket',
            companyText: 'Unternehmen',
            regardingText: 'Betreff',
            notesText: 'Notizen',
            priorityText: 'Priorität',
            leaderText: 'Organisator',
            categoryText: 'Kategorie',
            locationText: 'Standort',
            dialogHeaderFormatText: '${actionText} ${activityType} - ${description}',
            scheduledByFormatText: 'Geplant von ${user} am ${date}',
            completeScheduledByFormatText: 'Geplant von ${user} am ${date} ursprünglich für ${startDate}',
            newConfirmationHeaderFormatText: 'Bestätigen der von ${user} geplanten ${activityType}',
            otherConfimationHeaderFormatText: '${activityType} ${actionText} von ${user}',
            acceptedText: 'Akzeptiert',
            declinedText: 'Abgelehnt',
            scheduledText: 'Geplant',
            updatedText: 'Aktualisiert',
            deletedText: 'Gelöscht',
            cancelText: 'Abbrechen',
            okText: 'OK',
            completeText: 'Abschließen',
            completeBtnText: 'Abschließen...',
            completedText: 'Abgeschlossen',
            deleteText: 'Löschen',
            lookupActText: 'Firma suchen',
            lookupContactText: 'Kontakt suchen',
            lookupOpportunityText: 'Verkaufschance suchen',
            lookupTicketText: 'Ticket suchen',
            lookupLeadText: 'Interessenten suchen',
            lookupLeaderText: 'Organisator suchen',
            lookupResourcesText: 'Mitglieder und Ressourcen hinzufügen',
            addResourceText: 'Hinzufügen',
            mainPhoneText: 'Haupttelefonnummer',
            typeText: 'Typ',
            subTypeText: 'Untertyp',
            nameText: 'Name',
            cityText: 'Stadt',
            stateText: 'Bundesland/Kanton',
            workphoneText: 'Geschäftliche Telefonnummer',
            emailText: 'E-Mail',
            acctMgrText: 'Acct. Manager',
            descriptionText: 'Beschreibung',
            stageText: 'Phase',
            statusText: 'Status',
            ownerText: 'Zugriffsberechtigter',
            ticketNumberText: 'Ticket-Nummer',
            phoneText: 'Telefon',
            urgencyText: 'Dringlichkeit',
            areaText: 'Bereich',
            recurringText: 'Wiederkehrend',
            resultText: 'Ergebnis',
            followupText: 'Folgeaktivität',
            noneText: 'Keine',
            carryOverAttachmentsText: 'Anlagen übertragen',
            carryOverNotesText: 'Notizen übertragen',
            asScheduledText: 'Wie geplant',
            nowText: 'Jetzt',
            responseText: 'Antwort',
            acceptText: 'Akzeptieren',
            declineText: 'Ablehnen',
            deleteConfText: 'Bestätigung löschen',
            closeText: 'Schließen',
            leadFullNameText: 'Name',
            postalText: 'Postleitzahl',
            failedLoadingDataMsg: 'Beim Laden der Daten ist ein Fehler aufgetreten.',
            removeText: 'Entfernen',
            noText: 'Nein',
            yesText: 'Ja',
            areYouSureText: 'Sie sind im Begriff, diesen Datensatz permanent zu löschen.',
            couldNotSaveErrorText: 'Da ein Fehler auftrat, konnte die Aktivität leider nicht gespeichert werden.',
            couldNotDeleteErrorText: 'Da ein Fehler auftrat, konnte die Aktivität leider nicht gelöscht werden.',
            couldNotCompleteErrorText : 'Da ein Fehler auftrat, konnte die Aktivität leider nicht abgeschlossen werden.'
        })
);
