require({cache:{
'dijit/form/nls/en/validate':function(){
define('dijit/form/nls/en/validate',{});
},
'dijit/form/nls/en-au/validate':function(){
define('dijit/form/nls/en-au/validate',{});
},
'dijit/_editor/nls/en/commands':function(){
define('dijit/_editor/nls/en/commands',{});
},
'dijit/_editor/nls/en-au/commands':function(){
define('dijit/_editor/nls/en-au/commands',{});
},
'dijit/nls/en/loading':function(){
define('dijit/nls/en/loading',{});
},
'dijit/nls/en-au/loading':function(){
define('dijit/nls/en-au/loading',{});
},
'dijit/form/nls/en/ComboBox':function(){
define('dijit/form/nls/en/ComboBox',{});
},
'dijit/form/nls/en-au/ComboBox':function(){
define('dijit/form/nls/en-au/ComboBox',{});
},
'dijit/nls/en/common':function(){
define('dijit/nls/en/common',{});
},
'dijit/nls/en-au/common':function(){
define('dijit/nls/en-au/common',{});
}}});
define("dijit/nls/dijit_en-au", [], 1);
