require({cache:{
'dijit/form/nls/en/validate':function(){
define('dijit/form/nls/en/validate',{});
},
'dijit/form/nls/en-us/validate':function(){
define('dijit/form/nls/en-us/validate',{});
},
'dijit/_editor/nls/en/commands':function(){
define('dijit/_editor/nls/en/commands',{});
},
'dijit/_editor/nls/en-us/commands':function(){
define('dijit/_editor/nls/en-us/commands',{});
},
'dijit/nls/en/loading':function(){
define('dijit/nls/en/loading',{});
},
'dijit/nls/en-us/loading':function(){
define('dijit/nls/en-us/loading',{});
},
'dijit/form/nls/en/ComboBox':function(){
define('dijit/form/nls/en/ComboBox',{});
},
'dijit/form/nls/en-us/ComboBox':function(){
define('dijit/form/nls/en-us/ComboBox',{});
},
'dijit/nls/en/common':function(){
define('dijit/nls/en/common',{});
},
'dijit/nls/en-us/common':function(){
define('dijit/nls/en-us/common',{});
}}});
define("dijit/nls/dijit_en-us", [], 1);
