require({cache:{
'dijit/form/nls/en/validate':function(){
define('dijit/form/nls/en/validate',{});
},
'dijit/form/nls/en-nz/validate':function(){
define('dijit/form/nls/en-nz/validate',{});
},
'dijit/_editor/nls/en/commands':function(){
define('dijit/_editor/nls/en/commands',{});
},
'dijit/_editor/nls/en-nz/commands':function(){
define('dijit/_editor/nls/en-nz/commands',{});
},
'dijit/nls/en/loading':function(){
define('dijit/nls/en/loading',{});
},
'dijit/nls/en-nz/loading':function(){
define('dijit/nls/en-nz/loading',{});
},
'dijit/form/nls/en/ComboBox':function(){
define('dijit/form/nls/en/ComboBox',{});
},
'dijit/form/nls/en-nz/ComboBox':function(){
define('dijit/form/nls/en-nz/ComboBox',{});
},
'dijit/nls/en/common':function(){
define('dijit/nls/en/common',{});
},
'dijit/nls/en-nz/common':function(){
define('dijit/nls/en-nz/common',{});
}}});
define("dijit/nls/dijit_en-nz", [], 1);
