require({cache:{
'dijit/form/nls/en/validate':function(){
define('dijit/form/nls/en/validate',{});
},
'dijit/form/nls/en-bz/validate':function(){
define('dijit/form/nls/en-bz/validate',{});
},
'dijit/_editor/nls/en/commands':function(){
define('dijit/_editor/nls/en/commands',{});
},
'dijit/_editor/nls/en-bz/commands':function(){
define('dijit/_editor/nls/en-bz/commands',{});
},
'dijit/nls/en/loading':function(){
define('dijit/nls/en/loading',{});
},
'dijit/nls/en-bz/loading':function(){
define('dijit/nls/en-bz/loading',{});
},
'dijit/form/nls/en/ComboBox':function(){
define('dijit/form/nls/en/ComboBox',{});
},
'dijit/form/nls/en-bz/ComboBox':function(){
define('dijit/form/nls/en-bz/ComboBox',{});
},
'dijit/nls/en/common':function(){
define('dijit/nls/en/common',{});
},
'dijit/nls/en-bz/common':function(){
define('dijit/nls/en-bz/common',{});
}}});
define("dijit/nls/dijit_en-bz", [], 1);
