require({cache:{
'dijit/form/nls/en/validate':function(){
define('dijit/form/nls/en/validate',{});
},
'dijit/form/nls/en-ca/validate':function(){
define('dijit/form/nls/en-ca/validate',{});
},
'dijit/_editor/nls/en/commands':function(){
define('dijit/_editor/nls/en/commands',{});
},
'dijit/_editor/nls/en-ca/commands':function(){
define('dijit/_editor/nls/en-ca/commands',{});
},
'dijit/nls/en/loading':function(){
define('dijit/nls/en/loading',{});
},
'dijit/nls/en-ca/loading':function(){
define('dijit/nls/en-ca/loading',{});
},
'dijit/form/nls/en/ComboBox':function(){
define('dijit/form/nls/en/ComboBox',{});
},
'dijit/form/nls/en-ca/ComboBox':function(){
define('dijit/form/nls/en-ca/ComboBox',{});
},
'dijit/nls/en/common':function(){
define('dijit/nls/en/common',{});
},
'dijit/nls/en-ca/common':function(){
define('dijit/nls/en-ca/common',{});
}}});
define("dijit/nls/dijit_en-ca", [], 1);
