define(
        ({
            newTabText: 'Новая закладка',
            addContentText: 'Добавить наполнение',
            editOptionsText: 'Изменить свойства',
            hideTabText: 'Скрыть закладку',
            closeText: 'Закрыть',
            copyTabText: 'Копировать закладку',
            showTabText: 'Показать закладку',
            shareTabText: 'Доступ',
            deleteTabText: 'Удалить закладку',
            deleteTabConfirmText: 'Вы действительно хотите удалить эту закладку?',
            descriptionText: 'Описание',
            everyoneText: 'Всем',
            saveTabText: 'Сохранить закладку',
            helpText: 'Помощь',
            addText: 'Добавить',
            invalidMessage: 'Недопустимый символ',
            invalidDuplicateMessage: 'Название должно быть уникальным.',
            deleteText: 'Удалить',
            titleText: 'Название:',
            chooseTemplateText: 'Выберите шаблон, который вы хотите использовать:',
            oneColumnText: 'Один столбец',
            twoColumnText: 'Разделить на две колонки',
            fatLeftText: 'Две колонки, большая левая',
            fatRightText: 'Две колонки, большая правая',
            makeDefaultText: 'Использовать по умолчанию',
            releaseFetchErrorText: 'Ошибка выборки списка релизов',
            releaseDeleteNoneSelected: 'Элементы не выбраны.',
            releasedToText: 'Доступно:',
            typeText: 'Тип',
            addLookup: 'Добавить',
            okButton: 'Ок',
            errorText: 'Ошибка',
            warningText: 'Предупреждение',
            permissionErrorText: 'Ошибка: Пользователь не имеет права на выполнение этого действия.',
            permissionErrorPerformCopyText: 'Вы хотите создать персональную копию этой страницы?',
            yesText: 'Да',
            noText: 'Нет'
        })
);