define(
        ({
            newTabText: 'Nuova tabulazione',
            addContentText: 'Aggiungi Contenuto',
            editOptionsText: 'Modifica opzioni',
            hideTabText: 'Nascondi scheda',
            closeText: 'Chiudi',
            copyTabText: 'Copia Tab',
            showTabText: 'Visualizza scheda',
            shareTabText: 'Condividi scheda',
            deleteTabText: 'Elimina Scheda',
            deleteTabConfirmText: 'Sei sicuro di voler eliminare questa scheda?',
            descriptionText: 'Descrizione',
            everyoneText: 'Tutti',
            saveTabText: 'Salva scheda',
            helpText: 'Aiuto',
            addText: 'Aggiungi',
            invalidMessage: 'Carattere non valido',
            invalidDuplicateMessage: 'Il titolo deve essere univoco.',
            deleteText: 'Elimina',
            titleText: 'Titolo:',
            chooseTemplateText: 'Scegliere il modello che si desidera utilizzare:',
            oneColumnText: 'Una colonna',
            twoColumnText: 'Spacca in due Colonne',
            fatLeftText: 'Due Colonne più larghe a Sinistra',
            fatRightText: 'Due Colonne più larghe a Destra',
            makeDefaultText: 'Predefinito',
            releaseFetchErrorText: 'Errore nel recupero dell\'elenco dei rilasci.',
            releaseDeleteNoneSelected: 'Nessun elemento selezionato.',
            releasedToText: 'Rilasciato a:',
            typeText: 'Tipo',
            addLookup: 'Aggiungi',
            okButton: 'OK',
            errorText: 'Errore',
            warningText: 'Attenzione',
            permissionErrorText: 'Errore: l\'utente non possiede i diritti per eseguire questa azione.',
            permissionErrorPerformCopyText: 'Si desidera creare una copia personale della pagina?',
            yesText: 'Sì',
            noText: 'No'
        })
);
