define(
        ({
            newTabText: 'Nouvel Onglet',
            addContentText: 'Ajouter du contenu',
            editOptionsText: 'Modifier les options',
            hideTabText: 'Masquer l\'onglet',
            closeText: 'Fermer',
            copyTabText: 'Copier l\'onglet',
            showTabText: 'Afficher l\'onglet',
            shareTabText: 'Partager l\'onglet',
            deleteTabText: 'Supprimer un onglet',
            deleteTabConfirmText: 'Voulez-vous vraiment supprimer cet onglet ?',
            descriptionText: 'Description',
            everyoneText: 'Tous les utilisateurs',
            saveTabText: 'Enregistrer l\'onglet',
            helpText: 'Aide',
            addText: 'Ajouter',
            invalidMessage: 'Caractère non valide',
            invalidDuplicateMessage: 'Le nom de la connexion doit être unique.',
            deleteText: 'Supprimer',
            titleText: 'Titre :',
            chooseTemplateText: 'Choisir le modèle à utiliser :',
            oneColumnText: 'Une colonne',
            twoColumnText: 'Partage en deux colonnes',
            fatLeftText: 'Deux colonnes plus grande à gauche',
            fatRightText: 'Deux colonnes plus grande à droite',
            makeDefaultText: 'Utiliser par défaut',
            releaseFetchErrorText: 'Erreur lors de la récupération des propriétés disponibles.',
            releaseDeleteNoneSelected: 'Aucun élément sélectionné.',
            releasedToText: 'Diffusé à :',
            typeText: 'Type',
            addLookup: 'Ajouter',
            okButton: 'OK',
            errorText: 'Erreur',
            warningText: 'Avertissement',
            permissionErrorText: 'Erreur : l\'utilisateur ne dispose pas des droits suffisants pour effectuer cette action.',
            permissionErrorPerformCopyText: 'Voulez-vous créer une copie personnelle de cette page ?',
            yesText: 'Oui',
            noText: 'Non'
        })
);
