define(
        ({
            defaultWidgetText: 'Modifier les paramètres du build',
            settingsText: 'Paramètres',
            viewGroupText: 'Afficher le groupe',
            Bar_Chart: 'Graphiques à barres',
            Column_Chart: 'Histogramme',
            Group_List: 'Liste de groupe',
            Pie_Chart: 'Graphique en secteurs',
            Funnel_Chart: 'Graphique en entonnoir',
            Line_Chart: 'Graphique en courbes',
            Default: 'Par défaut',
            Links: 'Lien',
            Recently_Viewed: 'Affiché récemment',
            Todays_Activities: 'Activités du jour',
            Today_s_Activities: 'Activités du jour',
            Welcome: 'Bienvenue',
            Closing_Opportunities: 'Opportunités en cours de fermeture',
            Quick_Actions: 'Actions rapides',
            Do_You_Know___: 'Savez-vous...',
            All_Leads: 'Tous les leads',
            My_Notes: 'Mes remarques',
            Open_Opportunities: 'Opportunités ouvertes',
            Recent_Lead_Creation_History: 'Historique récent de création de leads',
            My_Activity_trend: 'Les tendances de mon activité',
            My_Completed_Activities_by_Type: 'Mes activités terminées par type',
            Active_Campaigns: 'Campagnes actives',
            All_Open_Opportunities: 'Toutes les opportunités ouvertes',
            Top_Opportunities: 'Meilleures opportunités',
            Open_Defect_Distribution: 'Distribution de défaut ouvert',
            My_Dashboard: 'Mon tableau de bord',
            Sales: 'Ventes',
            Group_List_Description: 'Affiche une liste d’enregistrements de groupe par entité. Par exemple, un groupe de campagnes actives.',
            Welcome_Description: 'Affiche une introduction à Sage SalesLogix avec un lien vers la rubrique d’aide Introduction à SalesLogix for Web.',
            Line_Chart_Description: 'Affiche des données sous la forme d’une série de points de données reliés par une courbe. Ceci est utile lorsque les données représentent plusieurs groupes ou plusieurs catégories.',
            Bar_Chart_Description: 'Affiche des données sous la forme de groupe de barres horizontales. Ceci est utile pour comparer plusieurs ensembles de données.',
            Column_Chart_Description: 'Affiche des données sous la forme d\'ensemble de barres verticales regroupées par catégorie. Ceci est utile pour afficher les modifications qui ont affecté les données pendant une période de temps donnée ou pour illustrer les comparaisons entre des éléments.',
            Funnel_Chart_Description: 'Affiche les données en tant que proportions progressives sous la forme d’un entonnoir. Les données sont représentées en pourcentages et il n’y a pas d\'axe.',
            Pie_Chart_Description: 'Affiche les données en tant que proportions d’un tout. Chaque valeur est calculée comme pourcentage du total. Ce graphique ne comporte pas d’axe.',
            Recently_Viewed_Description: 'Affiche les liens vers les enregistrements récemment consultés, dont le type de fichier est indentifié par une icône. Par exemple,  un compte ou un contact.',
            Todays_Activities_Description: 'Affiche les liens vers les activités du jour.',
            Links_Description: 'Affiche les liens que vous avez créés. Par exemple, des liens vers une vue Détails dans Sage SalesLogix ou vers un site Web externe.'
        })
);
