require({cache:{
'dijit/form/nls/en/validate':function(){
define('dijit/form/nls/en/validate',{});
},
'dijit/form/nls/en-jm/validate':function(){
define('dijit/form/nls/en-jm/validate',{});
},
'dijit/_editor/nls/en/commands':function(){
define('dijit/_editor/nls/en/commands',{});
},
'dijit/_editor/nls/en-jm/commands':function(){
define('dijit/_editor/nls/en-jm/commands',{});
},
'dijit/nls/en/loading':function(){
define('dijit/nls/en/loading',{});
},
'dijit/nls/en-jm/loading':function(){
define('dijit/nls/en-jm/loading',{});
},
'dijit/form/nls/en/ComboBox':function(){
define('dijit/form/nls/en/ComboBox',{});
},
'dijit/form/nls/en-jm/ComboBox':function(){
define('dijit/form/nls/en-jm/ComboBox',{});
},
'dijit/nls/en/common':function(){
define('dijit/nls/en/common',{});
},
'dijit/nls/en-jm/common':function(){
define('dijit/nls/en-jm/common',{});
}}});
define("dijit/nls/dijit_en-jm", [], 1);
