require({cache:{
'dijit/form/nls/en/validate':function(){
define('dijit/form/nls/en/validate',{});
},
'dijit/form/nls/en-tt/validate':function(){
define('dijit/form/nls/en-tt/validate',{});
},
'dijit/_editor/nls/en/commands':function(){
define('dijit/_editor/nls/en/commands',{});
},
'dijit/_editor/nls/en-tt/commands':function(){
define('dijit/_editor/nls/en-tt/commands',{});
},
'dijit/nls/en/loading':function(){
define('dijit/nls/en/loading',{});
},
'dijit/nls/en-tt/loading':function(){
define('dijit/nls/en-tt/loading',{});
},
'dijit/form/nls/en/ComboBox':function(){
define('dijit/form/nls/en/ComboBox',{});
},
'dijit/form/nls/en-tt/ComboBox':function(){
define('dijit/form/nls/en-tt/ComboBox',{});
},
'dijit/nls/en/common':function(){
define('dijit/nls/en/common',{});
},
'dijit/nls/en-tt/common':function(){
define('dijit/nls/en-tt/common',{});
}}});
define("dijit/nls/dijit_en-tt", [], 1);
