require({cache:{
'dijit/form/nls/en/validate':function(){
define('dijit/form/nls/en/validate',{});
},
'dijit/form/nls/en-za/validate':function(){
define('dijit/form/nls/en-za/validate',{});
},
'dijit/_editor/nls/en/commands':function(){
define('dijit/_editor/nls/en/commands',{});
},
'dijit/_editor/nls/en-za/commands':function(){
define('dijit/_editor/nls/en-za/commands',{});
},
'dijit/nls/en/loading':function(){
define('dijit/nls/en/loading',{});
},
'dijit/nls/en-za/loading':function(){
define('dijit/nls/en-za/loading',{});
},
'dijit/form/nls/en/ComboBox':function(){
define('dijit/form/nls/en/ComboBox',{});
},
'dijit/form/nls/en-za/ComboBox':function(){
define('dijit/form/nls/en-za/ComboBox',{});
},
'dijit/nls/en/common':function(){
define('dijit/nls/en/common',{});
},
'dijit/nls/en-za/common':function(){
define('dijit/nls/en-za/common',{});
}}});
define("dijit/nls/dijit_en-za", [], 1);
