define(
    ({
        labelWidth: '120',
        tabNameGeneralText: 'Общие',
        tabNameAttachmentsText: 'Вложения',
        scheduleText: 'Планировать',
        startTimeText: 'Запланировано',
        completedDateText: 'Заверш.',
        timeLessText: 'В течение дня',
        durationText: 'Длительность',
        contactText: 'Контакт',
        accountText: 'Субъект',
        leadText: 'Наводка',
        opportunityText: 'Сделка',
        ticketText: 'Заявка',
        companyText: 'Компания',
        regardingText: 'Тема',
        resultText: 'Результат',
        notesText: 'Заметки',
        priorityText: 'Приоритет',
        leaderText: 'Руководитель',
        categoryText: 'Категория',
        locationText: 'Размещение',
        scheduledByFormatText: 'Scheduled by ${user} on ${date}',
        cancelText: 'Отмена',
        okText: 'Ок',
        deleteText: 'Удалить',
        lookupActText: 'Поиск Субъекта',
        lookupContactText: 'Поиск Контакта',
        lookupOpportunityText: 'Поиск сделки',
        lookupTicketText: 'Поиск Заявки',
        lookupLeadText: 'Поиск Наводки',
        lookupLeaderText: 'Поиск лидера',
        lookupResourcesText: 'Поиск',
        mainPhoneText: 'Основной тел.',
        typeText: 'Тип',
        subTypeText: 'Подтип',
        nameText: 'Имя',
        cityText: 'Город',
        stateText: 'Область',
        workphoneText: 'Раб. телефон',
        emailText: 'Эл.почта',
        acctMgrText: 'Менеджер',
        descriptionText: 'Описание',
        stageText: 'Стадия',
        statusText: 'Статус',
        ownerText: 'Доступ',
        ticketNumberText: 'Номер заявки',
        phoneText: 'Телефон',
        urgencyText: 'Срочность',
        areaText: 'Область',
        recurringText: 'Повторение',
        followupText: 'Последующее',
        noneText: 'Нет',
        carryOverAttachmentsText: 'Перенести вложения',
        carryOverNotesText: 'Перенести заметки',
        asScheduledText: 'Как запланировано',
        insertText: 'Добавить',
        couldNotSaveErrorText: 'К сожалению, история не может быть сохранена, потому что произошла ошибка.',
        deleteMessage: 'Запись будет удалена без возможности восстановления',
        deleteTitle: 'Удаление истории',
        postalText: 'Почтовый индекс',
        couldNotDeleteErrorText: 'К сожалению, история не может быть удалена, потому что произошла ошибка.'
       
    })
);
