define(
        ({
            activityOccurrsText: 'Это дело выполняется...',
            onceText: 'Один раз',
            dailyText: 'Ежедневно',
            weeklyText: 'Еженедельно',
            monthlyText: 'Ежемесячно',
            yearlyText: 'Ежегодно',
            occursOnceText: 'Это дело происходит только один раз',
            everyText: 'Каждый(е)',
            daysText: 'День(дней)',
            daysAfterText: 'День(дней) после завершения',
            startRecurringText: 'Начало повторений: ',
            endAfterText: 'Заверишть после',
            endOnText: 'Конец повторений',
            occurrencesText: 'вхождения',
            weeksOnText: 'Неделя(и)',
            monText: 'Понедельник',
            tueText: 'Вторник',
            wedText: 'Среда',
            thurText: 'Четверг',
            friText: 'Пятница',
            satText: 'Суббота',
            sunText: 'Воскресенье',
            weeksAfterText: 'Недель после завершения',
            monthsOnText: 'День месяца',
            monthsOnTheText: 'месяц (а) в',
            monthsAfterText: 'Месяцев  после завершения',
            firstText: '1-й',
            secondText: '2-ой',
            thirdText: '3-й',
            fourthText: '4-ый',
            lastText: 'последний',
            yearsOnText: 'Год (лет)',
            yearsAfterText: 'Лет после окончания',
            janText: 'Январь',
            febText: 'Февраль',
            marText: 'Март',
            aprText: 'Апрель',
            mayText: 'Май',
            junText: 'Июнь',
            julText: 'Июль',
            augText: 'Август',
            sepText: 'Сентябрь',
            octText: 'Октябрь',
            novText: 'Ноябрь',
            decText: 'Декабрь',
            theText: 'Каждый(ое)',
            inText: 'в'
        })
);
      