define(
    ({
        dialogCaption: "Rechnungsdetails",
        loadingText: "Laden...",
        lblInvoiceCaption: "Rechnung:",
        lblNetTotalCaption: "Rechnungsbetrag:",
        lblInvoiceDateCaption: "Rechnungsdatum:",
        lblInvoiceDiscountAmountCaption: "Rabatt:",
        lblDueDateCaption: "Fälligkeitsdatum:",
        lblInvoiceDiscountPercentCaption: "Rabattprozentsatz:",
        lblCustomerPOCaption: "Kundenbestellnummer:",
        lblCarrierTotalPriceCaption: "Lieferung:",
        lblSettlementDiscountPercentCaption: "Skontoprozentsatz:",
        lblTaxCaption: "Steuer:",
        lblSettlementDiscountTermsCaption: "Zahlungsbedingungen:",
        lblNotesCaption: "Kommentare:",
        lblOperatingCompanyCurrencyCaption: "Währung des aktiven Unternehmens:",
        lblCostTotalCaption: "Gesamtkosten:",
        lblOperatingCompanyCurrencyExchangeRateDateCaption: "Wechselkursdatum:",
        lblProfitTotalCaption: "Gesamtertrag:",
        lblOperatingCompanyCurrencyExchangeRateCaption: "Wechselkurs:",
        lblPriceListCaption: "Preisliste:",
        lblOCCurrencyCaption: "Währung des aktiven Unternehmens:",
        lblCurrencyCaption: "Währung:",
        lblSalesPersonCaption: "Verkäufer:",
        detailsTabTitle: "Details",
        addressTabTitle: "Adressen",
        invoiceLinesTabTitle: "Rechnungspositionen",
        paymentsTabTitle: "Zahlungen",
        deliveriesTabTitle: "Lieferungen",
        grdInvoice_Name: "Rechnungsnr.",
        grdInvoice_Date: "Rechnungsdatum",
        grdInvoice_Amount: "Rechnungsbetrag",
        grdInvoice_PO: "Kaufauftrag des Kunden",
        grdInvoice_PaymentTerms: "Zahlungsbedingungen",
        grdInvoice_NetTotal: "Nettosumme",
        grdInvoice_Tax: "Steuer",
        grdAddress_Name: "Beschreibung",
        grdAddress_address1: "Zahlungsmittelsreferenz",
        grdAddress_address2: "Adresse2",
        grdAddress_City: "Stadt",
        grdAddress_State: "Bundesland/Kanton",
        grdAddress_Zip: "Postleitzahl",
        grdItems_ActualPrice: "Tatsächlicher Preis",
        grdItems_ChargesTotal: "Gesamtkosten",
        grdItems_Commodity: "Ware",
        grdItems_CommodityDimension: "Dimension",
        grdItems_CommodityVariant: "Variante",
        grdItems_DiscountTotal: "Rabatt gesamt",
        grdItems_GrossTotal: "Summe brutto",
        grdItems_InitialPrice: "Ausgangspreis",
        grdItems_Line: "Positionsnummer",
        grdItems_NetTotal: "Nettosumme",
        grdItems_Quantity: "Menge",
        grdItems_Status: "Status",
        grdItems_TaxTotal: "Steuer gesamt",
        grdItems_Type: "Positionstyp",
        grdItems_UnitOfMeasure: "Einheit",
        grdPayments_Charges: "Kosten",
        grdPayments_Currency: "Währung",
        grdPayments_Date: "Datum",
        grdPayments_Discounts: "Rabatte",
        grdPayments_GrossTotal: "Summe brutto",
        grdPayments_Name: "Name",
        grdPayments_NetTotal: "Nettosumme",
        grdPayments_ProcessDate: "Verarbeitungsdatum",
        grdPayments_Status: "Status",
        grdPayments_Tax: "Steuern",
        grdPayments_TenderReference: "Zahlungsmittelreferenz",
        grdPayments_TenderType: "Zahlungsmitteltyp",
        grdPayments_Type: "Typ",
        grdDeliveries_ActualDate: "Tatsächliches Datum",
        grdDeliveries_ActualTime: "Tatsächliche Uhrzeit",
        grdDeliveries_Carrier: "Versanddienst",
        grdDeliveries_CarrierReference: "Versanddienstreferenz",
        grdDeliveries_DeliveredQuantity: "Gelieferte Menge",
        grdDeliveries_ExceptionReason: "Begründung der Ausnahme",
        grdDeliveries_Method: "Methode",
        grdDeliveries_Number: "Zahl",
        grdDeliveries_RequestedDate: "Angefordert am",
        grdDeliveries_RequestedQuantity: "Angeforderte Menge",
        grdDeliveries_Status: "Status",
        grdDeliveries_Type: "Typ",
        btnCloseCaption: "Schließen"
    })
);