define(
    ({
        dialogCaption: "Verkaufsauftragsdetails",
        loadingText: "Laden...",
        lblSalesOrderCaption: "Verkaufsauftrag:",
        lblStatusCaption: "Status:",
        lblGrossTotalCaption: "Auftragsbetrag:",
        lblOrderDateCaption: "Auftragsdatum:",
        lblTaxTotalCaption: "Steuer gesamt:",
        lblHoldStatusCaption: "Status \"Aussetzen\":",
        lblCurrencyCaption: "Währung:",
        lblTypeCaption: "Typ:",
        lblCostTotalCaption: "Gesamtkosten:",
        lblPONumberCaption: "Bestellnummer:",
        lblProfitTotalCaption: "Gesamtgewinn:",
        lblQuotationCaption: "Angebot:",
        lblInvoiceStatusCaption: "Rechnungsstatus:",
        lblContactCaption: "Kontakt:",
        lblDeliveryDateCaption: "Lieferdatum:",
        lblDueDateCaption: "Fälligkeitsdatum:",
        lblPriceListCaption: "Preisliste:",
        lblCarrierCaption: "Versanddienst:",
        lblNetTotalCaption: "Nettosumme:",
        lblAllocationStatusCaption: "Zuordnungsstatus:",
        lblDiscountTotalCaption: "Rabatt gesamt:",
        lblDeliveryStatusCaption: "Lieferstatus:",
        lblChargesTotalCaption: "Gesamtkosten:",
        detailsTabTitle: "Details",
        salesPersonsTabTitle: "Verkäufer",
        addressTabTitle: "Adressen",
        salesOrderLinesTabTitle: "Verkaufsauftragspositionen",
        paymentsTabTitle: "Zahlungen",
        deliveriesTabTitle: "Lieferungen",
        grdSalesOrder_Edit: "Bearbeiten",
        grdSalesOrder_OrderNumber: "Auftragsnummer",
        grdSalesOrder_OrderDate: "Auftragsdatum",
        grdSalesOrder_Status: "Status",
        grdSalesOrder_HoldStatus: "Status \"Aussetzen\"",
        grdSalesOrder_Type: "Typ",
        grdSalesOrder_PO: "Bestellnummer",
        grdSalesOrder_NetTotal: "Nettosumme",
        grdSalesOrder_DiscountTotal: "Rabatt gesamt",
        grdSalesOrder_ChargesTotal: "Gesamtkosten",
        grdSalesOrder_TaxTotal: "Steuer gesamt",
        grdSalesOrder_GrossTotal: "Summe brutto",
        grdSalesOrder_Currency: "Währung",
        grdSalesPersons_Name: "Name",
        grdSalesPersons_Type: "Typ",
        grdSalesPersons_Extension: "Erweiterung",
        grdSalesPersons_Relationship: "Beziehung",
        grdAddress_Name: "Name",
        grdAddress_Address1: "Zahlungsmittelsreferenz",
        grdAddress_Address2: "Adresse2",
        grdAddress_City: "Stadt",
        grdAddress_State: "Bundesland/Kanton",
        grdAddress_Zip: "PLZ",
        grdItems_Line: "Positionsnummer",
        grdItems_Type: "Typ",
        grdItems_Commodity: "Ware",
        grdItems_CommodityVariant: "Variante",
        grdItems_CommodityDimension: "Dimension",
        grdItems_UnitOfMeasure: "Einheit",
        grdItems_Location: "Standort",
        grdItems_PriceList: "Preisliste",
        grdItems_Quantity: "Menge",
        grdItems_InitialPrice: "Ausgangspreis",
        grdItems_ActualPrice: "Tatsächlicher Preis",
        grdItems_NetTotal: "Nettosumme",
        grdItems_ChargesTotal: "Gesamtkosten",
        grdItems_DiscountTotal: "Rabatt gesamt",
        grdItems_TaxTotal: "Steuer gesamt",
        grdItems_GrossTotal: "Summe brutto",
        grdPayments_Date: "Zahlungsdatum",
        grdPayments_Name: "Name",
        grdPayments_Type: "Typ",
        grdPayments_Status: "Status",
        grdPayments_NetTotal: "Nettosumme",
        grdPayments_Discounts: "Rabatte",
        grdPayments_Charges: "Kosten",
        grdPayments_Tax: "Steuer",
        grdPayments_GrossTotal: "Summe brutto",
        grdPayments_Currency: "Währung",
        grdPayments_TenderType: "Zahlungsmitteltyp",
        grdPayments_TenderReference: "Zahlungsmittelreferenz",
        grdPayments_ProcessDate: "Verarbeitungsdatum",
        grdDeliveries_Number: "Zahl",
        grdDeliveries_Type: "Typ",
        grdDeliveries_Status: "Status",
        grdDeliveries_RequestedDate: "Angefordert am",
        grdDeliveries_ActualDate: "Tatsächliches Datum",
        grdDeliveries_ActualTime: "Tatsächliche Uhrzeit",
        grdDeliveries_RequestedQuantity: "Angeforderte Menge",
        grdDeliveries_DeliveredQuantity: "Gelieferte Menge",
        grdDeliveries_Method: "Methode",
        grdDeliveries_Carrier: "Versanddienst",
        grdDeliveries_CarrierReference: "Versanddienstreferenz",
        grdDeliveries_ExceptionReason: "Begründung der Ausnahme",
        errorERPRequest: "Eine Verkaufsauftrag-Detailansicht zu bekannten Absatzmöglichkeiten in Buchhaltungssystemen. ",
        errorERPRequestDetails: "${0}, ${1} Anforderung: ${2}",
        btnCloseCaption: "Schließen"
    })
);
