define(
    ({
        dialogCaption: "Детали счета",
        loadingText: "загрузка...",
        lblInvoiceCaption: "Счет:",
        lblNetTotalCaption: "Сумма счета:",
        lblInvoiceDateCaption: "Дата счета:",
        lblInvoiceDiscountAmountCaption: "Скидка:",
        lblDueDateCaption: "Плановая дата:",
        lblInvoiceDiscountPercentCaption: "Процент скидки:",
        lblCustomerPOCaption: "Номер заказа:",
        lblCarrierTotalPriceCaption: "Отгрузка:",
        lblSettlementDiscountPercentCaption: "Урегулированный процент скидки:",
        lblTaxCaption: "Налог:",
        lblSettlementDiscountTermsCaption: "Сроки оплаты:",
        lblNotesCaption: "Комм-рии:",
        lblOperatingCompanyCurrencyCaption: "Валюта действующей Компании:",
        lblCostTotalCaption: "Общая стоимость:",
        lblOperatingCompanyCurrencyExchangeRateDateCaption: "Дата курса обмена:",
        lblProfitTotalCaption: "Всего выгода:",
        lblOperatingCompanyCurrencyExchangeRateCaption: "Курс обмена:",
        lblPriceListCaption: "Прайс-лист:",
        lblOCCurrencyCaption: "Действующая валюта компании:",
        lblCurrencyCaption: "Валюта:",
        lblSalesPersonCaption: "Продавец:",
        detailsTabTitle: "Детали",
        addressTabTitle: "Адреса",
        invoiceLinesTabTitle: "Линии счета",
        paymentsTabTitle: "Платежи",
        deliveriesTabTitle: "Доставка",
        grdInvoice_Name: "Счет #",
        grdInvoice_Date: "Дата счета",
        grdInvoice_Amount: "Сумма счета",
        grdInvoice_PO: "Номер заказа",
        grdInvoice_PaymentTerms: "Сроки оплаты",
        grdInvoice_NetTotal: "Сумма нетто",
        grdInvoice_Tax: "Налог",
        grdAddress_Name: "Описание",
        grdAddress_address1: "Улица",
        grdAddress_address2: "Дом",
        grdAddress_City: "Город",
        grdAddress_State: "Область",
        grdAddress_Zip: "Почтовый код",
        grdItems_ActualPrice: "Фактическая цена",
        grdItems_ChargesTotal: "Всего расходов",
        grdItems_Commodity: "Товар",
        grdItems_CommodityDimension: "Размеры",
        grdItems_CommodityVariant: "Вариант",
        grdItems_DiscountTotal: "Всего скидки",
        grdItems_GrossTotal: "Всего брутто",
        grdItems_InitialPrice: "Первоначальная цена",
        grdItems_Line: "Номер линии",
        grdItems_NetTotal: "Сумма нетто",
        grdItems_Quantity: "Кол-во",
        grdItems_Status: "Статус",
        grdItems_TaxTotal: "Налог, всего",
        grdItems_Type: "Тип линии",
        grdItems_UnitOfMeasure: "Единица",
        grdPayments_Charges: "Расходы",
        grdPayments_Currency: "Валюта",
        grdPayments_Date: "Дата",
        grdPayments_Discounts: "Скидки",
        grdPayments_GrossTotal: "Всего брутто",
        grdPayments_Name: "Имя",
        grdPayments_NetTotal: "Сумма нетто",
        grdPayments_ProcessDate: "Дата обработки",
        grdPayments_Status: "Статус",
        grdPayments_Tax: "Налоги",
        grdPayments_TenderReference: "Ссылка на тендер",
        grdPayments_TenderType: "Тип тендера",
        grdPayments_Type: "Тип",
        grdDeliveries_ActualDate: "Фактическая дата",
        grdDeliveries_ActualTime: "Фактическая время",
        grdDeliveries_Carrier: "Перевозчик",
        grdDeliveries_CarrierReference: "Ссылка на перевозчика",
        grdDeliveries_DeliveredQuantity: "Кол-во доставленного",
        grdDeliveries_ExceptionReason: "Причина исключения",
        grdDeliveries_Method: "Метод",
        grdDeliveries_Number: "Число",
        grdDeliveries_RequestedDate: "Требуемая дата",
        grdDeliveries_RequestedQuantity: "Требуемое количество",
        grdDeliveries_Status: "Статус",
        grdDeliveries_Type: "Тип",
        btnCloseCaption: "Закрыть"
    })
);