define(
        ({
            labelWidth: '100',
            tabNameGeneralText: 'Generale',
            tabNameAvailabilityText: 'Disponibilità',
            tabNameAssociationsText: 'Associazioni',
            tabNameRecurringText: 'Ricorrente',
            tabNameAttachmentsText: 'Allegati',
            tabNameNotesText: 'Nota',
            scheduleText: 'Pianifica',
            startTimeText: 'Ora iniziale',
            timeLessText: 'Senza orario',
            alarmText: 'Allarme',
            durationText: 'Durata',
            rolloverText: 'Riporta automaticamente al giorno successivo',
            contactText: 'Contatto',
            accountText: 'Azienda',
            leadText: 'Nominativo',
            opportunityText: 'Opportunità',
            ticketText: 'Ticket',
            companyText: 'Società',
            regardingText: 'Argomento',
            notesText: 'Nota',
            priorityText: 'Priorità',
            leaderText: 'Responsabile',
            categoryText: 'Categoria',
            locationText: 'Posizione',
            dialogHeaderFormatText: '${actionText} ${activityType} - ${description}',
            scheduledByFormatText: 'Pianificato da ${user} il ${date}',
            completeScheduledByFormatText: 'Pianificato da ${user} il ${date} in origine per ${startDate}',
            newConfirmationHeaderFormatText: 'Conferma ${activityType} Pianificato da ${user}',
            otherConfimationHeaderFormatText: '${activityType} ${actionText} da ${user}',
            acceptedText: 'Accettato',
            declinedText: 'Diminuito',
            scheduledText: 'Pianificato',
            updatedText: 'Aggiornato',
            deletedText: 'Eliminato',
            cancelText: 'Annulla',
            okText: 'OK',
            completeText: 'Completa',
            completeBtnText: 'Completa...',
            completedText: 'Completato',
            deleteText: 'Elimina',
            lookupActText: 'Ricerca Azienda',
            lookupContactText: 'Ricerca Contatto',
            lookupOpportunityText: 'Ricerca opportunità',
            lookupTicketText: 'Ricerca Ticket',
            lookupLeadText: 'Ricerca Nominativo',
            lookupLeaderText: 'Ricerca Leader',
            lookupResourcesText: 'Aggiungi membri e risorse',
            addResourceText: 'Aggiungi',
            mainPhoneText: 'Telefono principale',
            typeText: 'Tipo',
            subTypeText: 'Sotto-Tipo',
            nameText: 'Nome',
            cityText: 'Città',
            stateText: 'Status',
            workphoneText: 'Tel. Ufficio',
            emailText: 'E-Mail',
            acctMgrText: 'Responsabile',
            descriptionText: 'Descrizione',
            stageText: 'Fase',
            statusText: 'Status',
            ownerText: 'Proprietario',
            ticketNumberText: 'Numero Ticket',
            phoneText: 'Telefono',
            urgencyText: 'Urgenza',
            areaText: 'Area',
            recurringText: 'Ricorrente',
            resultText: 'Risultato',
            followupText: 'Seguito',
            noneText: 'Nessuno',
            carryOverAttachmentsText: 'Riporta Allegati',
            carryOverNotesText: 'Riporta note',
            asScheduledText: 'Come pianificato',
            nowText: 'Adesso',
            responseText: 'Risposta',
            acceptText: 'Accetta',
            declineText: 'Rifiuta',
            deleteConfText: 'Conferma Eliminazione',
            closeText: 'Chiudi',
            leadFullNameText: 'Nome',
            postalText: 'Cap',
            failedLoadingDataMsg: 'Errore durante il caricamento dei dati.',
            removeText: 'Rimuovi',
            noText: 'No',
            yesText: 'Sì',
            areYouSureText: 'Stai per eliminare definitivamente questo record.',
            couldNotSaveErrorText: 'L\'attività non poteva essere salvata perché si è verificato un errore.',
            couldNotDeleteErrorText: 'L\'attività potrebbe non essere stata eliminata perché si è verificato un errore.',
            couldNotCompleteErrorText : 'L\'attività potrebbe non essere completata perché si è verificato un errore.'
        })
);
