SELECT     sysdba.USERSECURITY.USERID as EUROUSERID, tmpTeams.SECCODEID as TEAMSECCODEID
FROM         sysdba.USERSECURITY CROSS JOIN
                          (SELECT     SECCODEID
                            FROM          sysdba.SECCODE
                            WHERE      (SECCODEID IN ('FEUROA00002D', 'FEUROA00002E', 'FEUROA00002F', 'FEUROA00003F'))) AS tmpTeams
WHERE     (sysdba.USERSECURITY.TYPE IN ('W', 'N', 'C'))

SELECT     EUROUSERTEAMACCESSID, CREATEUSER, CREATEDATE, MODIFYUSER, MODIFYDATE, EUROUSERID, TEAMSECCODEID
FROM         sysdba.EUROUSERTEAMACCESS