Update sysdba.HISTORY
SET  TORECIPIENTS= sysdba.EMAILARCHIVE.TORECIPIENTS,
     CCRECIPIENTS =sysdba.EMAILARCHIVE.CCRECIPIENTS,
     BCCRECIPIENTS= sysdba.EMAILARCHIVE.BCCRECIPIENTS
FROM         sysdba.HISTORY INNER JOIN
                      sysdba.EMAILARCHIVE ON sysdba.HISTORY.EMAILARCHIVEID = sysdba.EMAILARCHIVE.EMAILARCHIVEID