Update sysdba.Opportunity
SET     SECCODEID = sysdba.EUROXHISTORYMAPPING.XHISTORYSECCODEID
FROM         sysdba.OPPORTUNITY INNER JOIN
                      sysdba.ACCOUNT ON sysdba.OPPORTUNITY.ACCOUNTID = sysdba.ACCOUNT.ACCOUNTID INNER JOIN
                      sysdba.EUROXHISTORYMAPPING ON sysdba.ACCOUNT.SECCODEID = sysdba.EUROXHISTORYMAPPING.MAINACCOUNTSECCODEID
                      
Create View [sysdba].[VHistOwner]
as
SELECT     sysdba.ACCOUNT.ACCOUNTID, ISNULL(sysdba.EUROXHISTORYMAPPING.XHISTORYSECCODEID, sysdba.ACCOUNT.SECCODEID) AS HistOwner
FROM         sysdba.ACCOUNT LEFT OUTER JOIN
                      sysdba.EUROXHISTORYMAPPING ON sysdba.ACCOUNT.SECCODEID = sysdba.EUROXHISTORYMAPPING.MAINACCOUNTSECCODEID                      