define(
        ({
           colNameComplete:'Abschließen',
           colNameAttachment:'Anlage',
           colNameRecurring:'Wiederkehrend',
           colNameAlarm:'Alarm',
           colNameType:'Aktivitätstyp',
           colNameStartDate:'Startdatum',
           colNameDuration:'Dauer',
           colNameContact:'Name',
           colNameLead:'Interessent',
           colNameAccount:'Firma/Unternehmen',
           colNameCompany:'Unternehmen',
           colNameRegarding:'Betreff',
           colNamePriority:'Priorität',
           colNameUserId:'Organisator',
           colNameTimeless:'Ohne Zeitangabe',
           colNameTypeName:'Typ',
           colNameContactName:'Name'     
        })
);