define(
        ({
            activityOccurrsText: 'Diese Aktivität erfolgt...',
            onceText: 'Ein Mal',
            dailyText: 'Täglich',
            weeklyText: 'Wöchentlich',
            monthlyText: 'Monatlich',
            yearlyText: 'Jährlich',
            occursOnceText: 'Diese Aktivität erfolgt nur einmal',
            everyText: 'Alle',
            daysText: 'Tag(e)',
            daysAfterText: 'Tag(e) nach Abschluss',
            startRecurringText: 'Sich wiederholende Aktivität starten: ',
            endAfterText: 'Beenden nach',
            endOnText: 'Wiederholung beenden',
            occurrencesText: 'Wiederholungen',
            weeksOnText: 'Woche(n) am',
            monText: 'Montag',
            tueText: 'Dienstag',
            wedText: 'Mittwoch',
            thurText: 'Donnerstag',
            friText: 'Freitag',
            satText: 'Samstag',
            sunText: 'Sonntag',
            weeksAfterText: 'Wochen nach Abschluss',
            monthsOnText: 'Monat(e) an Tag',
            monthsOnTheText: 'Monat(e) am',
            monthsAfterText: 'Monate nach Abschluss',
            firstText: '1',
            secondText: '2',
            thirdText: '3',
            fourthText: '4',
            lastText: 'letzte(r/s)',
            yearsOnText: 'Jahre am',
            yearsAfterText: 'Jahr(e) nach nach Abschluss',
            janText: 'Januar',
            febText: 'Februar',
            marText: 'März',
            aprText: 'April',
            mayText: 'Mai',
            junText: 'Juni',
            julText: 'Juli',
            augText: 'August',
            sepText: 'September',
            octText: 'Oktober',
            novText: 'November',
            decText: 'Dezember',
            theText: 'Der/Die/Das',
            inText: 'in'
        })
);
      