define([
        'Sage/LanguageList',
        'dojo/_base/lang'
],
function (LanguageList, lang) {
    var nls = {
        root: {
            activityOccurrsText: 'This activity occurs...',
            onceText: 'Once',
            dailyText: 'Daily',
            weeklyText: 'Weekly',
            monthlyText: 'Monthly',
            yearlyText: 'Yearly',
            occursOnceText: 'This activity occurs only once',
            everyText: 'Every',
            daysText: 'Day(s)',
            daysAfterText: 'Day(s) after completion',
            startRecurringText: 'Start Recurring: ',
            endAfterText: 'End After',
            endOnText: 'End Recurring',
            occurrencesText: 'occurrences',
            weeksOnText: 'Week(s) on',
            monText: 'Monday',
            tueText: 'Tuesday',
            wedText: 'Wednesday',
            thurText: 'Thursday',
            friText: 'Friday',
            satText: 'Saturday',
            sunText: 'Sunday',
            weeksAfterText: 'Week(s) after completion',
            monthsOnText: 'Month(s) on day',
            monthsOnTheText: 'Month(s) on the',
            monthsAfterText: 'Month(s) after completion',
            firstText: '1st',
            secondText: '2nd',
            thirdText: '3rd',
            fourthText: '4th',
            lastText: 'last',
            yearsOnText: 'Year(s) on',
            yearsAfterText: 'Year(s) after completion',
            janText: 'January',
            febText: 'February',
            marText: 'March',
            aprText: 'April',
            mayText: 'May',
            junText: 'June',
            julText: 'July',
            augText: 'August',
            sepText: 'September',
            octText: 'October',
            novText: 'November',
            decText: 'December',
            theText: 'The',
            inText: 'in'
        }
    };
    return lang.mixin(LanguageList, nls);
});