define(
        ({
            labelWidth: '120',
            tabNameGeneralText: 'Général',
            tabNameAvailabilityText: 'Disponibilité',
            tabNameAssociationsText: 'Associations',
            tabNameRecurringText: 'Périodicité',
            tabNameAttachmentsText: 'Pièces jointes',
            tabNameNotesText: 'Notes',
            scheduleText: 'Planification',
            startTimeText: 'Heure de début',
            timeLessText: 'Heure indéfinie',
            alarmText: 'Alarme',
            durationText: 'Durée',
            rolloverText: 'Reporter automatiquement au jour suivant',
            contactText: 'Contact',
            accountText: 'Compte',
            leadText: 'Lead',
            opportunityText: 'Opportunité',
            ticketText: 'Ticket',
            companyText: 'Société',
            regardingText: 'Objet',
            notesText: 'Notes',
            priorityText: 'Priorité',
            leaderText: 'Responsable',
            categoryText: 'Catégorie',
            locationText: 'Emplacement',
            dialogHeaderFormatText: '${actionText} ${activityType} - ${description}',
            scheduledByFormatText: 'Planifié par ${user} le ${date}',
            completeScheduledByFormatText: 'Planifié par ${user} le ${date} initialement pour ${startDate}',
            newConfirmationHeaderFormatText: 'Confirmer ${activityType} planifié par ${user}',
            otherConfimationHeaderFormatText: '${activityType} ${actionText} par ${user}',
            acceptedText: 'Accepté',
            declinedText: 'Refusé',
            scheduledText: 'Planifié',
            updatedText: 'Mis à jour',
            deletedText: 'Supprimé',
            cancelText: 'Annuler',
            okText: 'OK',
            completeText: 'Terminer',
            completeBtnText: 'Terminer...',
            completedText: 'Terminé',
            deleteText: 'Supprimer',
            lookupActText: 'Rechercher un compte',
            lookupContactText: 'Rechercher un contact',
            lookupOpportunityText: 'Rechercher une opportunité',
            lookupTicketText: 'Rechercher un ticket',
            lookupLeadText: 'Recherche un lead',
            lookupLeaderText: 'Rechercher le responsable',
            lookupResourcesText: 'Ajouter des membres et des ressources',
            addResourceText: 'Ajouter',
            mainPhoneText: 'Tél. principal',
            typeText: 'Type',
            subTypeText: 'Sous-Type',
            nameText: 'Nom',
            cityText: 'Ville',
            stateText: 'Département',
            workphoneText: 'Téléphone professionnel',
            emailText: 'E-mail',
            acctMgrText: 'Resp. du compte',
            descriptionText: 'Description',
            stageText: 'Phase',
            statusText: 'Etat',
            ownerText: 'Propriétaire',
            ticketNumberText: 'Numéro de ticket',
            phoneText: 'Téléphone',
            urgencyText: 'Priorité',
            areaText: 'Zone',
            recurringText: 'Périodicité',
            resultText: 'Résultat',
            followupText: 'Suivi',
            noneText: 'Aucun',
            carryOverAttachmentsText: 'Reporter les pièces jointes',
            carryOverNotesText: 'Reporter les notes',
            asScheduledText: 'Telle que planifiée',
            nowText: 'Maintenant',
            responseText: 'Taux de retours',
            acceptText: 'Accepter',
            declineText: 'Refuser',
            deleteConfText: 'Confirmation de la suppression',
            closeText: 'Fermer',
            leadFullNameText: 'Nom',
            postalText: 'Code postal',
            failedLoadingDataMsg: 'Une erreur est survenue lors du chargement des données.',
            removeText: 'Retirer',
            noText: 'Non',
            yesText: 'Oui',
            areYouSureText: 'Vous êtes sur le point de supprimer définitivement cet enregistrement.',
            couldNotSaveErrorText: 'Impossible de sauvegarder l\'activité car une erreur s\'est produite.',
            couldNotDeleteErrorText: 'Impossible de supprimer l\'activité car une erreur s\'est produite.',
            couldNotCompleteErrorText : 'Impossible de terminer l\'activité car une erreur s\'est produite.'
        })
);
